redfish-core/lib/log_services.hpp

/redfish/v1/Systems/system/LogServices/EventLog
ERROR - LogService.v1_0_0.LogService:Actions : Could not get
details on this property (This item should not be a List)
ERROR - Actions: Item is present, but no schema found
Before:
curl -k https://${bmc}/redfish/v1/Systems/system/LogServices/EventLog/
{
"@odata.context": "/redfish/v1/$metadata#LogService.LogService",
"@odata.id": "/redfish/v1/Systems/system/LogServices/EventLog",
"@odata.type": "#LogService.v1_1_0.LogService",
"Actions": [
{
"#LogService.ClearLog": {
"target": "/redfish/v1/Systems/system/LogServices/EventLog/Actions/LogService.ClearLog"
}
}
],
After:
curl -k https://${bmc}/redfish/v1/Systems/system/LogServices/EventLog/
{
"@odata.context": "/redfish/v1/$metadata#LogService.LogService",
"@odata.id": …

Fix Redfish Validator Errors in EventLog

---

redfish-core/include/utils/json_utils.hpp
redfish-core/lib/managers.hpp
redfish-core/lib/systems.hpp

Commit d573bb2a regressed the PATCH operation
on the system redfish node. By initializing
result to no_content, the commit broke the subsequent
json_util::readJson, which checks if the result is "ok"
at the end of the function.
This commit fixes it by making readJsonValues() and its
descendants return a bool status. readJson() no longer
relies on the response object result to indicate success/
failure.
Tested:
-- Verified that PATCH operations on the system node now work.
-- Verified PATCH operations work on manager, accountservice and
ethernetinterfaces nodes.
-- No new errors from the Redfish validator.
Change-Id: I54080392297a8f0276161da8b48d8f9518cbdcfe

Fix Regression in PATCH on system node

---

CMakeLists.txt
crow/include/crow/http_connection.h
crow/include/crow/http_request.h
include/logging_middleware.hpp
include/token_authorization_middleware.hpp
include/webserver_common.hpp
redfish-core/lib/redfish_sessions.hpp
src/webserver_main.cpp

This commits adds support to log request and respose
for all REST and Redfish traffic flowing through BMCWEB.
It does this by defining a new crow middleware.
The middleware can be compiled out at build time if it is not
desired by using the BMCWEB_ENABLE_TRAFFIC_LOGGING compile
option.
The option is not enabled by default, recipes can add this
option as required.
This logging can also be turned ON or OFF at runtime by using
the Enabled property on the /xyz/openbmc_project/logging/rest_api_logs
DBUS object.
The middleware makes decisions on what data needs to be logged
by looking at the request URL. Per IBM's requirements, it does not
log data for REST and Redfish routes that contain passwords.
Tested:
1) Made sure that by default, the compile option disables any logging.
2) Compiled …

REST and Redfish Traffic Logging

---

bmcweb.service.in

Now bmcweb have dependency on the user manager where
bmcweb creates the user role map(user and its associated privilege)
when it starts, suppose if user manager starts after the bmcweb
then bmcweb would not be having the roles for the user and the authorization
will fail.
This will remain forever untill we restart the bmcweb.
This commit fixes this behaviour.
In one of the CI machine I have observed the following behaviour.
Jul 12 17:29:41 : Started Start bmcweb server.
Jul 12 17:30:08 : Started Phosphor User Manager.
TestedBy: Stopped the user manager service and LDAP conf service.
restart the bmcweb and make sure that user manager and LDAP conf
starts before the bmcweb.
Signed-off-by: Ratan Gupta <ratagupt@linux.vnet.ibm.com>
Change-Id: Ief61ea2171545d32d554a64036719126a3b128f1

Add user manager dependency and LDAP conf dependency

---

include/sessions.hpp

The access to Redfish resources are based on the user role. When a
session is created, the role of the user at that time is stored in
the session details. The role changes, if any, will not be applicable
to the alreay created sessions.
Consider a scenario when bmcweb is restarted. If user role is not included
in the persistent session data, then at the time of starting bmcweb, the
current role of the user has to be considered as the role at the time of
creating the session is not known. The current role may be different from
the role when the session was created. That means, after creating a
session, role changes,if any, will be applied if bmcweb is restarted. If
bmcweb is not restarted during the life of a session, then role changes
are not applied. To avoid this difference in behaviour, …

Include user role in the persistent session data

---

redfish-core/lib/cpudimm.hpp

This commit fixes a bug in getAcceleratorDataByService
when looking up the Present and Functional properties
on D-Bus.
The properties are booleans, but the code was trying
to read them as strings.
Tested:
-- Redfish validator comes out clean
-- Tested various combinations of present and functional
properties on the GPU inventory objects:
xyz.openbmc_project.Inventory.Manager
/xyz/openbmc_project/inventory/system/chassis/motherboard/gv100card0
xyz.openbmc_project.State.Decorator.OperationalStatus Functional b "false"
/xyz/openbmc_project/inventory/system/chassis/motherboard/gv100card0
xyz.openbmc_project.Inventory.Item Present b "true"
$ curl -k -H "X-Auth-Token: $bmc_token" -X GET
https://${bmc}/redfish/v1/Systems/system/Processors/gv100card0
{
"@odata.context": …

Fixed Accelerator State

---

redfish-core/lib/systems.hpp

https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/22661/
bmcweb implementation of NMI (soft reset) control code
Tested: Verified following
1) Redfish validator result is Negative
2) verified following command triggered NMI on host
curl -k -H "X-Auth-Token: $bmc_token" -X POST
https://9.5.180.47/redfish/v1/Systems/system/Actions/ComputerSystem.Reset
-d '{"ResetType":"Nmi"}'
Response : OK
2) Host rebooted and crash dump is collected
Signed-off-by: Lakshminarayana R. Kammath <lkammath@in.ibm.com>
Change-Id: I09efa1e3d94437c89afbe1a1b9d148cc4f577ebe

bmcweb implementation of NMI (soft reset) control code

---

include/token_authorization_middleware.hpp

Needed to support IE 11.
Coming soon, IE 11 support, via https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24062
bmcweb fails when attempting to login with a Content header of
application/json; charset=utf8.  This is because of an exact string
compare.  This commit changes the check to only check the begining of
the string, and adds some logging to make it more clear when we hit this
in the future.
Signed-off-by: Ed Tanous <ed.tanous@intel.com>
Change-Id: I972a80c174a18295205340271b781c9d6693ee17

Ignore charset for /login attempts

---

redfish-core/lib/chassis.hpp

Chassis.v1_9_1 is only part of the 2019.1 schema, we are using 2018.3
schema.
This fixes 6 Validator errors:
ERROR - 1 failProp errors in /redfish/v1/Systems/system
ERROR - 4 failMandatoryProp errors in /redfish/v1/Chassis
ERROR - Error message present in /redfish/v1/Chassis/chassis
ERROR - Error message present in /redfish/v1/Chassis/powersupply0
ERROR - Error message present in /redfish/v1/Chassis/powersupply1
ERROR - 1 failProp errors in /redfish/v1/Managers/bmc
2 errors still exist:
ERROR - 1 failProp errors in /redfish/v1/Chassis/motherboard
ERROR - 1 problemResource errors in /redfish/v1/Chassis/motherboard/Sensors
caused by
curl -k https://${bmc}/redfish/v1/Chassis/motherboard/Sensors
Internal Server Error

Fix Redfish Validator caused by Chassis.v1_9_1

---

redfish-core/lib/chassis.hpp
redfish-core/lib/sensors.hpp

**Gerrit review**
* https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/24014
* Has 3 +1s including James Feist from Intel.
**Commit message**
Made the following enhancements related to power supplies in Redfish:
* Moved power supplies from Chassis schema to Power schema
* Added support for multiple power supplies within one chassis
* Added support for multiple sensors associated with one power supply
* Set power supply Name and MemberId to inventory item name (like
powersupply0) rather than sensor name (like ps0_input_power).
* Set power supply VPD fields like Manufacturer and SerialNumber
Also improved support for power sensors that are not related to power
supplies, such as VRM sensors.  These sensors are no longer treated as
power supplies, and they will not be included in the Power …

Redfish: Move power supplies to Power schema

---

redfish-core/lib/power.hpp

The average and maximum consumed power aggregation history is read and
stored every 30 seconds within an openpower interface per power supply.
This pulls the entire aggregation history for each metric, over all
power supplies, and calculates a total average and maximum.
The total average consumed power is the result from adding the average
of all aggregation history entries per power supply. This is presented
as the `AverageConsumedWatts` in Redfish.
The total maximum consumed power is the result from adding the maximum
value determined from the aggregation history per power supply over the
same aggregation period. This is presented as the `MaxConsumedWatts` in
Redfish.
The `IntervalInMin` Redfish attribute is a single interval(in minutes)
at which all the Redfish power metrics were …

Redfish: Add power metrics for openpower

---

redfish-core/lib/sensors.hpp

Added support for the IndicatorLED property for physical leds
associated with Thermal and Power sensors.
Gerrit Review:
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/24110/
Testing: Verified output on a witherspoon.
Change-Id: I4e49b3c1769742e49f57c6c1b77a82511cdc8b99
Signed-off-by: Anthony Wilson <wilsonan@us.ibm.com>

bmcweb: Add IndicatorLED property to sensors

---

redfish-core/lib/systems.hpp

ProcessorSummary State is always Disabled and Count shows 0.
Fixed it by using correct interface to get these values.
Doing GET on Interface xyz.openbmc_project.State.Decorator.OperationalStatus
instead of xyz.openbmc_project.Inventory.Item.Cpu to get the State of CPU
Tested:
-- Ran GET request on the ComputerSystem node
--when 2 CPUs are present and functional
"ProcessorSummary": {
"Count": 2,
"Status": {
}
},
--when 2 CPUs are present but only 1 is functional
"ProcessorSummary": {
"Count": 2,
"Status": {
}
},
--when only 1 CPU present and functional
"ProcessorSummary": {
"Count": 1,
"Status": {
}
},
--when only 1 CPU present and Not Functional
"ProcessorSummary": {
"Count": 1,
"Status": {
"State": "Disabled"
}
},
--Ran …

Fix ProcessorSummary Count and Status

---

redfish-core/lib/systems.hpp

"MemorySummary" Status is always Disabled.Fixed it.
Doing GET on Interface xyz.openbmc_project.State.Decorator.OperationalStatus
instead of xyz.openbmc_project.Inventory.Item.Dimm to get the State of Dimm
Tested:
-- Ran GET request on the ComputerSystem node when Host is Up
curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Systems/system
"MemorySummary": {
"Status": {
},
"TotalSystemMemoryGiB": 0
},
Redfish schema validator.
ComputerSystem.v1_0_0.MemorySummary:Status
value: OrderedDict([('State', 'Enabled')]) <class 'collections.OrderedDict'>
has Type: Resource.Status complex
is Optional
***going into Complex
Resource.Status:State
value: Enabled <class 'str'>
has Type: Resource.State enum
is Optional
permission OData.Permission/Read
Success …

Fix "MemorySummary" status: Disabled on IBM systems

---

redfish-core/lib/sensors.hpp

Upstream https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/24475
Tested OP940 branch with this change. 
Map DeratingFactor from PowerSupplyAttributes.interface.yaml
to the Redfish property PowerSupply "EfficiencyPercent".
Only do this call when the "Power" schema is called.
Use the InventoryItem class introduced in
adc4f0db57568c5e5d2a3398fce00dbb050a3b72
Tested: Power, Thermal, all look good.
Passed the Redfish Validator.
"PowerSupplies": [
{
"@odata.id": "/redfish/v1/Chassis/chassis/Power#/PowerSupplies/0",
"EfficiencyPercent": 90,
"IndicatorLED": "Off",
"MemberId": "powersupply0",
"Model": "2B1D",
"Name": "powersupply0",
"PartNumber": "01KL471",
"PowerInputWatts": 12.0,
"SerialNumber": "71G370",
"Status": {
}
},
Change-Id: …

Add Power Supply Attributes

---

redfish-core/include/privileges.hpp
redfish-core/lib/roles.hpp

The callback is an IPMI only role which should not be able to login
to Redfish/GUI. This follows the new GUI user management page
role table.
Fixes defect: 
SW474799, GUI Callback user has all user privileges but should
have only IPMI access as per GUI.
Upstream was merged here:
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/24712/4
Callback privilege user must not be allowed to login,similar to IPMI.
This user is used for callback purpose from IPMI point of it, and
must be maintained in bmcweb to be consistent with IPMI, Hence
removing the access to login for callback user
Tested:
1.Create a user with username 'test1' and privilege -
"Callback" via Redfish.
2.Using that Callback level credentials, try to do
"Get" at this URI https://<ip-addr>/redfish/v1/Systems/system
3.output: …

SW474799: Fix remove callback user privilege access to login

---

redfish-core/lib/update_service.hpp

This change is to GET and PATCH the ApplyTime property using the
UpdateServce redfish schema. GET request can be used to check the value
before initiating the BMC image upload and activation. PATCH request
can be used to update the ApplyTime value.
If the ApplyTime value is Immediate, force-reboot.service gets called
which reboots the BMC. If the ApplyTime value is OnReset, no force reboot
will be triggered and the new BMC image will be functional till the user
decideds to reboot the BMC manually.
Tested:
Changes passed the Redfish-Service-Validator test.
Success Scenarios:
1. If the value of ApplyTime is Immediate (GET request)
GET https://$bmc/redfish/v1/UpdateService
{
"@odata.context": "/redfish/v1/$metadata#UpdateService.UpdateService",
"@odata.id": "/redfish/v1/UpdateService", …

Redfish: ApplyTime property GET and PATCH support (SW471786)

---

include/openbmc_dbus_rest.hpp

Allow a value of true/false to be used to set a property value of type
byte. The boolean value will be translated to 1/0.
Tested:
$ curl -k -H "X-Auth-Token: $bmc_token" -X PUT -d '{"data":false}' https://$bmc/xyz/openbmc_project/software/8d622e87/attr/Priority
{
"data": null,
"message": "200 OK",
"status": "ok"
}
Signed-off-by: Adriana Kobylak <anoo@us.ibm.com>
Change-Id: I82f2acfe63c6fb6cc6130fb4c63552d0a45945f4

openbmc_dbus_rest: Support boolean value to set property of type byte

---

include/openbmc_dbus_rest.hpp

To be backwards compatible with OP910-OP930, need to return the invalid
path in the error message on REST api's. The xcat team relies on this
path to do post processing work.
Verified with xcat team that it is only the "path or object not found:"
error that requires this.
Tested:
Previous Response:
{
"data": {
"description": "org.freedesktop.DBus.Error.FileNotFound: path or object not found"
},
"message": "404 Not Found",
"status": "error"
}
New Response:
{
"data": {
"description": "org.freedesktop.DBus.Error.FileNotFound: path or object not found: /xyz/openbmc_project/sensors/chassis/PowerSupplyRedundancy"
},
"message": "404 Not Found",
"status": "error"
}

Return invalid path in REST error response

---

redfish-core/include/privileges.hpp
redfish-core/lib/roles.hpp

This commit, the revert, was merged into master here:
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/25319
Even though this change did remove permissions for the callback user to "GET" Redfish and /xyz resources it failed to prevent the callback user from using SOL console, KVM and attach virtual media devices. This change also introduced a Redfish Validator error.
Instead of this change, the callback role will be shown as a Read-only role with ssh, IPMI, WebUI, and Redfish access in the GUI User Management table and in documentation for OP940. This is more consistent.
This will close SW476583. Have reopened SW474799.
SW474799 will be deffered until a later release.
Original commit:
This reverts commit 8e69d148249f6a45cea10e988ec03430a5932784.
Reason for revert: This causes service …

SW476583: Revert "Fix remove callback user privilege access to login"

---

include/openbmc_dbus_rest.hpp

The REST call in this commit is needed for backward compatibility.
In earlier webserver(phosphor-rest-server), this API was available,
but not implemented in bmcweb.
So, this commit implements this API in bmcweb that enables resetting
the root user password.
Tested By:
curl -k -H "X-Auth-Token: $bmc_token" -d '{"Password":"0penBmc123"}' -X PATCH https://${bmc}/xyz/openbmc_project/user/root/action/SetPassword
Signed-off-by: asmithakarun <asmitk01@in.ibm.com>
Change-Id: I149d2dd9446ade976e57d447060150b24fb09228

Change to reset the password

---

include/openbmc_dbus_rest.hpp

XCAT makes a call to delete all event logs as
/xyz/openbmc_project/logging/action/deleteAll
This worked before OP940 because the phosphor-rest-server was
case insensitive for method names. bmcweb is case sensitive so
requires "DeleteAll".
This is the least invasive and simplest way to make
this work I could think of.
Considered creating a new phosphor-dbus-interface and
implementing it in phosphor-logging but this gets complicated fast.
Also considered making all of these case insensitive.
Tested:
Other methods appeared to work, as did deleteAll.
Before:
curl -b cjar -k -H 'Content-Type: application/json' -X POST \
-d '{"data":[]}' https://$bm/xyz/openbmc_project/logging/action/deleteAll
{
"data": {
"description": "The specified method cannot be found"
},
"message": "404 Not Found", …

Allow deleteAll to delete all logs

---

include/logging_middleware.hpp
include/openbmc_dbus_rest.hpp

(DO NOT MERGE)
Change to reset the password
The REST call in this commit is needed for backward compatibility.
In earlier webserver(phosphor-rest-server), this API was available,
but not implemented in bmcweb.
So, this commit implements this API in bmcweb that enables resetting
the root user password.
Tested By:
curl -k -H "X-Auth-Token: $bmc_token" -d '{"data":["0penBmc123"]}'
-X POST https://${bmc}/xyz/openbmc_project/user/root/action/SetPassword
Signed-off-by: asmithakarun <asmitk01@in.ibm.com>
Change-Id: I149d2dd9446ade976e57d447060150b24fb09228

In the previous pull request, the password was being displayed in the logs. This has the changes to fix it.

---

include/persistent_data_middleware.hpp
redfish-core/lib/network_protocol.hpp

If the ethernet interface is having the domain
name entry then Redfish GET request on network
manager protocol was crashing the bmcweb.
This commit fixes this behaviour.
Tested By:
Configure the Domain Name and run the GET request
on the network protocol: PASS
GET request on the network protocol even the
domain name was not configured : PASS
Redfish Validator: PASS
Signed-off-by: Ratan Gupta <ratagupt@linux.vnet.ibm.com>
Change-Id: I1e6cd6e3fe507ff375463ece1f6f10bae4d4fb6a

Fix crash during GET of manager network protocol

---

redfish-core/lib/ethernet.hpp

Tested by:
this commit has dependency on backend changes,phosphor-networkd commit
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/21088.
GET
PATCH -d '{"DHCPv4":{"FallbackAddress":"AutoConfig"}}'
PATCH -d '{"DHCPv4":{"FallbackAddress":"None"}}'
PATCH -d '{"DHCPv4":{"FallbackAddress":"Static"}}'
FallbackAddress is introduced in schema EthernetInterface.v1_5_0
Change-Id: Id7ef44a17d318d2bae1616f6d7a0614f7d4f25ee

Redfish:Add GET and PATCH support for DHCP FallbackAddress

---

redfish-core/lib/ethernet.hpp
static/redfish/v1/schema/EthernetInterface_v1.xml

Linklocal fallback is not working in op940, so reverting linklocal fallback option changes

Revert linklocal auto conf changes in bmcweb

---

crow/include/crow/routing.h
include/json_msg_utility.hpp
include/openbmc_dbus_rest.hpp
include/pam_authenticate.hpp
include/persistent_data_middleware.hpp
include/sessions.hpp
include/token_authorization_middleware.hpp
redfish-core/include/error_messages.hpp
redfish-core/include/node.hpp
redfish-core/include/privileges.hpp
redfish-core/lib/account_service.hpp
redfish-core/lib/redfish_sessions.hpp
redfish-core/src/error_messages.cpp

The first commit (d9d7571) is in review here: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/25146
This first set of changes was tested in an internal test driver.
Note that bmcweb master (file include/sessions.hpp) has diverged from the OP940 branch: In master, the userRole has been removed from the UserSession object and is looked up for every operation.  For OP940, the userRole is still present in the UserSession.
The second two commits are bug fixes for the SetPassword API and to allow basic auth (syntax like GET https://root:0penBMC@${BMC}/xyz/...) to proceed when the password is expired.  They have not been reviewed.

Op940.01 expired password

---

redfish-core/lib/account_service.hpp

SW474797: GUI User and Operator privileged users are unable to change their own account's password.
The Readonly and Operator roles need to access paths such as 
/redfish/v1/AccountService/ (AccountService schema) and
/redfish/v1/AccountService/Accounts (ManagerAccountCollection schema)
to change thier own password. 
They will need to get properties such as max and min password length which are at
/redfish/v1/AccountService/.
According to Redfish PrivilegeRegistry
https://redfish.dmtf.org/registries/Redfish_1.0.4_PrivilegeRegistry.json  
"GET" should be a "Login" Privilege for the ManagerAccountCollection
and AccountService resources.
This was changed in Redfish 2019.3, redfish issue 1914 explains
more but one of the reasons was this exact case. 
Upstream can be found at: …

Update privileges for sw474797

---

crow/include/crow/routing.h
include/json_msg_utility.hpp
include/openbmc_dbus_rest.hpp
include/pam_authenticate.hpp
include/persistent_data_middleware.hpp
include/sessions.hpp
include/token_authorization_middleware.hpp
redfish-core/include/error_messages.hpp
redfish-core/include/node.hpp
redfish-core/include/privileges.hpp
redfish-core/lib/account_service.hpp
redfish-core/lib/redfish_sessions.hpp
redfish-core/src/error_messages.cpp

This includes both PR#54 and PR#55 which constitute the BMCWeb PasswordChangeRequired fixes.  This brings OP940 up to the OP940.01 function.
- PR#54 was reviewed and included in OP940.01.
- PR#55 was reviewed and approved but did not make it into OP940.01.
Both sets of fixes were tested in their original PRs.  Testing for this PR included compiling successfully and very brief functional testing.

Op940 fixes for bmcweb from 940.01

---

redfish-core/lib/network_protocol.hpp

The Managers NTP node did not get implemented correctly.  The first
level parsing did not search for "NTP" as the base entry, nor did it
correctly attempt to acquire the NTPServers, NTPEnabled sub-nodes.
Removed the data response as it was returning a string vector instead
of a json::array. The original code caused a seg fault. Instead of
returning a carbon copy of the values sent, the return is a 204 code,
indicating success and returning no data.
Change-Id: Ifb82855e1cd143e3cf2cb8979531b01b27d32234
Signed-off-by: Johnathan Mantey <johnathanx.mantey@intel.com>

Redfish: Make PATCH NTP Servers operate correctly

---

include/ssl_key_handler.hpp

Currently bmcweb rejects the certificates  with  validity
starts after the current  time also replaces with self signed
certificate. This change will allow to install the certificate
with "notBefore" date after current time.

Allow certificate upload for "not yet valid" case

---

crow/include/crow/http_connection.h

The current image size limit is 30MB, which will cause some images to
fail to upload.
So it may be more reasonable to increase to 35MB.
Signed-off-by: Ben Pai <Ben_Pai@wistron.com>

Increase max http request body size to 35MB

---

redfish-core/lib/assembly.hpp
redfish-core/lib/chassis.hpp

A newer way of thinking in Redfish is for a simple rack server to have
one Redfish Chassis and things like boards modeled as Redfish
Assemblies under the Chassis.
This commit move Board under assembly. Moreover, if the association path
has "chassis/motherboard" or "/board/<Panel info>" this commit is able
to retrieve both information under assembly
busctl call xyz.openbmc_project.ObjectMapper \
/xyz/openbmc_project/object_mapper xyz.openbmc_project.ObjectMapper \
GetSubTreePaths sias /xyz/openbmc_project/ 0 1 \
xyz.openbmc_project.Inventory.Item.Board
as 2 "/xyz/openbmc_project/inventory/system/board/Blyth_Panel"
"/xyz/openbmc_project/inventory/system/board/Nisqually_Backplane"
Tested: manually tested on system …

Move Inventory.Item.Board from Chassis to Assembly

---

include/ibm/locks.hpp

BMC till now was saving the locks for HMC at BMC filesystem
"/var/lib/bmcweb/ibm-management-console/locks/ibm_mc_persistent_lock_data.json"
This commit removed this file, as there is no usecase for HMC-eBMC
interface to persist the lock record in a file and retrive the same
after a BMC reboot
HMC will need to re-acquire the locks after every BMC reboot. The
lock records will be only in-memory
Tested by:
1. With the patch, verified the lock records are not saved to the file
2. Removed the lock file and verified that its not created again for the
next acquireLock API
3. All other lock APIs are working fine (GET and DELETE)
Change-Id: Ib81634ef5bc1dbb6c906fabad8d95675e7d6a4ea

HMC Lock Management : Remove lock json file

---

redfish-core/lib/power.hpp
redfish-core/lib/redfish_util.hpp
redfish-core/lib/sensors.hpp

When we tried to Move Inventory.Item.Board from Chassis to Assembly
as you see in this commit:- https://github.com/ibm-openbmc/bmcweb/pull/75
this commit brack Redfish validator and we below error
- 1 failProp errors in /redfish/v1/Systems/system
- 2 failProp errors in /redfish/v1/Managers/bmc
- 1 problemResource errors in /redfish/v1/Chassis/Blyth_Panel
This error message we get.
ERROR - Links.Chassis[0]: GET of resource at URI /redfish/v1/Chassis/Blyth_Panel returned HTTP 404. Check URI.
This error we get because we tried to move Item.Board from chassis to assembly that might be affected other place.
https://github.ibm.com/Abhishek-Patel/openbmc/commit/761a771cd99bc428bce6bcd526adad3f7c8b3b3a
To fix that, we remove Item.Board from all below files, So they unable to retrieve association …

remove Item.Board from Power Redfish_util sensors

---

redfish-core/lib/systems.hpp

Add Model & CoreCount to ProcessorSummary
In Redfish ComputerSystem schema, the ProcessorSummary parameter
lists summary information of the Processors on the system. This commit
adds the 'Model' and 'CoreCount' properties to ProcessorSummary.
If the CPU Models are different, then the 'Model' field takes the first
entry in alphabetical order.
Testing:
1. Redfish Validator Testing successfully passed.
2. Curl testing:
curl -k -H "X-Auth-Token: $tok" https://$bmc/redfish/v1/Systems/system
...
"ProcessorSummary": {
"CoreCount": 24,
"Count": 2,
"Model": "test_name",
"Status": {
"HealthRollup": "OK",
"State": "Disabled"
}
},
...
Change-Id: Idda4f20bd1bb3f5002791ad20787979c632ed5f0 …

processorSummary edits

---

http/http_connection.hpp

This upstream commit https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/46831 merged today. 
This is a straight cherry-pick. 
This should fix the CI fail we are seeing in our -30 PR’s.
Commit msg:
The previous commit moved userSession to possibly be a per-request
structure.  Previously, it was only a per-connection structure, so there
wasn't explicit clearing of it in between requests.  This can lead to
problems where a user remains authorized despite explicitly logging
themselves out.
Tested:
redfishtool -S Always -A Session -u root -p 0penBmc -vvvvvvvvv -r 192.168.7.2 raw GET /redfish/v1/Managers/bmc
Succeeded
Then a subsequent:
curl -vvvv --insecure  "https://192.168.7.2/redfish/v1/Managers/bmc"
Failed with 401
Signed-off-by: Ed Tanous <edtanous@google.com>
Change-Id: …

Clear UserSession in between requests

---

redfish-core/include/redfish.hpp
redfish-core/lib/processor.hpp

Created this PR to pull the upstream patch (https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38570/43) to address the below comment.
- Enabled the Hardware Isolation (aka Guard) feature for Core and Memory #77 (comment)
**Note:** This upstream patch is required to enable the manual guard feature.

Implement SubProcessors for processor core

---

redfish-core/lib/event_service.hpp

This commit: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/46837 merged last week. 
This follows the spec. 
This should also fix 1 of the Validator errors George is seeing in -30.
Per the definition of HttpHeaders in the schema "This object shall be
null or an empty array in responses."  This commit does as the
specification commands.
In theory, this could break clients that were checking the HttpHeaders
after posting it, but it's not being put behind an option flag in this
patchset for a couple reasons:
1. This has the potential to leak security secrets, as the normal use
case for this is to put in Authorization headers.
2. Given that the most likely client that would "break" is the one doing
the POST to this API, and it already has the data, it seems unlikely
that there's any …

Nullify HttpHeaders per the specification

---

redfish-core/lib/chassis.hpp

https://github.ibm.com/openbmc/openbmc/pull/1376 is turning off
the old Power/Thermal.
When testing I did not see the ThermalSubsystem, on investigation
noticed this bad merge conflict resolve.
ThermalSubsystem should not be part of the BMCWEB_ALLOW_DEPRECATED_POWER_THERMAL
since is new and not deprecated. 
Tested: NONE

Thermal: Fix bad merge conflict resolve

---

http/http_connection.hpp

Because http connection can possibly fail on a bad host header, we need
to fill in the request object earlier in the flow.  This has the
potential to lead to use after free bugs, although in practice, we have
null checks, so it's a lower likelihood.
Tested:
Ran
redfishtool -S Always -A Session -u root -p 0penBmc -vvvvvvvvv -r 192.168.7.2 raw GET /redfish/v1/Managers/bmc
and verified it returned a 200 and the managers data structure.
Signed-off-by: Ed Tanous <edtanous@google.com>
Change-Id: I789d50f67dff14b769ccefacf55530b0b7c5c7cd

Fill in request earlier

---

redfish-core/lib/processor.hpp

Created this PR to address the below comments.
- Enabled the Hardware Isolation (aka Guard) feature for Core and Memory #77 (comment)
**Note:** 
- This workaround (Refer commit message for more details) patch is required to enable the manual guard feature. 
- This PR is created on top of https://github.com/ibm-openbmc/bmcweb/pull/95 so, please ignore the first commit in this PR.

Workaround to handle DCM (Dual-Chip Module) package for Redfish

---

meson.build
meson_options.txt
src/webserver_main.cpp

REST D-Bus, while providing useful functionality, also allows
authenticated users access to privileged information that may be above
their permission level. This change sets the default to disabled. Users
if they wish can turn it back on in their own layers.
A lot of functionality previously provided by REST D-Bus is now
available on Redfish with more coming all the time.
Note: phosphor-webui uses the REST D-Bus so a user of that will have to
enable this in their layer. webui-vue, the replacement for
phosphor-webui, uses Redfish. See here [1].
Resolves openbmc/bmcweb/issues/114
[1] https://github.com/openbmc/webui-vue
Tested: Rest D-Bus was disabled
Change-Id: I35682b113287b3be4e19b033d0296790b204d8e0
Signed-off-by: James Feist <james.feist@linux.intel.com>
Signed-off-by: Ali Ahmed …

Change Default of REST D-Bus to OFF

---

redfish-core/lib/chassis.hpp
redfish-core/lib/health.hpp

The health status of the current CPUs and powersupplies will not rollup
to chassis. This submission implements rollup of the health status of
CPUs and powersupplies to chassis.
Tested:
We need add the xyz.openbmc_project.Inventory.Item.Global interface to the chassis.
I create a critical association of powersupply1 using the same method as phosphor-logging:
https://github.com/openbmc/phosphor-logging/blob/76198a2ea2e3deb14078e0d3dd3932b657ddd9b8/extensions/openpower-pels/service_indicators.cpp#L83
Then the chassis HealthRollup will become critical:
curl -k -H "X-Auth-Token: $token" -X GET   https://${bmc}/redfish/v1/Chassis/chassis
"Status": {
"HealthRollup": "Critical",
},

Redfish: Implement HealthRollup in chassis schema

---

redfish-core/lib/systems.hpp

TrustedModuleRequiredToBoot is a sub-parameter of the 'Boot' parameter.
Edits the patch code to make sure the patch happens under
'{"Boot":{"TrustedModuleRequiredToBoot": false}}', instead of current:
'{"TrustedModuleRequiredToBoot":false}'.
Testing:
1) Curl testing:
curl -k -H "X-Auth-Token: $token" -X PATCH \
-d '{"Boot":{"TrustedModuleRequiredToBoot": true}}' \
https://${bmc}/redfish/v1/Systems/system
curl -k -H "X-Auth-Token: $token" \
https://${bmc}/redfish/v1/Systems/system
{
...
"Boot": {
"AutomaticRetryAttempts": 3,
"AutomaticRetryConfig": "Disabled",
"AutomaticRetryConfig@Redfish.AllowableValues": [
"Disabled",
"RetryAttempts"
],
"BootSourceOverrideEnabled": "Disabled",
"BootSourceOverrideTarget": "BiosSetup",
"BootSourceOverrideTarget@Redfish.AllowableValues": [
"None",
"Pxe", …

Move TPMRequiredToBoot under Boot for PATCH call

---

redfish-core/include/utils/hw_isolation.hpp
redfish-core/lib/memory.hpp
redfish-core/lib/processor.hpp

Created this PR to address the below comments.
- Enabled the Hardware Isolation (aka Guard) feature for Core and Memory #77 (comment)
**Note:** 
- This patch is required to enable the manual guard feature. 
- This PR is created on top of https://github.com/ibm-openbmc/bmcweb/pull/95 and https://github.com/ibm-openbmc/bmcweb/pull/96 so, please ignore the first two commits in this PR.

Enabled the Hardware Isolation (aka Guard) feature for Core and Memory

---

redfish-core/lib/log_services.hpp

This upstream  commit: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/46886
Add a ServiceProviderNotify property that can be used to indicate that
this event log should be notified to the service provider, if that is
implemented on the system.
ServiceProviderNotified is boolean true if notified, false otherwise.
@odata.type updated to  "#LogEntry.v1_9_0.LogEntry" to support
ServiceProviderNotified.
Tested:
Manually tested on the system, Run Redfish validator. Found no error.
https://${bmc}/redfish/v1/Systems/system/LogServices/EventLog/Entries
/{id}
{
"@odata.id": "/redfish/v1/Systems/system/LogServices/EventLog/
Entries/1",
"@odata.type": "#LogEntry.v1_9_0.LogEntry",
"AdditionalDataURI": "/redfish/v1/Systems/system/LogServices/ …

Add ServiceProviderNotify

---

redfish-core/lib/systems.hpp

This commit is added get and set for StopBootOnFault Policy.
The StopBootOnFault is defined in ComputerSystem(boot).
It contains two values "Never" and "AnyFault".
ref:https://redfish.dmtf.org/schemas/v1/ComputerSystem.v1_15_0.json
Tested:
1.Validator passes
2.doGet method to get StopBootOnFault.
https://${bmc}/redfish/v1/Systems/system
{
"@odata.type": "#ComputerSystem.v1_13_0.ComputerSystem",
...
"Boot": {
"AutomaticRetryAttempts": 3,
"AutomaticRetryConfig": "RetryAttempts",
"AutomaticRetryConfig@Redfish.AllowableValues": [
"Disabled",
"RetryAttempts"
],
"BootSourceOverrideEnabled": "Disabled",
"BootSourceOverrideMode": "Legacy",
"BootSourceOverrideTarget": "None", …

Add support for redfish StopBootOnFault

---

redfish-core/include/redfish.hpp
redfish-core/lib/log_services.hpp

This commit allows users of any privilege to access Event Log entries
with 'Hidden' property set to false. The Log entries with 'Hidden'
property set to true are only accessed by users with admin role.
This commit is for downstream only
Testing:
- Redfish-Service-Validator test passed for CELog endpoints
- Docker unit test passed
- Run the following curl commands:
1. curl -k -X GET
https://root:0penBmc@ever9bmc:18080/redfish/v1/Systems/system/LogServices/
2. curl -k -X GET
https://root:0penBmc@ever9bmc:18080/redfish/v1/Systems/system/LogServices\
/EventLog
3. curl -k -X GET
https://root:0penBmc@ever9bmc:18080/redfish/v1/Systems/system/LogServices\
/EventLog/Entries
- All non-hidden entries displayed (see entry format in test-4)
4. curl -k -X GET …

bmcweb: Add support for CE Event Log

---

redfish-core/lib/certificate_service.hpp

Post method:
1) /redfish/v1/CertificateService/Actions/
CertificateService.GenerateCSR/
ConfigureComponents-> ConfigureManager
This change allows only Admin users to Generate CSR Certificate and
restrict Operator user.
Tested: Ran curl Post requests with Admin and Operator privileged users
Get output as expected.
Email sent to openbmc list:
https://lists.ozlabs.org/pipermail/openbmc/2021-August/027232.html
Signed-off-by: Abhishek Patel <Abhishek.Patel@ibm.com>
Change-Id: I46d505357cfc55a31911e75e8bd9948a0db90555

Fix certificate_service privileges

---

redfish-core/include/registries/privilege_registry.hpp
redfish-core/lib/ethernet.hpp
redfish-core/lib/log_services.hpp
scripts/parse_registries.py

SubordinateOverrides:
This commit attempts to automate the creation of SubordinateOverrides
privileges structures from the redfish privilege registry. In
addition, it enhances the function of parse_registries.py.
It read SubordinateOverrides privilege registry from DMTF and
generates const defines SubordinateOverrides for all the privilege
registry entries in the same format that the Privileges struct
accepts.
Moreover, it generates unique const defines for all
SubordinateOverrides target levels.
Ex: EthernetInterface SubordinateOverrides has two "Targets":
["Manager", "EthernetInterfaceCollection"]. So
parse_registries.py generates two unique const
1) Subordinate override for Manager -> EthernetInterface
2) Subordinate override for Manager ->
EthernetInterfaceCollection -> …

Added SubordinateOverrides & Fix Log_services privileges

---

redfish-core/include/registries/privilege_registry.hpp
redfish-core/lib/hypervisor_system.hpp

As Teeks and I learned, if you run the parse registries script
downstream the outputted files don't match. This is becuase in
downstream we have a patch that edits the priviledge registry.
At the top of the file:
"// privilege_registry.hpp is generated.  Do not edit directly"
Respect that.
Downstream only since the following commit is downstream only:
https://github.com/ibm-openbmc/bmcweb/commit/cb2fecf012c7f20fa93b16bc799eb1a70f3c003b#diff-36d772115a7d28a9c1bbe1c848e05d4570875f056b876cec47513927088437f5
Tested: It builds. No Other testing.

Don't edit generated registries

---

include/obmc_console.hpp
meson.build
meson_options.txt
src/webserver_main.cpp

This commit adds `wss://${window.location.host}/console1` WebSocket
into bmcweb. it retrieves 'PHYP debug shell' info and displays
WebSocket data into WebUI using SOL (Serial over LAN) console.
'console1' read data from UNIX domain socket '@obmc-console.hypervisor'
and display it in WebUI.
Privilege set to {"ConfigureComponents", "ConfigureManager"}.
That mean only Administrator and Operator can retrieve console data.
Tested:
configure UNIX domain socket '@obmc-console.hypervisor' with
'wss://${window.location.host}/console0' (which currently use for
retrieve 'host serial console data on SOL'). The test is successful,
able to receive 'PHYP debug shell' data in SOL on WebUI.
Signed-off-by: Abhishek Patel <Abhishek.Patel@ibm.com>
Change-Id: Icece6ceddd0eeab8db7ebf1e5e863c22a59ae45f

Added Hypervisor Serial Socket

---

meson.build
redfish-core/include/event_service_manager.hpp
redfish-core/include/utils/telemetry_utils.hpp
redfish-core/lib/metric_report.hpp
redfish-core/lib/metric_report_definition.hpp
redfish-core/lib/sensors.hpp

PR to grab support for Telemetry service's: 1) MetricReport, 2) MetricDefinition, and 3) MetricReportDefinition resource collections. 
These changes add some Get, Push, Delete REST operations for the above collections. 
Note: The changes here were pulled from gerrit upstream. Some commits are still WIP and merit revisiting for improved support and functionality, especially once they are successfully reviewed and merged upstream. 
Upstream changes:
1. Sync Telmetry service with EventService: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38798
2. Switched bmcweb to use new telemetry service API: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/44270
3. Add support for MetricDefinition property in MetricReport:  https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/44512
4. Sync …

Initial Telemetry Service Framework

---

include/event_dbus_monitor.hpp
redfish-core/lib/log_services.hpp

Tested By:
Listing of an SBE dump:
** curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Systems/system/LogServices/Dump/Entries/SBE_7
{
"@odata.id": "/redfish/v1/Systems/system/LogServices/Dump/Entries/SBE_7",
"@odata.type": "#LogEntry.v1_7_0.LogEntry",
"AdditionalDataSizeBytes": 283079,
"AdditionalDataURI": "/redfish/v1/Systems/system/LogServices/Dump/Entries/SBE_7/attachment",
"Created": "2021-10-05T03:43:59+00:00",
"DiagnosticDataType": "OEM",
"EntryType": "Event",
"Id": "SBE_7",
"Name": "System Dump Entry",
"OEMDiagnosticDataType": "SBE"
}
Deletion of an SBE dump:
** curl -k -H "X-Auth-Token: $bmc_token" -X DELETE https://${bmc}/redfish/v1/Systems/system/LogServices/Dump/Entries/SBE_5
Clear all host dumps:
** curl -k -H "X-Auth-Token: $bmc_token" -X POST …

Add redfish support for SBE dumps

---

redfish-core/lib/event_service.hpp

When we refreshed bmcweb we pulled in https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/46874 which causes the SNMP stuff not to compile. Revert it for now until it can be refreshed  
This reverts commit 8daa31dcf745df01d4791402534ed6bcf1fe7bd2.

Revert "Redfish: Implement SNMP Trap" to fix compile fails

---

redfish-core/include/event_service_manager.hpp
redfish-core/lib/event_service.hpp

Implement SNMPTrap in EventDestination of Redfish. We can use
this Redfish interface to add/get/delete the SNMPTrap port and
destination address. When the error log is generated, phosphor-snmp
will send SNMPTrap messages to our configured SNMPTrap destination.
The MIB is here:
https://github.com/openbmc/phosphor-snmp/blob/master/mibs/NotificationMIB.txt
Refer:
https://www.dmtf.org/sites/default/files/standards/documents/DSP0268_2019.3.pdf
SNMPTrap test: Tested ok on the Witherspoon machine.
Steps are as follows:
1. Use this Redfish interface to configure the port and
destination address:
curl -k -H "X-Auth-Token: $token" -X POST   https://${bmc}/redfish/v1/EventService/Subscriptions   -d '{"Destination": "snmp://192.168.31.89:162", "SubscriptionType": "SNMPTrap", "Protocol": "SNMPv2c"}' …

Redfish: Implement SNMP Trap

---

redfish-core/lib/systems.hpp

Upstream is https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/44564 but this also includes getting the model. 
This should no impact, just moves the code closer to what is upstream.
In Redfish ComputerSystem schema, the ProcessorSummary parameter
lists summary information of the Processors on the system. This commit
adds the 'Model' and 'CoreCount' properties to ProcessorSummary.
If the CPU Models are different, then the 'Model' field takes the first
entry in alphabetical order.
Testing:
1. Redfish Validator Testing successfully passed.
2. Curl testing:
curl -k -H "X-Auth-Token: $tok" https://$bmc/redfish/v1/Systems/system
...
"ProcessorSummary": {
"CoreCount": 24,
"Count": 2,
"Model": "test_name",
"Status": {
"HealthRollup": "OK",
"State": "Disabled"
}
},
... …

Add Model & CoreCount to ProcessorSummary

---

redfish-core/lib/log_services.hpp

Currently, the task timer is set to 3 minutes to listen
for the dump completion status. But the bmc dumps are
taking a bit longer timer than 3 minutes (around 4 minutes)
during ipl and the task timer expires with the task state set
to cancelled. Hence, with this change, the task timer is doubled
to 6 minutes to avoid the task timer expiration.
Tested By:
Poweron the host
Initiate bmc dump
Get on the task for task status and the created dump URI
Task status - Completed
Fixes the defect:
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW538120
Gerrit change:
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38954/58..59/redfish-core/lib/log_services.hpp#828

Increase the dump create task timer

---

redfish-core/lib/systems.hpp

Per recent internal team discussions, IBM will be disabling the
ForceRestart ResetType option. This is because the hypervisor firmware
on IBM based systems requires host reboots to always be graceful to
ensure certain BIOS settings are correctly set.
Tested:
curl -k -H "X-Auth-Token: $token" -X POST https://${bmc}/redfish/v1/Systems/system/Actions/ComputerSystem.Reset -d '{"ResetType": "ForceRestart"}'
{
"error": {
{
"Message": "The action Reset was submitted with the invalid parameter ForceRestart.",
"Reset",
"ForceRestart"
],
"MessageId": "Base.1.8.1.ActionParameterUnknown",
"MessageSeverity": "Warning",
"Resolution": "Correct the invalid parameter and resubmit the request if the operation failed."
} …

redfish: disable ForceRestart support

---

redfish-core/lib/account_service.hpp

Upstream is https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/48564
In Redfish spec, the Operator and Readonly group should only change
their own password using patch in ManagerAccount.
(because of their ConfigureSelf privilege).
Currently, they were able to change other properties like their RoleId.
This was introduced in
https://github.com/openbmc/bmcweb/commit/6c51eab135bb573c292d111170bc138b3a4b4eb0
https://www.dmtf.org/sites/default/files/standards/documents/DSP2046_2021.2.pdf
Test:
the 'xiao' is a Operator
~ curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"RoleId":"ReadOnly"}'
https://${bmc}/redfish/v1/AccountService/Accounts/xiao
{
"error": {
{
"Message": "There are insufficient privileges for the account
or …

Security: Stop Privilege Escalation 

---

http/http_client.hpp
http/http_connection.hpp
http/logging.hpp
include/authorization.hpp
include/event_dbus_monitor.hpp
src/webserver_main.cpp

Per a SoS meeting, enabling the error traces in bmcweb to better be able to debug issues. This is not uptreamable as the discussion there has continued to be that by default, no logging is enabled.

1020 100821 add error traces to bmcweb

---

redfish-core/include/redfish.hpp
redfish-core/lib/chassis.hpp
redfish-core/lib/environment_metrics.hpp

PR to grab support for EnvironmentMetrics:
Note: The changes here were pulled from gerrit upstream, and just solved some conflicts.
Upstream changes:
Add Redfish EnvironmentMetrics schema in bmcweb: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/43170
Add PowerLimitWatts in EnvironmentMetrics: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/47300

Environment metrics

---

redfish-core/lib/sensors.hpp

It was noticed recently when enabling bmcweb error traces to assist
with some debug, the journal was filling with logs like this:
Nov 09 21:23:46 p10bmc bmcweb[249]: (2021-11-09 21:23:46) [ERROR "sensors.hpp":2584] fan3_1 not in sensor list
Nov 09 21:23:46 p10bmc bmcweb[249]: (2021-11-09 21:23:46) [ERROR "sensors.hpp":2584] fan3_0 not in sensor list
Nov 09 21:23:46 p10bmc bmcweb[249]: (2021-11-09 21:23:46) [ERROR "sensors.hpp":2584] fan4_0 not in sensor list
...
This was the result of a test case reading a single sensor:
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Chassis/chassis/Sensors/fan4_1
This code logic is fairly complex but appears to get all sensors of the
type passed in, then iterates through them looking for the one(s) of
interest. This code path should …

redfish:sensors: change verbose error trace to debug

---

redfish-core/lib/log_services.hpp
static/redfish/v1/JsonSchemas/OemLogEntry/index.json
static/redfish/v1/schema/OemLogEntry_v1.xml

This commit adds a new oem property for user-trigerred
dumps, that will be used to indicate the session id of
the user that triggered the dump creation. When multiple
clients manages the bmc, there was a requirement that
which client has initiated the dump before offloading/
performing any operations on that dump. Hence, this prop
tags the session id of the redfish client that has initiated the
dump creation.
There is a discussion at DMTF to add this property to
the redfish end-point on LogEntry schema. This can
be also used for audit purposes. Please see
https://redfishforum.com/thread/547/usage-originofcondition-parameter-logentry-schema
So right now, this property has been added to
oemlogentry schema that was added here:
https://github.com/ibm-openbmc/bmcweb/pull/121/files
The dbus …

Add GeneratorId prop to LogEntry schema for user trigerred dumps

---

http/http_client.hpp
redfish-core/include/event_service_manager.hpp
redfish-core/lib/event_service.hpp

When the BMC is rebooted, the persisted httpHeader was not
sent to the http client object. Thus the custom headers set
by the subscriber were not sent along with the events
This commit inititalizes the http client connection after the
custom headers are loaded to the subscriber after a BMC reset
Tested by:
1. Create new subscription with http custom header and see events
are received by the subscriber
2. Reboot the BMC and check the further events are reported good
Signed-off-by: sunharis <sunharis@gfwa129.aus.stglabs.ibm.com>
Change-Id: I87295e7ed4d3d94786dead370351a69ec9ef1982

EventService: Fix the httpHeader initialization

---

redfish-core/lib/processor.hpp

- In this patch, added the DCM workaround to the processor
PATCH request handler function which is missed early.
- Refer to "4b9628f" commit for the workaround details i.e the BMC
inventory modeled the processor as DCM (Dual-Chip Module) package
but, the Redfish doesn't support the DCM so added the workaround
for that.
Tested:
- Without fix:
```
curl -k -H "X-Auth-Token: $bmc_token" -X PATCH \
https://${bmc}/redfish/v1/Systems/system/Processors/dcm0-cpu0 \
-d '{ "LocationIndicatorActive" : false }'
{
"error": {
{
"Message": "The requested resource of type \
#Processor.v1_12_0.Processor named dcm0-cpu0 \
was not found.",
"#Processor.v1_12_0.Processor",
"dcm0-cpu0"
],
"MessageId": …
```

redfish-core: Processor: Fixed the processor object search

---

redfish-core/lib/fan.hpp

https://github.com/ibm-openbmc/bmcweb/pull/163/files
introduced clang-format and clang-format fails.
You can see these fails at: 
https://github.com/ibm-openbmc/bmcweb/pull/169
```
```
```
clang/../redfish-core/include/../lib/fan.hpp:408:5: [0m[0;1;31merror: [0m[1mdo not use 'else' after 'return' [readability-else-after-return,-warnings-as-errors][0m
else
```

Run clang-format and clang-tidy to fix CI

---

include/dump_offload.hpp
redfish-core/lib/environment_metrics.hpp

2 fixes here, both are legit potential bugs, especially the 2nd.
1)  Fix potential null pointer dereference
When building with buildtype=debug:
| ../git/include/dump_offload.hpp:168:34: error: potential nullreference]
|   168 |                 this->dumpSize = *dumpsize;
|       |
This has been a issue for a while.
Slack discussion here on this:
https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1635947639390400
I took this fix from https://github.ibm.com/openbmc/bmcweb/pull/89/files
2)  Bail if controlMode is invalid  
This error was introduced in #135
When buildtype=debug:
../lib/environment_metrics.hpp:354:52: error: 'powerCapEnable' may be used
uninitialized in this function [-Werror=maybe-uninitialized]
Add the return.
Tested: bmcweb builds with buildtype=debug. Did not do any …

Fix buildtype=debug

---

redfish-core/include/redfish.hpp
redfish-core/lib/update_service.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemUpdateService/index.json
static/redfish/v1/schema/OemUpdateService_v1.xml

This commit adds a new update command to be used by
the management console to perform concurrent updates.
It works like the current update command, but with
added support for the OnReset apply time setting.
Tested: Ensured that redfish command updates as usual
and updates still occured while the ApplyTime was in
the OnReset state.

Redfish OEM Update Command for Concurrent Update

---

redfish-core/lib/ethernet.hpp
redfish-core/lib/hypervisor_system.hpp

This commit removes few unnecessary error logs in hyp_ethernet and
ethernet header files and changes them to debug level traces.
Tested By:
Before the changes:
Nov 26 06:10:46 bmc bmcweb[264]: (2021-11-26 06:10:46) [ERROR "hyperv \
isor_system.hpp":211] Got extra property: Type on the /xyz/openbmc_pr \
oject/network/hypervisor/eth0/ipv4/addr0 object
Nov 26 06:10:46 bmc bmcweb[264]: (2021-11-26 06:10:46) [ERROR "hyperv \
isor_system.hpp":211] Got extra property: Origin on the /xyz/openbmc_ \
project/network/hypervisor/eth1/ipv4/addr0 object
Nov 26 06:10:46 bmc bmcweb[264]: (2021-11-26 06:10:46) [ERROR "hyperv \
isor_system.hpp":211] Got extra property: Type on the /xyz/openbmc_pr \
oject/network/hypervisor/eth1/ipv4/addr0 object
After changes:
These traces wont be logged unless the bmcweb …

Change errors to debug level traces

---

redfish-core/lib/assembly.hpp

This commit implements change to use util api to fetch
prettyName property for any given assembly and publish
it as "Name" in assembly schema.
In case prettyName is blank for that FRU, then last part
of the object path will be used to populate assembly name.
Validator executed with no new errors.
Sample Output:
curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Chassis/chassis/Assembly/
{
"Assemblies": [
{
"@odata.id": "/redfish/v1/Chassis/chassis/Assembly#/Assemblies/0",
"Location": {
"ServiceLabel": "U78DB.ND0.WZS000B-P0"
}
},
"MemberId": "0",
"Model": "2E2F",
"Name": …

Util api to fetch pretty name for assemblies

---

http/http_connection.hpp
http/timer_queue.hpp

During the system boot, huge request-reponse exchange between the
managemenet console and BMC intermittently causes the queue overflow
resulting in closing the tcp socket used for the communication.
The re-attempt requests and the other requests in flight gets SSL PeerShutdown
error and following requests in the queue will hit the SSL handshake
exception
This situation automatically recovers after the timer gets cancelled after
processing/failing the current requests in line. But by that time various
errors are hit at HMC and system will be moved to Incomplte/NoConnection/Error
state depending on the commands which randomly fail
This commit is to bump up the time queue size from 100 to 300, to make room
for the huge incoming traffix at bmcweb
Testedby:
On a dual HMC setup:
1. Several IPLs …

HMC-BMC: SSLHandshakeException fix

---

include/ibm/management_console_rest.hpp
include/login_routes.hpp
include/multipart_parser.hpp
include/ut/multipart_test.cpp
meson.build

As part of HMC performance improvement, this commit implements
multiple configfile upload with a single http request
This commit uses the upstream MIME parsing algorithm.
Upstream commit: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/34974
The 2nd commit is a downstream only based on https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/32174/
Tested by:
1. Multiple file upload
curl -k -H "X-Auth-Token: $bmc_token" -H "Content-Type: multipart/form-data"
-X POST https://${bmc}/ibm/v1/Host/ConfigFiles -F "testfile1=@<path>;type=application/octet-stream"
-F "testfile2=@<path>;type=application/octet-stream"
2. Tested the single file upload for sanity

Multipart parser

---

redfish-core/include/registries/openbmc_message_registry.hpp
redfish-core/include/utils/error_log_utils.hpp
redfish-core/include/utils/hw_isolation.hpp
redfish-core/lib/log_services.hpp
redfish-core/lib/memory.hpp
redfish-core/lib/processor.hpp

This is downstream changes (no Gerrit links for the added patches)
Below are Changes included in this PR:
- **LogServices: HardwareIsolation: Fixed the "AdditionalDataURI"**
- In the IBM platform system, recently the error entries are listed in the two different Redfish URI as mentioned below.
- /redfish/v1/Systems/system/LogServices/EventLog/Entries/N
- /redfish/v1/Systems/system/LogServices/CELog/Entries/N
- But, the HardwareIsolation LogEntry "AdditionalDataURI" property (which is used to point the associated error log entry) using the old link i.e "EventLog" so if the user tried to access the hidden error log through that property then, that won't work so fixed that issue in this PR.
- **LogServices: HardwareIsolation: Fixed the LogEntryCollection**
- Recently, the hardware isolation …

Enabled deconfiguration reason support to the DIMM and Core and Few fixes

---

redfish-core/lib/FabricAdapters.hpp

The commit upgrades the version of adapter schema from v_1_0_0
to v_1_1_0 in order to publish "LocationCode" property.

Version upgrade for adapter schema

---

redfish-core/lib/assembly.hpp

Add the Item.Connector and Item.Drive interfaces to
the list of interfaces we expose as Redfish inventories.

Redfish Assembly: Add More Inventory Types

---

redfish-core/include/redfish.hpp
redfish-core/lib/chassis.hpp

Noticed EnvironmentMetrics was not in the chassis resource after talking with the GUI team.
EnvironmentMetrics is part of the new PowerSubsystem, ThermalSubsystem
so move it under the correct option.
Also moved PowerSubsystem to make it correct and fixed redfish.hpp.
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/40326/26/redfish-core/lib/chassis.hpp
was correct upstream and left a comment on
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/43170.
BMCWEB_ALLOW_DEPRECATED_POWER_THERMAL is disabled downstream while
BMCWEB_NEW_POWERSUBSYSTEM_THERMALSUBSYSTEM is enabled downstream.
https://github.com/ibm-openbmc/openbmc/blob/1020/meta-ibm/recipes-phosphor/interfaces/bmcweb_%25.bbappend#L4
This is going to introduce a validator error when the system is off. This error isn't new, it …

Fix EnvironmentMetrics not showing

---

redfish-core/lib/FabricAdapters.hpp

This commit implement changes to populate link to PCIeDevice
schema in case the given Fabric adapter also implements
"xyz.openbmc_project.Inventory.Item.PCIeDevice" interface.
Sample output:
curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Systems/system/FabricAdapers/pcie_card10
{
"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/pcie_card10",
"@odata.type": "#FabricAdapter.v1_0_0.FabricAdapter",
"Id": "pcie_card10",
"Links": {
{
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/pcie_card10"
}
],
"PCIeDevices@odata.count": 1
},
"Location": {
"ServiceLabel": "U78DA.ND0.WZS0066-P0-C10"
}
},
"Model": "6B87",
"Name": "NVME JBOF  RISER",
"PartNumber": "03FL288",
"Ports": {
"@odata.id": …

Link Fabric adapter to PCIeDevice schema

---

http/http_connection.hpp
http/http_request.hpp
include/ut/multipart_test.cpp

Upstream is https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/47123/5 
This has been merged upstream, no problems have been observed upstream. 
This was suggested by @sunharis to pick up for the general performance improvement. 
I am not sure if we will see any real benefit here but it can't hurt and this commit is more correct.
The 2nd commit is making changes to include/ut/multipart_test.cpp to support this, something we recently pulled in. 
The 3rd commit is removing  several lines around query_params
Tested: GUI works including requests like powering on 
Orginal commit msg: 
In the current model, URLs get parsed twice, once to satisfy the
authenticate method, and once again later to satisfy the handle() call.
This commit deduplicates the parsing.  This is wasteful, and as of the …

Deduplicate url parsing code

---

include/ibm/locks.hpp
include/ibm/management_console_rest.hpp

This commit optimizes the release lock code and adds
some traces to give more data for lock conflict scenarios
Tested by:
1. With dual HMC, tested create & activate LPARs
2. Triggered lock conflict by starting create LPAR on both HMCs
at the same time
Change-Id: I13f642be2f98059ee3401d35a767863b6d78d225

HMC Lock management improvements

---

redfish-core/lib/FabricAdapters.hpp

The commit does a version upgrate for adapter schema.
The upgrade is required to include link to PCIeDevices
from adapter.
Validator has been executed and no new error has been found.

Fabric adapter version upgrade

---

redfish-core/lib/log_services.hpp

Currently create dump task timer set to 6 minutes
but in latest drivers MPIPL dump creation taking more time
so setting timer to 20 minute to make it for both rainier/everest
Defect is SW540793

GHE: Set create dump task timer to 20 minutes

---

redfish-core/lib/chassis.hpp

From original commit msg:
Spare part number field is missing from Chassis URI via Redfish
This commit added that.
Test:
curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}:${port}/redfish/v1/Chassis/chassis
{
"@odata.id": "/redfish/v1/Chassis/chassis",
"@odata.type": "#Chassis.v1_14_0.Chassis",
"Actions": {
"#Chassis.Reset": {
"@Redfish.ActionInfo": "/redfish/v1/Chassis/chassis/ResetActionInfo",
"target": "/redfish/v1/Chassis/chassis/Actions/Chassis.Reset"
}
},
"ChassisType": "RackMount",
"Id": "chassis",
...
"Location": {
"ServiceLabel": "U78DA.ND0.WZS0066"
}
},
"Model": "2E2D",
"Name": "chassis",
...
"PartNumber": "03KP024",
...
"PowerState": "Off",
...
"SerialNumber": "YF32UF18C00A",
"SparePartNumber": "02WG677", …

1020: Add Spare Part Number for Chassis

---

redfish-core/lib/pcie.hpp

The commit implement changes to handle empty "DeviceType"
in PCIeDevice schema.
The property expects an enum value  and since  Dbus object
path for PCIeDevices are primed the value fetched from D-Bus
can be empty for the field.
Validator has been executed an no new error has been found.

Handle empty enum values in PCIeDevice and PCIeFunctions

---

redfish-core/include/event_service_manager.hpp
redfish-core/lib/metric_report.hpp
redfish-core/lib/metric_report_definition.hpp

1) Refactor MetricReport in EventService.
2) Add CollectionTimeScope, CollectionFunction, CollectionDuration to MetricReportDefinition schema.
This PR requires a rebase of [Telemetry repo on upstream master for synchronization between bmcweb and telemetry binaries.](https://github.com/openbmc/telemetry/commits/master)
GHE-1020 srcrev bump: https://github.ibm.com/openbmc/openbmc/pull/1653 
NB:
1. Using ReportUpdate signal is no longer supported. Instead, Event Service monitors for PropertiesChanged signal from /xyz/openbmc_project/Telemetry/Reports path.  
Commits:
"Sync Telmetry service with EventService":
Change-Id: I2fc1841a6c9259a8bff30b34bddc0d4aabd41912
"Switched bmcweb to use new telemetry service API":
Change-Id: I2cd17069e3ea015c8f5571c29278f1d50536272a …

Telemetry MetricReportsDefinition Collections update

---

redfish-core/lib/chassis.hpp

The commit removes current support that assumes 1:1
system:Chassis for Chassis/PCIeDevices.
Current implementation populates the same collection of
PCIeDevices w.r.t chassis as w.r.t. system.
For systems with multiple chassis the current assumption
does not hold true.
Validator has been executed with no new errors.

Remove link from Chassis to PCIeDevice

---

redfish-core/lib/pcie_slots.hpp

PCIeSlots support empty JSON object in do PATCH command
Tested:
If we have 10 pcieslots,and we want to set 2nd slot's
LocationIndicatorActive to true, we can use the following command:
'{"Slots":[{},{"LocationIndicatorActive":true},{},{},{},{},{},{},{},{}]}'

Redfish: PCIeSlots support empty JSON object in do PATCH command

---

redfish-core/lib/hypervisor_system.hpp

This change removes the explicit setting of enabled property
to false whenever user configures a new ip. The flow will be
like: user configures an ip (patch) -> bmcweb calls the create ip
method of the dbus object -> ip address object will be updated with
user given values -> pldm sets the enabled property to true when the
host consumes it. bmcweb need not explicitly set the ip address.
Tested By:
* Poweroff host
GET https://${bmc}/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth1{
"@odata.id": "/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth1",
"@odata.type": "#EthernetInterface.v1_5_1.EthernetInterface",
"DHCPv4": {
"DHCPEnabled": false
},
"Description": "Hypervisor's Virtual Management Ethernet Interface",
"HostName": "hn",
"IPv4Addresses": [],
"IPv4StaticAddresses": [], …

Remove setting of enabled property of hyp eth obj

---

redfish-core/lib/systems.hpp

There are 2 fixes here. 1) To account for integer representation in
json and 2) To fix the initial coreCount value.
1) The ProcessorSummary CoreCount is interpreted as a json integer.
nlohmann::json::get_ptr() wants a nlohmann::json::number_integer_t,
which by default is std:int64_t.
Switched from uint64_t to int64_t to pick up the previous value set
for CoreCount.
2) Previously, the Redfish CoreCount was set to 0 if json::get_ptr
returned a nullptr. Really, Redfish CoreCount should be set to whatever
value was recieved from dbus.
Change-Id: Ie054d378154d152dda98df3d53b2966cb5928b22

Fix ProcessorSummary CoreCount

---

redfish-core/lib/bios.hpp

Bmcweb crashes when a bios attribute is patched with a value of
type that is not accepted. Say, when patching an attribute of
type string with other types - bool, float, int, bmcweb crashes
(current implementation). This pr fixes this issue by validating
the type of user given value in the redfish request.
This fixes the following defect:
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW541381
Upstream commit:
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38702
Tested By:
* Int datatype:
PATCH -d '{"Attributes": {"vmi_if0_ipv4_prefix_length": 22}}' https://${bmc}/redfish/v1/Systems/system/Bios/Settings
>> Success
PATCH -d '{"Attributes": {"vmi_if0_ipv4_prefix_length":"24"}}' https://${bmc}/redfish/v1/Systems/system/Bios/Settings
{ …

Fix bmcweb crash when patching bios attributes

---

http/http_client.hpp
http/http_connection.hpp
http/http_server.hpp
http/timer_queue.hpp

This reverts the following PR: 
https://github.com/ibm-openbmc/bmcweb/pull/207/files
reverts the following 5 commits: 
Add back error message from 
Implement connection limit
Deduplicate doAccept code
Make timer system use boost 
Revert "HMC-BMC: SSLHandshakeException fix
Test reported seeing CI code update fails, @geissonator was not able to reproduce that but was able to reproduce code update taking 5 times as long. 
We will live with what we have, "Sunitha's workaround which bumps up the timer queue from 100 to 300."
This was verified to fix on a CI machine.

Revert use boost timer with 100 connection limit

---

http/obmc_shell.hpp
meson.build
meson_options.txt
src/webserver_main.cpp

This commit includes a web-based shell, making it possible to access secure shell servers through standard web browsers using WebSocket. 
Path of WebSocket:
wss://{hostname}/bmc-console
Implementation:
So when bmcweb WebSocket gets a request for a new connection, it creates a child process of bmcweb using "/bin/sh" via calling bp::Child, which is similar to call exec("/bin/sh").
bmcweb is communicating with that child process using async_pipe. So the shell can execute all commands like ls, cd, etc.
Here shell WebSocket only retrieves individual charactor at a time.
WebSocket gets 'l', 's', and '\n' three char separately for the ls command. So bmcweb buffer them and pass to the child's process when it gets '\n'. In return child process return the output of that command. Which bmcweb return …

OBMC_SHELL web-base_shell

---

meson.build
meson_options.txt
redfish-core/lib/managers.hpp
redfish-core/lib/oem/ibm/usb_code_update.hpp
static/redfish/v1/JsonSchemas/OemManager/index.json
static/redfish/v1/schema/OemManager_v1.xml

Implement USB code update Enable/Disable.
This is an OEM schema.
Tested: Validator no error
First, we need to pick this commit:
https://gerrit.openbmc-project.xyz/c/openbmc/service-config-manager/+/48780/5
1. Get USB code update state
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Managers/bmc
{
"@odata.id": "/redfish/v1/Managers/bmc",
"@odata.type": "#Manager.v1_11_0.Manager",
...
"Oem": {
"@odata.id": "/redfish/v1/Managers/bmc#/Oem",
"@odata.type": "#OemManager.Oem",
"IBM": {
"USBCodeUpdateEnabled": true
},
"OpenBmc": {
"@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc",
"@odata.type": "#OemManager.OpenBmc",
"Certificates": {
"@odata.id": "/redfish/v1/Managers/bmc/Truststore/Certificates"
}
}
},
...
2. Set disable USB code update
curl -k -H "X-Auth-Token: $token" …

Redfish : Add USB code update Enable/Disable

---

redfish-core/include/registries/privilege_registry.hpp
scripts/parse_registries.py

Testing:
- The privilege_registry.hpp was generated successfully after running
the parse_registries script
- bmcweb was built with newly generated privilege registry file
Signed-off-by: Shantappa Teekappanavar <sbteeks@yahoo.com>

Bump up privilege_registry to Redfish_1.2.0

---

redfish-core/lib/systems.hpp

The following phosphor-dbus-interfaces commit introduced a new
BootProgress value:
https://github.com/openbmc/phosphor-dbus-interfaces/commit/d01d1f84191894ad605a9ba5b546280bcfc64f7d
Add support for this to the Redfish API provided by bmcweb.
Tested:
- Manually set BootProgress D-Bus property to SystemSetup and verify
busctl set-property xyz.openbmc_project.State.Host
/xyz/openbmc_project/state/host0 xyz.openbmc_project.State.Boot.Progress
BootProgress s
xyz.openbmc_project.State.Boot.Progress.ProgressStages.SystemSetup
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Systems/system
"BootProgress": {
"LastState": "SetupEntered"
},
- Verified validator passed when LastState was "SetupEntered"
Change-Id: Ie966766b88d2923bc0d10d89370713c7b17df14b
Signed-off-by: Andrew …

boot-progress: add support for SetupEntered

---

redfish-core/lib/account_service.hpp

This got broke when moving to the Automate PrivilegeRegistry and was
correct before.
https://github.com/openbmc/bmcweb/commit/f5ffd8062e556cb3bdf5f441dd393e784b771e85
https://github.com/openbmc/bmcweb/blame/2c37b4b0f465344aeea311efd61fd9a217ad8e3e/redfish-core/lib/account_service.hpp#L569
This is moving AccountService patch privilege from Login to
ConfigureUsers, moving to what it was before.
Without this change a ReadOnly user could set the AccountUnlockTimeout
and patch LDAP.
Upstream is https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/50094 and has been merged 
Defect is https://w3.rchland.ibm.com/projects/bestquest/?defect=SW541092
Change-Id: I7fe3727e0909fe5c94b655bbb3bbc7ce7b3c842a

Fix AccountService patch privileges

---

redfish-core/lib/chassis.hpp

https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/48719 added
support for the Chassis SparePartNumber. SparePartNumber was added to
the Chassis schema in v1_16_0 so need to bump the Chassis schema.
Bumped to v1_16_0 instead of the latest (v1_18_0) due to old guidance
from Redfish "only bump the schema if you need to". I.e. only bump if
using some property, etc in the schema. bmcweb has followed this.
The validator flags this as:
ERROR - SparePartNumber not defined in schema Chassis.v1_14_0 (check
version, spelling and casing)
From https://redfish.dmtf.org/schemas/v1/Chassis.v1_18_0.json:
"SparePartNumber": {
"description": "The spare part number of the chassis.",
...
"versionAdded": "v1_16_0"
},
Upstream is https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/50092 and has been …

Bump Chassis schema to fix error

---

redfish-core/include/error_messages.hpp
redfish-core/include/license_messages.hpp
redfish-core/include/registries/license_message_registry.hpp
redfish-core/lib/license_service.hpp
redfish-core/lib/message_registries.hpp
redfish-core/src/error_messages.cpp
scripts/parse_registries.py

This commit implements redfish License registry schema to handle  license errors 
Tested By: 
curl -k -H "X-Auth-Token: $bmc_token" -H "Content-Type: application/octet-stream" -X  POST https://${bmc}/redfish/v1/LicenseService/Licenses -d '{"LicenseString": "CA1F000000412C200000gyLzCwvb3rRUTg"}'
{
"error": {
{
"@odata.type": "#Message.v1_0_0.Message",
"Message": "Indicates that the license is not applicable to the target.",
"MessageArgs": null,
"MessageId": "License.1.0.0.notApplicableToTarget",
"Resolution": "None.",
"Severity": "Critical"
}
],
"code": "License.1.0.0.notApplicableToTarget",
"message": "Indicates that the license is not applicable to the target."
}
}bash-4.2$ curl -k -H "X-Auth-Token: $bmc_token" -H "Content-Type: application/octet-stream" -X …

Add LicenseRegistry support

---

redfish-core/lib/assembly.hpp

Look for the OperationalStatus to set the Assembly Health.
If the OperationalStatus is false, then set the Health to "Critical"
If the OperationalStatus is true, then the Health is "OK"

Redfish: Implements Redfish Assembly Health

---

bmcweb.service.in
http/routing.hpp

bmcweb now can start without any defined dependencies on the
user manager application. But bmcweb requires the user manager
to be up and running to serve the incoming requests while checking
the user authorization
This commit adds this runtime dependancy to the bmcweb and an
improvement at the GetUserInfo failure trace
Tested by:
1. BMC reboot with test image
2. Connect redfish client and reboot the BMC and see all
incoming commands are processed good after reboot
3. No GetUserInfo failures observed while rebooting the bmc
Change-Id: Ic444f9c7b8e04ee31b6414224c3ec66dc4009070

Add pre-req to phosphor-user-manager service

---

redfish-core/lib/managers.hpp

Currently BMC PowerState hardcoded to "On" on redfish interface.
this commit adds check to display bmc state based on current bmc state on state manager D-bus 
This is to fix HMC-BMC defect SW541358
Tested by:
GET /redfish/v1/Managers/bmc for different bmc states
Redfish validator passed

Return right BMC state to the redfish client

---

redfish-core/lib/managers.hpp

Implement LocationIndicatorActive property for Manager.
We can use the following command to set LocationIndicatorActive to true or false:
curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"LocationIndicatorActive":false}' https://${bmc}/redfish/v1/Managers/bmc

Redfish: Implement LocationIndicatorActive Property for Manager

---

include/dbus_utility.hpp
redfish-core/lib/processor.hpp

The following typedefs that are commonly used by redfish services
to get dbus subtree objects:
MapperServiceMap =
std::vector<std::pair<std::string, std::vector<std::string>>>
MapperGetSubTreeResponse =
std::vector<std::pair<std::string, MapperServiceMap>>
This commit adds the above mentioned typedefs to dbus utility namespace
and removes locally defined typedefs in processor.hpp.
Testing:
Validator: No errors
Few sample outputs from curl command:
$ curl -k -X GET https://{$bmc}/redfish/v1/Systems/system/Processors
{
"@odata.id": "/redfish/v1/Systems/system/Processors",
"@odata.type": "#ProcessorCollection.ProcessorCollection",
"Members": [
{
"@odata.id": "/redfish/v1/Systems/system/Processors/dcm0-cpu0"
},
{
"@odata.id": "/redfish/v1/Systems/system/Processors/dcm0-cpu1"
},
{
"@odata.id": …

bmcweb: Add/Move common typedefs to dbus utility

---

redfish-core/include/error_messages.hpp
redfish-core/include/privileges.hpp
redfish-core/lib/account_service.hpp
redfish-core/lib/roles.hpp
redfish-core/src/error_messages.cpp

This adds a new OEM Redfish privilege OemIBMPerformService. This is needed
to mark REST API operations which should be restricted to the service user.
This adds a new custom Redfish role OemIBMServiceAgent which corresponds to
the priv-oemibmserviceagent role in phosphor-user-manager. This role has
all privileges including the new OemIBMPerformService privilege.
Tested:
Tested only local users, not LDAP RemoteRoleMapping.
Tested on a system which had the new OemIBMServiceAgent role.
Setup: Ensure there is a "service" use who has role=OemIBMPerformService.
How? Log into the BMC command shell as the root user:
useradd service -G priv-oemibmserviceagent,web,redfish
-m -N -s /bin/sh -e ""
passwd service ---enter the password twice---
systemctl restart xyz.openbmc_project.User.Manager.service …

Add newRedfish role OemIBMServiceAgent

---

include/openbmc_dbus_rest.hpp
include/source_location.hpp
include/ssl_key_handler.hpp
meson.build
redfish-core/include/error_messages.hpp
redfish-core/lib/redfish_util.hpp
redfish-core/src/error_messages.cpp

The goal here is to just bring in the upstream commit to add logging when a InternalError is returned to the user. The features in that commit though required c++20. Bringing in c++20 brought in other upstream commit requirements. Nothing seems all that risky here but there are quite a few commits. The only one I didn't pull in from upstream is the last one. I'm pretty sure this was also fixed upstream but in a more complex manner. I went with the simpler solution in our downstream code (utilize auto).
Upstream Commits:
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/49313
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/48547
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/47574
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/49650 …

Add logging to internal error

---

redfish-core/lib/power_subsystem.hpp

Change the PowerSubsystem Id from "1" to "PowerSubsystem"
Before: 
```
curl -k https://$bmc/redfish/v1/Chassis/chassis15361/PowerSubsystem
{
"@odata.id": "/redfish/v1/Chassis/chassis15361/PowerSubsystem",
"@odata.type": "#PowerSubsystem.v1_0_0.PowerSubsystem",
"Id": "1",
"Name": "Power Subsystem for Chassis",
"PowerSupplies": {
"@odata.id": "/redfish/v1/Chassis/chassis15361/PowerSubsystem/PowerSupplies"
}
}
$ curl -k https://$bmc/redfish/v1/Chassis/chassis15361/ThermalSubsystem
{
"@odata.id": "/redfish/v1/Chassis/chassis15361/ThermalSubsystem",
"@odata.type": "#ThermalSubsystem.v1_0_0.ThermalSubsystem",
"Fans": {
"@odata.id": "/redfish/v1/Chassis/chassis15361/ThermalSubsystem/Fans"
},
"Id": "ThermalSubsystem", <---- Make it match the ThermalSubsystem Id and a most other resources 
"Name": …
```

Fix PowerSubsystem Id

---

redfish-core/lib/fan.hpp

1. Missing fan "Health" state not updated to reflect "Functional"
dbus property for fan
https://github.com/ibm-openbmc/dev/issues/3449
2. Repeatedly adding [ERROR "fan.hpp":587] The fan obtained at this
time does not belong to chassis to journal
https://github.com/ibm-openbmc/dev/issues/3448

Fix bmcweb::redfish bug Fan Health does not reflect "Functional"

---

meson.build
meson_options.txt
redfish-core/lib/managers.hpp

This new option for the PID and Stepwise controllers Fan data here:
https://github.com/ibm-openbmc/bmcweb/blob/1020/static/redfish/v1/JsonSchemas/OemManager/index.json
fan-oem-data is defaulted to disable so these properties will no longer
appear on systems built from our downstream.
Tested: Redfish Validator passes. Manager resource looks good. USB code
update PATCH / GET still work.
With USB Code update enabled: 
```
"Oem": {
"@odata.id": "/redfish/v1/Managers/bmc#/Oem",
"@odata.type": "#OemManager.Oem",
"IBM": {
"@odata.id": "/redfish/v1/Managers/bmc#/Oem/IBM",
"@odata.type": "#OemManager.IBM",
"USBCodeUpdateEnabled": true
},
"OpenBmc": {
"@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc",
"@odata.type": "#OemManager.OpenBmc",
"Certificates": {
"@odata.id": …
```

Add new fan-oem-data meson option

---

redfish-core/lib/assembly.hpp

when we do a patch request on Assembly it gives following response:
'{"Assemblies":[{"MemberId" : "2", "LocationIndicatorActive":true}]}'
https://${BMC_IP}/redfish/v1/Chassis/chassis/Assembly
{
"Assemblies": [],
"Assemblies@odata.count": 0,
"Id": "Assembly",
"Name": "Assembly Collection"
}
This response is not expected. This commit will fix this issue.
Tested:
when we do a patch request on Assembly it does not give any response:
'{"Assemblies":[{"MemberId" : "2", "LocationIndicatorActive":true}]}'
https://${BMC_IP}/redfish/v1/Chassis/chassis/Assembly

Redfish: Fix issue of set Assemply LocationIndicatorActive

---

redfish-core/include/redfish.hpp
redfish-core/lib/cable.hpp
redfish-core/lib/service_root.hpp

This commit implements Cable and Cable collection schema
on bmcweb. 
Testing:
$ curl -k -X GET https://root:0penBmc@rain100bmc:18080/redfish/v1
{
"@odata.id": "/redfish/v1",
"@odata.type": "#ServiceRoot.v1_5_0.ServiceRoot",
"AccountService": {
"@odata.id": "/redfish/v1/AccountService"
},
"Cables": {
"@odata.id": "/redfish/v1/Cables"
},
...
}
$ curl -k -X GET https://root:0penBmc@rain100bmc:18080/redfish/v1/Cables
{
"@odata.id": "/redfish/v1/Cables",
"@odata.type": "#CableCollection.CableCollection",
"Description": "Collection of Cable Entries",
"Members": [
{
"@odata.id": "/redfish/v1/Cables/dp0_cable0"
},
{
"@odata.id": "/redfish/v1/Cables/dp0_cable1"
},
{
"@odata.id": "/redfish/v1/Cables/dp0_cable2"
},
{
"@odata.id": "/redfish/v1/Cables/dp0_cable3"
}
],
"Members@odata.count": 4,
"Name": …

Implement Cable schema

---

redfish-core/lib/ethernet.hpp
redfish-core/lib/managers.hpp
redfish-core/lib/storage.hpp
redfish-core/lib/systems.hpp
redfish-core/lib/task.hpp

Fixes https://github.com/ibm-openbmc/dev/issues/3459
health.hpp is based on https://github.com/openbmc/docs/blob/master/designs/redfish-health-rolllup.md
It uses an xyz.openbmc_project.Inventory.Item.Global to identify
resources that have a HealthRollup and then uses "critical" or
"warning" associations to set that HealthRollup. It is largely unused
by us downstream. The only place we are using healthRollup is chassis.
This change removes health.hpp expect from chassis.hpp.
Instead, we tend to use Functional to set the Health and haven't been
setting HealthRollup.
We actually have a few resources where we have a race condition with the Health.
E.g. With the introduction of https://github.com/ibm-openbmc/bmcweb/pull/221/files
which sets the BMC health, as does this health.hpp, it is a race …

Remove health.hpp calls where unneeded

---

include/dump_offload.hpp
redfish-core/lib/log_services.hpp

This commit is to return appropriate error for  invalid dump offload requests.
Fixes https://w3.rchland.ibm.com/projects/bestquest/?defect=SW542649
Tested by:
curl -k -H "X-Auth-Token: $bmc_token" -X GET -D header.txt https://${bmc}/redfish/v1/Systems/system/LogServices/Dump/Entries/System_1/attachment
bash-4.2$ cat header.txt 
HTTP/1.1 404 Not Found
bash-4.2$ 
bash-4.2$ curl -k -H "X-Auth-Token: $bmc_token" -X GET -D header.txt https://${bmc}/redfish/v1/Systems/system/LogServices/Dump/Entries/System_1
{
"error": {
{
"Message": "The requested resource of type System dump named System_1 was not found.",
"System dump",
"System_1"
],
"MessageId": "Base.1.8.1.ResourceNotFound",
"MessageSeverity": "Critical", …

Handle resource not found error while dump offload

---

redfish-core/lib/log_services.hpp

Currently, the issue is when trying to form the Redfish URI for
the isolated core, we are only looking at the parent object but, that
will fail for the core since the same core might exist in the other
the processor that might present in the different DCM so, switching to
the GetAncestors D-Bus API to get the parents id of the isolated
resource.
Tested:
- Without fix:
```
> curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/ \
Systems/system/LogServices/HardwareIsolation/Entries
{
"@odata.id": "/redfish/v1/Systems/system/LogServices/HardwareIsolation/ \
Entries",
"@odata.type": "#LogEntryCollection.LogEntryCollection",
"Description": "Collection of System Hardware Isolation Entries",
"Members": [
{
"@odata.id": "/redfish/v1/Systems/system/LogServices/ \ …
```

HW-Isolation: Fix, Use GetAncestors to get the parents id

---

redfish-core/lib/sensors.hpp

Refer: https://github.com/ibm-openbmc/dev/issues/3463
ThermalMetrics works but see excess traces in the Journal
```
curl -k https://$mybmc/redfish/v1/Chassis/chassis/ThermalSubsystem/ThermalMetrics/
{
"@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/ThermalMetrics",
"@odata.type": "#ThermalMetrics.v1_0_0.ThermalMetrics",
"Id": "ThermalMetrics",
"Name": "Chassis Thermal Metrics",
"TemperatureReadingsCelsius": [
{
"@odata.id": "/redfish/v1/Chassis/chassis/Sensors/PCIE_1_Temp",
"DataSourceUri": "/redfish/v1/Chassis/chassis/Sensors/PCIE_1_Temp",
"DeviceName": "PCIE_1_Temp",
"Reading": 29.0
},
{
"@odata.id": "/redfish/v1/Chassis/chassis/Sensors/NVMe_JBOF_Card_1_Temp",
"DataSourceUri": "/redfish/v1/Chassis/chassis/Sensors/NVMe_JBOF_Card_1_Temp",
"DeviceName": "NVMe_JBOF_Card_1_Temp", …
```

Remove excess traces in the ThermalMetrics Query

---

redfish-core/include/utils/error_log_utils.hpp

This PR will address the [SW542539](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW542539)
- The error log used to return in the Redfish response when the BMC
returns the DIMM or Core (deconfigured one) details, and hardware
isolation records.
- Currently, the bmcweb returns an internal error if failed to get
the error log for the above use case but, the user might be deleted
the error through Redfish or error log tool so, fixing to avoid
internal error, just skipping the respective Redfish property that's
used to return the error log URI and added the trace.
- Note, The deconfigured reason still be "Error" as per backend implementation
just skipping the error log URI property if there is a failure to get
the error log when the client tried to get DIMM or Core details.
Tested:
- …

HW-Isolation: Fix, Don't throw internal error if failed to get error log

---

http/http_connection.hpp

With the current 1min timeout, there are cases when the image upload
times out due to slow network connections.
Signed-off-by: Adriana Kobylak <anoo@us.ibm.com>

http_connection: Bump connection timeout to 3min

---

http/http_client.hpp
include/event_service_store.hpp
include/persistent_data.hpp
redfish-core/include/event_service_manager.hpp
redfish-core/lib/event_service.hpp

Push style eventing implements sendEvent retries based on the
maximum retry limits set at the event service. When the max retry
is hit, it means that the subscriber is gone and bmc need not
attempt sending the event to that suscriber when next event occurs.
BMC should delete the subcription in this case.
Current implementation does not delete the subscription on hitting
maximum number of sendEvent retries. This overloads the http_client
at bmc to attempt a sendEvent to a non-existing or stale subscription.
This commit implements
1. Delete subscription after max retires
2. Store subscription id as a member of subscriber
3. Some trace enhancements at http client
Tested by:
1. Subscribe to events and close the subscriber abruptly to see
bmc retries and after all retry attempt failures, stops …

Push-style event: Delete subscriber after retry failures

---

meson.build
redfish-core/include/utils/stl_utils.hpp
redfish-core/lib/network_protocol.hpp
redfish-core/ut/stl_utils_test.cpp

This PR pulls two upstream commits related to ntp servers (that were merged long back).
1. Remove NTPServers duplicate values and null values
When saving the set NTPServers values from webUI, NTPServer may contain
duplicate values and null values and update them to D-Bus.
Now, need to parse and verify the value of the ntpServers attribute,and
remove duplicate values and null values.
2. Fix NTPServers are hard-coded for eth0
Since bmcweb is getting and patching NTPServers only from
'/xyz/openbmc_project/network/eth0' object, and this is hard-coded, if
we use eth1, it will broken the NTP configuration and fail to route to
the correct NTPServer.
All NTPServers of xyz.openbmc_project.Network.EthernetInterface
interface should be updated. …

Pull ntp related upstream commits

---

redfish-core/lib/chassis.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemChassis/index.json
static/redfish/v1/schema/OemChassis_v1.xml

Mex is updating via a lid in the host image, updated via PHYP.
PHYP sends an FRU record set PDR and sends the io enclosure version
data via the frurecord table and pldm parses that and hosts the
Version Interface on the mex chassis object.
This implementation retrieves that mex chassis FirmwareVersion data,
which defined via the manufacturer for the associated chassis, and
displayed on Redfish OEM schema for chassis.
Test: Tested Using Jankins validator. All Oem related checks are failing.

OEM - Enclosure Firmware Version

---

redfish-core/lib/sensors.hpp

Seeing "Sensor doesn't have a value interface" because a core dump
issue. To potentially debug this issue, incldue the Sensor Name.

Add Sensor Name to Debug trace

---

include/http_utility.hpp
include/ut/http_utility_test.cpp

Upstream is https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/50879
Defect is https://w3.rchland.ibm.com/projects/bestquest/?defect=SW542274 
Remove q-factor weighting on Accept Header
bmcweb does not do anything with the q-factor weighting (;q=) so just
remove it from the encoding.
This is needed because routes like
"/redfish/v1/Systems/system/LogServices/EventLog/Entries/<str>/attachment"
have a check for isOctetAccepted. Even though `*/* `is in the Accept
Header isOctetAccepted still fails due to the q-factor weighting.
On the system I tested, on firefox, Accept looks like:
`Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8`
On chrome it looks like: 
`Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image …

Fix download log entry details and says bad request

---

redfish-core/lib/oem/ibm/usb_code_update.hpp

If usb code update service is not available, to not return the data
associated with it, instead of returning an InternalError response for
it.

Not return InternalError when there is no usbcodeupdate service

---

redfish-core/lib/environment_metrics.hpp

Add the allowable range for the power cap/limit.
The AllowableMax and AllowableMin properties come from DBus.
Ran validator on hardware all EnvironmentMetrics passed.
Verified on hardware:
curl -s -k -X GET https://$bmc/redfish/v1/Chassis/chassis/EnvironmentMetrics
"Id": "EnvironmentMetrics",
"Name": "Chassis Environment Metrics",
"PowerLimitWatts": {
"AllowableMax": 3584,
"AllowableMin": 2700,
"ControlMode": "Disabled",
"SetPoint": 990
},
Change-Id: I7866b7243c56316fe7b883f58f4c2a88c62e2bdf
Signed-off-by: Chris Cain <cjcain@us.ibm.com>

EnvMetrics: Add AllowableMin/Max to PowerLimitWatts

---

redfish-core/lib/oem/ibm/lamp_test.hpp

debug as the function is not available yet.

SW541807 : FTC1020:Rainier: bmcweb error logs for lamp test to

---

redfish-core/lib/log_services.hpp

When Dump manager hits a org.freedesktop.DBus.Error.NoReply error
from the dbus, bmcweb returns Internal Server Error response to
the clients for the create dump request
This commit implements translating this dbus error to a meaningful
ServiceTemporarilyUnavailable error with 60 sec retry timeout
Tested by:
Create dump call is tested for sanity
Change-Id: I2d585b685150089874a893e8d85d6c4119ca807e

Dump Offload Error message improvement

---

http/http_stream.hpp
include/dump_offload.hpp

Return Service_Unavailable http code when dump manager/pldmd is not ready to offload dump
Currently bmcweb shares unix socket file path to dump manager/pldmd to connect
so that data can be transferred through socket.
In error case, pldmd/Dump manager may not setup socket and bmcweb tries to connect 3 times 
and returns 500 error code.
This commit modifies this error code to  Service_Unavailable
Tested By:
Ran offload dump in failure case where dump manager failure to start new process for dump offload.

DumpOffload: Return appropriate http error codes 

---

http/timer_queue.hpp

Bump the timer queue max size to 1000 as discussed in the design call on
3/1.
https://github.com/ibm-openbmc/bmcweb/pull/175 bumped this max size to
300 and the SSLHandshakeException largely went away but still
infrequently seeing them as SW544871, SW543056, and SW544631 shows. It
is largely unknown how the HMC can create enough requests to hit this
300 but bump to 1000 as a workaround.
Long term we will want to move to the new boost timer with 100
connection limit like upstream has  but when we did so here,
https://github.com/ibm-openbmc/bmcweb/pull/207, we were unable to code
update so that needs fixed first, tracked by
https://github.com/ibm-openbmc/dev/issues/3426.
1000 was choose arbitrarily, still wanted a max but big enough this
won't get in our way again.
Tested: Sanity testing …

HMC-BMC: SSLHandshakeException workaround

---

redfish-core/lib/power_supply.hpp

This commit makes use of the Available property on the power supply
D-Bus object when determining the power supply state and health in the
PowerSupply response.  The power supply monitor code from phosphor-power
will set the property to false if it can determine that the power supply
isn't able to provide power due to certain faults.
If the PS isn't available, then the Health property will be set to
Critical, and the State will be set to UnavailableOffline (assuming it
shouldn't be Absent instead).
This is necessary because on IBM systems the Functional property
determines the fault LED state as well as the health value, and in
certain cases the fault LED needs to stay off even though the PS health
is not OK.  A specific example of this is when the PS cord is unplugged:
no fault LED is …

Check PowerSupply availability prop for State/Hlth

---

include/dump_offload.hpp

Generally system/LPA dumps may take few mins to offload dump.
In slow network scenarios it may take few hours and client can choose to stop 
dump offload abruptly from client side.
This commit does unix socket cleanup when client abruptly closes
http connection while offloading dump.
This is downstream only since the dump offload is downstream only, 
we plan to upstream dump offload one day <or insert the real plan>
There isn't a defect for this but issue was seen without this change 
Tested by:
Interrupt curl command while offloading system dump 
Interrupt curl command while offloading LPA dump

DumpOffload: Clean up Unix Socket on abrupt http connection close

---

include/dump_offload.hpp
redfish-core/lib/log_services.hpp

These traces helps while debugging DUMP issues
1. In dump offload case, we have multiple defects where two HMCs connected
so we wanted to have trace which include client origin ip. so that we can confirm which HMC offloaded dump.
2. Printing Dump id to identify Dump in error case

Enhance DUMP debug traces

---

meson.build
meson_options.txt
redfish-core/lib/oem/ibm/system_attention_indicator.hpp
redfish-core/lib/systems.hpp
static/redfish/v1/JsonSchemas/OemComputerSystem/index.json
static/redfish/v1/schema/OemComputerSystem_v1.xml

This commit simplifies the IBM OEM LED functions in the ComputerSystem
schema. Instead of using multiple feature flags for system attention
indicator and lamp test, this collapses them to just one: `ibm-led-extensions`
This simplifies the patch code significantly, while fixing erroneous
"unknown property" responses.

Fix IBM OEM LED Bugs

---

redfish-core/include/error_messages.hpp
redfish-core/lib/account_service.hpp
redfish-core/src/error_messages.cpp

This commit enhances the redfish API to retrieve and set userGroups
information for each user account.
"Redfish" is always enabled in each user role. That's why it was
hardcoded into JSON response data in the old redfish API, where now it
gets retrieved using dbus interface xyz.openbmc_project.User.Attributes.
UserGroups.
UserGroups retrieve data are "redfish", "ssh", "web", and "ipmi", where
redfish DMTF Schema has predefined enum type as described below.
"AccountTypes": {
"enum":["Redfish", "SNMP", "OEM", "HostConsole", "ManagerConsole",
"IPMI", "KVMIP", "VirtualMedia", "WebUI"]
}
Here UserGroups ssh is mapped with two AccountTypes "HostConsole",
"ManagerConsole".
- Redfish ManagerConsole == SSH to port 22 == Phosphor User manager
Phosphor “ssh” privilege
- Redfish HostConsole == SSH to …

GET PATCH userGroups Information ("AccountTypes")

---

http/http_client.hpp
redfish-core/lib/event_service.hpp

As discussed in the 3/10 call, seeing cores when deleting a subsription,
SW545127 and
https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1644609233481139?thread_ts=1644608150.995019&cid=C0Q6TQP5Z
are 2 backtraces. The theory is the lack of locking between subsequent
calls is causing this. This tracing will help prove this.
Did not test, added traces only.

Add traces when deleting subsription

---

include/dump_offload.hpp

Currently bmcweb allows multiple dump offload request for both bmc and host dumps.
Allowing multiple requests causing issues.
1. pldmd crash due to no EID resources
2. dump manager dump file open issues
Here is one of the defect
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW545731
This commit  handles these cases by returning ServiceUnavailable to client
if one the connection is already offloading dump
With this commit
1. Only one bmc dump offload allowed at a time.
2. Only one host dump offload allowed at a time.
3. One BMC dump and one HOST dump allowed to offload parallely.
Tested by:
1. Test Offloading one host dump while another one is offloading.
2. Test Offloading one bmc dump while another one is offloading.
3. Test  One BMC dump and one HOST dump offload works …

DumpOffload: Allow only one dump offload at a time

---

http/http_client.hpp

When BMC hits a idle onnection timeout, and the subscriber
socket is closed, the next sendEvent fails with broken pipe
error. There is a 30 sec expire timeout for this socket and
this delays the next retry to 30 sec
This commit removed that 30 sec timer for sendMesage. Thus
after a send failure, the socket will be recreated immediately
Tested by:
1. CEC IPL and tested good path of events
2. Left the setup for more than 30 mins idle timeout which is
set at HMC. Then triggered an event to see the retry is done
immediately
Change-Id: I714722381bd204c9922bb297930c10e4b3a525c8

Push-style event: Remove 30 sec expire timer for sendMessage

---

redfish-core/lib/hypervisor_system.hpp

This commit enhances the logs with the values of
all the ip properties when a user tries to configure
a static ip along with the ip address of the user
who initiated the request.
Tested By:
Checked journal logs for the ip properties

Enhance logs for static ip config

---

redfish-core/lib/account_service.hpp

Fix StrictAccountTypes parameter set under ManagerAccount.
Fix:
StrictAccountTypes was attached under AccountService, which was wrong 
based on http://redfish.dmtf.org/schemas/v1/ManagerAccount.v1_8_1.json
this PR delete that StrictAccountTypes from AccountService and attach under
ManagerAccount and also update schemas version with the right version. 
This fixes the Validator Error George spotted.
Commit will be made upstream. 
Tested: 
using Redfish validator

Fix StrictAccountTypes Validator Error

---

include/dump_offload.hpp
include/event_dbus_monitor.hpp

Currently Power off/MPIPL allowed during System Dump offload and 
Socket and connection handler are not getting cleaned up.
This commit does clean up of connection handler and unix socket on Host Poweroff state change event.
Tested By:
Ran few iterations of create and offload system dump with HMC

DumpOffload: Handle poweroff during Dump offload

---

redfish-core/lib/processor.hpp

If State is UnavailableOffline or Absent, still allow Health to be set
to Critical.
This should fix part of SW545991.
This matches with what we do in like other places in processor.hpp, Assemblies, Fans, Memory etc: 
https://github.com/ibm-openbmc/bmcweb/blob/9d3146f5b2710c387f353846e23fc22b8fe42a99/redfish-core/lib/processor.hpp#L481

Health and State are independent

---

redfish-core/include/utils/hw_isolation.hpp

- Currently, The state of the isolated Core and DIMM will be set as
"Disabled" if the host tried to recover and mark it as functional
even if there is a hardware isolation record for the Core and DIMM.
- Fixed that by changing the state as Enabled if hardware isolation
status event is "Recovered".
Tested:
- Without Fix:
```
curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/ \
Systems/system/Processors/dcm0-cpu0/SubProcessors/core0
{
"@odata.id": "/redfish/v1/Systems/system/Processors/dcm0-cpu0/SubProcessors/core0",
"@odata.type": "#Processor.v1_12_0.Processor",
"Enabled": false,
"Id": "core0",
"Name": "core0",
"Status": {
"Conditions": [
{
"Message": "The reason for the resource isolation: Recovered",
"Recovered"
],
"MessageId": …
```

HW-Isolation: Fix, Update State if the Core and DIMM are recovered

---

redfish-core/include/utils/name_utils.hpp

getPrettyName method gets called more than one time.
required Service information to debug the error messages.
Enhancing util logging message to retire service information.
Signed-off-by: Abhishek Patel <Abhishek.Patel@ibm.com>

Enhance Name Utils Loggin

---

redfish-core/lib/systems.hpp

On the Control.Power.RestorePolicy interface, a value of "None" is
allowed on the PowerRestorePolicy property and Redfish should handle
this value instead of throwing an internal error. Until support of
"None" as a one time parameter is included into the Redfish schema,
return "AlwaysOff" to align with the dbus interface.
Tested:
Set PowerRestorePolicy to "None" enum value
Verified `PowerRestorePolicy` value is "AlwaysOff" thru Redfish
Set PowerRestorePolicy to "AlwaysOff" enum value
Verified `PowerRestorePolicy` value is "AlwaysOff" thru Redfish
Ran Redfish validator:
Elapsed time: 0:02:47
invalidPropertyValue: 44
metadataNamespaces: 2390
pass: 4384
passAction: 10
passGet: 212
passRedfishUri: 170
repeat: 1
skipNoSchema: 3
skipOptional: 4530
warnDeprecated: 319
warningPresent: 64 …

redfish:systems: Handle power restore policy of "None"

---

redfish-core/lib/account_service.hpp
redfish-core/lib/roles.hpp

This PR reverts a commit that added support for ldap priv-noaccess role
https://github.com/openbmc/bmcweb/commit/e9e6d240ab85e515f8d264e39b47a75043b73374

Revert "account_service: Added NoAccess role to Redfish"

---

bmcweb.service.in

This fixes SW546837, which is caused by a 500 because of the bmc state manager not being up.
We have seen several defects where bmcweb returns 500 on an interface
because the service providing the interface isn't up. A 500 leads to the
HMC going to no connection. It has been a whack a mole, where we don't
return 500 when the service isn't up. E.g.
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/50799.
For critical services like bmc state manager, let's just have bmcweb
start after. This will not be unstreamed at this time but do plan on discussing
this more upstream at a later date. 
Discussed here:
https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1648047781163589
Tested: Loaded on a system and did several reboots.
bmcweb looks good.
I see BMCState Manager start before
``` …
```

SW546837: Start bmcweb after bmc state manager

---

redfish-core/lib/systems.hpp

The Power.Mode and Power.IdlePowerSaver data is only available when the
occ-control service is running. During a BMC reboot the service may
temporarly not be available so this data can not be provided.
Redfish clients would bet getting internalErrors when the power data is
not available. This change will allow the other system data to be returned.
Change-Id: I5ce64ebde9789b900daaca6e84554351b35dfbad
Signed-off-by: Chris Cain <cjcain@us.ibm.com>

Prevent error when occ-control server not available

---

redfish-core/include/utils/hw_isolation.hpp

- The backend application will return the "InsufficientPermission" error
if the user is not allowed to clear the system isolated hardware entry.
- The Redfish service provider need to return an appropriate error
for the above case so added the support for the same.
Tested:
- Verified by clearing the system isolated hardware entry through the Redfish.
```
curl -k -H "X-Auth-Token: $bmc_token" -X PATCH https://${bmc}/redfish/v1/ \
Systems/system/Memory/dimm0 -d '{"Enabled" : true }'
{
"error": {
{
"Message": "The delete request failed because the resource requested cannot be deleted.",
"MessageId": "Base.1.8.1.ResourceCannotBeDeleted",
"MessageSeverity": "Critical",
"Resolution": "Do not attempt to …
```

HW-Isolation: Return ResourceCannotBeDeleted error

---

include/ibm/locks.hpp
redfish-core/ut/lock_test.cpp

When codeupdate was being performed from HMC, adding an IO
adaptor was allowed by BMC. This is due to a problem in
the lock algorithm, where if the resourceId bytes are matched,
lock conflict is not sent out to HMC
This commit sends lock conflict error for such scenarios
Testedby:
1. Manual curl commands to acquireLock using same resourceId
with different combinations of lock type
2. Tested the scenario of adding IO adaptor when code update
was running

HMC-BMC Lock management: Fix resourceId check

---

bmcweb.service.in

This fixes SW547232, which is caused by HMC not getting the system
state information.
The system state information is optional in the System schema and
today bmcweb just leaves off when the Host State Manager isn't up.
The HMC goes to a No Connection state though when it can't get this
information. The HMC team will change their code by looking for BMC
Ready state but to move forward let's just wait for Host State Manager.
Tested:
See bmcweb start after Host State Manager.
```
Mar 29 14:30:57 ever20bmc phosphor-hypervisor-state-manager[544]: Change to Hypervisor State: xyz.openbmc_project.State.Host.HostState.Off
Mar 29 14:30:57 ever20bmc systemd[1]: Started Phosphor Host State Manager.
Mar 29 14:30:57 ever20bmc systemd[1]: Started Start bmcweb server.
```
This pushed bmcweb back another …

SW547232: Start bmcweb after host state manager

---

redfish-core/lib/log_services.hpp

Dump manager return Unavailable error for delete operation
when then same dump offload is getting offloaded.
This PR maps Unavailable D-bus error to redfish
ServiceTemporaryUnavailable error.

DELETE Dump: Handle Unavailable D-bus error

---

redfish-core/lib/update_service.hpp

https://github.com/ibm-openbmc/bmcweb/commit/43691c15aaee5bf99eb142b063b9c5b1f4b423c6 added name_util::getPrettyName and one of the places it added it was Firmware Inventory (e.g. /redfish/v1/UpdateService/FirmwareInventory/7aaab73b). 
getPrettyName isn't as smart as it should probably be and it flags xyz.openbmc_project.Software.BMC.Updater and xyz.openbmc_project.Software.Version for having the same object (not just both having prettyName at the same object). 
We don't use PrettyName for Firmware Inventory so let's just remove this name_util::getPrettyName and save us a D-Bus call and the potential for this internalError.
The interalError seen on a rainier system was:
Mar 28 15:16:58 xxxx bmcweb[518]: (2022-03-28 15:16:58) [ERROR "name_utils.hpp":38] Invalid Service Size 2
Mar 28 …

Remove name_util::getPrettyName from FirmwareInventory

---

redfish-core/lib/hypervisor_system.hpp

Earlier, GET on the hypervisor ethernet interface hardcodes
InterfaceEnabled property of the redfish response as true and
vmi ip config data will be displayed based on the dbus object's
"Enabled" property - display ip when the property is true, else
return null.
With this change, the vmi ip config data will be displayed irrespective
of the "Enabled" property's value and InterfaceEnabled property of
the redfish response is mapped to the "Enabled" property of the dbus object.
This allows the client to know the configuration data, whether it is consumed
by host/not.
Tested By:
dbus introspect command for vmi eth interface:
busctl introspect xyz.openbmc_project.Network.Hypervisor /xyz/openbmc_project/network/hypervisor/eth1/ipv4/addr0
GET …

Display vmiIp irrespective of interfaceEnabled prop

---

http/http_client.hpp
include/event_service_store.hpp
include/persistent_data.hpp

We had a bmcweb crash when the subscriber is deleted using
redfish command after its marked for delete via the event
retry policy "TerminateAfterRetries"
This commit reverts the "TerminateAfterRetries" support
Tested by:
Send DELETE subscriber on a subscription which was set to
TerminateAfterRetries. Verified there is no bmcweb crash

Push-sytle eventing: Revert "TerminateAfterRetries

---

redfish-core/lib/event_service.hpp

This reverts commit ed4b3c0437b4293e9af9c200502e39b956824263.
Extra logging was added to debug SW545127.
SW545127 was fixed here:
https://github.com/ibm-openbmc/bmcweb/pull/303
Revert this commit that added the logging:
https://github.com/ibm-openbmc/bmcweb/pull/279/files
Note: The Log Error on TerminateAfterRetries in http/http_client.hpp
stayed due to thinking it would be useful and was touched in #303.
Reason for change: Help keep the journal clean/No longer needed. 
Testing: None. Straight forward change.

Revert "Add traces when deleting subsription (#279)"

---

include/dump_offload.hpp

This commit adds check to clean up connection handlers of system/resource dumps if there is a unexpected Poweroff during system or resource dump offload.
This is only needed for system/resource dumps
Other dumps like Hostboot, hw dump, and sbe dumps are stored on bmc
Fixes https://w3.rchland.ibm.com/projects/bestquest/?defect=SW547805
Tested by:
Power off while system dump offloading.
Power off while other host dump offloading

Reset connection handlers of resource/system dump on power off

---

redfish-core/lib/roles.hpp

This changes the Operator role to Restricted=true which means no users can have the Operator role.
Tested:
1. GET /redfish/v1/AccountService/Roles/Operator and ensure it has Restricted:true.
2. POST /redfish/v1/AccountService/Accounts/new with Role:Operator
Ensure it failed with message Base.1.9.0.RestrictedRole.
Posting a new Administrator user is successful.
3. PATCH /redfish/v1/AccountService/Accounts/ordinary with Role:Operator.  Ensure it failed.
Changing a user to the ReadOnly role is successful.
4. PATCH the OemIBMServiceAgent role as the LocalRole within the RemoteRoleMapping property && ensure it failed.

Restrict the Operator role

---

redfish-core/lib/network_protocol.hpp

There was no way to differentiate between the static and
DHCP assigned NTP servers. Networkd and Dbus has added
support for StaticNTPServers to save the static configuration
and NTPServers will be read-only and contain the current active
NTP servers at the system.
Tested by:
1. PATCH /redfish/v1/Managers/bmc/NetworkProtocol
-d '{"NTP" : { "NTPServers": ["9.3.1.2"]}}'
Verify that this adds the NTPs server to the NetworkProtocol
2. Enable DHCP to fetch NTP servers list from the DHCP server.
Verify that they are listed when GET on NetworkProtocol
Change-Id: Ifac77485485839292b770d36def35da17d723c4e

NetworkProtocol: Set StaticNTPServers dbus on PATCH

---

redfish-core/lib/sensors.hpp

Add humidity ReadingUnits and ReadingType
This should have been included in https://github.com/ibm-openbmc/bmcweb/pull/320
Tested: Built this code and loaded on a Rainier with a humidity sensor.
Validator passed.
Before with 320:
```
{
"@odata.id": ["/redfish/v1/Chassis/chassis/Sensors/Relative_Humidity"](https://rain104bmc.aus.stglabs.ibm.com/redfish/v1/Chassis/chassis/Sensors/Relative_Humidity),
"@odata.type": "#Sensor.v1_0_0.Sensor",
"Id": "Relative_Humidity",
"Name": "Relative Humidity",
"Reading": 58.532714841832004,
"ReadingRangeMax": 100.0,
"ReadingRangeMin": 0.0,
"Status": {
}
}
```
After: 
```
{
"@odata.id": ["/redfish/v1/Chassis/chassis/Sensors/Relative_Humidity"](https://rain104bmc.aus.stglabs.ibm.com:18080/redfish/v1/Chassis/chassis/Sensors/Re …
```

Sensors: Add humidity ReadingUnits and ReadingType

---

redfish-core/lib/event_service.hpp

The current DeliveryRetryIntervalSeconds range is 30 - 180 seconds. As
far as I can tell, this is arbitrary. Lower the minimum to 5 seconds
so the HMC can set it to this low. The current default will still be
30 seconds. The HMC wants this lower because the data might not be
correct by the time the event is retried. The reason for not lowering
further is concern about performance, a bunch of events retrying very
fast, and the more time, the more likely the 2nd and 3rd try will be
successful.
See defect https://w3.rchland.ibm.com/projects/bestquest/?defect=SW548556 
Before:
curl -k -X PATCH https://$bmc/redfish/v1/EventService/ -d '{"DeliveryRetryIntervalSeconds": 5}'
{
"error": {
{
"Message": "The value 5 for the query …

Allow a lower DeliveryRetryIntervalSeconds

---

redfish-core/lib/log_services.hpp

Dump manager returns Unavailable D-bus error when Dump-manager is not ready
to create dump.
This commit maps this D-bus error to ResourceInUse
Tested By:
Run create dump request while another dump creation going on

CreateDump: Return error while Dump-manager busy with other dump

---

redfish-core/include/redfish.hpp
redfish-core/lib/log_services.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemLogEntryAttachment/index.json
static/redfish/v1/schema/OemLogEntryAttachment_v1.xml

Add call to getPELJson for both EventLog and CELog log services.
Returns PEL in json format.
Dev story is https://github.com/ibm-openbmc/dev/issues/3538. 
This is downstream only. 
Commit message:
[Add call to getPELJson interface](https://github.com/ibm-openbmc/bmcweb/pull/324/commits/b3ff538190a1e2a7fa58daede4034ce6867cf173) 
Add call to getPELJson for both EventLog and CELog log services.
Returns PEL in json format.
EventLog path is redfish/v1/Systems/system/LogServices/EventLog
CELog    path is redfish/v1/Systems/system/LogServices/CELog
Tested:
1) Passed redfish validator
2) Curl testing passed
a) curl -k -H "X-Auth-Token: $token" -X GET \
https://$bmc/redfish/v1/Systems/system/LogServices/CELog/Entries/4/OemPelAttachment
{
"Oem": {
"@odata.type": "#OemLogEntryAttachment.Oem",
"IBM": …

Add call to getPELJson interface

---

redfish-core/include/error_messages.hpp
redfish-core/include/utils/hw_isolation.hpp
redfish-core/lib/log_services.hpp
redfish-core/src/error_messages.cpp

It fixes [SW547295](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW547295) - LogService: HW-Isolation: Return an appropriate error
- Hardware isolation D-Bus service errors:
- Returns "NotAllowed" error when the manual hardware isolation request
is not allowed during host power on or running.
- Redfish server returns "ChassisPowerStateOffRequired" error.
- Returns "InsufficientPermission" error when the user is not allowed
to delete the hardware isolation entry that's created by the system due to
some error.
- Redfish server returns "ResourceCannotBeDeleted" error for the DELETE
method request.
- Returns "InvalidArgument" if the given resource is unable to locate in the
backend system model (aka, device tree) to process the request.
- Redfish server returns …

LogService: HW-Isolation: Return an appropriate error

---

include/ibm/management_console_rest.hpp

Currently VMI cert timeout increased to 60 sec as a workaround due to VMI issue earlier.
VMI cert request is generally completed with in a second.
This commit sets max timeout back to 10 seconds.
Tested By:
Using SignCSR curl command

VMI Cert: Reduce timeout to 10 seconds

---

redfish-core/lib/account_service.hpp

Upstream is https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/47083 and merged in October. 
This error has been seen intermittently but @gkeishin reported it twice in the last 2 days, let's pull this in, fix the validator error, and keep the logs clean.
See more discussion at: https://ibm-systems-power.slack.com/archives/C1HT3FHNK/p1651161739925549
I did not personally test but this change is very straightforward.
The error looks like:
```
ERROR - OpenBMC: EntityType resource does not contain required @odata.id property, attempting default /OpenBMC
```
Original Commit Message:
Whomever wrote the AccountService oem properties seems to have forgotten
that all resources need an odata.id.
Tested:
Ran Redfish service validator.  No longer fails with:
ERROR - OpenBMC: EntityType resource …

Fix service validator on OEM account service

---

redfish-core/lib/log_services.hpp
redfish-core/lib/task.hpp

Currently, HMC doesn’t have a way to return an error on resource
dump create request.
When HMC requests for a resource dump collection, there wont be any
validation on the BMC, bmcweb starts a task and returns the same
as the redfish response. HMC will then poll on the Redfish task
before returning success/failure on the createDump request thread.
Now with this change, the flow will be like:
> CreateDump will return 202 with task url - (current behavior)
> Task will be created with initial state as 'Starting'
> Dump manager will set the DumpRequestStatus to Success when the
resource selector validation is success - (current behavior)
> With this change, bmcweb will change the taskstate to 'Running'
once the validation is Success
> HMC will poll the task URL to look for taskstate==Starting …

CreateDump: change the Task states for resource dump

---

http/app.hpp
http/http_connection.hpp
http/http_response.hpp
http/routing.hpp
http/websocket.hpp

This commit mainly implies support for asyncResp to handle upgrades for
WebSocket connection.
The current implementation uses the earlier method of using the response
object and calling response. end() to initiate completion handler.
This commit modifies the implementation to use asyncResp, where the
completion handler gets called asynchronously as the response object
goes out of scope.
This change is mainly for handling privilege into WebSocket connections.
test:
tested using bmc_console on the Rainer system. Able to test success cases.
Hard to reproduce failed test case.

SW549923: Add asyncResp support during handleUpgrade

---

redfish-core/lib/power_subsystem.hpp

Add the Allocation properties to the PowerSubsystem output.
Set the Redfish properties based on properties from the D-Bus
xyz.openbmc_project.Control.Power.Cap interface:
* Redfish AllocatedWatts property:
* Set to PowerCap property if PowerCapEnable is true
* Set to MaxPowerCapValue property if PowerCapEnable is false
* Redfish RequestedWatts property:
* Set to MaxPowerCapValue property
Tested:
* Passed the Redfish Validator
* For detailed test plan, see
https://gist.github.com/smccarney/cadb51e27e97d669b46426b91bd5f659
Example Output:
$ curl -k https://${bmc}/redfish/v1/Chassis/chassis/PowerSubsystem
{
"@odata.id": "/redfish/v1/Chassis/chassis/PowerSubsystem",
"@odata.type": "#PowerSubsystem.v1_0_0.PowerSubsystem",
"Allocation": {
"AllocatedWatts": 5020,
"RequestedWatts": 6111
},
"Id": …

PowerSubsystem: Add Allocation properties

---

http/app.hpp
http/obmc_shell.hpp
http/routing.hpp
include/dbus_monitor.hpp
include/kvm_websocket.hpp
include/obmc_console.hpp
include/obmc_hypervisor.hpp
include/vm_websocket.hpp

This commit enables a privilege check for the user(s) in case of upgraded
connections.
Previously there was no chack for WebSocket Privileges. Users with no
privileges will also be able to access WebSockets connections. For
bmc_console and other WebSocket privileges are defined, but they are
useless without check.
Here there are mainly two commits retrieved from upstream.
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/46990/1
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/46991/1
downstream PR is also there for WebSocket connection
establishment, mainly 101 checks (when WebSocket establishes connection).
https://github.com/ibm-openbmc/bmcweb/pull/322
Tested:
Tested using the rainier system, where bmc_console only creates
a WebSocket connection for the service user. Admin, …

SW549923: Add Support for WebSocket privilege check

---

redfish-core/include/utils/chassis_utils.hpp

williwakas is an assembly and this is how we associate slots to Flett(cable and pcie_slots).
now to describe association we need to provide a route path which we have in chassis assembly. 
chassis assembly has code that defines the route path for the chassis runtime. the code uses a member ID number in the route path which assigns runtime. Moreover, if someone removes that part from the chassis then its member ID also gets updated.
to fix this problem we have to have a similar code that generates a member ID number similar manner and provides proper indexing.
this code provides the same methodology to retrieve the member ID endpoint list with the same index.
So anyone can retrieve a list and find an index for that endpoint and use that index to build a route path.

Retrieve Chassis Assembly Interface

---

redfish-core/lib/pcie.hpp

This commit adds Status and Health elements to the json object of
PCIe Device when requested to get the device properties. These two
elements are derived from LinkStatus of the PCIe Slot.
This commit is downstream only.
Testing:
https://service:passwd@rain118bmc:18080/redfish/v1/Systems/system/PCIeDevices/pcie_card0
{
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/pcie_card0",
...
"Status": {
"Health": "Degraded",
}
}
https://service:passwd@rain118bmc:18080/redfish/v1/Systems/system/PCIeDevices/pcie_card0
{
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/pcie_card0",
...
"Status": {
"Health": 0,
"State": "Absent"
}
}
$ curl -k -X …

bmcweb: Add link Status and Health to PCIe device

---

redfish-core/lib/log_services.hpp

Dump D-bus entry "Elapsed" property value populated in microseconds
This commit converts microseconds to seconds to display correct timestamp
This PR Fixes SW550169
Tested By:
Get on Dump entry

Dump: Fix Epoch time convertion for Elapsed property

---

redfish-core/lib/service_root.hpp
static/redfish/v1/JsonSchemas/OemServiceRoot/index.json
static/redfish/v1/schema/OemServiceRoot_v1.xml

Partial fix for SW546530
This adds the Oem.IBM.ACFWindowActive boolean property to the Redfish service root at URI /redfish/v1.
Tested:
Via curl https://${BMC}/redfish/v1
Tested values true, false, and panel app not running.
Simulated pressing function 74 via busctl set-property "com.ibm.PanelApp"
"/com/ibm/panel_app" "com.ibm.panel" "ACFWindowActive" b true

Add ACFWindowActive to /redfish/v1

---

http/obmc_shell.hpp
include/obmc_hypervisor.hpp

https://w3.rchland.ibm.com/projects/bestquest/?defect=SW549923
bmcweb has limitations for WebSocket privilege, where none of the
current WebSocket checks for privilege before allowing users to access
WebSocket.
bmc-console need to check for a ser (privilege) before allowing a user
to access the console.
hypervisor console needs to check for a ser (privilege) before allowing
a user to access the hypervisor  console
based on the current bmcweb implementation, it is easy to check the
username for an upcoming request. So this commits checking for a
username before allowing a user to access the console. if a user's name
is "service," they can only access bmc-console.
this change is tested using the Rainier system.

SW549923: Only service user can access bmc-console/hypervisor

---

redfish-core/lib/pcie_slots.hpp

This commit adds PCIeSlot to NVMe backplane assembly link.
The link is listed in Oem property for each of the configured
PCIe slots.
This is for downstream only.
Issue: https://github.com/ibm-openbmc/dev/issues/3535
Testing:
- Validator test PASSED
- List properties for all PCIe Slots
https://service:passwd@rain127bmc:18080/redfish/v1/Chassis/chassis/PCIeSlots
{
"Slots": [
{
"Lanes": 0,
"Links": {
"Oem": [
{
"@odata.id":
"/redfish/v1/Chassis/chassis/Assembly#/Assemblies/24"
}
],
{
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/drive0"
}
]
},
},
...
https://service:passwd@rain127bmc:18080/redfish/v1/Chassis/chassis/Assembly#/Assemblies/24
{
...
{
"@odata.id": …

bmcweb: Add PCIeSlot to Associated assembly link

---

redfish-core/lib/account_service.hpp

The number of users was limited to 17 and redfish
logins were included in the IPMI group.
This PR prevents redfish users from being included
in the IPMI group which is limited to 15 users.
A seperate PR for phosphor-user-manager fixes the
problem that limited the total number of system
users to 15 and not the maximum of 30.
(Note the root user is not counted in the 30.)
Tested: Three IPMI users existed on the system.
A service user existed on the system. A script
was run to create 30 more redfish users.  The system
allowed the creation of 26 redfish users for a total
of 30 users.
tippolit@gfwa166:~/Code/openbmc/build/p10bmc$ curl -k -X
GET https://service:0penBmc0@ever8bmc:18080/redfish/v1
/AccountService/Accounts
{
"@odata.id": "/redfish/v1/AccountService/Accounts",
"@odata.type": …

Update to fix SW544220.

---

redfish-core/lib/power_supply.hpp

Mex-supported chassis does not support the power supply firmware version.
where current bmcweb code tries to retrieve that data even that interface is not supported via dbus.
adding an error check code will determine why it is failing.
if it failed because of `EBADR` then no return error in redfish API 
Tested: using the mex rainier system 
Defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW549511

MEX not Support PowerSupply FirmwareVersion

---

redfish-core/lib/pcie.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemPCIeDevice/index.json
static/redfish/v1/schema/OemPCIeDevice_v1.xml

This commit sets linkReset property to the requested value
This is downstream change only
Issue:
https://github.com/ibm-openbmc/dev/issues/3551
Redfish Validator: Passed
Testing:
Set LinkReset to 'true' using PATCH API, and verified the property using GET API
$ curl -k -X PATCH https://service:passwd@host:18080\
/redfish/v1/Systems/system/PCIeDevices/pcie_card0 -d '{"Oem": {"IBM": {"LinkReset": true}}}'
$ curl -k -X GET https://service:passwd@host:18080/redfish/v1/Systems/system/PCIeDevices/pcie_card0
{
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/pcie_card0",
"Id": "pcie_card0",
"Name": "PCIe Cable Card",
"Oem": {
"@odata.type": "#OemPCIeDevice.Oem",
"IBM": {
"@odata.type": "#OemPCIeDevice.IBM",
"LinkReset": true …

PCIe Topology: Redfish: Reset Link

---

bmcweb.service.in

Defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW550081
Currently our systemd service are automatically restarted on failure a
max of 2 times over 30 seconds. I.e. our current settings are:
StartLimitIntervalSec=30
StartLimitBurst=2
Done via https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/8400
Certificate manager restarts bmcweb when a new certificate is uploaded,
we have seen this happen 3 times in a 30 second period.
Allow bmcweb to be restarted 4 times over a 30 second period before
stopping. I.e. 
StartLimitIntervalSec=30
StartLimitBurst=4
This is a short term fix, the long term fix is Certificate manager will
throttle how often it restarts bmcweb or bmcweb doesn't require a restart.
Since bmcweb is critical to our operations, we are also okay with more retries. …

Increase bmcweb automatic restart

---

redfish-core/lib/log_services.hpp

When a user initiates a dump, the dump manager creates the
dump entry dbus object and bmcweb starts a task which monitors
property changed signal on this object. The task will be in its
initial state "Starting".
Now, in case of resource dump, the dbus call to create dump
expects additional parameters from the user, which will be
validated. Once the validation is successful, the task state
moves to "Running", if not it moves to "Cancelled".
But for the other dump types, there will be no validation
done on the user input. Hence, the task state should directly
move from "Starting" to "Running" and then to "Completed" once
the dump collection is successful.
This commit adds the change to move the task state to "Running"
once it is started, for all the dumps except resource dump.
Fix for the …

Move TaskState to Running for dumps except rsc dump

---

redfish-core/lib/cable.hpp

Add CableStatus, Status.State, Status.Health to cables collection
Testing
1) curl testing:
curl -k -H "X-Auth-Token: $t" https://$bmc/redfish/v1/Cables/dp0_cable1
{
"@odata.id": "/redfish/v1/Cables/dp0_cable1",
"Id": "dp0_cable1",
...
"Name": "Cable",
"Status": {
"State": "StandbyOffline"
}
}
2) validator testing passed for added properties

Add CableStatus, Status.State, Status.Health

---

http/http_stream.hpp
http/routing.hpp
include/dump_offload.hpp

As per design, pldm needs to reset OffloadURI while handling FileAck
after dump offload completed for resource and system dumps
for other dumps dump manager handles.
bmcweb still needs to reset OffloadUri on dump offload failure cases.
This is applies to all dump including BMC stored host dump and BMC dump 
This PR fixes SW548188 which is already MUST FIX approved
Tested by:
1.Few iterations of Offload system dump
2.Abruptly close connection while dump offloading
Note:

DumpOffload: Avoid reset OffloadUri on dump offload success

---

redfish-core/lib/systems.hpp
static/redfish/v1/JsonSchemas/OemComputerSystem/index.json
static/redfish/v1/schema/OemComputerSystem_v1.xml

SW551103: Add the ability to see when system is in safe mode.
Tested: caused safe mode in system. checked redfish OEM
Signed-off-by: Sheldon Bailey <baileysh@us.ibm.com>

Add safe mode to user interface

---

redfish-core/lib/metric_definition.hpp

[SW544335](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW544335): For TelemetryService MetricDefinitions, remove references to
redfish uri paths under old Power#/Thermal# schemas. These paths
are outdate and not supported.
For each MetricDefinition, under MetricProperties paths with
'Power#' or 'Thermal#' will no longer appear. This will reduce
the internal errors thrown for clients using TelemetryService.

Remove Power#/Thermal# Uris from MetricProperties

---

static/redfish/v1/schema/OemSession_v1.xml

The current OemSession schema file doesn't have a proper schema
declaration for the OemSession XML file.
because of that, Jenkins validator failed to validate Oem
"redfish/v1/SessionService/Sessions/{sessionID}" redfish value.
This commit fixes OemSeesion Schema.
Tested using Jenkins Validator. 
Defect:
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW550227

OemSessionSchema

---

redfish-core/lib/metric_report_definition.hpp

This commit fixes the core dump seen when the telemetry service returns when the argument list is too long.
for more info:
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW550900
Also saw at [SW549950](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW549950) and [SW551207](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW551207)
In the old code when bmcweb get `boost::system::errc::argument_list_too_long` error  it try to build JSON array object and pass that to the `messages::propertyValueIncorrect` method, which only accept string argument `nlohmann::json propertyValueIncorrect(const std::string& arg1,const std::string& arg2);`
, but that JSON array object gets upcasted to std::string object and get pass to that method (still need investigation why).
Then bmcweb …

Fix core dump at metricProperties when argument_list_too_long

---

redfish-core/lib/roles.hpp

SW546643: The Redfish GET API for AccountService role descriptions should return "ServiceAgent" for the case of the OemIBMServiceAgent role and not "OemIBMServiceAgent".
Tested:
/redfish/v1/AccountService/Roles/ROLE shows the intended descriptions.
Signed-off-by: Tom Ippolito <thomas.ippolito@ibm.com>

Update ServiceAgent role Description

---

redfish-core/lib/bios.hpp

This is 1 of 3 fixes for SW544661
BiosAttributeRegistry was ConfigureManager, that doesn't make sense and
was causing the GUI problems.
The upstream commit has moved to "Login", let's do the same.
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/29670/57/redfish-core/lib/bios.hpp#374
Redfish implies  (https://redfish.dmtf.org/registries/Redfish_1.2.0_PrivilegeRegistry.json) this should be login:
{
"Entity": "MessageRegistryFile",
"OperationMap": {
"GET": [
{
"Privilege": [
"Login"
]
}
],
The other registries are.
Just a bit of a question mark because https://redfish.dmtf.org/schemas/v1/MessageRegistryFile_v1.xml is really at /redfish/v1/Registries/{MessageRegistryFileId}
https://github.com/ibm-openbmc/bmcweb/blob/8044381620b228f99b707ea2b444c7675e714f26/redfish-core/lib/message_registries.hpp …

Part of SW544661: Change BiosAttributeRegistry to Login

---

redfish-core/lib/metric_report_definition.hpp

UnpackErrorReason moved to enum at
https://gerrit.openbmc.org/c/openbmc/sdbusplus/+/50321/24/include/sdbusplus/exception.hpp
We pulled https://gerrit.openbmc.org/c/openbmc/bmcweb/+/44270/43/redfish-core/lib/metric_report_definition.hpp
in but it hasn't merged upstream.
I was concerned about moving to something like:
`static_cast<int>(error.reason)`
due to CI passing but builds failing so just removed using this property.
Could bump [sdbusplus](https://github.ibm.com/openbmc/openbmc/blob/1020-ghe/meta-phosphor/recipes-extended/sdbusplus/sdbusplus-rev.inc) but I think this is just safest, remove this property all together. 
There is only 2 enums (missingProperty, wrongType). I don't think these Redfish messages get that much attention. 
This has to be addressed anyway upstream.
Tested: …

UnpackErrorReason moved to enum

---

include/ibm/management_console_rest.hpp

https://w3.rchland.ibm.com/projects/bestquest/?defect=SW551687
As decided, OCC passthrough should be service only:
https://app.slack.com/client/T0JA1U9GV/C0Q6TQP5Z/thread/C0Q6TQP5Z-1614612567.256600/1615218172.434700
For security concerns lock this interface down. 
This is downstream only. This OCC passthrough and this Service Agent are downstream only. 
Tested: For admin got Forbidden back. Service user still works. 

SW551687: Restrict OCC passthrough to service

---

include/ibm/management_console_rest.hpp

SW551763: When there is a 1000 partition configuration, HMC
is not able to install OS on all of them due to the
configFile directory size limit applied by BMC
The current limit is 10MB. HMC requires this to be
bumped up to 25MB.
This commit increases this upper limit
Tested by:
Checked the save area upload works with this change
Change-Id: Idcde692de9758e8eca3e9444beb2a4a9ff2bc36d

Bump up the ConfigFile directory max limit

---

include/ibm/management_console_rest.hpp

Currently, bmcweb returns 400 Bad request when there is a lock
conflict. HMC has a separate retry mechanism for lock conflict
and it expects 409 conflict error from bmcweb. So HMC cannot
detect 400 BAD Request error as lock conflict. Hence this change.
Fix for the defet at: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW551506
Tested.
Change-Id: I5eebf61d51e2788462ccb94794ad58455654437f

Return HTTP 409 Error for a lock conflict

---

redfish-core/lib/sensors.hpp

[SW551358](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW551358): Add the Accuracy property to power supply input power sensors.
The current implementation is a temporary measure to meet the near-term
deadlines.  A long term implementation that obtains the accuracy
information from D-Bus will be delivered at a later date.
Tested:
* Ran validator
* Tested with PowerSubsystem URI
* Verified no changes in output
* Tested with PowerSubsystem/PowerSupplies URI
* Verified no changes in output
* Tested with PowerSupply URI
* Verified no changes in output
* Tested with ThermalSubsystem URI
* Verified no changes in output
* Tested with ThermalSubsystem/ThermalMetrics URI
* Verified no changes in output
* Tested with Sensors URI
* Verified no changes in output
* Tested with …

sensors: Add Accuracy property to PS input power

---

redfish-core/include/task_messages.hpp
redfish-core/lib/task.hpp
redfish-core/lib/update_service.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemMessage/index.json
static/redfish/v1/schema/OemMessage_v1.xml

This commit provides a new Redfish OEM schema for Message that
will display error log information given a code update error.
This addition will provide users with a more detailed explanation
of the reason an update has failed.
Defect SW542946 (https://w3.rchland.ibm.com/projects/bestquest/?verb=view&id=SW542946)
Tested:
Ensured that upon code update failure, the task message included
the new OEM field where the corresponding error interface can be
displayed.
excerpt from validation pass:
Schema file OemMessage_v1.xml not found in ./SchemaFiles/metadata
Attempt 1 of /redfish/v1/schema/OemMessage_v1.xml
Response Time for GET to /redfish/v1/schema/OemMessage_v1.xml:
0.2782340639969334 seconds.
Writing online XML to file: OemMessage_v1.xml

Redfish OEM Message for Code Update Errors

---

redfish-core/include/task_messages.hpp
redfish-core/lib/task.hpp
redfish-core/lib/update_service.hpp
scripts/update_schemas.py

https://github.com/ibm-openbmc/bmcweb/pull/294 never had CI ran.
Seeing CI fail on commits like https://github.com/ibm-openbmc/bmcweb/pull/375
Remove the trailing spaces in python causing this.
Run clang-format for the C++ code. 

Fix CI code formatting

---

redfish-core/include/utils/fw_utils.hpp

Fix defect [SW551248](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW551248)
Discussed in discord here: https://discord.com/channels/775381525260664832/981260009256140852/981263933442785290
EBADR is the resource not found error code.
If we get one of those, just return when populating the firmware info for /redfish/v1/Managers/bmc.
We have saw where between the mapper call and the inner call here to
phosphor-bmc-code-mgmt, phosphor-bmc-code-mgmt deleted the iamge.
systemd[1]: Finished Delete image a from BMC storage.
bmcweb[698]: (2022-05-19 19:00:29) [ERROR "fw_utils.hpp":139] error_code = generic:53
bmcweb[698]: (2022-05-19 19:00:29) [ERROR "fw_utils.hpp":140] error msg = Invalid request descriptor
bmcweb[698]: (2022-05-19 19:00:29) [CRITICAL "error_messages.cpp":233] Internal …

SW551248: On code update EBADR ec don't throw error

---

redfish-core/lib/oem/ibm/pcie_topology_refresh.hpp
redfish-core/lib/systems.hpp
static/redfish/v1/JsonSchemas/OemComputerSystem/index.json
static/redfish/v1/schema/OemComputerSystem_v1.xml

This commit allows us to Patch and gets the PCIeTopologyRefresh property.
when this property is set to true allow PLDM to refresh PCIe topology data.
Tested :
```
curl -v -k -H "X-Auth-Token: $bmc_token" -X GET https://${BMC_IP}/redfish/v1/Systems/system/
{
...
....
"Oem": {
"IBM": {
"LampTest": false,
"PartitionSystemAttentionIndicator": false,
"PlatformSystemAttentionIndicator": true,
"SafeMode": false
}
},
....
...
}
```
```
curl -v -k -H "X-Auth-Token: $bmc_token" -X PATCH https://${BMC_IP}/redfish/v1/Systems/system/ -d '{"Oem":{"IBM":{"PCIeTopologyRefresh":true}}}'
// which set property true.
```
Run Jenkins validator.

Refresh of PCIe Topology

---

redfish-core/lib/ethernet.hpp

This PR remove AddressOrgin and AddressStatus from IPv6StaticAddresses
to fix redfish validator errors
Redfish Validator Passed

Fix redfish validator error for IPv6StaticAddresses

---

redfish-core/lib/ethernet.hpp

This commit has following changes
1.Adds "StatelessAddressAutoConfig" support
as per latest EthernetInterface.v1_8_0 schema.
2.Update schema version to EthernetInterface.v1_8_0
3.Remove support for deprecated Stateful and Stateless enums of
DHCPv6 "OperatingMode"
Tested by:
GET
PATCH -d '{"StatelessAddressAutoConfig": { "IPv6AutoConfigEnabled": true}}'
PATCH -d '{"StatelessAddressAutoConfig": { "IPv6AutoConfigEnabled": false}}'
PATCH -d '{"DHCPv6" : {"OperatingMode":"Enabled"}}'
PATCH -d '{"DHCPv6" : {"OperatingMode":"Disabled"}}'
Redfish Validator passed
Change-Id: I29d471750ef513074bc5e49c31a16fa15d3d760c

Add IPv6 StatelessAddressAutoConfiguration

---

redfish-core/lib/pcie_slots.hpp
static/redfish/v1/JsonSchemas/OemPCIeSlots/index.json
static/redfish/v1/schema/OemPCIeSlots_v1.xml

This commit Fix Oem Links for Associated Assembly.
Tested not throw error in validator:
curl -k -H 'X-Auth-Token: $bmc_token' -X GET https://${BMC_IP}/redfish/v1/Chassis/chassis/PCIeSlots
...
....
"Slots": [
{
"Lanes": 0,
"Links": {
"Oem": {
"IBM": {
"AssociatedAssembly": [
{
"@odata.id": ["/redfish/v1/Chassis/chassis/Assembly#/Assemblies/19"]}
]
}
},
...
....

Fix Oem AssociatedAssembly Link

---

redfish-core/lib/ethernet.hpp
redfish-core/lib/hypervisor_system.hpp

This PR pulls the following gerrit commits that add vmi ipv6 support:
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/45063
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/54109
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/54126
This PR also removes AddressOrgin and AddressStatus from IPv6StaticAddresses
to fix redfish validator errors.
Redfish Validator passed.

Add ipv6 support for hypervisor network configuration

---

include/ibm/locks.hpp
redfish-core/ut/lock_test.cpp

This PR fixes https://w3.rchland.ibm.com/projects/bestquest/?defect=SW551506
This PR  has following changes
1. Reverts https://github.com/ibm-openbmc/bmcweb/pull/295
2. Fixes isConflictRecord() method return value
Tested by:
Tested with all possible lock record combinations

Fix lock record comparison to identify lock conflicts

---

redfish-core/lib/pcie.hpp

The below commit update LanesInUse  data type that's why it was failing
https://github.com/ibm-openbmc/phosphor-dbus-interfaces/commit/9fe8e065b4e73a888483bafbc02d8397883d3763
this commit fixes data type to size_t to int64_t, which fixes this.
Tested: 
```
curl -k -H 'X-Auth-Token: $bmc_token' -X GET https://${BMC_IP}/redfish/v1/Systems/system/PCIeDevices/logical_slot2_io_module2_slot1_adapter1
{
...
...
"PCIeInterface": {
"LanesInUse": 4294967295
},
"Status": {
"State": "Absent"
}
...
...
}
```

 FIX LanesInUse data type

---

redfish-core/include/utils/fabric_util.hpp
redfish-core/lib/FabricAdapters.hpp
redfish-core/lib/cable.hpp
redfish-core/lib/port.hpp

Defect is https://w3.rchland.ibm.com/projects/bestquest/?defect=SW552762
This commit makesFabric Adapters objects unique, before this commit
bmcweb shows Fabric Adaptersobjects with the same path even though all
the dbus objects have unique paths
{"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/io_module1"},
{"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/io_module1"}
after this change bmcweb retrieve FabricAdapterdevice endpoint information and
then, replace redfish FabricAdapter device as
"chassisN-logical_slotN-io_moduleN".
Tested: Validator passed
Motherboard FabricAdapter also gets affected.
```
curl -k -H "X-Auth-Token: $token" -X GET  https://${bmc}/redfish/v1/Systems/system/FabricAdapters/
{
...
...
{"@odata.id": …
```

Build Fabric Adapters Unique Path

---

redfish-core/lib/ethernet.hpp

This commit removes ipv6 support on the bmc ethernet interfaces
thus not allowing user to configure static ipv6 address, enable/
disable dhcp v6 on ethernet interfaces, patch default gateway.
Defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW553310
Tested By:
PATCH -d '{"IPv6StaticAddresses":[{"Address": "<>", "PrefixLength": <>}], \
"IPv4StaticAddresses":[{"Address": "<>","SubnetMask": "<>","Gateway":"<>"}]}' \
https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth1
Change-Id: Ia73784510f21ffe0570420d4d70176aa54f2afbf

Remove bmc ipv6 support

---

static/redfish/v1/JsonSchemas/OemLogEntry/index.json
static/redfish/v1/schema/OemLogEntry_v1.xml

[SW551554](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW551554): OemLogEntry.v1_0_0.OpenBMC schema is not declared perfectly, which failed the Jenkin validator.
fix OemLogEntry schema fix Oem Log Entry Schema.
tested: this schema does not throw an error in Jenkin valiator.

Fix OemLogEntry Schema

---

redfish-core/lib/oem/ibm/pcie_topology_refresh.hpp
redfish-core/lib/systems.hpp
static/redfish/v1/JsonSchemas/OemComputerSystem/index.json
static/redfish/v1/schema/OemComputerSystem_v1.xml

This is the first part of https://w3.rchland.ibm.com/projects/bestquest/?defect=SW553479
This commit implements GET and PATCH for OEM IBM property Save PCIe Topology info.
SavePCIeTopologyInfo is boolean variable . This property when set to 'true' saves the topology information. The information is saved in the form of a PEL(Error Log).
Tested:  using Jenksin validator
```
curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${BMC_IP}/redfish/v1/Systems/system/
```
output:
```
{
...
"Oem": {
"IBM": {
"LampTest": false,
"PCIeTopologyRefresh": false,
"PartitionSystemAttentionIndicator": false,
"PlatformSystemAttentionIndicator": true,
"SafeMode": false,
"SavePCIeTopologyInfo": false
}
},
...
}
```
Patch:
``` …
```

PCIe Topology: SavePCIeTopologyInfo

---

redfish-core/lib/log_services.hpp

[SW553394](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW553394): When PEL's with guard entry are deleted the severity type of guard record changed from Predictive to Manual in Deconfiguration records page.
Redfish severity "Warning" is translated to either "Predictive/Manual" in GUI. GUI marks the guard record as "Manual" if associated errorlog entry object is not found.
When a PEL is deleted associated error log object is deleted and GUI should not treat the associated guard records as "Manual"
Now using severity "OK" from the redfish schema to specify manually created guard records.
Signed-off-by: Marri Devender Rao <devenrao@in.ibm.com>
Change-Id: Idaa622b002b5409858ff2bbd01f82b162d53fe8c

HW-Isolation: : map "Manual" error message to Logging severity "OK"

---

redfish-core/lib/oem/ibm/pcie_topology_refresh.hpp
redfish-core/lib/systems.hpp

This would be the fix for [SW553662](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW553662) if approved. 
I do want to note this is an error case, i.e. PLDM being stopped is an error case.
Redfish API is fully discoverable, which means things like the entire tree can be walked (hypermedia API) and properties that can be PATCHed are present in the GET.
There was 2 IBM OEM PCIETopology properties (SavePCIeTopologyInfo and PCIeTopologyRefresh) added to the PATCH of /redfish/v1/Systems/system. These properties are used on the GUI PCIe Topology page. Because they were added to the PATCH they have also been added to the /redfish/v1/Systems/system GET because of said Redfish rule above.
These properties call PLDM, when PLDM is down or hung …

Remove PCIe Topology Properties GET

---

include/obmc_console.hpp

Part of [SW553027](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW553027)
Currently, ReadOnly has access to the host console.
Restrict it to Admin or above.
This appears to add a half-second delay in starting the websocket (I assume this is for the dbus call). It is just noticeable but hard to measure (e.g. under a second).. Or I am going crazy. 
I followed code in https://github.com/ibm-openbmc/bmcweb/blob/8044381620b228f99b707ea2b444c7675e714f26/include/nbd_proxy.hpp#L417 
Tested: For a ReadOnly user I see 
```
websocket console0/ closed.
code: 1000
reason: Unathourized access
```
in the browser development tools console.
For Admin and Service the console works as normal as does the "Open in new tab". 
In the browser development tools console I see websocket console0/ opened …

Restrict host console to ConfigureManager

---

http/http_connection.hpp

https://w3.rchland.ibm.com/projects/bestquest/?defect=SW553617
Before this was 12 mins but have seen real examples of slow networks
hitting this 12 min timeout. Bump this timeout to 26 mins which should
support an upload speed of as low as 0.641 Mbit/s.
This will be all connections, not just code update.
This is definitely a bandage, long term:
1. code update connection timeout should not be the same as other
connection timeouts
2. We should install a lower code update timeout (e.g. 30 seconds) that
gets reset every time we get a packet
3. We should look at our image size, and make sure we can't make that
smaller
Tested: GUI works
Will continue to test 

Bump our connection timeout to 26 mins

---

redfish-core/lib/account_service.hpp

This changes the Redfish create new user API (POST /redfish/v1/AccountService/Accounts/) so only Administrator users will have the HostConsole AccountType value.  This is the same as the "ssh" phosphor privilege group.
Doing so prevents new ReadOnly users from using SSH port 2200.
Note that ReadOnly user created prior to this change will have the HostConsole AccountType privilege.  A BMC admin can PATCH a user's AccountTypes property to add or remove the HostConsole value.
Tested: Yes

ReadOnly users should not have ssh

---

include/security_headers.hpp

Fixes https://w3.rchland.ibm.com/projects/bestquest/?defect=SW554049
fw1020.10
Been merged upstream for 4 months. https://gerrit.openbmc.org/c/openbmc/bmcweb/+/52039
The HTTP Content-Security-Policy (CSP) plugin-types directive has been
removed from the specification and is not supported by most browsers.
Chrome browser suggests to specify "object-src 'none'" instead to block
plugins, so replace it with that directive.
Refer https://github.com/w3c/webappsec-csp/issues/394 for details about
this change.
Tested:
* In Chrome 99.0.4844.74, it no longer gives errors about CSP
plugin-types directive.
* Checked neiter <embed>, <object> or <applet> tags are used in eiter
phosphor-webui or webui-vue.
* Using webui-vue, KVM and SOL Console works.
Change-Id: I79d7ed1de2c4d204bf040e7b32a7b6afe354862c …

Replace CSP plugin-types directive with object-src

---

redfish-core/include/utils/chassis_utils.hpp

[SW554254](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW554254): IBM does not use the xyz.openbmc_project.Inventory.Item.Board interface for
chassis objects. Remove that interfaces so only objects implementing
xyz.openbmc_project.Inventory.Item.Chassis are returned for getValidChassisID
Testing not complete.
List of currently files using getValidChassisID():
1) redfish-core/lib/thermal_subsystem.hpp
2) redfish-core/lib/power_supply.hpp
3) redfish-core/lib/fan.hpp
4) redfish-core/lib/environment_metrics.hpp
5) redfish-core/lib/power_subsystem.hpp
6) redfish-core/lib/pcie_slots.hpp
7) redfish-core/lib/power_supply_metrics.hpp)

Remove Inventory.Item.Board interface from Chassis - FW1020.10

---

http/utility.hpp
redfish-core/lib/metric_report.hpp

This defect is https://w3.rchland.ibm.com/projects/bestquest/?defect=SW553937 and is marked for fw1020.10 
Telemetry service is using timestamp with milliseconds accuracy. Bmcweb
code assumed that timestamp is in seconds which produced a bad result.
This patchset updates the APIs, and adds a getDateTimeUintMs method,
which can be used to convert a millisecond timestamp into a string.
The work here is copied from upstream gerrit commit
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/50027.
The reason for selected copy from the upstream commit is preserve
getDateTime() function as is. Other Redfish services will continue
to use getDateTime() without any disruption.
Testing:
1) Redfish validator passed.
2) Curl output passed.
curl -k -H "X-Auth-Token: $token" -X GET \ …

Add getDateTimeUnitMs function

---

http/http_connection.hpp

Fix https://w3.rchland.ibm.com/projects/bestquest/?defect=SW554552
https://github.com/ibm-openbmc/bmcweb/commit/6dc5b8923fcecb3d3062e2b9a127262e4bfd26ed
added a trace for async_handshake failed.
These traces can clutter the journal and it isn't like the request is
actually failing.
Jul 15 15:19:49 z2331ebmc bmcweb[1835]: (2022-07-15 15:19:49) [ERROR "http_connection.hpp":303] 0x1945480async_handshake failed: asio.ssl error
Jul 15 15:19:49 z2331ebmc bmcweb[1835]: (2022-07-15 15:19:49) [ERROR "http_connection.hpp":303] 0x1c8f1c0async_handshake failed: asio.ssl error
Jul 15 15:19:49 z2331ebmc bmcweb[1835]: (2022-07-15 15:19:49) [ERROR "http_connection.hpp":303] 0x18810f8async_handshake failed: asio.ssl error
Jul 15 15:19:49 z2331ebmc bmcweb[1835]: (2022-07-15 15:19:49) [ERROR …

Remove async_handshake failed trace

---

http/obmc_shell.hpp
include/dump_offload.hpp
include/kvm_websocket.hpp
include/vm_websocket.hpp
redfish-core/include/server_sent_events.hpp
redfish-core/lib/sensors.hpp

Needed to move our downstream CI to more recent clang so changes we pull
in from upstream will pass. This found a few minor issues in our
downstream bmcweb code. I'm sure this is fixed upstream somewhere
already (since CI is passing against upstream code) but cherry picking
in changes from upstream is getting complex due to our divergent
streams. We'll just knock this one out when we fully rebase with
upstream in 1040

clang: default inits for variables

---

redfish-core/lib/log_services.hpp

Currently resource dump argument  parsing does not have
argument size checks so it tries to access out of bound index and crashes
when user does not pass last argument.
This commit fixes this issue by adding input argument size checks
Tested By:
Tested resource dumps with differnt resource strings
"OEMDiagnosticDataType":"Resource_vsp -globalfr"
"OEMDiagnosticDataType":"Resource_lp 2_pwd"

Resource Dump: Fix dump input argument checks

---

redfish-core/lib/log_services.hpp

Currently these traces are logged as Error traces which look like
an error case while looking at journal.
These Traces are needed for debug so making it as INFO traces
This PR fixes https://w3.rchland.ibm.com/projects/bestquest/?defect=SW554910

Dump: Move Error traces as INFO traces

---

redfish-core/lib/account_service.hpp

Currently LDAP configuration D-bus errors are not mapped to Redfish Errors,
so returing internalError irrespective of D-bus error.
This commit handles InvalidArgument D-bus error for LDAP config
Tested By:
Configure LDAP with various invalid arguments.
Change-Id: I6adaedd936fb3d9d906750649792a4d414b54b73

AccountService: Handle InvalidArgument D-bus errors

---

include/dbus_utility.hpp
redfish-core/lib/account_service.hpp
redfish-core/lib/assembly.hpp
redfish-core/lib/power_supply_metrics.hpp

Remove chassisID hardcoded hack. This was added to avoid showing Metrics
for MEX I/O drawer power supplies.
Add in a getValidInputHistory utility. Use associations to get the input
history aggregation items matched up with chassis and power supply.
Default the response to resourceNotFound. If a valid input history item
is found, clear the resourceNoteFound. Only return Redfish Metrics type
for aggregation items (average & maximum) that have an association. This
will avoid providing those Metrics for power supplies that do not
support it (MEX I/O drawer power supplies do not support input history).
Tested:
Rainier 2S2U + MEX I/O drawer
Verify Metrics for .../chassis/.../powersupply0 & 1
Verify error for non-existent powersupply on chassis.
Verify error for non-existent chassis1.
Verify …

Filter PowerSupplyMetrics via associations

---

redfish-core/lib/assembly.hpp

The commit make required changes to enable  panel CM
by initiating the deletion of base and LCD panel FRU
and re-collection of base and LCD panel FRU as and
when initiated via GUI.
Validator was executed for this commit. No error was reported.

Update schema to enable panel CM

---

static/redfish/v1/JsonSchemas/OemMessage/index.json
static/redfish/v1/schema/OemMessage_v1.xml

Redfish validator throws an error due to OemMessage EntityType resource
not containing the required @odata.id property.
This is defect https://w3.rchland.ibm.com/projects/bestquest/?defect=sw553910 
Should also go into 1030.
Testing:
Ran validator and verified the error is not thrown, and the overall
validator test passed.
Known Issue: Validator test gives WARNING/FAIL for OEM properties.
This is across all downstream OEM schemas. This needs to be handled
separately for all OEM schemas.
Signed-off-by: Shantappa Teekappanavar <sbteeks@yahoo.com>

Fix OemMessage Schema

---

bmcweb.service.in

This is a backport of https://github.com/ibm-openbmc/bmcweb/commit/5fbc4926b4de9a21c28b8099db78b5c424449661
* Increase bmcweb automatic restart
Currently our systemd service are automatically restarted on failure a
max of 3 times over 30 seconds. I.e. our current settings are:
StartLimitInterval=30
StartLimitBurst=3
Certificate manager restarts bmcweb when a new certificate is uploaded,
we have seen this happen more than 3 times in a 30 second period.
Allow bmcweb to be restarted 5 times over a 15 second period before
stopping.
This is a short term fix, the long term fix is Certificate manager will
throttle how often it restarts bmcweb.
* Address comments
Used StartLimitIntervalSec.
5 times over 20 seconds.
Put under [Unit]
Signed-off-by: …

Increase bmcweb automatic restart (#356)

---

redfish-core/include/error_messages.hpp
redfish-core/lib/bios.hpp
redfish-core/src/error_messages.cpp

Current implementation displays internal error message when BIOS
attribute value is not within the lower and upper bound values.
Also, the same internal error message is displayed when the length
of the String type value for the attribute to be updated is not
within the specified limit.
This commit displays property value out of range error message for
Integer type-based attributes in case of an error, and property value
incorrect for String type-based attributes.
Testing:
$ curl -k -X PATCH -d '{"Attributes":{"hb_mfg_flags_current":
"000000000000000000000000000000000"}}'
https://user:password@host/redfish/v1/Systems/system/Bios/Settings
{
"error": {
{
"Message": "The property 'hb_mfg_flags_current' with the
requested …

bmcweb: Add property value out of range error msg

---

redfish-core/lib/update_service.hpp

This is needed for 1020.20 and 1030.
This is for defect https://w3.rchland.ibm.com/projects/bestquest/?defect=SW556361 
Upstream is https://gerrit.openbmc.org/c/openbmc/bmcweb/+/56999
This 10 second timeout is for the write, untar, inotify fire, and creation of a software D-Bus object.
IBM has large images for its p10bmc, 200M for 1030 . We have seen this take longer than 10 seconds on a AST2600. Bump this timeout to 25 seconds.
Most of the 10 seconds seems to be the untar.
This default 10 seconds is only used for the http upload path. TFTP already bumps this timeout to 600 seconds.
https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/update_service.hpp#L488
Could have instead added the 25 seconds to the
monitorForSoftwareAvailable call but figured having the default be 25 is …

Bump timeout for code update file

---

redfish-core/lib/update_service.hpp

This is needed for 1020.20 and 1030.
This is for defect https://w3.rchland.ibm.com/projects/bestquest/?defect=SW556361
Upstream is https://gerrit.openbmc.org/c/openbmc/bmcweb/+/56999
https://github.com/ibm-openbmc/bmcweb/pull/432 is the original but this further increases the timeout (let's use that same defect.)
This timeout is for the write, untar, inotify fire, and creation of a software D-Bus object.
IBM has large images for its p10bmc, 125M and growing. We have seen this take longer than 10 seconds on a AST2600. Bump this timeout to 55 seconds.
Most of the 10 seconds seems to be the untar.
https://github.com/ibm-openbmc/bmcweb/pull/432 bumped this timeout to 25 but after discussing in SOS on 9/13/22 it was decided to bump to 55 due to moving to var and just safer this way. 
This …

Bump timeout for code update file to 55

---

redfish-core/lib/assembly.hpp

The commit resets fault LED related to tod_battery after a successful replacement.

Reset fault LED after CM

---

redfish-core/lib/account_service.hpp

This commit also needs to go in 1030. 
As mentioned in SW556104, Redfish accurately accepts passwords greater than 20 chars in almost all of our cases. 
The 20 char limit displayed in the API comes from IPMI, which is enabled upstream.
Downstream we have IPMI disabled by default, so up this password max length to 64.
Due to that, at this time, this is a downstream only change.
The GUI will then "Read the ManagerAccount object via GET /redfish/v1/AccountService/Accounts/<USER> and look at the AccountTypes property. If AccountTypes contains the "IPMI" AccountType, know that MaxPasswordLength is effectively 20 for this user.". This GUI change is part 2 of SW556104.
64 was chosen because it gives sufficient randomness for all practical purposes.
It makes sense the limit reflects the default …

SW556104: Part 1: Bump the max password length to 64

---

http/http_connection.hpp

This change ensures that all "success" responses are catched and audit logs the appropriate message accordingly. Prior to this change, there was a response that was missed because of the method used to determine an valid and invalid request, but this ensures it is logged as well.

Expand Success Case For Audit Logging

---

http/http_connection.hpp
include/authorization.hpp
include/ibm/management_console_rest.hpp
include/login_routes.hpp
include/persistent_data.hpp
include/sessions.hpp
redfish-core/lib/redfish_sessions.hpp

Pulling the changes from https://gerrit.openbmc.org/c/openbmc/bmcweb/+/56088 to Move ClientID parameter out of OEM

Move ClientID parameter out of OEM

---

redfish-core/lib/redfish_sessions.hpp

https://github.com/ibm-openbmc/bmcweb/pull/449/files should have bumped the session schema like https://gerrit.openbmc.org/c/openbmc/bmcweb/+/56088 did.
George reported the error here: https://ibm-systems-power.slack.com/archives/C1HT3FHNK/p1666326196830579
From https://redfish.dmtf.org/schemas/v1/Session.v1_5_0.json:
"Context": {
"description": "A client-supplied string that is stored with the session.",
"longDescription": "This property shall contain a client-supplied context ...
....
"versionAdded": "v1_5_0"
},
Tested: None.

Fix Validator: Bump session schema

---

include/event_dbus_monitor.hpp
src/webserver_main.cpp

This commit adds the dbus notification monitors which will
send out redfish events as and when the dbus signals are
generated.
If a property change needs to be notified via push style
redfish event, this file needs to be updated with the appropriate
signal monitors.

Push-style Event Dbus Monitor support

---

redfish-core/lib/update_service.hpp

Cherry picked for 1040, not tested for 1040 but only a 1 line change. Upstream we have 25 seconds.
This timeout is for the write, untar, inotify fire, and creation of a software D-Bus object.
IBM has large images for its p10bmc, 125M and growing. We have seen this take longer than 10 seconds on a AST2600. Bump this timeout to 55 seconds.
Most of the 10 seconds seems to be the untar.
https://github.com/ibm-openbmc/bmcweb/pull/432 bumped this timeout to 25 but after discussing in SOS on 9/13/22 it was decided to bump to 55.
This default 25 seconds is only used for the http upload path. TFTP already bumps this timeout to 600 seconds.
https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/update_service.hpp#L488
On a fail:
Sep 07 12:15:01 p10bmc phosphor-version-software-manager[752]: …

Bump timeout for code update file to 55 (#436)

---

redfish-core/lib/account_service.hpp

Cherry-picked for 1040. 
As mentioned in SW556104, Redfish accepts a password greater than 20 chars.
The 20 char limit comes from IPMI which is enabled upstream.
Downstream we have IPMI disabled be default, so up this limit to 64.
Due to that, at this time, this is a downstream only change.
The GUI will then "Read the ManagerAccount object via GET /redfish/v1/AccountService/Accounts/<USER> and look at the AccountTypes property. If AccountTypes contains the "IPMI" AccountType, know that MaxPasswordLength is effectively 20 for this user."
64 was choosen because it gives sufficient randomness for all practical purposes.
It makes sense the limit reflects the default.
This limit is on the Account Service, not the account, hence why we can't change this per account.
Tested: None. Code review …

Bump the max password length to 64 (#437)

---

redfish-core/lib/cable.hpp

Add PartNumber property to cables.
Also fix code so CableType and LengthMeters properties display correctly.
Testing:
1) Redfish validator passed
2) curl testing:
time curl -k -H "X-Auth-Token: $token" -X GET \
https://$bmc/redfish/v1/Cables/external_cable_0
{
"@odata.id": "/redfish/v1/Cables/external_cable_0",
"CableType": "optical",
"Id": "external_cable_0",
"LengthMeters": 2.0,
...
"Name": "Cable",
"PartNumber": "78P6567 ",
"Status": {
}
}

Add PartNumber to Cables (#394)

---

redfish-core/lib/ethernet.hpp
redfish-core/lib/managers.hpp
redfish-core/lib/storage.hpp
redfish-core/lib/systems.hpp
redfish-core/lib/task.hpp

Fixes https://github.com/ibm-openbmc/dev/issues/3459
health.hpp is based on https://github.com/openbmc/docs/blob/master/designs/redfish-health-rolllup.md
It uses a xyz.openbmc_project.Inventory.Item.Global to identify resources that have a HealthRollup and then uses "critical" or "warning" associations to set that HealthRollup. It is largely unused by us downstream. The only place we are using healthRollup is chassis. This change removes health.hpp expect from chassis.hpp. Instead we tend to us Functional to set the Health and haven't been setting HealthRollup.
We have recently hit some performance problems and Andrew noted "Over a 13 second window at runtime on an Everest, there was 1.8 MB/s traffic over D-Bus. The biggest packet size (mapper←bmcweb) was 500KB."
Atleast some of these …

Remove health.hpp calls where unneeded (#237)

---

redfish-core/lib/cable.hpp

Cable Length property value is NaN by default. The current implementation ignores processing other remaining Cable properties if the length is NaN. Per Ed's comment here we need to ignore if length is NaN and continue to process remaining properties: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/50265/4..7/redfish-core/lib/cable.hpp#b51
Testing:
1. Validator test not done, assumed it is OK since it is a minor change in the code logic.
2. curl testing: $ curl -k https://user:password@host:18080/redfish/v1/Cables/dp0_cable1 {
"@odata.id": "/redfish/v1/Cables/dp0_cable1",
"CableType": "",
"Id": "dp0_cable1",
"Name": "Cable",
"Status": {
"State": "StandbyOffline"
}
}
Upstream is …

bmcweb: Ignore Cable Length property value if NaN

---

redfish-core/lib/log_services.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemLogEntry/index.json
static/redfish/v1/schema/OemLogEntry_v1.xml

This brings in 2 event log related commits from the earlier release, and adds a commit to fix some bool definitions that showed up at some point.
One commit brought forward adds support for the IBM OEM ManagementSystemAck property, which the HMC sets after it has processed an event log.
```
"Oem": {
"OpenBMC": {
"@odata.type": "#OemLogEntry.v1_0_0.LogEntry",
"ManagementSystemAck": false
}
```
The other one fills in the Event ID property with the SRC words, and changes the Message property to something else.
```
"EventId": "BD802003 00080055 2E330010 00000000 00000000 00000000 00000000 00000000 00000000",
"Message": "BD802003 event in subsystem: Platform Firmware",
```
The last commit changes some of the bool arguments passed into sdbusplus::unpackPropertiesNoThrow() to pointers to be …

Bring PEL related commits into 1050

---

redfish-core/lib/service_root.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemServiceRoot/index.json
static/redfish/v1/schema/OemServiceRoot_v1.xml

This commit adds additional properties.
Testing:
1) redfish validator: not tested
2) curl command
curl -k <bmc_ip>/redfish/v1
"Oem": {
"@odata.type": "#OemServiceRoot.Oem",
"IBM": {
"@odata.type": "#OemServiceRoot.IBM",
"DateTime": "2022-11-15T01:24:44+00:00",
"DateTimeLocalOffset": "+00:00",
"Model": "9105-22A",
"SerialNumber": "139EF60"
}
},
Signed-off-by: Shantappa Teekappanavar <shantappa.teekappanavar@ibm.com>
Change-Id: Id4e3562ef4b8a56eca3cd98cc7adcedfb36d293d

Add OemServiceRoot schema

---

http/http_connection.hpp

The connection timeout is set to 26 minutes to logged in users to support our large code update images, otherwise timeout is set to 120 seconds.
This matches what we had on 1020 and 1030.
Same as what we will have on 1050.
Took from https://github.com/ibm-openbmc/bmcweb/pull/455 Replaces https://github.com/ibm-openbmc/bmcweb/commit/63314c086a28f6d60839277fc381cf6717f47eb1

Bump connection timeout to 26 mins

---

redfish-core/lib/assembly.hpp

When bmcweb is told the RTC battery is replaced after a CM operation, set the Functional property on its assembly object path back to true before restarting the adcsensor daemon.
This does two things:
1) Causes the fault LED to turn off
2) Sets the Redfish representation back to healthy so the web UI doesn't
show it has unhealthy it after the CM operation.  Of course if
adcsensor detects an error again it would go back to unhealthy.
Since this is handling the fault LED, the previous code that explicitly turned off the fault LED group was removed.
Defect PE00DX9W. For 1020.30
Signed-off-by: Matt Spinler <spinler@us.ibm.com>

Set Functional property after battery CM

---

include/authentication.hpp
redfish-core/include/error_messages.hpp
redfish-core/include/privileges.hpp
redfish-core/lib/account_service.hpp
redfish-core/lib/roles.hpp
redfish-core/src/error_messages.cpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemManagerAccount/index.json
static/redfish/v1/schema/OemManagerAccount.v1_0_0.xml

This PR adds support for upload of ACF certificate files, in addition to a new OEM user role.
Tested: Certificate is able to be uploaded via:
```
curl -k -H "X-Auth-Token: $TOKEN" -X PATCH -d '{"Oem":{"IBM":{"ACF":{"ACFFile":"'${service_acf_base64}'"}}}}' https://${BMC}:${BMC_HTTPS_port}/redfish/v1/AccountService/Accounts/service
```
and the BMC is accessible by logging as service.

IBM ACF Support

---

include/ibm/management_console_rest.hpp

Code changes to fix SW558001.
Limit the GET function on configfiles to display only regular files and return an error if the user try to GET on a subfolder in configfiles, created manually, avoiding the bmcweb crash.
Tested:
Create subfolder under configfiles path
curl -k -H "X-Auth-Token: $bmc_token" -X GET -D patch1.txt
https://${bmc}/ibm/v1/Host/ConfigFiles
Without fix:
Lists all contents of the ConfigFiles folder
With Fix:
lists only the regular files
Run the command with subfolder
curl -k -H "X-Auth-Token: $bmc_token" -X GET -D patch1.txt
https://${bmc}/ibm/v1/Host/ConfigFiles/testfolder
Without fix:
bmcweb crashes
With the fix:
“Description”: “Resource Not Found”
Corresponding upstream commit : https://gerrit.openbmc.org/c/openbmc/bmcweb/+/59077/6/include/ibm/management_console_rest. …

Restrict use of subfolder in configfiles path

---

http/obmc_shell.hpp
meson.build
meson_options.txt
src/webserver_main.cpp

This commit includes a web-based shell, making it possible to access secure shell servers through standard web browsers using WebSocket.
Path of WebSocket:
wss://{hostname}/bmc-console
Implementation:
So when bmcweb WebSocket gets a request for a new connection, it
creates a child process of bmcweb using the forking bmcweb process
(which begins a new process operating in a pseudoterminal).
Then on that pseudoterminal call exec("/bin/sh") which replaces the
current process image with a "/bin/sh" process image.
bmcweb is communicating with that child process using
stream_descriptor, similar to read write from a file descriptor,
with asynchronous ability. So the shell can execute all commands
like ls, cd, etc.
WebSocket here only acts as a mediator between child process, which
acts as a …

BMC_SHELL web-base_shell

---

redfish-core/lib/account_service.hpp
redfish-core/lib/service_root.hpp
static/redfish/v1/JsonSchemas/OemManagerAccount/index.json
static/redfish/v1/schema/OemManagerAccount.v1_0_0.xml

Background: The Access Control File (ACF) service access is a 2-factor authentication scheme intended for BMC administrators to determine when authorized service and support representatives (SSRs) are allowed to access their BMC but not allow the administrator to have access. In this scheme, only the SSR can create valid ACFs,m which they then give it to the BMC admin for upload to the BMC.  Doing so authorizes the SSR to login to the BMC's service account via an unique password.
A problem with this scheme is some BMC admins lose their password.  To solve this, Operator Panel function 74 opens a 30 minute time window where anyone is allowed to upload a valid ACF to the BMC.
A problem with that solution is that in some installations there is difficulty gaining physical access to the …

New property to always AllowUnauthACFUpload

---

redfish-core/include/redfish.hpp
redfish-core/lib/assembly.hpp
redfish-core/lib/chassis.hpp

This commit implements Redfish Assembly schema on bmcweb. This schema will be used to publish inventory data for FRUs which are attached to a given Chassis and does not map to any specific schema definition.
The properties which are published in this commit are LocationCode, SparePartNumber, Model, SerialNumber and PartNumber.
One of the major use case to publish these properties via redfish is for service engineers to identify the FRU and its location in the system, which in turn will help them in repair/replacement related to that FRU.
The validator has been executed on the change and no error has been found.
As this has been tested on a development image some fields are empty in the below pasted output for which warning was thrown by validator but no errors.
Sample Output:
curl -k -H …

Inventory properties via Assembly schema on bmcweb

---

scripts/update_schemas.py

Merged upstream here: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/59633
https://github.com/ibm-openbmc/bmcweb/blob/1050/run-ci isn't in 1030 or 1020 but without this change in 1020/1030 this script fails if using the docker container or if you pip install / pip update so probably worth fixing https://github.com/ibm-openbmc/bmcweb/pull/480 is the 1050 one and it already is in. 
Python packaging seems to have changed to be much more stringent about what version strings is accepts.  It's not clear why this was done, but we need a fix to unbreak CI.
This commit adds more parsing code into the script to parse out version numbers from  the form of LogEntry.v1_2_3 to split them up into a custom class, and sort manually.  Despite dropping the dependency, this ends up dropping a net 7 lines of …

1030: Fix python packaging problem

---

scripts/update_schemas.py

Merged upstream here: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/59633
https://github.com/ibm-openbmc/bmcweb/blob/1050/run-ci isn't in 1030 or 1020 but without this change in 1020/1030 this script fails if using the docker container or if you pip install / pip update so probably worth fixing  https://github.com/ibm-openbmc/bmcweb/pull/480 is the 1050 one and it already is in. 
Python packaging seems to have changed to be much more stringent about what version strings is accepts.  It's not clear why this was done, but we need a fix to unbreak CI.
This commit adds more parsing code into the script to parse out version numbers from  the form of LogEntry.v1_2_3 to split them up into a custom class, and sort manually.  Despite dropping the dependency, this ends up dropping a net 7 lines of …

1020: Fix python packaging problem

---

http/http_connection.hpp

Defect is [SW558078 ](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW558078) and needs to go into 1030 as well.
This is only a partial fix  
Upstream is  https://gerrit.openbmc.org/c/openbmc/bmcweb/+/59803/4 and has merged. Will be picked up on the next rebase of 1050 bmcweb. 
If given a bad URI, e.g. "https://$bmc/?a=id;" return http bad request (400) like we do other places, e.g. a few lines below.
Certain scanners expect to see bad request when crawling and probing for vulnerabilities and using not valid URIs. Just dropping the connection causes errors with these scanners. They think connection problem or worse the server was taken down.
Tested: Tested downstream https://$bmc/?a=id; returns bad request
Prashanth Katti …

SW558078 (partial fix): Return bad request if can't construct

---

redfish-core/lib/chassis.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemChassis/index.json
static/redfish/v1/schema/OemChassis_v1.xml

* OEM - Enclosure Firmware Version
Mex is updating via a lid in the host image, updated via PHYP.
PHYP sends an FRU record set PDR and sends the io enclosure version data via the frurecord table, and pldm parses that and hosts the Version Interface on the mex chassis object.
This implementation retrieves that mex chassis FirmwareVersion data, which define via the manufacturer for the associated chassis, and displayed on Redfish OEM schema for chassis.
* Fix All commnet
Co-authored-by: Abhishek Patel <Abhishek.Patel@ibm.com>

OEM - Enclosure Firmware Version (#241)

---

redfish-core/lib/log_services.hpp

The OriginOfCondition Link should have an odata.id which was missing for assemblies. All other Deconfig records already correctly had this property.
curl -k -H "X-Auth-Token: $bmc_token" -XGET
https://${BMC_IP}/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries/50 {
"@odata.id":
"/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries/50",
"@odata.type": "#LogEntry.v1_9_0.LogEntry",
"Created": "2023-01-03T10:38:43+00:00",
"EntryType": "Event",
"Id": "50",
"Links": {
"OriginOfCondition": "/redfish/v1/Chassis/chassis/Assembly#/Assemblies/49"
<-- missing @odata.id
},
"Message": "TPM Card",
"Name": "Hardware Isolation Entry",
"Severity": "OK"
}
curl -k -H "X-Auth-Token: $bmc_token" -XGET
https://${BMC_IP}/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries/50 …

Add missing odata.id field under OriginOfCondition for assemblies

---

redfish-core/lib/log_services.hpp

The OriginOfCondition Link should have an odata.id which was missing for assemblies. All other Deconfig records already correctly had this property.
Fixed the same and as shown below the odata.id is present
-bash-4.2$ curl -k -H "X-Auth-Token: $bmc_token" -XGET https://${BMC_IP}/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries/50 {
"@odata.id":
"/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries/50",
"@odata.type": "#LogEntry.v1_9_0.LogEntry",
"Created": "2023-01-03T10:38:43+00:00",
"EntryType": "Event",
"Id": "50",
"Links": {
"OriginOfCondition": {
"@odata.id": "/redfish/v1/Chassis/chassis/Assembly#/Assemblies/49"
<-- odata.id is present after the fix
}
},
"Message": "TPM Card",
"Name": "Hardware Isolation Entry",
"Severity": "OK"
}
Signed-off-by: deepakala …

Add missing odata.id field for assemblies

---

config/bmcweb.service.in

This is 4 cherry-picks: 
1. https://github.com/ibm-openbmc/bmcweb/pull/222  Add pre-req to phosphor-user-manager service #222 
2. https://github.com/ibm-openbmc/bmcweb/commit/5c1f9c758d11c90326e94d80d034b41a3a126e28 Start bmcweb after bmc state manager (https://github.com/ibm-openbmc/bmcweb/pull/298)
3. https://github.com/ibm-openbmc/bmcweb/commit/802c381289fe3b2dd715e9c4fda88a30ccbc48b4 Start bmcweb after bmc code update manager (https://github.com/ibm-openbmc/bmcweb/pull/302)
4. https://github.com/ibm-openbmc/bmcweb/commit/222d582231f83b3cc51deb26837f951072417b51 SW547232: Start bmcweb after host state manager (https://github.com/ibm-openbmc/bmcweb/pull/306)
These were all needed so bmcweb doesn't come up until we have the required services. …

After other services

---

http/http_client.hpp

**This should also go into 1020.** 
Not a separate defect for this, but a minor part of PE00F2N4/PE00F476 (this fix shouldn't be considered fixing those defects though.)
Just in the last month, been pinged 3 or 4 times about excess tracing in the journal around events. That is happening because the HMC is leaving around an event subscription. The HMC should clean this up, but they aren't. The HMC uses RetryForever and 5 seconds retry, so they continue to spam the journal pretty frequently. TerminateAfterRetries or SuspendRetries would also help clean this up but the HMC moving to that has some risk involved. On our side, much of this tracing is excessive.
Move 2 traces that are clearly not errors to debug so they don't appear in the journal:
`Dec 04 02:36:27 xxx bmcweb[794]: (2022-12-04 …

Move some event traces to DEBUG

---

Redfish.md
include/dbus_utility.hpp
redfish-core/include/redfish.hpp
redfish-core/include/utils/sw_utils.hpp
redfish-core/include/utils/systems_utils.hpp
redfish-core/lib/chassis.hpp
redfish-core/lib/led.hpp
redfish-core/lib/power_subsystem.hpp
redfish-core/lib/power_supply.hpp
redfish-core/lib/systems.hpp

These commits implement the Redfish PowerSupply schema and populate the PowerSupplyCollection members.
Include:
- Efficiency Percent
- FirmwareVersion
- Location
- LocationIndicatorActive
- Manufacturer
- Model
- PartNumber
- SerialNumber
- SparePartNumber
- Status
Upstream commits:
<https://gerrit.openbmc.org/c/openbmc/bmcweb/+/58924/17>
<https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57668/25>
<https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57669/17>
<https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57670/14>
<https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57765/23>
<https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57671/9>
<https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57672/9>
<https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57673/9>
<https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57709/7> …

1050.power supply

---

include/ibm/management_console_rest.hpp

These interfaces used by management console to get root and client certificates and to establish connection to hypervisor.
Redfish supports certificate service but BMC never acts as the CA so redfish doesn't have the support for signCSR interface. In our IBM case hypervisor acts as a CA that signs the CSR, so we kept this as IBM-specific interface.
Design Doc: https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/23420
Rest interfaces: GET https://${BMC_IP}/ibm/v1/Host/Certificate/root POST -d '{"CsrString":"ceritifate string"}'
https://${BMC_IP}/ibm/v1/Host/Actions/SignCSR
Tested By:
Tested signCSR interface with valid and invalid CSRs.  curl -k -H "X-Auth-Token: $bmc_token" -X POST -d '{"CsrString":"cert"}' https://${BMC_IP}/ibm/v1/Host/Actions/SignCSR
curl -k -H "X-Auth-Token: …

Root and signCSR interfaces for hypervisor

---

redfish-core/lib/pcie.hpp

This commit publishes inventory properties like SparePartNumber, Model, PartNumber, SerialNumber for PCIe devices.
It also modifies the implementation to pick service name and object paths for PCIe devices via mapper instead of using static values.
(Not Ready to review)
Change-Id: I850fe5eb2b3b3b9d47f4256ce0c4408bb1dd2bd1

Redfish PCIeDevice schema on bmcweb.

---

include/ibm/locks.hpp
include/ibm/management_console_rest.hpp

This commit has changes to:
1. Avoid having stale entries in the lock table in BMC
2. Fix unnecessary lock conflicts due to seg length validation
3. Remove stale lock table entries of invalid sessionid

Fix for some lock related defects

---

include/ibm/management_console_rest.hpp
test/include/ibm/configfile_test.cpp

This PR combines all downstream changes for the ConfigFile usecases
1. Picked upstream commit https://gerrit.openbmc.org/c/openbmc/bmcweb/+/54120 to support multipart ConfigFile upload
2. Downstream changes for sending the redfish event when the ConfigFile is deleted
3. Downstream change to Bump up the max size of the ConfigFile

Configfile prs

---

redfish-core/lib/account_service.hpp

* ReadOnly users should not have ssh
This changes the Redfish create new user API (POST /redfish/v1/AccountService/Accounts/) so only Administrator users will have the HostConsole AccountType value.  This is the same as the "ssh" phosphor privilege group.
Doing so prevents new ReadOnly users from using SSH port 2200.
Note that ReadOnly user created prior to this change will have the HostConsole AccountType privilege.  A BMC admin can PATCH a user's AccountTypes property to add or remove the Hostconsole value.
Tested: Yes
* fixup code formatting
Tested: Compiles

ReadOnly users should not have ssh (#408)

---

http/http_server.hpp
include/persistent_data.hpp

Currently it collects bmcweb_persistent_data.json as part of BMC dump, but this file does not contain all existing redfish sessions
IBM only implementation needed for debugging HMC-BMC issues
This commit is to collect all sessions into bmcweb_current_session_persistent_data.json during bmc dump creation, on receiving SIGUSR1 from dump manager.
* Add event subscriptions data along with session data

FFDC: Collect current in-memory sessions for BMC dump

---

include/persistent_data.hpp

This commit fix compilation error which was hit due to new json infra changes from upstream
bmcweb/include/persistent_data.hpp:228:35: error: no matching function for call to 'nlohmann::json_abi_v3_11_2::basic_json<>::push_back(<brace-enclosed initializer list>)'

Fix sessions json object compilation errors

---

redfish-core/lib/chassis.hpp
redfish-core/lib/roles.hpp

Change 1) pull in https://github.com/ibm-openbmc/bmcweb/commit/26c886543e0d33bccf26c4b11156d09b5a3eedd9. This fixes 4 validator errors `ERROR - Restricted not defined in schema Role.v1_2_2 (check version, spelling and casing)`
Change 2) Redfish chassis: Only return Inventory.Item.Chassis
Part of https://github.com/ibm-openbmc/bmcweb/commit/f300f37d4dcde1f476459d18962f7ff2552ed8b3
Want it now so the validator doesn't fail. The assemblies can come later. Fixes 3 validator errors, that 2nd board Tola_Board goes away 
Tested: no longer see these validator errors

Fix redfish validator errors

---

http/http_stream.hpp
include/dump_offload.hpp

This commit
1.Enables dynamic response support
2.Defines new bmcweb rule to support dump streaming. 3.Implemented routes for bmc and system dump offload.
Tested By:
1. BMC dump offload
2. System dump offload

Add Dump offload support using http dynamic response

---

http/logging.hpp
src/webserver_main.cpp

In order to be able to more easily debug bmcweb related issue, lets enable error traces by default. So by default all Error and Critical level traces are now written to the journal. If the dev enables the bmcweb-logging feature then they will get all levels of trace.
There are some error traces periodically being written to the journal which do not appear to be errors (since all is working fine). The next commit will change the level of these logs.
Testing:
- Verified only the error and critical logs were displayed

enable error traces in bmcweb

---

redfish-core/include/redfish.hpp
redfish-core/lib/update_service.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemUpdateService/index.json
static/redfish/v1/schema/OemUpdateService_v1.xml

This commit adds a new update command to be used by the management console to perform concurrent updates. It works like the current update command, but with added support for the OnReset apply time setting.
Tested: Ensured that redfish command updates as usual and updates still occurred while the ApplyTime was in the OnReset state.

Redfish OEM Update Command for Concurrent Update (#141)

---

redfish-core/lib/systems.hpp

Per recent internal team discussions, IBM will be disabling the
ForceRestart ResetType option. This is because the hypervisor firmware
on IBM based systems requires host reboots to always be graceful to
ensure certain BIOS settings are correctly set.
Tested:
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Systems/system/ResetActionInfo {
"@odata.id": "/redfish/v1/Systems/system/ResetActionInfo",
"@odata.type": "#ActionInfo.v1_1_2.ActionInfo",
"Id": "ResetActionInfo",
"Name": "Reset Action Info",
"Parameters": [
{
"AllowableValues": [
"On",
"ForceOff",
"ForceOn",
"GracefulRestart",
"GracefulShutdown",
"PowerCycle",
"Nmi"
],
"DataType": "String",
"Name": "ResetType",
"Required": true
}
]
}

redfish: remove ForceRestart from AllowableValues

---

redfish-core/lib/roles.hpp

This changes the Operator role to Restricted=true which means no users can have the Operator role.
Tested:
1. GET /redfish/v1/AccountService/Roles/Operator and ensure it has Restricted:true.
2. POST /redfish/v1/AccountService/Accounts/new with Role:Operator Ensure it failed with message Base.1.9.0.RestrictedRole. Posting a new Administrator user is successful.
3. PATCH /redfish/v1/AccountService/Accounts/ordinary with Role:Operator.  Ensure it failed.
Changing a user to the ReadOnly role is successful.
4. PATCH the OemIBMServiceAgent role as the LocalRole within the RemoteRoleMapping property && ensure it failed.

Restrict the Operator role (#319)

---

scripts/websocket_test.py

Merged upstream at https://gerrit.openbmc.org/c/openbmc/bmcweb/+/60653
Seeing CI fails:
```
Running beautysh
Running black
reformatted scripts/websocket_test.py
```
```
diff --git a/scripts/websocket_test.py b/scripts/websocket_test.py
index 21c7f160..fce9cd7e 100755
--- a/scripts/websocket_test.py
+++ b/scripts/websocket_test.py
@@ -45,10 +45,10 @@ async def hello():
authbytes = "{}:{}".format(args.username,
args.password).encode("ascii")
auth = "Basic
{}".format(base64.b64encode(authbytes).decode("ascii"))
headers = {"Authorization": auth}
-    async with websockets.connect(
-        uri, ssl=ssl_context, extra_headers=headers
-    ) if args.ssl else websockets.connect(
-        uri, extra_headers=headers
+    async with (
+        websockets.connect(uri, ssl=ssl_context, …
```

Fix CI; Run black

---

redfish-core/lib/roles.hpp

The Redfish GET API for AccountService roles should return "ServiceAgent" for the case of the OemIBMServiceAgent role and not "OemIBMServiceAgent".
Tested:
/redfish/v1/AccountService/Roles/ROLE shows the intended descriptions.
Signed-off-by: Tom Ippolito <thomas.ippolito@ibm.com>
Co-authored-by: Tom Ippolito <thomas.ippolito@ibm.com>

Update ServiceAgent role Description (#366)

---

http/http_connection.hpp

This is a cherry-pick from upstream  https://github.com/openbmc/bmcweb/commit/a4326fe2710d12e30cf39dee2aaaba2e4fd0abfd.
http::end_of_stream log is not properly detected and thus it is being traced as error. It will be fixed to be traced as warning so they do not show up when just error traces are enabled (new default)
Here's the log we was getting:
Jan 10 13:34:32 ever6bmc bmcweb[2496]: (2023-01-10 13:34:32) \ [ERROR "http_connection.hpp":784] 0x14bd360 Error while \ reading: end of stream
Change-Id: I6ecee813c4f7806a676ba0ad3e4ab1a8f78747fd
Signed-off-by: Myung Bae <myungbae@us.ibm.com>

Clean up http end_of_stream traces

---

http/http_connection.hpp

This merged upstream here:
https://github.com/openbmc/bmcweb/commit/262f115299479c8f1142954622a358d53318e9fd
Just easier if we cherry-pick into 1050, since not sure when we will rebase next. I just worry, if it doesn't get cherry-picked, I get a defect. ;) 
If given a bad URI, e.g. "https://$bmc/?a=id;" return http bad request (400) like we do other places, e.g. a few lines below.
Certain scanners expect to see bad request when crawling and probing for vulnerabilities and using not valid URIs. Just dropping the connection causes errors with these scanners. They think connection problem or worse the server was taken down.

Return bad request if can't construct

---

meson.build
meson_options.txt
redfish-core/lib/oem/ibm/lamp_test.hpp
redfish-core/lib/oem/ibm/system_attention_indicator.hpp
redfish-core/lib/systems.hpp
static/redfish/v1/JsonSchemas/OemComputerSystem/index.json
static/redfish/v1/schema/OemComputerSystem_v1.xml

Implement OEM lamp test in redfish/v1/Systems/system
Implement SystemAttentionIndicator in redfish/v1/Systems/system
refer: https://github.com/ibm-openbmc/dev/issues/2120
We use macros to control the URL, which need to be enabled in
bmcweb_%.bbappend to see it, for example:
EXTRA_OEMESON_append = " \
-Dibm-led-extensions=enabled \
"
Tested:
1. Get the lamp test and SAI:
curl -k -H "X-Auth-Token: $token" \
https://${bmc}/redfish/v1/Systems/system
{
...
"Oem": {
"IBM": {
"LampTest": false,
"PartitionSystemAttentionIndicator": false,
"PlatformSystemAttentionIndicator": false
}
},
...
}
2. Set the lamp test and …

1050: Implement OEM lamp test and SAI

---

redfish-core/lib/account_service.hpp
redfish-core/lib/service_root.hpp
static/redfish/v1/JsonSchemas/OemServiceRoot/index.json
static/redfish/v1/schema/OemServiceRoot_v1.xml

* Add ACFWindowActive to /redfish/v1
This adds the Oem.IBM.ACFWindowActive boolean property to the Redfish service root at URI /redfish/v1.
Tested:
Via curl https://${BMC}/redfish/v1
Tested values true, false, and panel app not running. Simulated pressing function 74 via busctl set-property "com.ibm.PanelApp"
"/com/ibm/panel_app" "com.ibm.panel" "ACFWindowActive" b true
* Add ACFWindowActive to /redfish/v1
This restructures the ACFWindowActive code to BMCWeb coding style. This defaults to ACFWindowActive=false when the value is not available. This add the XML schema.
Tested:
Tested both true and false values via:
curl -k https://127.0.0.1:2643/redfish/v1
and simulating button press via
busctl set-property "com.ibm.PanelApp" …

Add ACFWindowActive to /redfish/v1 (#331)

---

Redfish.md
redfish-core/include/redfish.hpp
redfish-core/lib/chassis.hpp
redfish-core/lib/led.hpp
redfish-core/lib/pcie_slots.hpp

Implement LocationIndicatorActive for PCIeSlot schema, We can use locationindicatoractive to set or get the status of the location led of each pcie slot.
https://redfish.dmtf.org/schemas/v1/PCIeSlots.v1_4_1.json
We need to set the LocationIndicatorActive of all the slots in the dopatch command, even if we only want to modify one of them.(ex: see the third test result)
1、Get LocationIndicatorActive
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots {
"@odata.type": "#PCIeSlots.v1_4_1.PCIeSlots",
"Id": "PCIeSlots",
"Name": "PCIe Slot Information",
"Slots": [
{
"Lanes": 16,
"PCIeType": "Gen1",
"SlotType": …

Redfish : Implement LocationIndicatorActive for PCIeSlots

---

redfish-core/lib/ethernet.hpp

Dbus for "xyz.openbmc_project.Network" changed to no protocol in object path[0]. And this is in line with expectations[1]. Since that, it will get empty IP address when calling
"/redfish/v1/Managers/bmc/EthernetInterfaces/eth1".
Dbus before:
/xyz/openbmc_project/network/eth0/ipv4/52348b91
Now:
/xyz/openbmc_project/network/eth0/_66e80_3a_3aa00_3a27ff_3afee1_3a5408
Test:
Before:
GET /redfish/v1/Managers/bmc/EthernetInterfaces/eth1
```
{
"IPv4Addresses": [],
"IPv4StaticAddresses": [],
"IPv6AddressPolicyTable": [],
"IPv6Addresses": [],
}
```
After:
GET /redfish/v1/Managers/bmc/EthernetInterfaces/eth1
```
{
"IPv4Addresses": [
{
"Address": "192.168.1.108",
"AddressOrigin": "DHCP",
"Gateway": "192.168.1.2",
"SubnetMask": "255.255.255.0"
}
],
"IPv6Addresses": [
{
"Address": …
```

Ethernet: Fix getting empty IP address

---

include/obmc_console.hpp

Original PR: #407 
Cherry-picked
Currently, ReadOnly has access to the host console. Restrict it to Admin or above.
Part of
[SW553027](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW553027)
Currently, ReadOnly has access to the host console. Restrict it to Admin or above.
This appears to add a half-second delay in starting the websocket (I assume this is for the dbus call). It is just noticeable but hard to measure (e.g. under a second).. Or I am going crazy.
I followed code in
https://github.com/ibm-openbmc/bmcweb/blob/8044381620b228f99b707ea2b444c7675e714f26/include/nbd_proxy.hpp#L417
The 1050 story: 
So the user management code is a bit of a mess. 
.privileges({{"ConfigureComponents", "ConfigureManager"}})
or 
.privileges({{ "ConfigureManager"}})
doesn't actually work. We need …

Restrict host console to ConfigureManager (#407)

---

redfish-core/lib/managers.hpp

Upstream: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/50494
We can use the following command to set LocationIndicatorActive to true or false:
'{"LocationIndicatorActive":false}'
https://${bmc}/redfish/v1/Managers/bmc
https://github.com/ibm-openbmc/bmcweb/pull/219

Implement LocationIndicatorActive property for Manager.

---

redfish-core/lib/assembly.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemAssembly/index.json
static/redfish/v1/schema/OemAssembly_v1.xml

OEM Battery Concurrent Maintenance For Everest System 
The current impementation of this feature supports
the redfish OEM ReadyToRemove property for the TOD
battery on assembly.  The TOD battery is put in the
ReadyToRemove state by stopping the adcsensor application.
The reverse occurs when the adcsensor application
is restarted.  The adcsensor is stopped and started
by calling systemd.  Note that this implementation
only works if the adcsensor application handles one
ADC sensor.
* Update for PR: https://github.com/ibm-openbmc/bmcweb/pull/224

1050: OEM Battery Concurrent Maintenance for Everest System

---

redfish-core/include/event_service_manager.hpp

Fix this bug: ibm-openbmc/dev#3599
Don't send event to snmptrap subscription.
Upstream: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/38599
https://github.com/ibm-openbmc/bmcweb/pull/413

1050: Fix bug: bmcweb SNMP errors in the Journal

---

redfish-core/lib/assembly.hpp

When bmcweb is told the RTC battery is replaced after a CM operation, set the Functional property on its assembly object path back to true before restarting the adcsensor daemon.
This does two things:
1) Causes the fault LED to turn off
2) Sets the Redfish representation back to healthy so the web UI doesn't
show it has unhealthy it after the CM operation.  Of course if
adcsensor detects an error again it would go back to unhealthy.
Since this is handling the fault LED, the previous code that explicitly turned off the fault LED group was removed.

1050: Set Functional property after battery CM (#476)

---

Redfish.md
redfish-core/include/redfish.hpp
redfish-core/lib/thermal_metrics.hpp
redfish-core/lib/thermal_subsystem.hpp

The ThermalMetrics is a new resource in Redfish version 2020.4[1]. It contains an array of temperature readings.
It is a child of the ThermalSubsystem schema[2].
The current value of each temperature sensor and the corresponding link are enumerated in this collection.
Reference:
[1] https://www.dmtf.org/sites/default/files/standards/documents/DSP0268_2020.4.pdf [2] https://redfish.dmtf.org/schemas/v1/ThermalMetrics.v1_0_0.json
Test:
1. Validator passed.
2. doGet method: curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/ \ Chassis/chassis/ThermalSubsystem/ThermalMetrics
{
"@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/ \
ThermalMetrics",
"@odata.type": "#ThermalMetrics.v1_0_0.ThermalMetrics",
"Id": "ThermalMetrics",
"Name": "Chassis Thermal Metrics", …

1050: Add Redfish ThermalMetrics schema in bmcweb

---

redfish-core/lib/account_service.hpp

The current LDAP group map on /redfish/v1/AccountService is incorrect and is creating a bad JSON response. instead of an array of objects, is creating a nested array of objects. The problem is visible on the website adding a new LDAP group map, it will show 2 empty rows instead of one with the correct data.
The current JSON data is:
"RemoteRoleMapping": [
[
{
"RemoteGroup": "groupname"
}
],
[
{
"LocalRole": "Operator"
}
]
],
The correct JSON is:
"RemoteRoleMapping": [
{
"LocalRole": "Operator",
"RemoteGroup": "groupname"
}
],
The tests redfish/account_service/test_ldap_configuration crashed BMCWEB generates around 9 core dump files.
Tested:
redfish/account_service/test_ldap_configuration passed the tests Adding a new LDAP group map on the website, showing the correct data,
Change-Id: …

Problem with RemoteRoleMapping JSON

---

redfish-core/lib/chassis.hpp

Extend the hasIndicatorLed array and add
xyz.openbmc_project.Inventory.Item.Chassis interface.
Tested:
curl -k https://$bmc/redfish/v1/Chassis/chassis
{
"@odata.id": "/redfish/v1/Chassis/chassis",
"@odata.type": "#Chassis.v1_16_0.Chassis",
"Actions": {
"#Chassis.Reset": {
"@Redfish.ActionInfo": "/redfish/v1/Chassis/chassis/ResetActionInfo",
"target": "/redfish/v1/Chassis/chassis/Actions/Chassis.Reset"
}
},
"IndicatorLED": "Off",
"Model": "23",
"Name": "chassis",
...
}

1050: Update indicator LED verification

---

redfish-core/lib/assembly.hpp

Upstream: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/42441
when we do a patch request on Assembly it gives following response: curl -k -H "X-Auth-Token: $token" -X PATCH -d
'{"Assemblies":[{"MemberId" : "2", "LocationIndicatorActive":true}]}' https://${BMC_IP}/redfish/v1/Chassis/chassis/Assembly {
"Assemblies": [],
"Assemblies@odata.count": 0,
"Id": "Assembly",
"Name": "Assembly Collection"
}
This response is not expected. This commit will fix this issue.
Tested:
when we do a patch request on Assembly it does not give any response: curl -k -H "X-Auth-Token: $token" -X PATCH -d
'{"Assemblies":[{"MemberId" : "2", "LocationIndicatorActive":true}]}' …

1050: Redfish: Fix issue of set Assemply LocationIndicatorActive

---

redfish-core/include/registries/privilege_registry.hpp
redfish-core/lib/log_services.hpp
scripts/parse_registries.py

SubordinateOverrides:
This commit attempts to automate the creation of SubordinateOverrides
privileges structures from the redfish privilege registry. In
addition, it enhances the function of parse_registries.py.
It read SubordinateOverrides privilege registry from DMTF and
generates const defines SubordinateOverrides for all the privilege
registry entries in the same format that the Privileges struct
accepts.
Moreover, it generates unique const defines for all
SubordinateOverrides target levels.
Ex: EthernetInterface SubordinateOverrides has two "Targets":
["Manager", "EthernetInterfaceCollection"]. So
parse_registries.py generates two unique const
1) Subordinate override for Manager -> EthernetInterface
2) Subordinate override for Manager ->
EthernetInterfaceCollection -> …

1050: Added SubordinateOverrides & Fix Log_services privileges

---

redfish-core/lib/bios.hpp
redfish-core/lib/log_services.hpp

Defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=PE00FKYD
Needs to go into 1020, 1030, and 1040. 1050 will be separate. 
Errors we are seeing are 
1 failRedfishUriStrict errors in /redfish/v1/Systems/system/Bios/Settings
1 failRedfishUriStrict errors in /redfish/v1/Systems/system/LogServices/PostCodes
Example:
ERROR - URI /redfish/v1/Systems/system/LogServices/PostCodes does not match object IDs of resource chain
ERROR - URI /redfish/v1/Systems/system/Bios/Settings does not match object IDs of resource chain
The first commit is a cherry-pick of https://gerrit.openbmc.org/c/openbmc/bmcweb/+/60766
The 2nd commit is based on that and fixes 
1 failRedfishUriStrict errors in /redfish/v1/Systems/system/Bios/Settings. The 2nd commit isn't upstream because …

Correct id parameter to pass validator

---

redfish-core/lib/pcie.hpp
redfish-core/lib/pcie_slots.hpp

This PR contains 2 commits as the second one requires the first.
1. Add Pcie slot to Pcie device link - https://github.com/ibm-openbmc/bmcweb/commit/cc625a7e94736ad5af3750fc21a7c75a91c3ea2d
This commit implements to detect and populate link between PCIe
slot and PCIe device attached to that slot.
3.  bmcweb: Add link Status and Health to PCIe device (#340) - https://github.com/ibm-openbmc/bmcweb/commit/a3c00833c2dd424a11f3e8169c2210fd04339f4e
This commit adds Status and Health elements to the json object of
PCIe Device when requested to get the device properties. These two
elements are derived from LinkStatus of the PCIe Slot.

1050: bmcweb: Add link Status and Health to PCIe device (#340) with PCIeSlots Link

---

redfish-core/lib/ethernet.hpp
redfish-core/lib/hypervisor_system.hpp

This PR adds ipv6 support for hypervisor nw configuration & hypervisor IPv6 SLAAC support
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/54109
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/54126

Support ipv6 on hypervisor ethernet interface

---

meson.build
meson_options.txt
redfish-core/include/error_messages.hpp
redfish-core/include/redfish.hpp
redfish-core/include/registries/openbmc_message_registry.hpp
redfish-core/include/utils/error_log_utils.hpp
redfish-core/include/utils/hw_isolation.hpp
redfish-core/include/utils/name_utils.hpp
redfish-core/lib/assembly.hpp
redfish-core/lib/chassis.hpp
redfish-core/lib/log_services.hpp
redfish-core/lib/memory.hpp
redfish-core/lib/processor.hpp
redfish-core/lib/storage.hpp
redfish-core/lib/update_service.hpp
redfish-core/src/error_messages.cpp

Sync HardwareIsolation commits from 1030 to 1050. 
Here is the upstream commits for the relevant ones. 
Implement LocationIndicatorActive for CPU resource | https://gerrit.openbmc.org/c/openbmc/bmcweb/+/37045
Implement SubProcessors for processor core | https://gerrit.openbmc.org/c/openbmc/bmcweb/+/38570
Implement LocationIndicatorActive for CPU resource | https://gerrit.openbmc.org/c/openbmc/bmcweb/+/37045
For the HWIsolation, the commits do not have respective upstream commits, as we do not have a standard guard implementation in the upstream
Test output:
After adding the patches, the Hardware Isolation records are 
-bash-4.2$ curl -k -H "X-Auth-Token: $bmc_token" -XGET https://${BMC_IP}/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries
{
"@odata.id": …

Sync HardwareIsolation 1030 commits to 1050

---

redfish-core/lib/log_services.hpp

Merged upstream at https://gerrit.openbmc.org/c/openbmc/bmcweb/+/60766 
A similar change was done for 1020, 1030, 1040 
The Journal and EventLog now fail redfish-service-validators new test. Per the specification, the "Id" parameter should match the elements odata id segment in the collection.  The validator now tests for this, and these two fail.
Tested: Redfish service validator now passes.
Change-Id: I463eea7ae7a7dfd6a9d6d562ae4f03dc887a9478

Correct Id parameter for two log services

---

redfish-core/lib/led.hpp

DBus inventory association uses "/identifying"
instead of "/identify_led_group" according to the latest association interface [1].
[1] https://github.com/openbmc/phosphor-dbus-interfaces/commit/9eb460c6cfc2d7c2feb29c86f4beb31d4c3d9250
upstream: https://gerrit.openbmc.org/c/openbmc/openbmc/+/61068

1050: bmcweb update `identify` association for LED & Item assciation

---

http/routing.hpp

Despite introduction of a new enum class containing method verbs, some functions were still using the one from Boost. This had caused erratic behaviour when trying to create a websocket (e.g. /nbd/<str>), because enum value of old type was compared to the one of new type. This change fixes that.
Tested:
Verified that websockets are now created without errors and access
hostconsole from the GUI.
Upstream work:
- Cherry-picked following commit from upstream and tested
https://github.com/openbmc/bmcweb/commit/1c99da037b2242c6fbad3441038081c5703dc1e9
Change-Id: I52c874de9b02463618143d3b031f5c795dd42ad8

Add missing usage of new verb class in router

---

redfish-core/lib/processor.hpp

```
This reverts commit 9ec664e7971399184865fe1680325de85a596fb0.
```

1050: Revert: Add SubProcessors and CpuCore

---

redfish-core/lib/pcie.hpp
redfish-core/lib/pcie_slots.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemPCIeSlots/index.json
static/redfish/v1/schema/OemPCIeSlots_v1.xml

Added Redfish OEM.IBM property 'LinkId' to PCIeSlots under redfish/v1/Chassis. LinkId maps to dbus BusId property for the Inventory.Item.PCIeSlots interface.
Added Redfish property 'LanesInUse' to PCIeDevices under redfish/v1/Systems. LanesInUse maps to dbus LanesInUse property for the Inventory.Item.PCIeDevice interface. Note: GUI might map this property to 'LinkWidth'
`LinkWidth`: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/58753
`BusId`:     IBM OEM
Tested:
1) Redfish validator passed
2) Curl testing
A)
curl -k <token> https://$bmc/redfish/v1/Chassis/chassis/PCIeSlots ...
{
"Links": {
{
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/pcie_card8"
}
],
...
"Oem": {
"@odata.type": "#OemPCIeSlots.Oem",
"IBM": {
"@odata.type": "#OemPCIeSlots.IBM",
"LinkId": 0
}
}, …

1050: Add Get for PCIe properties LinkId and  LinkWidth (#348)(#398)

---

redfish-core/lib/account_service.hpp

This fixes a bug with the ACF upload function which was introduced in 921ba85e0bc68779573db121790bde574332d395 (the AllowUnauthACFUpload function).  The bug prevents PATCHing the {"ACFFile":null} value from deleting the ACF.  Patching an empty string {"ACFFile":""} works and effectively deletes the ACF.
In this fix, you can PATCH the /redfish/v1/AccountService/Accounts/service property Oem.IBM.ACF.ACFFile to have either the null value, an empty string, or a correct base64-encoded ACF content
Tested: Combinations of ACFFile and AllowUnauthACFUpload property values.

Bug fix: cannot delete ACF

---

redfish-core/lib/pcie.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemPCIeDevice/index.json
static/redfish/v1/schema/OemPCIeDevice_v1.xml

NOTE:A fix of  phosphor-dbus-interface related to  com.ibm.Control.Host.PCIeLink  is needed.
This commit sets linkReset property to the requested value
This is downstream change only
Issue:
https://github.com/ibm-openbmc/dev/issues/3551
Redfish Validator: test passed
Testing:
Set LinkReset to 'true' using PATCH API, and verified the property using GET API
$ curl -k -X PATCH
https://service:passwd@host:18080/redfish/v1/Systems/system/PCIeDevices/pcie_card0 -d '{"Oem": {"IBM": {"LinkReset": true}}}'
https://service:passwd@host:18080/redfish/v1/Systems/system/PCIeDevices/pcie_card0 {
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/pcie_card0",
"Id": "pcie_card0",
"Name": "PCIe Cable Card",
"Oem": { …

1050: PCIe Topology: Redfish: Reset Link (#352)

---

redfish-core/lib/ethernet.hpp

This commit fixes IP address object paths in IP address Patch/Delete functions as per new networkd d-bus object paths
Tested By:
Delete IPv4/IPv6 IP addresses
PATCH IPv4/IPv6 IP addresses
Change-Id: Ia5a9db763a9ce7a2964f4e07cf8ecb85f04d374f

Fix async_method_call object paths while updating/deleting IP address

---

redfish-core/lib/memory.hpp

The redfish validator failed with Enabled not defined.
Bumped the schema to v1_12_0 to access the enabled property.
Signed-off-by: Deepa Karthikeyan <deepakala.karthikeyan@ibm.com>

Bump schema to access Enabled property

---

redfish-core/lib/systems.hpp

This commit adds "system" as the system name in the redfish route handler (/redfish/v1/Systems/system) instead of /redfish/v1/Systems/<str>
The reason for this change is that there are basically two routes defined:
[1] /redfish/v1/Systems/<str>
[2] /redfish/v1/Systems/hypervisor
Whenever a user does a get on /redfish/v1/Systems/hypervisor, the first route is hit and that checks if <str> is system and if not, bmcweb throws resource not found error.
The below upstream commit is causing this issue:
[1] https://github.com/openbmc/bmcweb/commit/22d268cb2c0bc00676d08c79f6ab8958bee74a25#diff-cddfc26fddb6ba29f3fd81ecf5840fc6d9a8554bbca92f578d81b97db8b14895
To resolve this issue, the route handler is changed back to /redfish/v1/Systems/system in this commit.

Add system name in the Redfish Systems route

---

redfish-core/include/utils/pcie_util.hpp
redfish-core/lib/cable.hpp
redfish-core/lib/pcie.hpp
redfish-core/lib/pcie_slots.hpp

This commit makes redfish adapter objects unique, before this commit bmcweb shows redfish adapter objects with the same path even though all the dbus objects have unique paths
{"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/adapter1"}, {"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/adapter1"}.
after this change bmcweb retrieve PCI device endpoint information and then, replace redfish PCI device as
"chassisN_io_moduleN_slotN_adapterN".
this change also affect below path because they also has slot and chassis value in their path.
"/xyz/openbmc_project/inventory/system/chassis/motherboard/pcieslot0/pcie_card0"
Tested result:
```
curl -k -H "X-Auth-Token: $token" -X GET  https://${bmc}/redfish/v1/Systems/system
{
...
...
...
...
{"@odata.id": …
```

1050: Make PCIe Adapter Paths Unique (#372)(#391)

---

redfish-core/lib/oem/ibm/pcie_topology_refresh.hpp
redfish-core/lib/systems.hpp
static/redfish/v1/JsonSchemas/OemComputerSystem/index.json
static/redfish/v1/schema/OemComputerSystem_v1.xml

This implements PATCH of PCIeTopologyRefresh & SavePCIeTopologyInfo.
```
curl -k -X PATCH https://${bmc}:18080/redfish/v1/Systems/system/ -d '{"Oem":{"IBM":{"PCIeTopologyRefresh":true}}}'
curl -k -X PATCH https://${bmc}:18080/redfish/v1/Systems/system/ -d '{"Oem":{"IBM":{"SavePCIeTopologyInfo":true}}}'
```
This pulls in the following 1030 PRs:
- https://github.com/ibm-openbmc/bmcweb/pull/377
- https://github.com/ibm-openbmc/bmcweb/pull/382
- https://github.com/ibm-openbmc/bmcweb/pull/404
- https://github.com/ibm-openbmc/bmcweb/pull/406
This commit also adds functionality, where bmcweb creates a watchdog (using timer) where timer waits for one second and then checks if PCIe Topology gets refreshed or not. If not, then wait for one more second and repeat this process eight times, and then …

1050: Refresh of PCIe Topology (#377)(#382)(#404)(#406)

---

redfish-core/lib/account_service.hpp

```
* Bug fix: cannot delete ACF
This fixes a bug with the ACF upload function which was introduced
in 921ba85e0bc68779573db121790bde574332d395 (the AllowUnauthACFUpload
function).  The bug prevents PATCHing the {"ACFFile":null} value from
deleting the ACF.  Patching an empty string {"ACFFile":""} works and
effectively deletes the ACF.
In this fix, you can PATCH the /redfish/v1/AccountService/Accounts/service
property Oem.IBM.ACF.ACFFile to have either the null value, an empty
string, or a correct base64-encoded ACF content
Tested: Combinations of ACFFile and AllowUnauthACFUpload property values.
* Fixup formatting error
Removed extra blanks
---------
Signed-off-by: …
```

1030: Bug fix: cannot delete ACF

---

redfish-core/lib/log_services.hpp

Redfish GET on system dump entries returned null eventhough the dump entries were found in the backend. This PR fixes this issue by appending to the "Members" field of the redfish response instead of overriding it.
Tested By:
GET https://${bmc}/redfish/v1/Systems/system/LogServices/Dump/Entries

Fix redfish GET issue on Dump collection

---

redfish-core/lib/managers.hpp
redfish-core/lib/oem/ibm/usb_code_update.hpp

Redfish cannot show USBCodeUpdateEnabled because the dbus path has changed:
[1] https://github.com/ibm-openbmc/service-config-manager/commit/4b8637db4280dde044ec37535c3f379362ed3b7c
Fix another issue. When we use PATCH, we receive a propertyUnknown error.
Test:
```
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Managers/bmc
"Oem": {
"@odata.id": "/redfish/v1/Managers/bmc#/Oem",
"@odata.type": "#OemManager.Oem",
"IBM": {
"@odata.id": "/redfish/v1/Managers/bmc#/Oem/IBM",
"@odata.type": "#OemManager.IBM",
"USBCodeUpdateEnabled": false
},
"OpenBmc": {
"@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc",
"@odata.type": "#OemManager.OpenBmc",
"Certificates": {
"@odata.id": "/redfish/v1/Managers/bmc/Truststore/Certificates"
}
}
},
```

1050: Fix redfish can't show USBCodeUpdateEnabled

---

redfish-core/include/utils/chassis_utils.hpp

IBM does not use the xyz.openbmc_project.Inventory.Item.Board interface for chassis objects. 
Remove that interfaces so only objects implementing xyz.openbmc_project.Inventory.Item.Chassis are returned for getValidChassisPath

1050: Remove Inventory.Item.Board interface from Chassis (#415)

---

redfish-core/lib/fabric_adapters.hpp

PCIeDevice device object is unique, but a fabric adapter on PCIeDevice is missing from it.  This fixes to make this Fabric Adapter on PCIeDevice as unique as like the other PCIeDevices.
PCIeDevices link should point to a correct/valid PCIeDevices.
```
% curl -k -X GET https://${bmc}:18080/redfish/v1/Systems/system/FabricAdapters/pcie_card10
{
"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/pcie_card10",
"Id": "pcie_card10",
"Links": {
{
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/chassis_motherboard_pcieslot10_pcie_card10"
}
],
"PCIeDevices@odata.count": 1
},
...
}%
```

Fix FabricAdapter Path on PCIeDevie to be unique

---

redfish-core/lib/pcie_slots.hpp

The commit implement channges to populate link(s) to processor associated witha given PCIeSlot.
The association is established by fetching mapper endpoints "upstream_processor" w.r.t given PCIeSlot.
Validator has been executed and no new error was found.
Sample output:
{
"Lanes": 0,
"Links": {
{
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/chassis_motherboard_pcieslot0_pcie_card0"
}
],
"Processors": [
{
"@odata.id": "/redfish/v1/Systems/system/Processors/dcm1-cpu1"
}
],
"Processors@odata.count": 1
},
"Oem": {
"@odata.type": "#OemPCIeSlots.Oem",
"IBM": {
"@odata.type": "#OemPCIeSlots.IBM",
"LinkId": 0
}
},
"SlotType": "FullLength"
},
}

Link PCIeSlots to Processor schema

---

redfish-core/lib/systems.hpp

The reason for this change is that there are basically two routes defined: [1] /redfish/v1/Systems/<str>/ResetActionInfo/ in systems.hpp [2] /redfish/v1/Systems/hypervisor/ResetActionInfo/ in hypervisor_system.hpp
Whenever a user does a get on /redfish/v1/Systems/hypervisor/ResetActionInfo, the first route is hit and that checks if <str> is "system" and if not, bmcweb throws resource not found error.
Error:
ERROR - Members: GET of resource at URI /redfish/v1/Systems/hypervisor/ResetActionInfo
returned HTTP error. Check URI.
ERROR - URI did not return resource /redfish/v1/Systems/hypervisor/ResetActionInfo
GET Failure HTTP Code (404)
The below upstream commit is causing this issue:
[1] openbmc/bmcweb@22d268c#diff-cddfc26fddb6ba29f3fd81ecf5840fc6d9a8554bbca92f578d81b97db8b14895
To resolve …

Add system name in the Redfish Systems ResetActionInfo

---

redfish-core/include/utils/collection.hpp
redfish-core/include/utils/fabric_util.hpp
redfish-core/lib/cable.hpp
redfish-core/lib/fabric_adapters.hpp
redfish-core/lib/port.hpp

Defect is https://w3.rchland.ibm.com/projects/bestquest/?defect=SW552762 This commit makesFabric Adapters objects unique, before this commit bmcweb shows Fabric Adaptersobjects with the same path even though all the dbus objects have unique paths
```
{"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/io_module1"},
{"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/io_module1"}
```
after this change bmcweb retrieve FabricAdapterdevice endpoint information and then, replace redfish FabricAdapter device as
"chassisN-logical_slotN-io_moduleN".
Tested: Validator passed
Motherboard FabricAdapter also gets affected.
```
curl -k -H "X-Auth-Token: $token" -X GET  https://${bmc}/redfish/v1/Systems/system/FabricAdapters/
{
...
...
"Members": [
{
"@odata.id": …
```

1050: Build Fabric Adapters Unique Path (#397)

---

static/redfish/v1/JsonSchemas/OemMessage/index.json
static/redfish/v1/schema/OemMessage_v1.xml

Redfish validator throws an error due to OemMessage EntityType resource not containing the required @odata.id property.
Testing:
Ran validator and verified the error is not thrown, and the overall validator test passed.
Known Issue: Validator test gives WARNING/FAIL for OEM properties. This is across all downstream OEM schemas. This needs to be handled separately for all OEM schemas.

1050: Fix OemMessage Schema (#431)

---

http/http_client.hpp
src/webserver_main.cpp

Currently there are no events send to HMC with OpenBMC upstream redfish event code.
This commit modifies SSL context to use "boost::asio::ssl::context::tlsv13_client" in the 
eventing code to send events to HMC
Tested By:
Connected BMC to HMC and seen event subscription added 
Noticed Task, Dump and save area redfish events received on HMC.

RedfishEvents: Fix upstream redfish events code for HMC

---

include/dbus_utility.hpp
redfish-core/include/utils/chassis_utils.hpp
redfish-core/include/utils/dbus_utils.hpp
redfish-core/include/utils/error_log_utils.hpp
redfish-core/include/utils/hw_isolation.hpp
redfish-core/include/utils/name_utils.hpp
redfish-core/lib/assembly.hpp
redfish-core/lib/log_services.hpp
redfish-core/lib/memory.hpp

Use sdbusplus::asio wrapper functions getProperty and getAllProperties in place of direct "Get" and "GetAll".
This is created to address the comment https://github.com/ibm-openbmc/bmcweb/pull/542#discussion_r1107935850
Tested output:
-bash-4.2$ curl -k -H "X-Auth-Token: 
{BMC_IP}/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries
{
"@odata.id": "/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries",
"@odata.type": "#LogEntryCollection.LogEntryCollection",
"Description": "Collection of System Hardware Isolation Entries",
"Members": [
{
"@odata.id": "/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries/1",
"@odata.type": "#LogEntry.v1_9_0.LogEntry",
"Created": "2023-03-06T00:43:47+00:00",
"EntryType": "Event",
"Id": "1",
"Links": {
"OriginOfCondition": { …

Using sdbusplus::asio wrapper functions

---

static/redfish/v1/JsonSchemas/OemMessage/index.json
static/redfish/v1/schema/OemMessage_v1.xml

Redfish validator throws an error due to OemMessage EntityType resource not containing the required @odata.id property.
Testing:
Ran validator and verified the error is not thrown, and the overall validator test passed.
Known Issue: Validator test gives WARNING/FAIL for OEM properties. This is across all downstream OEM schemas. This needs to be handled separately for all OEM schemas.

1050: Redo - Fix OemMessage Schema (#431)(#609)

---

http/http_connection.hpp
include/audit_events.hpp
include/login_routes.hpp
redfish-core/lib/redfish_sessions.hpp

This supersedes: https://github.com/ibm-openbmc/bmcweb/pull/456
This is a 1030.
Please cherry pick into 1040 as well. 
This fixes defects:  https://w3.rchland.ibm.com/projects/bestquest/?defect=SW558520  and https://w3.rchland.ibm.com/projects/bestquest/?defect=PE00DWMX
1. [swap strcpy for strncpy](https://github.com/ibm-openbmc/bmcweb/commit/3d8ae93444cee8875deb0b5d067f195041f3cb85)
a.     strncpy has range checks, which reduce the possibility of overrunning the buffer in the case of a bug. see https://github.com/ibm-openbmc/bmcweb/commit/eb7d3d5400555715d755ed03722dbbfe2b6607c9
2. [Refactor audit logs](https://github.com/ibm-openbmc/bmcweb/commit/def76ffbacc34a67369f4c91ea0b30b7e532d86f)
a.  Pass in UserName and IpAddress.
b.  Move to userSession->username over req.session->username 
c. …

Audit log enhancements and fixs

---

redfish-core/src/error_messages.cpp

This fixes the http error code of the operations of the restricted role which currently result in bad_request (400) instead of forbidden (403).
Defect:
https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=356235
Upstream: 
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/61657
Change-Id: I1b212ccb5a630750eb5d4197970b4fb75fceffd7
Tested:
```
user=service
pass=<admin's passwd>
$ redfishtool -r ${bmc}:18080 -u ${user} -p ${pass} -S Always raw POST /redfish/v1/AccountService/Accounts -d '{"UserName":"service","Password":"newPwd1","RoleId":"Operator"}'
redfishtool: Transport: Response Error: status_code: 403 -- Forbidden--user not authorized to perform action
redfishtool: raw: Error sending POST to resource, aborting
$ redfishtool -r …
```

1050: Return forbidden return code for RestrictedRole operations

---

redfish-core/lib/ethernet.hpp

Network backend does not return the AddressState and its currently displayed as null. This is misleading the user
This commit removes this property until backend suppports.
Tested by:
Verify ethernet interface does not return AddressState for IPv6
Change-Id: I5489f57ce3d50d1480033f27adf1bc95153fdd18
Signed-off-by: Sunitha Harish <sunithaharish04@gmail.com>

Remove AddressState from redfish response

---

redfish-core/include/resource_messages.hpp
redfish-core/lib/log_services.hpp

There were a few changes missed during the rebase activity
This change will fix the following issues:
* BMC dumps on successful creation is reported as Resource_<bmc dump id> in the task header
* Resource creation fails to initiate with "Wrong parameter values passed" error
Tested-By:
* Created a BMC dump and checked the task URI associated with this dump creation for correct bmc dump id in the "Location" field
* Successful reation of a resource dump

Fix issues while creating dumps

---

redfish-core/include/utils/name_utils.hpp

The method getPrettyName() may be called more than one time.
This will generate journal logging messages for the required Service name
if there are unexpected service names.

1050: Logging invalid service name for debug (#291)

---

redfish-core/lib/assembly.hpp

Defect is https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=454681
Have a defect where assemblies for the I/O expansion chassis's assemblies don't have an operationalStatus because we don't know the health of the FRU but we still have a Redfish Health for these FRUs. Upstream we have been default Health and State, the thinking is "Hey I reported this inventory item, mark it as good by default.". Upstream maybe we should do something different.
Didn't test directly but tested 1030.
https://github.com/ibm-openbmc/bmcweb/pull/627/ is the 1030/1040 PR.

1050: Remove the default assembly Health

---

include/dbus_utility.hpp

https://github.com/ibm-openbmc/bmcweb/pull/426/files added MapperGetObject but that code isn't in 1020 so just add this line to match 1030/1040 and allow
https://github.com/ibm-openbmc/bmcweb/commit/7d10d4550b194818db62c87196739e8a7915cf8e to compile.
https://github.com/ibm-openbmc/bmcweb/blob/1030/include/dbus_utility.hpp#L55
See https://ibm-systems-power.slack.com/archives/C04KG79NAUA/p1679089972649529?thread_ts=1679071244.184949&cid=C04KG79NAUA
Tested: None. 1020 bmcweb compiles though.

dbus_utility: Add MapperGetObject

---

redfish-core/lib/systems.hpp

Upstream is https://gerrit.openbmc.org/c/openbmc/bmcweb/+/61787 and it going to merge when Chris hits submit 
Prior commit missed adding a required property to a rewrite using sdbusplus::unpackProperties()
Fixes a regression introduced in commit
bc1d29de81216e99d0a73c5fd3b6bb7fd2194ba8
Validator passed:
IdlePowerSaver	[JSON Object]	ComputerSystem.v1_16_0.IdlePowerSaver	Yes	complex IdlePowerSaver.Enabled	False	boolean	Yes	PASS
IdlePowerSaver.EnterUtilizationPercent	8	number	Yes	PASS IdlePowerSaver.EnterDwellTimeSeconds	240	number	Yes	PASS IdlePowerSaver.ExitUtilizationPercent	12	number	Yes	PASS IdlePowerSaver.ExitDwellTimeSeconds	10	number	Yes	PASS
Change-Id: I345c714b71d50d6c8c03120c54bdabe0bd5d0714

systems: Fix missing EnterDwellTime property

---

http/ut/utility_test.cpp
http/utility.hpp
redfish-core/include/utils/hw_isolation.hpp
redfish-core/lib/certificate_service.hpp
redfish-core/lib/license_service.hpp
redfish-core/lib/log_services.hpp
redfish-core/lib/managers.hpp
redfish-core/lib/metric_report.hpp
redfish-core/lib/power_supply_metrics.hpp
redfish-core/lib/systems.hpp
redfish-core/lib/task.hpp

This commit fixes time_t over flow error.
Also fixes the issue of displaying wrong date expiration date for UAK and AIX key licences in the BMC when expiration date is date past 01/01/2038 .
Tested by :
curl -k -H "X-Auth-Token: $bmc_token" -X GET https://$/{bmc_ip}/redfish/v1/LicenseService/Licenses/UAK
curl -k -H "X-Auth-Token: $bmc_token" -X GET https://$/{bmc_ip}/redfish/v1/LicenseService/Licenses/AIX

Displaying wrong date expiration date for UAK and AIX key licences

---

redfish-core/lib/led.hpp

As a part of https://github.com/ibm-openbmc/bmcweb/pull/630, LocationIndicatorActive slot is added only if there is an association to Led Group.
This change have caused a side-effect of bmcweb coredump during PCIeSlots LocationIndicator handling.
So at this time, led.hpp will be rolled-back
so that the slot is always added even if there is no association.
The error happened with PR630.
```
$ curl -k -X GET https://${bmc}:18080/redfish/v1/Chassis/chassis/PCIeSlots
curl: (52) Empty reply from server
```
Its debug traces are:
```
(2023-03-23 20:56:56) [DEBUG "routing.hpp":1364] Matched rule '/redfish/v1/Chassis/<str>/PCIeSlots/' 1 / 2
(2023-03-23 20:56:56) [DEBUG "routing.hpp":1401] userName = service userRole = priv-oemibmserviceagent
(2023-03-23 20:56:56) [DEBUG "query.hpp":114] setup …
```

1050: Rollback to add LocationIndicator slot (#630)

---

redfish-core/lib/hypervisor_system.hpp

When a user enables "IPv6AutoConfigEnabled", the "AddressOrigin" property shows "Static" in the response. This commit will change it to "SLAAC".
Tested By:
PATCH -d '{"StatelessAddressAutoConfig": {"IPv6AutoConfigEnabled":true}}' \ https://${bmc}/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth0
Fixes: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=449841
Change-Id: Icf602401b9fa51aac6d30dd429e3623e6efbc402

Correct the AddressOrigin in redfish response

---

redfish-core/lib/processor.hpp

This was missed while rebasing 1030 changes. NA for Upstream as we do not have the method to patch Cpu Core Members on upstream
It is fixed now and handles 
curl -k -H "X-Auth-Token: $bmc_token" -X PATCH
https://${BMC_IP}/redfish/v1/Systems/system/Processors/dcm0-cpu0/SubProcessors/core8 -d '{"Enabled" : <true/false> }' successfully

Handle patchCpuCoreMembers request

---

http/utility.hpp
redfish-core/include/registries/openbmc_message_registry.hpp
redfish-core/lib/log_services.hpp
test/http/utility_test.cpp

- In the current state, the BIOS Post code message registry has a place holder to only display a hex based post code.
- Since Power 5 series of servers, IBM progress codes are ASCII based character codes as mentioned in the below link: (https://www.ibm.com/support/knowledgecenter/POWER5/ipha6_p5/progcodesmain.htm)
- These progress codes are displayed in multiple places like BMC GUI, Operator Panel , Hardware Management Console e.t.c, and most of the customers of power are well accustomed to seeing these character based codes. And in the current infrastructure we display the hex form of uint64 value, which can lead to misses where some customer does not know how to look up the code & translate it to ASCII and last thing we would want is for a service rep to do the translation.
- For most …

Add new Message registry with ASCII post code place holder

---

redfish-core/include/utils/hw_isolation.hpp
redfish-core/lib/log_services.hpp
redfish-core/lib/power_supply_metrics.hpp

This PR resolves the compilation issues related
to std::time_t due to upstream rebasing.
Tested By:
[1] GET https://${bmc}/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries/1
The redfish response showed the correct
"Created" date time value

Fix std::time_t compilation errors

---

redfish-core/lib/port.hpp

Port collection incorrectly returns an empty set
although the associated connectors are discovered.
For example,
FabricAdapter shows Ports.
```
% curl -k -X GET https://${bmc}/redfish/v1/Systems/system/FabricAdapters/chassis-motherboard-disk_backplane0
{
"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/chassis-motherboard-disk_backplane0",
"Id": "chassis-motherboard-disk_backplane0",
....
"Ports": {
"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/chassis-motherboard-disk_backplane0/Ports"
},
.....
}
}%
```
However, its port collection gives an empty list.
```
% curl -k -X GET https://${bmc}/redfish/v1/Systems/system/FabricAdapters/chassis-motherboard-disk_backplane0/Ports
{
"@odata.id": …
```

1050: Fix FabricAdapters Port Collection Handling

---

Redfish.md
http/http_client.hpp
redfish-core/include/redfish.hpp
redfish-core/include/redfish_aggregator.hpp
redfish-core/include/utils/query_param.hpp
redfish-core/lib/aggregation_service.hpp
redfish-core/lib/log_services.hpp
subprojects/boost.wrap
test/redfish-core/include/redfish_aggregator_test.cpp
test/redfish-core/include/utils/query_param_test.cpp

Confirmed that with these patches we can get /redfish/v1/AggregationService function working:
```
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/AggregationService
{
"@odata.id": "/redfish/v1/AggregationService",
"@odata.type": "#AggregationService.v1_0_1.AggregationService",
"AggregationSources": {
"@odata.id": "/redfish/v1/AggregationService/AggregationSources"
},
"Description": "Aggregation Service",
"Id": "AggregationService",
"Name": "Aggregation Service",
"ServiceEnabled": true
}
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/AggregationService/AggregationSources
{
"@odata.id": "/redfish/v1/AggregationService/AggregationSources",
"@odata.type": "#AggregationSourceCollection.AggregationSourceCollection",
"Members": [
{
"@odata.id": …
```

1050 upstream aggregation patches

---

http/http_connection.hpp

Added PUT event for HMC config file management to events tracked in the audit log. Body is not included since it contains the config file data itself. Excluding body data for all IBM management console events as the data can be binary and larger than the audit log buffer size.
Tested these URI:
{PUT|DELETE} /ibm/v1/Host/ConfigFiles
POST /ibm/v1/Host/ConfigFiles/Actions/IBMConfigFiles.DeleteAll
Tested these additional URI:
POST /ibm/v1/HMC/BroadcastService
POST /ibm/v1/HMC/LockService/Actions/LockService.AcquireLock
Confirmed non IBM management console events still getting body data in audit log entry.

Audit Log: Add PUT events to audit log for HMC config file management

---

http/websocket.hpp
include/sessions.hpp

Defect is https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=386332
Should go into 1020/1030/1040 but that is going to be a separate PR, Joseph and I can talk about who does that. 
https://github.com/openbmc/bmcweb/commit/f8aa3d2704d3897eb724dab9ac596af8b1f0e33e (4/15/20) added CSRF check into websockets but later setting cookieAuth to true was removed so this session->cookieAuth is always false. https://github.com/openbmc/bmcweb/commit/3909dc82a003893812f598434d6c4558107afa28 (7/15/20).
2 choices here add back this cookieAuth=true when cookie auth is used or remove this "if cookieAuth" and do this check anytime BMCWEB_INSECURE_DISABLE_CSRF_PREVENTION isn't enabled.
Really we shouldn't support any other auth on websockets so maybe if …

Fix websocket csrf checking

---

redfish-core/lib/memory.hpp

Issue:
Even after successfully guarding the Dimm, we see
ResourceNotFound Extended Error info
Fix:
When we try to enable or disble a Dimm using redfish, it tries to set the DimmData for the locationIndicatorActive everytime. This is to be called only when locationIndicatorActive is provided similar to how it is done for 1030. So updated the code to match 1030.
Tested and works as expected.

Fix ResourceNotFound on manual guard of Dimm

---

http/http_connection.hpp
http/http_response.hpp
http/http_stream.hpp
http/routing.hpp
include/dump_offload.hpp
redfish-core/include/redfish.hpp

The dumps were not getting offloaded and this is because the route handlers for the same were not invoked on a GET request.
This issue is resolved by modifying the dump offload code as per the upstream http connection framework and allows clients to offload dumps using redfish URI.
This PR:
1. Enables dynamic response support
2. Defines new bmcweb rule to support dump streaming.
3. Adds routes for bmc and system dump offload.
The existing http connection is implemented based on http string buffer and now the http stream connection is implemented using http dynamic buffer body that enables dump data streaming over https. This dynamic buffer sends the data size that is to be received by the client in the http header, so that the client waits till data with the given size is received before …

Fix dump offload issue

---

redfish-core/lib/fan.hpp

Add sparePartNumber for Fan
This commit fixes defect 459342, by adding sparePartNumber for Fan.
Tested-
-Ran Redfish service validator and no new errors were seen.
and can see the sparePartNumber for fans.
https://sys-openbmc-dev-jenkins.swg-devops.com/job/OpenBMC-Dev/job/test/job/continuous-integration/job/ebmc/job/Redfish-Service-Validator/1212/artifact/logs/ConformanceHtmlLog_04_01_2023_122547.html
-Verified on Rainier100 system, sparePartNumber shows up for fans.
curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan0_1
{
"@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan0_1",
"@odata.type": "#Fan.v1_3_0.Fan",
"Id": "fan0_1",
"Location": {
"ServiceLabel": "U78DA.ND0.WZS004A-A0"
}
}, …

Add sparePartNumber for Fan

---

http/app.hpp
http/http_connection.hpp
http/routing.hpp

Fix redfish browser to show html redfish logo.
It is also reported by tester - https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=483135
On bmc redish web view, DMTF Redfish logo fails to display.
It is because the headers in the Request is no longer valid
after the use of move().
The following upstream commits are needed.
- Add asyncResp support to handleUpgrade https://gerrit.openbmc.org/c/openbmc/bmcweb/+/46989
Change-Id: I1c6c91f126b734e1b5573d5ef204fe2bf6ed6c26
- Add Support for privilege check in handleUpgrade https://gerrit.openbmc.org/c/openbmc/bmcweb/+/46991?usp=search
Change-Id: I6f743c27e7e6077f1c6c56e6958922027e4404e8
- Fix some moves
Change-Id: Ib6d99726a64326b7c8bad15bc9d4ca774ab6256d …

1050: Fix redfish browser - html redfish logo display

---

http/http_client.hpp

- Repeated error logs about connection fail .
- Cleaning repeated error logs and displaying them as debug logs .

Display "connection fail" as DEBUG LOG not ERROR LOG

---

redfish-core/lib/redfish_v1.hpp

Defect is https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=486536
Upstream is merged at https://gerrit.openbmc.org/c/openbmc/bmcweb/+/61133
404/405 which are part of 4xx errors are client-side errors. These might be server errors, e.g. a client is walking the redfish tree and had a id that no longer exists but they could also be the client tried an id or URL that isn't there, e.g. a fuzz tester. Due to this, use WARNING log level.
A future commit attempts to better clarify our log levels.
Saw "404 on path v1/badinput/badinput"
Tested: None.
Change-Id: I4f056754638ef2d640615e9fcc74a7a68a767593

Change BMCWEB_LOG level for 404/405

---

src/webserver_main.cpp

This change will add call to register for VMI IP change signal, thus allowing bmcweb to send events related to VMI IP configuration.
Fixes:
[484430](https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=484430)
Tested By:
* Configure Static/DHCP ip on any interface
* Events are being sent to the connected/subscribed client

Add call to register VMI IP change monitor

---

redfish-core/lib/pcie.hpp

PCIe hardware topology fails to load io module PCIeDevices info like:
```
curl -k  -v 'https://${BMC}/redfish/v1/Systems/system/PCIeDevices?$expand=.($levels=2)'
curl -k  -X GET  https://${bmc}/redfish/v1/Systems/system/PCIeDevices/system_chassis15363_logical_slot1_io_module1
```
It is due to the missing interface specification to obtain getDbusObject().
Upstream is communicated in  https://gerrit.openbmc.org/c/openbmc/bmcweb/+/61625
Tested:
- Redfish validator passed
- Run PCIe hardware topology on GUI and monitor Web "inspect" Network activities
The error output is like:
```
curl -k  -X GET  https://${bmc}/redfish/v1/Systems/system/PCIeDevices/system_chassis15363_logical_slot1_io_module1
{
"error": {
{
"Message": "The …
```

1050: Fix GET PCIeDevice to io drawer module (e.g. MEX)

---

http/app.hpp
http/http_connection.hpp
http/routing.hpp

This reverts this PR: 
https://github.com/ibm-openbmc/bmcweb/pull/658
This PR was the only bmcweb PR to go into 2.22 
https://github.ibm.com/openbmc/release-notes/wiki/fw1050.00-2.22
2.22 is were we first saw bmcweb hanging and core dumping when shut down. Defects are: 
487666
487798
487741
The root cause can be investigated more but for now, let's get the train back on the tracks. 
Tested: bmcweb with 2.21 works on one of the systems we saw this happening on. Built bmcweb with this commit and loaded onto 2 of the bmcs we saw this on and no longer are hanging.

Revert commits to fix bmcweb crash hang

---

redfish-core/lib/pcie_slots.hpp

Bmcweb: Add PcieSlots Location Code
This commit fixes this STG Defect 478749.
This commit adds location code for pcieSlots.
Upstream commit- https://gerrit.openbmc.org/c/openbmc/bmcweb/+/62219
Tested:
-Ran Redfish service validator,
No new error and can see the Location code for pcieSlots
-Verified on Rainier100 system, Location code shows up for PCIeSlots.
curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots
{
"@odata.type": "#PCIeSlots.v1_5_0.PCIeSlots",
"Id": "1",
"Name": "PCIe Slot Information",
"Slots": [
{
"Lanes": 0,
"Links": {
"Oem": {
"IBM": {
"AssociatedAssembly": [
{
"@odata.id": "/redfish/v1/Chassis/chassis/Assembly#/Assemblies/19"
}
]
}
},
{ …

Bmcweb: Add PcieSlots Location Code

---

redfish-core/lib/fabric_adapters.hpp

The commit implement changes to make use of util function to populate name for fabric adapters.
Validator was executed and no new error was found.
Test output:
{
"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/motherboard-pcieslot0-pcie_card0",
"Id": "motherboard-pcieslot0-pcie_card0",
"Links": {
{
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/chassis_motherboard_pcieslot0_pcie_card0"
}
],
"PCIeDevices@odata.count": 1
},
"Location": {
"ServiceLabel": "U78DA.ND0.       -P0-C0"
}
},
"LocationIndicatorActive": null,
"Name": "PCIe Card",
"Ports": {
"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/motherboard-pcieslot0-pcie_card0/Ports"
},
"Status": {
"State": "Absent" …

Add pretty name for fabric adapters

---

http/utility.hpp

The upstream rule is to set the default value if the port is not compliant.
IBM requires an error to be returned if the port is not compliant. 
ref: https://github.com/ibm-openbmc/dev/issues/3626
Test:
```
curl -k -H "X-Auth-Token: $token" -X POST https://${bmc}/redfish/v1/EventService/Subscriptions -d '{"Destination":"snmp://9.41.166.76:65536", "SubscriptionType":"SNMPTrap", "Protocol":"SNMPv2c"}'
{
"Destination@Message.ExtendedInfo": [
{
"Message": "The value 'snmp://9.41.166.76:65536' for the property Destination is of a different format than the property can accept.",
"snmp://9.41.166.76:65536",
"Destination"
],
"MessageId": "Base.1.13.0.PropertyValueFormatError",
"MessageSeverity": "Warning",
"Resolution": "Correct the value …
```

1050: Redfish check snmpTrap port

---

redfish-core/lib/network_protocol.hpp
redfish-core/lib/redfish_util.hpp
redfish-core/lib/systems.hpp

Bonnell only has one ethernet port. A bug in bmcweb code was found when dealing with this in the redfish/v1/Managers/bmc/NetworkProtocol interface. See commit messages for more details and testing information.
This brings in one merged upstream change which is a pre-req to pulling in the 2 fixes (which are still under review):
- https://gerrit.openbmc.org/c/openbmc/bmcweb/+/44438
- https://gerrit.openbmc.org/c/openbmc/bmcweb/+/62229
- https://gerrit.openbmc.org/c/openbmc/bmcweb/+/62278
This was found as a part of Defect 484897 work

1050 single eth port fix

---

redfish-core/lib/log_services.hpp

Currently, when a user does a DELETE operation on
any of the system dumps, "Resource Not Found" error is being sent back by bmcweb.
This is because, all the system dump entry IDs will be of the format: < dumpType >_< ID >. For example, "Resource_1"/"System_1". Currently, no logic is present to get dump id from the above string to make dbus call and the call fails. This issue is resolved in this PR.
Fixes:
https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=493478
Change-Id: Ifde5a532bcc90e6c5c150a704c8e045b8befbf48

Fix system dump delete functionality

---

http/app.hpp
http/http_connection.hpp
http/routing.hpp

Fix redfish browser to show html redfish logo.
It is also reported by tester - https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=483135
On bmc redish web view, DMTF Redfish logo fails to display.
It is because the headers in the Request is no longer valid after the use of move().
The following upstream commits are needed.
- Add asyncResp support to handleUpgrade 
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/46989
Change-Id: I1c6c91f126b734e1b5573d5ef204fe2bf6ed6c26
- Fix Request use-after-move
Change-Id: Iae68a68817146c28377bbcade04716725e4a6096 
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/61768
Tested:
- Redfish validator passed
- `https://${bmc}/redfish/v1` is showing the pretty redfish logo
- Tried some GUI pages and worked …

1050: Fix Pretty redfish html logo display (#658) (#669)

---

redfish-core/lib/log_services.hpp

Fault data dump contains the server fault information and is collected by the BMC and is stored on the bmc.
This dump entry will be stored as one other bmc dump entry in the dbus. This code adds support for creation of this dump. Listing and deletion of this dump will be the same as how it is done for bmc dump.
Tested By:
* Create dump command: POST https://${bmc}/redfish/v1/Managers/bmc/LogServices/Dump\ /Actions/LogService.CollectDiagnosticData -d \
'{"DiagnosticDataType":"Manager", "OEMDiagnosticDataType":"FaultData"}'
* List dumps: GET https://${bmc}/redfish/v1/Managers/bmc/LogServices/Dump/Entries/
* Get dump: GET https://${bmc}/redfish/v1/Managers/bmc/LogServices/Dump/Entries/<id>
* Delete dump: DELETE https://${bmc}/redfish/v1/Managers/bmc/LogServices/Dump/Entries/<id>
Change-Id: …

Add support for fault data dump

---

include/dbus_utility.hpp
redfish-core/include/redfish.hpp
redfish-core/include/utils/power_supply_utils.hpp
redfish-core/lib/power_supply.hpp
redfish-core/lib/power_supply_metrics.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemPowerSupplyMetrics/index.json
static/redfish/v1/schema/OemPowerSupplyMetrics_v1.xml

Add support for the PowerSupplyMetrics Redfish schema.
Add the Metrics property to the Redfish PowerSupply output.  This property contains the URI for the power supply metrics.
Implement basic support for the PowerSupplyMetrics schema.  Initially support only power supply input power history.  Input history is not currently defined in the Redfish specification, and it is defined in OpenPower D-Bus interfaces, so it is stored in an IBM OEM property.
Modify the XML and JSON PowerSupplyMetrics schemas to define the IBM OEM property.
Tested:
* Passed the Redfish Validator
* Verified power supply input history displayed for chassis PSUs
* Verified power supply input history not displayed for I/O drawer PSUs
* For detailed test plan, see …

PowerSubsystem: Add PowerSupplyMetrics

---

http/utility.hpp

Allow the use of an empty port to configure the SNMP manager, and set it to 162 when the port number is empty.
Test:
curl -k -H "X-Auth-Token: $token" -X POST
https://${bmc}/redfish/v1/EventService/Subscriptions -d '{"Destination":"snmp://9.41.166.76:",
"SubscriptionType":"SNMPTrap", "Protocol":"SNMPv2c"}' {
{
"Message": "The resource has been created successfully.",
"MessageId": "Base.1.13.0.Created",
"Resolution": "None."
}
]
}
https://${bmc}/redfish/v1/EventService/Subscriptions/snmp1 {
"@odata.id": "/redfish/v1/EventService/Subscriptions/snmp1",
"@odata.type": "#EventDestination.v1_8_0.EventDestination",
"Context": "",
"Destination": …

1050: Redfish SNMP: Allow use of empty port

---

redfish-core/lib/account_service.hpp
redfish-core/lib/service_root.hpp
static/redfish/v1/JsonSchemas/OemManagerAccount/index.json
static/redfish/v1/schema/OemManagerAccount.v1_0_0.xml

* New property to always AllowUnauthACFUpload
This adds a new BMC security setting as a Redfish OEM property: URI /redfish/v1/AccountService/Accounts/service property Oem.IBM.ACF.AllowUnauthACFUpload can be set by the admin.  When true, any network agent is allowed to upload an ACF file to the BMC. The default value is false.  This capability is included in the existing URI /redfish/v1 property Oem.IBM.ACFWindowActive.  For example, when AllowUnauthACFUpload=true, ACFWindowActive is true.
This requires https://github.ibm.com/openbmc/openbmc/pull/3585
Tested: via Redfish scenarios
1. Ensure AllowUnauthACFUpload=false by default.
2. Ensure a non admin user is not allowed to GET or PATCH AllowUnauthACFUpload.
3. Ensure the admin can PATCH AllowUnauthACFUpload true and false, and GET the …

1050: New property to always AllowUnauthACFUpload (#466)

---

http/http_stream.hpp
http/routing.hpp
http/websocket.hpp
include/dbus_utility.hpp
include/nbd_proxy.hpp

There are a few issues in handling handleUpgrade - esp on websocket areas.
- Remove duplicated req var in a child http_stream
http_stream has a shadowed 'req' variable between parent and child classes and it may cause the confusion in execution.
- Copy privilegeset into websocket rule
privilegesSet became empty when a connection is upgraded.
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/62275
- Remove try-catch blocks on handleUpgrade
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/61617
- nbd proxy and websocket cleanups
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/51428
The nbd (and all websocket daemons) suffer from a problem
where there is no way to apply socket backpressure, so in certain
conditions, it's trivial to run the BMC out of memory on a given
message.  This is a problem. …

1050: Fix duplicated var definition in http_stream classes and fix handle upgrade

---

include/ibm/management_console_rest.hpp
redfish-core/include/event_service_manager.hpp

Broadcast events were not sent in the right format to the connected client due to which the client was unable to process the event.
Currently the events are sent in the following format: events:{
"Message": "<>",
"Name": "Broadcast Message",
"OriginOfCondition": "/ibm/v1/HMC/BroadcastService",
"Timestamp": "2023-05-05T03:15:50+00:00"
}
With this PR, the event json is changed to the following format which is the common format for all kinds of events: {
"@odata.type":"#Event.v1_4_0.Event",
"Events":{
"EventId":"Broadcast Event",
"EventTimestamp":"2020-07-15T12:03:30+00:00",
"MemberId":"Broadcast Event",
"Message":"Hi This is a message to forward to a single HMC",
"OriginOfCondition":"/ibm/v1/HMC/BroadcastService"
},
"Id":1,
"Name":"Event Log"
}
Fixes: …

Fix broadcast eventing issue

---

http/http_connection.hpp
include/audit_events.hpp
include/login_routes.hpp
meson.build
meson_options.txt
redfish-core/lib/managers.hpp
redfish-core/lib/redfish_sessions.hpp

Pull in all of the commits needed to support audit logging in bmcweb. These are all previously merged in 1030/1040.
This introduces a new bmcweb meson option, audit-events, which is defaulted to disabled. A later commit to openbmc/openbmc will enable audit logging on 1050. 
When audit-events is enabled all bmcweb PATCH, POST, PUT, and DELETE events are logged using the Linux kernel auditd subsystem. Additionally, login events coming through bmcweb are also recorded.
The body of the events is recorded as well except in the following cases:
- /redfish/v1/AccountService/Accounts PATCH/POST events - body is not recorded as it may contain clear text password
- /ibm/v1 PATCH/POST/PUT events - body is not recorded as it contains HMC config file binary data
Events are recorded in /var/log/audit/. …

1050 add audit log support

---

redfish-core/lib/pcie_slots.hpp

https://github.com/ibm-openbmc/bmcweb/pull/650 added PcieSlots Location Code but it throws an internal error when there is no location code interface. Location code isn't required and logical slots don't have a location code so just leave off location code if the interface isn't there. This is what we had for 1030.
Archana was seeing "Base.1.13.0.InternalError", at https://${bmc}/redfish/v1/Chassis/chassis15364/PCIeSlots
Tested: Loaded onto the system and didn't see the error anymore.

Don't internal error if no slot location code

---

include/login_routes.hpp

The audit logging of a success login case was happening even if the login failed. This was because of the placement of the callout to do the logging. Moved the callout so that the logging only happens after a pamAuthenticateUser() call. Success or fail reported will depend on result of the authentication.
This fixes STG Defect 532686.
Tested:
Initiated failed login and saw only failure audit entry added.
Initiated success login and saw only success audit entry added.

Audit Log: Correct logging of success login case.

---

subprojects/boost.wrap

Took this file from upstream at
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/62818/11/subprojects/boost.wrap
We don't actually need this to accomplish building upstream bmcweb with 1050. 
https://github.ibm.com/openbmc/openbmc/pull/3649
But will want if we start using Boost::urls::format or other boost 1.82 features. Because of that I propose we just move to it. 
Tested: Built with 1050 and looked good when running out to /tmp/ on a rainier

Move to boost 1.82

---

include/event_dbus_monitor.hpp
src/webserver_main.cpp

HMC is not receiving events for the SAI logical LEDs like platform_system_attention_indicator and
partition_system_attention_indicator due to which the System Attention LED on HMC GUI displayed wrong status.
This commit fixes it by registering the redfish events for the above mentioned logical LEDs, so that whenever there is a PropertiesChanged signal generated on Asserted property, a redfish signal gets generated with the origin /Systems/system.
HMC can now capture the signal with the origin /Systems/system and queries the Properties (under the origin) which are changed.
Test:
busctl set-property xyz.openbmc_project.LED.GroupManager
/xyz/openbmc_project/led/groups/platform_system_attention_indicator
xyz.openbmc_project.Led.Group Asserted b true
busctl set-property …

Register events for SAI logical LEDs

---

include/dump_offload.hpp

This Downstream only change removes ioCon.run() call in dump offload handlers
to avoid http connection issue.
Tested by:
Tested Dump offload of various dumps and checked
http connection count in bmcweb debug traces

Fix http connections during dump offload

---

include/login_routes.hpp

The audit logging of a success login case was happening even if the login failed. This was because of the placement of the callout to do the logging. Moved the callout so that the logging only happens after a pamAuthenticateUser() call. Success or fail reported will depend on result of the authentication.
This is for 1030.30 and 1040.10.
This fixes STG Defect 532686.
Tested: 
- Login failure with non-existent user shows only failure in audit log.
- Login failure with incorrect password shows only failure in audit log.
- Login success shows only success in audit log.

Audit Log: Correct logging of success login case

---

http/utility.hpp

Check snmpTrap port
1. Allow empty port, eg: 
"snmp://9.41.166.76:".
2. Invalid ports and out of range ports are not allowed, eg:
"snmp://9.41.166.76:ab"
"snmp://9.41.166.76:-40" 
"snmp://9.41.166.76:65536".
Test:
```
1. Empty port:
curl -k -H "X-Auth-Token: $bmc_token" -X POST -D headers.txt
https://${bmc}/redfish/v1/EventService/Subscriptions
-d '{"Destination":"snmp://9.41.166.76:",
"SubscriptionType":"SNMPTrap", "Protocol":"SNMPv2c"}'
{
{
"Message": "The resource has been created successfully.",
"MessageArgs": []
,
"MessageId": "Base.1.13.0.Created",
"Resolution": "None."
}
]
}
2. Invalid port:
curl -k -H "X-Auth-Token: $bmc_token" -X POST -D headers.txt …
```

1050: Redfish: Check snmpTrap port

---

meson.build
redfish-core/lib/sensors.hpp
redfish-core/lib/storage.hpp
static/redfish/v1/schema/OemLogEntryAttachment_v1.xml
static/redfish/v1/schema/OemServiceRoot_v1.xml
test/redfish-core/lib/sensors_test.cpp

Defect is 430415
Two commits: 
1) Upstream is https://gerrit.openbmc.org/c/openbmc/bmcweb/+/59027 and merged
Hidden in this commit is the missing piece to fix the following validator error (took a bit to figure out why downstream saw this error and upstream didn't)
```
1 failRedfishUriStrict errors in /redfish/v1/Chassis/chassis/Sensors/current_vdd_p0_dcm0_rail_iout
ERROR - The Id property does not match the last segment of the URI /redfish/v1/Chassis/chassis/Sensors/current_vdd_p0_dcm0_rail_iout
```
Original commit msg:
c1d019a6056a2a0ef50e577b3139ab5a8dc49355 Sensor Optimization
Recently changed the way Ids were calculated in the sensor subsystem. Unfortunately, it wasn't clear to the author that this would effect the sensor override system, which relies on matching up a member ID with …

Fix Redfish Validators: ERROR - /redfish/v1/Systems/system/Storage/1/Drives/media0 and failRedfishUriStrict

---

Redfish.md
redfish-core/include/utils/name_utils.hpp
redfish-core/lib/assembly.hpp
redfish-core/lib/chassis.hpp
redfish-core/lib/fabric_adapters.hpp
redfish-core/lib/log_services.hpp
redfish-core/lib/processor.hpp
redfish-core/lib/storage.hpp

- Update Processor Schema to 18.0
- Add processor throttle status and cause https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/63063 Throttled: An indication of whether the processor is throttled. ThrottledCauses: An array of reasons that the processor is throttled.
- Remove processor version from messages
- Change getPrettyName to take specific service name instead of map
Ran validator and no new errors were found.
Change-Id: Ia4a58ae0f26ffc6177f418420ba45063471323da

Processor: Add processor throttle status

---

redfish-core/lib/sensors.hpp

Sensors that are not found are incorrectly reported as internal Server error and its logging is done as Error.
.
It will be changed to 404 - Not found and its logging will be WARNING.
```
redfishtool raw GET -r ${bmc} -u admin -p 0penBmc0 -S Always /redfish/v1/Chassis/chassis/Sensors/temperature_PCIE_1_Temp_invalid
redfishtool: Transport: Response Error: status_code: 500 -- Internal Server Error
redfishtool: raw: Error getting response
curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis/Sensors/temperature_PCIE_1_Temp_invalid
{
"@odata.id": "/redfish/v1/Chassis/chassis/Sensors/temperature_PCIE_1_Temp_invalid",
"error": {
{
"Message": "The request failed due to an internal service error.  The service is still …
```

1050: Fix NotFound Sensors to report as 404

---

redfish-core/lib/chassis.hpp
redfish-core/lib/systems.hpp

Pulled two upstream merged commits to support new feature to not allow chassis/host boots when BMC is not Ready:
- https://github.com/openbmc/bmcweb/commit/51dab2a7284b0f7adf2296e4165bdf8a63e73b7d
- https://github.com/openbmc/bmcweb/commit/fc903b3d9b6b61a6b215aabf4ae68408c04787ef

1050 bmc notready

---

redfish-core/lib/fan.hpp
redfish-core/lib/power_supply.hpp

The DBus call to retrieve the power supply object was using the wrong DBus service, resulting in incorrect data being fetched. This commit fixes the issue by updating the DBus interfaces array and using the correct service name. Now, the power supply Location can be retrieved accurately.
Tested:
'''
curl -k https://${bmc}/redfish/v1/Chassis/chassis15363/PowerSubsystem/PowerSupplies/powersupply1 {
"@odata.id": "/redfish/v1/Chassis/chassis15363/PowerSubsystem/PowerSupplies/powersupply1",
"@odata.type": "#PowerSupply.v1_5_0.PowerSupply",
"EfficiencyRatings": [
{
"EfficiencyPercent": 90
}
],
"Id": "powersupply1",
"Location": {
"ServiceLabel": "U78CD.001.FZHCD44-E1"
}
},
"Name": "powersupply1",
"Status": {
} …

Fix incorrect DBus service in power supply schema

---

redfish-core/lib/hypervisor_system.hpp

This commit will send back relevant redfish error back if the client tries to configure the hypervisor network with invalid IPv6 address.
Tested By:
[1] PATCH -d '{"IPv6StaticAddresses": [{"Address": \ "9.3.2.3:1A:1B:1c:1D:1E:1F", "PrefixLength": 64}]}' \ https://${bmc}/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth0
Change-Id: I262fe3bd222e8e35ac48e4433ba52a4b6d5fb649

Hypervisor config: Send relevant error on patch

---

http/http_client.hpp
redfish-core/include/event_service_manager.hpp
redfish-core/include/redfish_aggregator.hpp
redfish-core/lib/event_service.hpp
src/webserver_main.cpp

Latest event design creates multiple connection pools and multiple sockets to the same subscriber, when there is a burst of events from the BMC. This commit fixes the socket cleanup issues while sending these parallel events to the redfish event subscriber. 
Tested by:
Connected two HMCs (good subscribers) and a standalone Redfish-event-listener (as a bad subscriber). 
Performed multiple poweron and poweroff to ensure that all events are delivered to HMC, and HMC does not end up in NoConnection state.

Event socket fix

---

redfish-core/lib/oem/ibm/system_attention_indicator.hpp

We should not return an internal error if the service is not up.
Fixes https://github.com/ibm-openbmc/dev/issues/3618

Fix internal error due to system_attention_indicator while booting

---

redfish-core/lib/ethernet.hpp

At present, DHCP parameters like DNSEnabled, NTPEnabled etc. are
shared between DHCPv4 and DHCPv6 in the network configuration.
This change is to enable the possibility to have separate writable
parameters for DHCPv4 and DHCPv6 in the network configuration 
to be able to configure them independently.
The DHCP configuration was in the network manager level earlier,
it has been moved to interface level with
https://github.com/ibm-openbmc/phosphor-networkd/pull/87.
This bmcweb change is to move the redfish settings to the interface level.
Tested by:
Patch request:
curl -k -H "X-Auth-Token: $bmc_token" -X  PATCH -d 
'{"DHCPv6":{"UseNTPServers":false}}' 
https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth1
Patch Response:
{
{
"@odata.type": …

Configure DHCP4 and DHCP6 independently

---

include/dbus_utility.hpp
redfish-core/lib/power_supply.hpp

Fix Redfish validator error for missing power supplies
In the current implementation, bmcweb retrieves the power supply list
by querying the powered_by associations. However, the redfish validator
is failing due to missing power supplies that do not have the required
xyz.openbmc_project.Inventory.Item.PowerSupply D-Bus interface. This
failure occurs when querying a power supply without the specified
interface.
To address this issue, the fix ensures that missing power supplies are
not listed if they have a powered_by association but does not have the
xyz.openbmc_project.Inventory.Item.PowerSupply interface.
Defect: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=548747
upstream:
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/62522 …

1050: Fix Redfish validator failure for missing power supplies

---

redfish-core/lib/ethernet.hpp

This PR is to fix the issue caused by
https://github.com/ibm-openbmc/bmcweb/commit/
cde6f8fc1322aed9186e0b87b155d0d10ed43a63
Upstream commit:
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/63390
Tested by:
Request:
PATCH -d '{"DHCPv6":{"UseDomainName":false}}'
https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth1
Response:
{
{
"Message": "The request completed successfully.",
"MessageId": "Base.1.13.0.Success",
"Resolution": "None"
}
]
Request:
GET https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth1
{
"@odata.id": "/redfish/v1/Managers/bmc/EthernetInterfaces/eth1",
"@odata.type": "#EthernetInterface.v1_8_0.EthernetInterface",
"DHCPv4": {
"DHCPEnabled": true, …

Fix for set DHCPConfig

---

http/http_connection.hpp
include/dump_utils.hpp

An invalid `/redfish/v1/Managers/bmc/LogServices/Dump/Entries/INVALID/attachment` generates non-redfish style error messages
```
% curl -k -X GET https://${bmc}:18080/redfish/v1/Managers/bmc/LogServices/Dump/Entries/INVALID/attachment
% echo $?
```
OR
```
https://${bmc}:18080/redfish/v1/Managers/bmc/LogServices/Dump/Entries/INVALID/attachment
Output:
This <BMC> page can’t be found
No webpage was found for the web
address: https://<BMC>:18080/redfish/v1/Managers/bmc/LogServices/Dump/Entries/INVALID/attachment
HTTP ERROR 404
```
```
$https://${bmc}:18080/redfish/v1/Managers/bmc/LogServices/Dump/Entries/INVALID/attachment
<BMC> is currently unable to handle this request.
HTTP ERROR 503
```
The better output will be like
```
{
"error": {
{
"@odata.type": …
```

Handle invalid dump attachment better as redfish NotFound

---

redfish-core/lib/hypervisor_system.hpp

Currently, when a user does a patch on "IPv6StaticDefaultGateways", the gateway is displayed only in "IPv6DefaultGateway" property. This commit will also display the former in the redfish response.
Tested By:
[1] PATCH -d '{"IPv6StaticDefaultGateways":["fe08::2"]}' https://${bmc}/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth<0/1>
The redfish response will include the following:
"""
"IPv6DefaultGateway": "fe08::2",
"IPv6StaticDefaultGateways": [
{
"Address": "fe08::2"
}
],
"""
Change-Id: I10c7b243cd25b26addca10f0aad49b6c3cda8f22

Show IPv6StaticDefaultGateways in redfish response

---

redfish-core/lib/ethernet.hpp

Upstream Commit: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/64542
Defect Link: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=549291
This commit will send back relevant redfish error back if the client tries to configure the IPv6 static ip with invalid IPv6 address.
Tested By:
PATCH -D patch.txt -d '{"IPv6StaticAddresses":
[{"Address": "1A:1B:1C:1D:10.5.5.6","PrefixLength": 64}]}' https://${bmc}/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth1
Current behaviour:
response: 500 Internal Server Error
The request failed due to an internal service error
Modified behaviour:
response: 400 Bad Request
The value '1A:1B:1C:1D:10.5.5.6' for the property Address
is of a different format than the property can accept.
Change-Id: …

Static IPv6 config: Send relevant error on patch.

---

src/webserver_main.cpp

This commit registers the bmcweb to sendout the IPL progress codes to the redfish event listener
Tested by:
Verified HMC receives the events on the PostCode url /redfish/v1/Systems/system/LogServices/PostCodes/Entries
Change-Id: Ic81054422a5e3b41433f356e3c18523b8c3c58e0

Events: Send PostCode events

---

redfish-core/lib/fabric_adapters.hpp
redfish-core/lib/pcie_slots.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemFabricAdapter/index.json
static/redfish/v1/schema/OemFabricAdapter_v1.xml

To support the correct location codes for spliiter I/O slots, new associations between FabricAdapter and its PCIeSlots are created by:
- https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/63812
- https://github.com/ibm-openbmc/pldm/pull/416
Using these associations, BMCWEB will show them via OEM properties as follows.
- FabricAdapter -> PCIeSlots: Oem `Slots` will point to `PCIeSlots`
```
"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/chassis15363-logical_slot2-io_module2",
"Id": "chassis15363-logical_slot2-io_module2",
...
"Oem": {
"@odata.type": "#OemFabricAdapter.Oem",
"IBM": {
"@odata.type": "#OemFabricAdapter.IBM",
"Slots": {
"@odata.id": "/redfish/v1/Chassis/chassis15363/PCIeSlots"
}
}
},
}
```
- PCIeSlots …

1050: Implement FabricAdapter OEM Slots schema

---

include/dbus_utility.hpp
redfish-core/lib/pcie_slots.hpp

1050: Refactor and Simplify PCIeSlot handling
PCIeSlots are currently obtained in 2 stages;
- getSubTree for PCIeSlots
- getAssociationEndPoint for each slot
This can be done in a simpler way by using `getAssociatedSubTree()`
in one step;
- getAssociatedSubTree for the given chassis
Tested:
- Compare the outputs of /redfish/v1/Chassis/chassis<X>/PCIeSlots
before and after the change
- Run Redfish Validator passed

1050: Refactor and Simplify PCIeSlot handling

---

redfish-core/lib/systems.hpp

GUI displays 0 as total system memory when the total size is not exactly divisible by 1024 as the code truncates the floating point value.
This commit has the fix for it.

Incorrect value displayed for total system memory

---

include/dbus_utility.hpp
redfish-core/lib/environment_metrics.hpp
redfish-core/lib/fan.hpp
redfish-core/lib/led.hpp
redfish-core/lib/oem/ibm/lamp_test.hpp
redfish-core/lib/oem/ibm/system_attention_indicator.hpp
redfish-core/lib/pcie.hpp
redfish-core/lib/power_supply.hpp
redfish-core/lib/power_supply_metrics.hpp
redfish-core/lib/sensors.hpp

Change the interface type to std::string_view in the getDbusObject function to ensure consistency with other functions such as getSubTree and getSubTreePaths.
Upstream commit:
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/60230
Tested: Redfish Validator passed

Use std::string_view interface type in getDbusObject

---

include/ibm/locks.hpp

ibm/locks that has had clang-tidy warnings disabled for a while due to multiple safety and endianness issues.
https://github.com/openbmc/bmcweb/commit/26b3630b181d1093483e4d5ebe6aeeb91a6a2976
this commit uncomments locks code which causes warnings and fixes these warnings
Tested by: create & list locks with redfish curl and management console
Change-Id: I569e0dc5c11f259b7cca4b22722c9b4d87c68c80

Fix clang-tidy error for ibm/locks

---

include/event_dbus_monitor.hpp

This commit adds check to clean up connection handlers of system/resource dumps
if there is a unexpected Poweroff during system or resource dump offload.
This is only needed for system/resource dumps
Other dumps like Hostboot, hw dump, and sbe dumps are stored on bmc
Tested by:
Power off while system dump offloading.
Power off while other host dump offloading

Reset connection handlers of system dump on power off

---

redfish-core/lib/fabric_adapters.hpp
redfish-core/lib/pcie_slots.hpp

A previous commit 3fb45da4 incorrectly generates an Oem Link, and it will be fixed.
BEFORE:
```
$ curl -k -X GET https://${bmc}:18080/redfish/v1/Chassis/chassis15363/PCIeSlots
{
"@odata.id": "/redfish/v1/Chassis/chassis15363/PCIeSlots",
"@odata.type": "#PCIeSlots.v1_5_0.PCIeSlots",
"Id": "1",
"Name": "PCIe Slot Information",
"Slots": [
...
{
...
"Oem": {
"@odata.type": "#OemPCIeSlots.Oem",
"IBM": {
"@odata.type": "#OemPCIeSlots.v1_0_1.OemPCIeSlots.IBM",
"LinkId": 385,
"UpstreamFabricAdapter": "/redfish/v1/Systems/system/FabricAdapters/chassis15363-logical_slot2-io_module2"
}
}
},
```
FIX:
```
$ curl -k -X GET [https://${bmc}:18080/redfish/v1/Chassis/chassis15363/PCIeSlots](https://%24%7Bbmc%7D:18080/redfish/v1/Chassis/chassis15363/PCIeSlots)
{ …
```

1050: Fix PCIeSlot UpstreamFabricAdapter Oem Link (#721)

---

include/dbus_utility.hpp
redfish-core/lib/FabricAdapters.hpp
redfish-core/lib/pcie_slots.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemFabricAdapter/index.json
static/redfish/v1/schema/OemFabricAdapter_v1.xml

To support the correct location codes for spliiter I/O slots, new associations between FabricAdapter and its PCIeSlots are created by:
- https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/63812
- https://github.com/ibm-openbmc/pldm/pull/414 - (for 1030)
This PR contains 3 commits
- Add the GetSubTree, GetSubTreePaths, and getAssociationEndPoints methods
This is a cherry-pick of upstream commits and adopt it to 1030 coding style.
- Implement local GetAssociatedSubTreePaths
This 1030 openbmc does not use DBUS API that contains GetAssociatedSubTreePaths and thus it is implemented locally in 1030 using getAssociationEndPoints() & getSubTreePath().
- Implement FabricAdapter OEM Slots schema
Using these associations, BMCWEB will show them via OEM properties as follows.
- …

1030: Implement FabricAdapter OEM Slots schema

---

http/http_connection.hpp
include/audit_events.hpp
include/login_routes.hpp
redfish-core/lib/redfish_sessions.hpp
test/include/audit_events_test.cpp

Added utility functions to centralize checking whether detail data for the request being logged should be included in the log message. Moved the building of the audit message into the audit namespace so main bmcweb code doesn't have to understand the details. Changed building of message buffer to use std::string to simplify existing logic.
Tested:
- CI passes with new unit tests and audit-events enabled.
- Confirmed sampling of events have the correct detail data included.
- Confirmed user session events do not have detail data.

Audit Log: Hide details of building audit message into auditEvent()

---

redfish-core/lib/ethernet.hpp

This PR is to fix the error introduced in https://github.com/ibm-openbmc/bmcweb/commit/cde6f8fc1322aed9186e0b87b155d0d10ed43a63
Property name of DHCP parameters are updated for dhcp6
Tested by:
Patch request:
curl -k -H "X-Auth-Token: $bmc_token" -X  PATCH -d
'{"DHCPv6":{"UseNTPServers":false}}'
https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth1
Patch Response:
{
{
"Message": "The request completed successfully.",
"MessageId": "Base.1.13.0.Success",
"Resolution": "None"
}
],
Get Request:
curl -k -H "X-Auth-Token: $bmc_token" -X GET
https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth1
Get Response:
{
"@odata.id": …

Configure DHCP4 and DHCP6 parameters independently

---

http/utility.hpp

Currently while parsing destination URL, host address enclosed in [] braces for IPv6 addresses, so Resolve hostname fails for IPv6 addresses because of this invalid hostname which is enclosed in [] braces.
This commit uses encoded_host_address() method to fix this parsing hostname for IPv6 address.
Tested By: Configured redfish event subscription with IPv6 destination URI verified parsing logic of destination URI with IPv6 addresses.
Change-Id: I0e43468086ae0b961eb724de30e211d61ccda2d8

Fix events destination url parsing for IPv6

---

http/routing.hpp
include/audit_events.hpp

bmcweb currently consumes the excessive memory during firmware update. It is due to the replications of the req.body (which is the full content of firmware).
- req.body is captured by-value instead of by-reference in a lambda when the user-validation.
- audit copies the entire req.body before truncating it to the buffer.
Tested:
- Redfish validator passes
- Monitor memory consumption of bmcweb process periodically. e.g., top -b -d 0.5 | grep /usr/bin/bmcweb
- With the fix, the max memory usage should only be increased about the size of the image.

1050: Reduce memory usage during Firmware update

---

http/http_client.hpp

ssl_handshake fails while establishing connection to IPv6 destination address. as IPv6 addressses considered as invalid value for SNI hostname due to special characters.
SNI allows valid HostName which Allows characters are only {alphabetic
characters (A-Z), numeric characters (0-9), the minus sign.
Tested By: Verified redfish events 1. Subscribing Destination with IPv6 address.  2. Subscribing Destination with IPv4 address.
Change-Id: I32d30292bbc29c753f1c1815c66fcc93e8074eaa

RedfishEvents: Avoid setting SNI for IP addresses

---

redfish-core/lib/update_service.hpp

Update is failing due to unknown update dbus error type but the cause can not be determined as its value is not showing.
This change is to add the error cause to journal in addition to CRITICAL internalError.
```
Aug 02 09:00:16 bmcweb[2476]: (2023-08-02 09:00:14) [ERROR
"update_service.hpp":396] Unknown Software Image Error type = <XXX>
Aug 02 09:00:16 bmcweb[2476]: (2023-08-02 09:00:14) [CRITICAL
"error_messages.cpp":284] Internal Error ....`
```
Not tested, but successfully compiled.
Change-Id: I20833d24042bf8d2f7e2d8a8e4359e3d80af702a
upstream: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/65700

1050: Show Update error type on logs if unknown

---

http/http_client.hpp

ssl_handshake fails while establishing connection to IPv6 destination address, as IPv6 addresses considered as invalid value for SNI hostname due to special characters.
SNI allows valid HostName which allows characters are only {alphabetic characters (A-Z), numeric characters (0-9), the minus sign
This commit adds check to avoid setting SNI hostname if its an IP address
Tested By: Verified redfish events 1. Subscribing Destination with IPv6 address.  2. Subscribing Destination with IPv4 address.

Avoid setting SNI hostname for IP addresses

---

include/security_headers.hpp

Upstream is merged at https://gerrit.openbmc.org/c/openbmc/bmcweb/+/66057
This adds a missing comma in the Permissions-Policy response header value.
Tested: no; I didn't even try to compile it.
Change-Id: I4f08b54a5e5af040e10a95d913ef8b457f5bd457

Add missing comma in Permissions-Policy

---

redfish-core/lib/task.hpp

After a task is created (by dump or code update etc), task collection are showing the incorrect URI entries.
For example,
```
$ curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/TaskService/Tasks
{
"@odata.id": "/redfish/v1/TaskService/Tasks",
"@odata.type": "#TaskCollection.TaskCollection",
"Members": [
{
"@odata.id": "redfish/v1/TaskService/Tasks/0"   <-- missing "/"
},
{
"@odata.id": "redfish/v1/TaskService/Tasks/1"  <-- missing "/"
}
],
"Members@odata.count": 2,
"Name": "Task Collection"
}
```
Tested:
- Initiate dump and do the task queries
```
$ curl -k  -X POST https://${bmc}:18080/redfish/v1/Managers/bmc/LogServices/Dump/Actions/LogService.CollectDiagnosticData \
-d '{"DiagnosticDataType": "Manager"}'
```
And then
``` …
```

1050: Fix Invalid TaskCollection URI entries

---

redfish-core/lib/pcie_slots.hpp

In PCIeSlots, Oem UpstreamFabricAdapter field is a link to the other resource (FabricAdapter) and thus it is more appropriate to put it as Links | Oem | IBM | UpstreamFabricAdapter.
Current:
```
$ curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis15363/PCIeSlots
"Oem": {
"IBM": {
"UpstreamFabricAdapter": {
"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/chassis15363-logical_slot2-io_module2"
}
```
After change:
```
$ curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis15363/PCIeSlots
"Links": {
"Oem": {
"IBM": {
"UpstreamFabricAdapter": {
"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/chassis15363-logical_slot2-io_module2"
}
```
Tested:
- Redfish validator passes
- Query `curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis15363/PCIeSlots` to check the new …

1050: Move PCIeSlots UpstreamFabricAdapter field under Links

---

redfish-core/lib/update_service.hpp

During code update, if another application logs an error unrelated to code update, this triggers an error event notification and causes the code update failure.
```
$ uri=$(curl -k https://${bmc}/redfish/v1/UpdateService | jq -r ' .HttpPushUri'); echo $uri
$ curl -k -H "Content-Type: application/octet-stream" -X POST -T ${image}  https://${bmc}${uri}
{
"error": {
...
"code": "Base.1.13.0.InternalError",
"message": "The request failed due to an internal service error.  The service is still operational."
}
}
```
This commit is to filter out those non-update-related error events from concluding the code update as failure.
Tested:
1.  Redfish validator passed
2.  Error injection during Update.
- Start the code update and wait for completion of update (e.g. using journalctl -f)
```
$ …
```

1030: Ignore Non-software-related events during Update

---

redfish-core/lib/pcie_slots.hpp

The latest Redfish-Validator reports the following errors.
```
26 err.Collection(Processor.Processor) errors in /redfish/v1/Chassis/chassis/PCIeSlots
16 failInvalidArray errors in /redfish/v1/Chassis/chassis/PCIeSlots
26 failProp errors in /redfish/v1/Chassis/chassis/PCIeSlots
ERROR - Property AssociatedAssembly should not be a List
ERROR - This object's type AssociatedAssembly should be a Collection, but it's of type Resource.OemObject...
ERROR - AssociatedAssembly: Value of property is an array but is not a Collection
ERROR - AssociatedAssembly: Value of property is an array but is not a Collection
...
WARNING - Couldn't get schema for object (?), skipping OemObject IBM : 'IBM'
WARNING - Couldn't get schema for object (?), skipping OemObject IBM : 'IBM'
```
It is caused because …

1050: Fix PCIeSlots Redfish validator Error

---

redfish-core/lib/update_service.hpp

```
During code update, if another application (e.g. pldm[1]) logs an error
unrelated to code update, this triggers an error event notification
and causes the code update failure.
```
$ uri=$(curl -k https://${bmc}/redfish/v1/UpdateService | jq -r ' .HttpPushUri'); echo $uri
$ curl -k -H "Content-Type: application/octet-stream" -X POST -T ${image}  https://${bmc}${uri}
{
"error": {
...
"code": "Base.1.13.0.InternalError",
"message": "The request failed due to an internal service error.  The service is still operational."
}
}
```
This commit is to filter out those non-update-related error events from concluding
the code update as failure.
The valid update-related errors are defined in
- https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/yaml/xyz/openbmc_project/Software/Version …
```

1020: Ignore Non-software-related events during Update (#751)

---

config/bmcweb.service.in
redfish-core/lib/systems.hpp

Defect is https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=566829
2 changes:
1) System: Error log level when internalError
In line with
https://github.com/openbmc/bmcweb/blob/master/DEVELOPING.md#logging-levels. When there is an InternalError, set the logging level to Error.
Added some additional traces to get the EC. Having the EC is really helpful when debugging.
IBM has bmcweb-logging=error enabled upstream and a patch downstream.
Upstream is https://gerrit.openbmc.org/c/openbmc/bmcweb/+/66416 but had to do manually due to the new logging upstream.
2) After=srvcfg-manager.service
Seen this situation in the lab where we've got the huge
/etc/srvcfg-mgr.json file. It has a bunch of old dropbear sessions in it
that the srvcfg-manager …

After=srvcfg-manager.service and more logging

---

redfish-core/lib/certificate_service.hpp

Upstream is https://gerrit.openbmc.org/c/openbmc/bmcweb/+/66453
Defect is https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=548905
Post:
```
/redfish/v1/CertificateService/Actions/CertificateService.ReplaceCertificate
```
The "@odata.id" field in the response will appear garbled. This is caused by boost::urls::url_view outlives its original char sequence. Fix this issue.
Tested:
```
1.Get token
2.curl -k -H "X-Auth-Token: $token" -X POST https://${bmc}/redfish/v1/CertificateService/Actions/CertificateService.ReplaceCertificate -d '{"CertificateUri": {"@odata.id":"/redfish/v1/Managers/bmc/NetworkProtocol/HTTPS/Certificates/1"}, "CertificateString":"...", "CertificateType": "PEM"}'
{
"@odata.id": …
```

certificate_service: Fix garbled display caused by dangling reference

---

http/http_connection.hpp

This reverts commit 5ae6f9254161f7229216c08b591e31eaf10f69e4.
And replaces it with patchset 3 from the same review, for which was tested to work properly.  This commit was merged erroneously.
Change-Id: I201924ad27d33923d43bdf82ecb016a0f214b4dd

Replace "Fix keepalive false" with patchset 3

---

redfish-core/lib/pcie_slots.hpp

In PCIeSlots, Oem UpstreamFabricAdapter field is a link to the other resource (FabricAdapter) and thus it is more appropriate to put it as Links | Oem | IBM | UpstreamFabricAdapter.
Current:
```
$ curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis15363/PCIeSlots
"Oem": {
"IBM": {
"UpstreamFabricAdapter": {
"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/chassis15363-logical_slot2-io_module2"
}
```
After change:
```
$ curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis15363/PCIeSlots
"Links": {
"Oem": {
"IBM": {
"UpstreamFabricAdapter": {
"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/chassis15363-logical_slot2-io_module2"
}
```
Tested:
- Redfish validator passes
- Query `curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis15363/PCIeSlots` to check the new …

1030: Move PCIeSlots UpstreamFabricAdapter field under Links (#750)

---

redfish-core/lib/oem/ibm/system_attention_indicator.hpp

https://github.com/ibm-openbmc/bmcweb/pull/760/files  caused this 
https://ibm-systems-power.slack.com/archives/C04KG79NAUA/p1694553582725739?thread_ts=1694463227.287219&cid=C04KG79NAUA 
```
bmcweb.p/src_webserver_main.cpp.o -MF bmcweb.p/src_webserver_main.cpp.o.d -o bmcweb.p/src_webserver_main.cpp.o -c ../git/src/webserver_main.cpp | In file included from ../git/redfish-core/lib/systems.hpp:27,
|                  from ../git/redfish-core/include/redfish.hpp:55,
|                  from ../git/src/webserver_main.cpp:21:
| ../git/redfish-core/lib/oem/ibm/system_attention_indicator.hpp: In lambda function:
| ../git/redfish-core/lib/oem/ibm/system_attention_indicator.hpp:62:67: error: 'ec' is not captured
|    62 |                     BMCWEB_LOG_ERROR << "DBUS response error " << ec.value(); …
```

Fix compile

---

http/http_client.hpp

During RetryForever support implementation, the front queued item is removed if the queud becomes full, regardless whether it is related to RetryForever option or not.
This logic may cause the side-effect.
For example, theoretically, if the queued item is still being handled and left in the async-call schedulers, the removed object may be referenced when the scheduler pops.
This change is to preserve the queued items to be active as long as they are still connected.  If the newer requests cause the queue pool overflowed, they will be rejected (rather than the queue item is to removed).

1050: Fix the removal of unrelated queued http request

---

include/dump_offload.hpp

Wasn't able to recreate the defect 13443 , adding BMCWEB logs which will helps us debug the issue if reoccurs .
 
**For defect :**
https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=543814
 
**Observations from logs Provided in defect**
- In defect scenario , the current system dump offload request fails with message :
  `"Can't allow dump offload opertaion, one of the host dump is already offloading"`
- but there is no dump found on phyp , or HMC .
- this scenario only reoccurs previous dump fails with
   ` bmcweb[2557]: (2023-08-24 11:11:24) [ERROR "dump_offload.hpp":104] DBUS response error: generic:5`
  
 
  It seems like there was an earlier request made for system dump offload which doesn't close as expected , these logs will …

Add logs to  track connection request dump offload

---

redfish-core/lib/account_service.hpp

Seen this at 576807. The Create User is failing, returning an ec, but the user is there. Printing the error message returned will help debug.
Also seen at
526180
395562
Upstream is https://gerrit.openbmc.org/c/openbmc/bmcweb/+/66858

Add trace for user create fail

---

redfish-core/lib/pcie_slots.hpp

Redfish Validator skips the validation on PCIeSlots by this
error.
```
1 exceptionResource errors in /redfish/v1/Chassis/chassis/PCIeSlots
ERROR - This complex object LinkId should be a dictionary or None, but it's of type int...
ERROR - Unable to gather property info for URI /redfish/v1/Chassis/chassis/PCIeSlots: AttributeError("'int' object has no attribute 'get'")
```
This change will enhance the code to avoid exceptionResource errors
and continue to examine PCIeSlots.
However, it will go back to previous errors like this.
```
26 err.Collection(Processor.Processor) errors in /redfish/v1/Chassis/chassis/PCIeSlots
26 failProp errors in /redfish/v1/Chassis/chassis/PCIeSlots
...
ERROR - Processors: Linked resource reports version Processor.v1_18_0.Processor not in Schema
```
This seems …

1050: Fix PCIeSlots RedfishValidator Error

---

redfish-core/lib/systems.hpp
static/redfish/v1/JsonSchemas/OemComputerSystem/index.json
static/redfish/v1/schema/OemComputerSystem_v1.xml

Add GET EnabledPanelFunctions in /redfish/v1/Systems/system.
An example output is:
```
curl -k -X GET https://${bmc}/redfish/v1/Systems/system
{
...
"Oem": {
"IBM": {
"EnabledPanelFunctions": [
21,
22,
65
],
```
Tested:
- Check `EnabledPanelFunctions` in /redfish/v1/Systems/system output
- Redfish Validator passed

1060: 1KW - Add GET Panel EnabledFunctions

---

http/app.hpp
http/routing.hpp
redfish-core/include/query.hpp

PATCH request containing If-Match header with the value of etag causes the BMCWEB to crash. To compute the etag, a new GET request for the same URI is internally generated. Same req.session is assigned to the new request. The new req gets authenticated and when privileges are assigned in  populateUserInfo() BMCWEB will get crashed when req.session members are accessed.
For the new GET request which have the same req.session created for original PATCH request, bypass authentication and privilege assignment, since the same credentials are already validated and its a overhead to validate again.
Tested: Run Redfish Protocol validator and got passed.
Change-Id: Iaad2b1f0e982b480e9fab24005ce8b7c258882c3
Upstream is https://gerrit.openbmc.org/c/openbmc/bmcweb/+/66685

Bypass authentication for requests sent internally

---

http/http_client.hpp

-   below error trace seems to flood the BMCWEB LOGS
`"Max pool size reached. Adding data to queue. destIP: "`
- will move the log level from ERROR to Debug to solve the problem 
UPSTREAM :
the log level of the mentioned trace is already DEBUG IN upstream 
so no changes need for upstream .
https://github.com/openbmc/bmcweb/blob/master/http/http_client.hpp#L757
DEFECT :
https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=580659

BMCWEB log flooding : move ERROR trace log to DEBUG

---

include/ibm/management_console_rest.hpp

When BMC is highly loaded , D-bus requests took long time causing VMI client certificate requests to timeout.
This commit increases VMI signCSR timeout to 30 sec
This commit fixes 579382 defect

VMI CSR: increase signCSR request timeout to 30s

---

redfish-core/include/redfish.hpp
redfish-core/lib/systems.hpp
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemComputerSystem/OemComputerSystem.json
static/redfish/v1/schema/OemComputerSystem_v1.xml

Add an Oem Action to ExecutePanelFunction for Panel functions, and the action will be enabled and executable under a specific conditions (e.g. IBM i systems).
```
$ curl -k -X GET https://${bmc}/redfish/v1/Systems/system
{
...
"Actions": {
...
"Oem": {
"#OemComputerSystem.v1_0_0.ExecutePanelFunction": {
"target": "/redfish/v1/Systems/system/Actions/Oem/OemComputerSystem.ExecutePanelFunction"
}
}
},
...
}
```
Action:
```
$ curl -k -X POST https://${bmc}/redfish/v1/Systems/system/Actions/Oem/OemComputerSystem.ExecutePanelFunction \
-d '{"FuncNo": <func-no>}'
```
Tested:
- Redfish validator passes
- Success case:
```
curl -k -X POST https://${bmc}/redfish/v1/Systems/system/Actions/Oem/OemComputerSystem.ExecutePanelFunction -d '{"FuncNo": 21}'
{
{
"@odata.type": …
```

1060: Add Oem action to execute Panel function

---

http/event_service.hpp
http/http_client.hpp
include/async_resolve.hpp
redfish-core/include/event_service_manager.hpp
redfish-core/include/query.hpp
redfish-core/include/redfish_aggregator.hpp
redfish-core/lib/aggregation_service.hpp
redfish-core/lib/event_service.hpp
src/webserver_main.cpp
test/redfish-core/include/redfish_aggregator_test.cpp

This Patch pulls 1030 redfish http client code into 1050.
Tested events in following scenarios:
Host poweroff, Host poweron,
PEL events, Save area events,
BIOS changes, VMI changes,
Dump events

RedfishEvents: Pull 1030 http client code into 1050

---

include/ibm/management_console_rest.hpp

- FFDC improvement needed as discussed in defect https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=583147
Tested By :
```
curl -k -H "X-Auth-Token: $bmc_token" -X DELETE [https://${bmc}/ibm/v1/Host/ConfigFiles/<filename>
curl -k -H "X-Auth-Token: $bmc_tokens" -X POST https://${bmc}/ibm/v1/Host/ConfigFiles/Actions/IBMConfigFiles.DeleteAll
```

configFile delete logs

---

redfish-core/lib/pcie_slots.hpp
static/redfish/v1/JsonSchemas/OemPCIeSlots/OemPCIeSlots.json
static/redfish/v1/schema/OemPCIeSlots_v1.xml

Redfish Validator generates warnings related to OemPCIeSlots schema.
For example,
```
$ python3 RedfishServiceValidator.py --auth Session -i https://${bmc}:18080 \
--payload Single /redfish/v1/Chassis/chassis/PCIeSlots
WARNING - Couldn't get schema for object , skipping OemObject IBM : 'IBM'
WARNING - Couldn't get schema for object , skipping OemObject IBM : 'IBM'
...
WARNING - LinkId not defined in schema Complex IBM Resource.OemObject (check version, spelling and casing)
WARNING - AssociatedAssembly not defined in schema Complex IBM Resource.OemObject (check version, spelling and casing)
WARNING - LinkId not defined in schema Complex IBM Resource.OemObject (check version, spelling and casing)
WARNING - AssociatedAssembly not defined in schema Complex IBM Resource.OemObject (check …
```

1060: Fix OemPCIeSlots Schema Redfish Validator warnings

---

http/http_client.hpp

http_client is not handling broken connections well. Eg: Connection termination by server due to keep alive timeout.
At present client is not aware of connection termination from server. So whenever next event ready to be sent client will try send/receives data over broken connection. After failed operation the client will try to restart the connection after closing the current connection. During the process the ssl shutdown will hang when it is made over a broken connection.
Solution:
Restart the connection using fresh new socket object rather than reusing object.Thus the ssl shutdown over broken connection can be avoided.
Tested:
Developer test has been done using bmc and hmc located in different network and let the keep-alive timeout occured. The connection has been restablished on …

No Connection: Fix for http client stale connection

---

static/redfish/v1/schema/OemAssembly_v1.xml

Redfish validator produces warnings related to OemAssembly
````
$ python3 RedfishServiceValidator.py --auth Session -i https://${bmc} \
--payload Single /redfish/v1/Chassis/chassis/Assembly
...
WARNING - Couldn't get schema for object (?), skipping OemObject OpenBMC : 'Assembly'
```
Tested:
- Validator run passes without those OemAssembly warnings

1060: Fix OemAssembly schema redfish validator warnings

---

http/http_connection.hpp

Have seen with defects 581366 and 580644 hitting the max connection limit after multiple HMCs added, etc.
Tested: 
I sent 180 basic auth requests seen bmcweb memory at 
```
PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
2189  2178 root     R    17812   2%  49% ./bmcweb
...
2189  2178 root     R    20776   3%  49% ./bmcweb
...
2189  2178 root     R    21448   3%  50% ./bmcweb
...
2189  2178 root     R    29080   4%  49% ./bmcweb
...
2189  2178 root     R    30952   4%  49% ./bmcweb
...
2189  2178 root     S    30400   4%   0% ./bmcweb
```
```
(2023-10-22 06:41:55) [DEBUG "http_connection.hpp":79] 0x17a3ab0 Connection open, total 127
...
(2023-10-22 06:42:42) [DEBUG "http_connection.hpp":79] 0x19bb5c8 Connection open, total 151
...
(2023-10-22 06:43:11) [DEBUG "http_connection.hpp":89] …
```

Up the max requests in flight to 200

---

include/login_routes.hpp

Fix 563602 by removing 
```
asyncResp->res.addHeader("Clear-Site-Data",
R"("cache","cookies","storage")");
```
https://github.com/openbmc/bmcweb/commit/d8139c683a2f42c47ed913b731becc6cd681e2dd https://github.com/ibm-openbmc/bmcweb/blame/1050/include/login_routes.hpp#L255
Causes the browsers to clear the cahce, cookie, and storage for that site.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data
That is a problem for when using the GUI from the HMC proxy because the HMC is also using the cookie and storage from the same URI. The proxy works by going to a URI and the HMC proxing it forward/reverse for the eBMC GUI.
Tested this on both FireFox and Chrome

Remove cookie clear

---

include/login_routes.hpp

```
asyncResp->res.addHeader("Clear-Site-Data",
R"("cache","cookies","storage")");
https://github.com/openbmc/bmcweb/commit/d8139c683a2f42c47ed913b731becc6cd681e2dd
https://github.com/ibm-openbmc/bmcweb/blame/1050/include/login_routes.hpp#L255
Causes the browsers to clear the cahce, cookie, and storage for that
site.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data
That is a problem for when using the GUI from the HMC proxy because the
HMC is also using the cookie and storage from the same URI. The proxy
works by going to a URI and the HMC proxing it forward/reverse for the
eBMC GUI.
Signed-off-by: Gunnar Mills <gmills@us.ibm.com>```

1050: Remove cookie clear (#787)

---

meson.build
redfish-core/lib/log_services.hpp
redfish-core/lib/task.hpp
test/redfish-core/lib/log_services_test.cpp

/redfish/v1/Managers/bmc/LogServices/Journal/Entries gives the system journal entries whose ID is based on the realtime timestmap. However, the system realtime may go backward if the system time is changed either manually or via NTP.
If that happens, those entries may not found via redfish GET as `sd_journal_seek_realtime_usec()`[1] may not always work on the entries which are not sorted in time-order.
This may cause the inconsistency between the content of `/redfish/v1/Managers/bmc/LogServices/Journal/Entries/` and /redfish/v1/Managers/bmc/LogServices/Journal/Entries/<bmc_journal_id>`.
For example,
```
sudo journalctl --vacuum-time=1s
<wait for a while to clear up journal>
date -s "<backward-time>"
date -s "<forward-time>"
```
Run redfish journal entries and get each entry id from the …

1060: Use MonotonicTimeStamp for bmc log id

---

redfish-core/lib/systems.hpp
static/redfish/v1/JsonSchemas/OemComputerSystem/OemComputerSystem.json
static/redfish/v1/schema/OemComputerSystem_v1.xml

Add Redfish ChapData Redfish OEM API for GET and PATCH of ChapName and ChapSecret.
This is a part of 1KW - https://jsw.ibm.com/browse/PFEBMC-1852
Its dbus property is added via
- https://github.com/ibm-openbmc/phosphor-dbus-interfaces/pull/88
The related PLDM PRs are:
- https://github.com/ibm-openbmc/pldm/pull/464
- https://github.com/ibm-openbmc/pldm/pull/482
1.Validator passes
2. GET /redfish/v1/Systems/system
```
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Systems/system
{
...
"Oem": {
"IBM": {
"ChapData": {
"ChapName": "",
"ChapSecret": ""
},
...
}
```
3. PATCH ChapData
```
$ curl -k -H "X-Auth-Token: $token" -X PATCH \
-d '{ "Oem" : { "IBM" : { "ChapData": { "ChapName": …
```

1060: Add Redfish ChapData Refish OEM API

---

redfish-core/lib/fabric_adapters.hpp
static/redfish/v1/JsonSchemas/OemFabricAdapter/OemFabricAdapter.json
static/redfish/v1/schema/OemFabricAdapter_v1.xml

Redfish validator produces warnings related to OemFabricAdapters
```
python3 RedfishServiceValidator.py --auth Session -i https://${bmc} \
-u admin -p 0penBmc0 --payload Single \
/redfish/v1/Systems/system/FabricAdapters/chassis15363-logical_slot2-io_module2
WARNING - Couldn't get schema for object (?), skipping OemObject IBM : 'IBM'
WARNING - Slots not defined in schema Complex IBM Resource.OemObject (check version, spelling and casing)
```
Tested:
- Validator passes without having OemFabricAdapters warnings

1060: Fix OemFabricAdapters schema validator warnings

---

redfish-core/lib/oem/ibm/lamp_test.hpp
redfish-core/lib/oem/ibm/system_attention_indicator.hpp
redfish-core/lib/systems.hpp
static/redfish/v1/JsonSchemas/OemComputerSystem/OemComputerSystem.json
static/redfish/v1/schema/OemComputerSystem_v1.xml

Redfish validator produces warnings related to OemComputerSystem
````
$ python3 RedfishServiceValidator.py --auth Session -i https://${bmc} \
--payload Single /redfish/v1/Systems/system
...
WARNING - Couldn't get schema for object (?), skipping OemObject IBM : maximum recursion depth exceeded while getting the str of an object
WARNING - EnabledPanelFunctions not defined in schema Complex IBM Resource.OemObject (check version, spelling and casing)
WARNING - LampTest not defined in schema Complex IBM Resource.OemObject (check version, spelling and casing)
WARNING - PartitionSystemAttentionIndicator not defined in schema Complex IBM Resource.OemObject (check version, spelling and casing)
WARNING - PlatformSystemAttentionIndicator not defined in schema Complex IBM Resource.OemObject (check …
```

1060: Fix OemComputerSystem schema validator warnings

---

redfish-core/lib/assembly.hpp
redfish-core/lib/led.hpp
redfish-core/lib/pcie_slots.hpp

Fixes [586076](https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=586076).
Bonnell's power supplies don't have firmware controlled LED. https://github.ibm.com/openbmc/openbmc/commit/7383a11080fa1b88bd6071e454648b308663d168 removed identify LED association to them.
Redfish still shows
"LocationIndicatorActive": null,
Just have Redfish leave off the LocationIndicatorActive when no association.
This matches
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/42221/38/redfish-core/lib/led.hpp#400
Also added a resourceNotFound when setting a LocationIndicatorActive with no association like 42221.
Tested:
- Validator passes
- PowerSupply without association
- GET
```
curl -k -H "X-Auth-Token: $bmc_token" -H "Content-Type: application/octet-stream" …
```

1060: Show LocationIndicatorActive only with association

---

redfish-core/lib/pcie_slots.hpp
static/redfish/v1/JsonSchemas/OemPCIeSlots/OemPCIeSlots.json
static/redfish/v1/schema/OemPCIeSlots_v1.xml

Previously, only one fabric adapter on a PCIeSlot can be allowed. However, multiple fabric adapters can be added to a slot, and it causes an error like
```
$ curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis15873/PCIeSlots
Jan 19 18:05:10 z1707cbmc bmcweb[766]: (2024-01-19 18:05:10) [CRITICAL "error_messages.cpp":258] Internal Error /usr/src/debug/bmcweb/1.0+git-r0/redfish-core/lib/pcie_slots.hpp(321:36) `red
Jan 19 18:05:10 z1707cbmc bmcweb[766]: (2024-01-19 18:05:10) [ERROR "pcie_slots.hpp":319] DBUS response has more than FabricAdapters of 2
```
This will fix the followings
- Allow multiple fabric adapters on a PCIeSlots
- Rename schema field `UpstreamFabricAdapter` to `UpstreamFabricAdapters`.
This would need the changes in webui-vue component.
Tested:
- After the fix, …

1060: Allow multiple fabric adapters on a slot

---

redfish-core/lib/account_service.hpp

I messed up https://github.com/ibm-openbmc/bmcweb/pull/768 but had this correct upstream.
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/66858/2/redfish-core/lib/account_service.hpp
Logging e doesn't hurt anything it just isn't helpful.
See 594123 
Jan 22 17:10:51 xxx bmcweb[2310]: (2024-01-22 17:10:51) [ERROR "account_service.hpp":344] DBUS response error: 0x290cb5c

Fix error user create fail

---

redfish-core/lib/account_service.hpp

```
I messed up https://github.com/ibm-openbmc/bmcweb/pull/768 but had this
correct upstream.
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/66858/2/redfish-core/lib/account_service.hpp
Logging e doesn't hurt anything it just isn't helpful.
Signed-off-by: Gunnar Mills <gmills@us.ibm.com>```

1050: Fix error user create fail (#805)

---

config/bmcweb.service.in
redfish-core/include/error_messages.hpp
redfish-core/include/privileges.hpp
redfish-core/include/schemas.hpp
redfish-core/lib/account_service.hpp
redfish-core/lib/roles.hpp
redfish-core/src/error_messages.cpp
scripts/generate_auth_certificates.py
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemManagerAccount/OemManagerAccount.json
static/redfish/v1/schema/OemManagerAccount_v1.xml

These are all of the ACF commits required from our downstream work to get the ACF functionality working. I've modified a few of these commits as I cherry picked them in to adapt to upstream changes like 480662d4 and to update the code formatting based on new upstream changes. Nothing functionally was changed.
Tested:
- Confirmed that these plus all the ACF functions from other repos combined allow us to upload a ACF and login with the service ID in simulation
-  TODO: Flash on real hardware and run Redfish validator

1110 ibm acf

---

config/bmcweb.service.in
redfish-core/lib/account_service.hpp

1) Bump the max password length to 64 (https://github.com/ibm-openbmc/bmcweb/pull/437)
As mentioned in SW556104, Redfish accepts a password greater than 20
chars.
The 20 char limit comes from IPMI which is enabled upstream.
Downstream we have IPMI disabled be default, so up this limit to 64. (see some discussion here https://ibm-systems-power.slack.com/archives/G3WAVQYTH/p1707250701989799?thread_ts=1707239077.955159&cid=G3WAVQYTH ) 
Due to that, at this time, this is a downstream only change.
The GUI will then "Read the ManagerAccount object via GET
/redfish/v1/AccountService/Accounts/<USER> and look at the AccountTypes
property. If AccountTypes contains the "IPMI" AccountType, know that
MaxPasswordLength is effectively 20 for this user."
64 was choosen because it gives sufficient …

Gunnar 1110 Bump the max password length to 64  and Increase bmcweb automatic restart

---

redfish-core/include/redfish.hpp
redfish-core/include/registries.hpp
redfish-core/include/registries/openbmc_message_registry.hpp
redfish-core/lib/log_services.hpp

Scaled down implementation of upstream design still under review [1].
This implements the LogService routes for retrieving audit log entries
and for downloading file of all audit log entries.
Routes for discovering the service:
```
$ curl -k -H "X-Auth-Token: $token" https://${BMC_IP}/redfish/v1/Systems/system/LogServices/
{
"@odata.id": "/redfish/v1/Systems/system/LogServices",
"@odata.type": "#LogServiceCollection.LogServiceCollection",
"Description": "Collection of LogServices for this Computer System",
"Members": [
[...]
{
"@odata.id": "/redfish/v1/Systems/system/LogServices/AuditLog"
},
[...]
],
"Members@odata.count": 7,
"Name": "System Log Services Collection"
}
$ curl -k -H "X-Auth-Token: $token" https://${BMC_IP/redfish/v1/Systems/system/LogServices/AuditLog
{
"@odata.id": …
```

1060 add audit log service

---

Redfish.md
redfish-core/include/redfish.hpp
redfish-core/lib/chassis.hpp
redfish-core/lib/led.hpp
redfish-core/lib/pcie_slots.hpp

This contains 3 PRs for PCIeSlots LocationIndicatorActive handling
- Implement LocationIndicatorActive for PCIeSlots (#543)
- Fix PCIeSlot LocationIndicatorActive Patch Handling (#712)
- Refactor and Simplify PCIeSlot handling (#722)
1. Implement LocationIndicatorActive for PCIeSlots (#543) Implement LocationIndicatorActive for PCIeSlot schema, We can use locationindicatoractive to set or get the status of the location led of each pcie slot.
https://redfish.dmtf.org/schemas/v1/PCIeSlots.v1_4_1.json
We need to set the LocationIndicatorActive of all the slots in the dopatch command, even if we only want to modify one of them.(ex: see the third test result)
1. Get LocationIndicatorActive
``` …
```

Implement PCIeSlots LocationIndicatorActive

---

redfish-core/include/redfish.hpp
redfish-core/include/schemas.hpp
redfish-core/lib/update_service.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemUpdateService/OemUpdateService.json
static/redfish/v1/schema/OemUpdateService_v1.xml

This commit adds a new update command to be used by the management console to perform concurrent updates. It works like the current update command, but with added support for the OnReset apply time setting.
Tested:
```
$ curl -k -H "X-Auth-Token: $token" -H "Content-Type: application/octet-stream"  -X POST -T ${image} \
https://${bmc}/redfish/v1/UpdateService/Actions/Oem/OemUpdateService.ConcurrentUpdate
```

1110: Redfish OEM Update Command for Concurrent Update (#141) (#518)

---

http/http_connection.hpp
include/audit_events.hpp
include/login_routes.hpp
meson.build
meson_options.txt
redfish-core/lib/redfish_sessions.hpp
test/include/audit_events_test.cpp

Rebase of all bmcweb commits to support service audit log.
This introduces a new bmcweb meson option, audit-events, which is defaulted to disabled. Recipe changes in GHE openbmc/openbmc enable audit logging.
When audit-events is enabled all bmcweb PATCH, POST, PUT, and DELETE events are logged using the Linux kernel auditd subsystem. Additionally, login events coming through bmcweb are also recorded.
The body of the events is recorded as well except in the following cases:
- /redfish/v1/AccountService/Accounts PATCH/POST events - body is not recorded as it may contain clear text password
- /ibm/v1 PATCH/POST/PUT events - body is not recorded as it contains HMC config file binary data
Events are recorded in /var/log/audit/. User type dreport will gather these log files.
Tested:
- Enabled …

Audit Log: Rebase service audit log

---

Redfish.md
meson_options.txt
redfish-core/lib/fan.hpp

This pull request includes two commits:
1. Fan LocationIndicatorActive:
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/42210
2. Enable Redfish New Powersubsystem Thermalsubsystem:
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/69228

Fan LocationIndicatorActive and enable PowerSubsystem/ThermalSubsystem by default

---

redfish-core/include/event_service_manager.hpp

Fix this bug: ibm-openbmc/dev#3599
Don't send event to snmptrap subscription.

Fix bug: bmcweb SNMP errors in the Journal

---

http/app.hpp
http/http_response.hpp
http/routing.hpp
redfish-core/include/query.hpp

Fix coredump and ifmatch etag handling
redfishtool PATCH may fail etag matching because bmcweb may return the
duplicated Etags on GET, and push it back on redfishtool PATCH call.
In addition, it may also cause bmcweb to coredump depending on timing
of  `validatePrivilege` execution. It is because `req' is captured as
reference, and it may be cleared-up before async-call method completes.
(This problem can be seen more frequently by enabling debug mode).
This commit is to put only one Etag on http_response on GET, and keep
`req` during to async-method execution.
Tested:
- Create a ReadOnly user - here, called as `readonly`
- Check the duplicated Etag on GET, and check it after fix
Before:
```
$ curl -v -k -X GET https://admin:${password}@${bmc}:18080/redfish/v1/AccountService/Accounts/reado …
```

1060: Fix coredump and ifmatch etag handling

---

redfish-core/lib/roles.hpp

https://github.com/ibm-openbmc/bmcweb/commit/06b023e584291b4b93f6c856692842736a796ab2 is the original commit 
ERROR - Restricted not defined in schema Role.v1_2_2 is the error 
This is required for the new "Restricted" property.
The comment on the spreadsheet was "This should either be done upstream or added as a part of whichever downstream commit utilizes the new Restricted property in v1.3". 
I think this was just missed. 
I updated the spreadsheet 
Seeing Validator errors because of this.

redfish: bump Role to v1_3_0

---

http/http_response.hpp
include/dbus_privileges.hpp

Fix coredump and ifmatch etag handling
redfishtool PATCH may fail etag matching because bmcweb may return the
duplicated Etags on GET, and push it back on redfishtool PATCH call.
In addition, it may also cause bmcweb to coredump depending on timing
of  `validatePrivilege` execution. It is because `req' is captured as
reference, and it may be cleared-up before async-call method completes.
(This problem can be seen more frequently by enabling debug mode).
This commit is to put only one Etag on http_response on GET, and keep
`req` during to async-method execution.
Tested:
- Create a ReadOnly user - here, called as `readonly`
- Check the duplicated Etag on GET, and check it after fix
Before:
```
$ curl -v -k -X GET https://admin:${password}@${bmc}:18080/redfish/v1/AccountService/Accounts/reado …
```

1110: Fix coredump and ifmatch etag handling

---

redfish-core/lib/log_services.hpp

Full audit log file download was only allowing 10MB size file based on the raw audit log file limit. But that didn't account for the added metadata when the audit log entries are turned into JSON format. Adjusted maximum size to allow for this growth.
Tested:
- Verified on system with 10MB of audit log data that full file download succeeds and easily fits in the allowed size.
Fixes: Defect 599496

Audit Log: Correct maximum full file download check

---

http/app.hpp
http/http_response.hpp
http/routing.hpp
redfish-core/include/query.hpp

Fix coredump and ifmatch etag handling
redfishtool PATCH may fail etag matching because bmcweb may return the
duplicated Etags on GET, and push it back on redfishtool PATCH call.
In addition, it may also cause bmcweb to coredump depending on timing
of  `validatePrivilege` execution. It is because `req' is captured as
reference, and it may be cleared-up before async-call method completes.
(This problem can be seen more frequently by enabling debug mode).
This commit is to put only one Etag on http_response on GET, and keep
`req` during to async-method execution.
Tested:
- Create a ReadOnly user - here, called as `readonly`
- Check the duplicated Etag on GET, and check it after fix
Before:
```
$ curl -v -k -X GET https://admin:${password}@${bmc}:18080/redfish/v1/AccountService/Accounts/reado …
```

1050: Fix coredump and ifmatch etag handling

---

redfish-core/lib/chassis.hpp

Extend the hasIndicatorLed array and add
xyz.openbmc_project.Inventory.Item.Chassis interface.
Tested:
```
curl -k https://$bmc/redfish/v1/Chassis/chassis
{
"@odata.id": "/redfish/v1/Chassis/chassis",
"@odata.type": "#Chassis.v1_16_0.Chassis",
"Actions": {
"#Chassis.Reset": {
"@Redfish.ActionInfo": "/redfish/v1/Chassis/chassis/ResetActionInfo",
"target": "/redfish/v1/Chassis/chassis/Actions/Chassis.Reset"
}
},
"IndicatorLED": "Off",
"Model": "23",
"Name": "chassis",
...
}
```

Update indicator LED verification

---

redfish-core/include/schemas.hpp
redfish-core/include/task_messages.hpp
redfish-core/lib/task.hpp
redfish-core/lib/update_service.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemMessage/OemMessage.json
static/redfish/v1/schema/OemMessage_v1.xml

This commit adds the Message OEM that will display error log information to taskAbort. This addition will allow users to see the exact error that caused the code update failure.
Tested:
- Ensured that upon code update failure, the task message includes the populated OEM with the relevant information.
```
{
"@odata.id": "/redfish/v1/TaskService/Tasks/0",
"@odata.type": "#Task.v1_4_3.Task",
"EndTime": "2022-05-11T17:01:15+00:00",
"Id": "0",
"Messages": [
{
"@odata.type": "#Message.v1_0_0.Message",
"Message": "The task with id 0 has started.",
"0"
],
"MessageId": "TaskEvent.1.0.1.TaskStarted",
"Resolution": "None.",
"Severity": "OK"
},
{
"@odata.type": "#Message.v1_0_0.Message",
"Message": "The task with id 0 has been aborted.",
...
],
"MessageId": …
```

1110: Add OemMessage for taskAbort Error (#519)(#617)

---

redfish-core/lib/log_services.hpp

fillAuditLogEntryJson() expects a string for each MessageArgs entry. When one of the entries was a nullptr bmcweb would core dump.
Handle a nullptr by replacing it with an empty string.
Note: Root cause here is that the entry being returned by
phosphor-auditlog is not of the expected type. Added a warning
message for this case for future debugging.
Tested:
Recreated core dump. Then using the same audit log source files
confirmed the nullptr was correctly handled and no core dump happened.
Fixes: 600216
Fix for phosphor-auditlog also coded: https://github.com/ibm-openbmc/phosphor-logging/pull/51

Audit Log: Handle nullptr for message args

---

redfish-core/include/schemas.hpp
redfish-core/lib/pcie_slots.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemPCIeSlots/OemPCIeSlots.json
static/redfish/v1/schema/OemPCIeSlots_v1.xml

Added Redfish Oem property 'LinkId' to PCIeSlots under redfish/v1/Chassis. LinkId maps to dbus BusId property for the Inventory.Item.PCIeSlots interface.
Tested:
- Redfish validator passed
- Get PCIeSlots
```
$ curl -k <token> https://$bmc/redfish/v1/Chassis/chassis/PCIeSlots
...
{
"Links": {
{
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/pcie_card8"
}
],
...
"Oem": {
"IBM": {
"@odata.type": "#OemPCIeSlots.v1_0_0.PCIeSlot"
"LinkId": 0
}
},
"SlotType": "FullLength"
},
```

1110: Add Get for PCIe properties LinkId (#578)

---

redfish-core/lib/memory.hpp

Look for OperationalStatus for the memory Health.
When functional is false, health is critical.
When functional is true, health is ok.
Upstream link: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/69859
Commit Id: Ifb7e4b5e6bfadd417122fda66ef3f6590ccc43b1
Set the dimm0 OperationalStatus to false, and see the health:
```
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Systems/system/Memory/dimm0
{
"Status": {
"Health": "Critical",
}
}
```

Redfish : Look for OperationalStatus for the memory Health

---

redfish-core/include/utils/chassis_utils.hpp

IBM does not use the `xyz.openbmc_project.Inventory.Item.Board` interface for chassis objects. 
Remove that interfaces so only objects implementing `xyz.openbmc_project.Inventory.Item.Chassis` are returned for getValidChassisPath

Remove Inventory.Item.Board interface from Chassis (#604)

---

include/ibm/locks.hpp
include/ibm/management_console_rest.hpp
test/include/ibm/configfile_test.cpp

This commit adds all the usecases of /ibm/v1
1. ConfigFile multipart update
2. Lock management fixes
3. SignCSR feature for VMI interface
4. Broadcast message event

1110: Add ibm/v1 route features

---

http/http_client.hpp
http/http_response.hpp
http/websocket.hpp
redfish-core/lib/managers.hpp

A few number of bugs (which could be critical) have been fixed, and it is catching up into downstream.
They are
- https://github.com/openbmc/bmcweb/commit/a6695a8441445e441009ad64ff04c732f2538426
Clear json object
-  https://github.com/openbmc/bmcweb/commit/f3cb5df94799e94df37f9e2e6c2fcc473e0cae4a
http_client:  fix for broken connection
- https://github.com/openbmc/bmcweb/commit/a88942019fdd3d8fc366999f7c178f3e1c18b2fe
bmcweb: Add nullptr check for weakptr

1060: Catching up a few bug fixes

---

redfish-core/include/utils/fabric_util.hpp
redfish-core/lib/fabric_adapters.hpp

Build Fabric Adapters Unique Path (#606)
Defect is https://w3.rchland.ibm.com/projects/bestquest/?defect=SW552762
This commit makesFabric Adapters objects unique, before this commit
bmcweb shows Fabric Adaptersobjects with the same path even though all
the dbus objects have unique paths
```
{"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/io_module1"},
{"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/io_module1"}
```
after this change bmcweb retrieve FabricAdapterdevice endpoint information and
then, replace redfish FabricAdapter device as
"chassisN-logical_slotN-io_moduleN".
Tested: Validator passed
Motherboard FabricAdapter also gets affected.
```
curl -k -H "X-Auth-Token: $token" -X GET  https://${bmc}/redfish/v1/Systems/system/FabricAdapters/
{
...
...
"Members": [
{ …
```

1110: Build Fabric Adapters Unique Path (#606)

---

redfish-core/lib/ethernet.hpp

Pulling the fix for "disabling UseDomainName has no impact on backend function and BMC is getting configured with Domain name" from upstream along with the recent review comment incorporations in DHCP parameters
Corresponding networkd PR: https://github.com/ibm-openbmc/phosphor-networkd/pull/124
Fixes : https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=598251
Upstream : https://gerrit.openbmc.org/c/openbmc/bmcweb/+/69609/7/redfish-core/lib/ethernet.hpp
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/63390

Fix Disabling UseDomainName has no impact on backend function

---

redfish-core/lib/ethernet.hpp

```
This commit modifies to use DomainEnabled D-bus property
Currently "UseDomainName" configuration is actually not controlling
DomainName setting in the backend networkd and networkd.
Networkd app does not have DomainName D-bus property implemented
and wrong D-bus property is being used in the bmcweb.
This fix make sure bmcweb uses DomainEnabled property and controls
UseDomainName configuration.
Here is backend networkd fix for DomainEnabled property
https://gerrit.openbmc.org/c/openbmc/phosphor-networkd/+/69604
Tested by:
Enabled DHCPv4 on one of the interface
Enable/Disable UseDomainName
Check if DHCP configured domain name configuration on BMC.
Change-Id: I68b86d4107a17db921ec463f5660a58aaa1396e3
```
```
At present, DHCP …
```

1050: DHCP Conf: Fix UseDomainName configuration & Configure DHCP4 and DHCP6 parameters independently

---

include/event_dbus_monitor.hpp
src/webserver_main.cpp

This commit add redfish event d-bus monitor which monitors d-bus objects/properties and sends redfish events based on d-bus signals generated

1110: Add redfish event D-bus monitor

---

include/authentication.hpp
redfish-core/lib/account_service.hpp

This commit implements the change where, when OpPanel function 74 is active, an unauthorized agent is allowed to PATCH in the ACF.
The following command without creating a session has been to test the functionality.
```
curl  -k -X PATCH -d '{"Oem":{"IBM":{"ACF":{"ACFFile":"'${service_acf_base64}'"}}}}'
https://${BMC}/redfish/v1/AccountService/Accounts/service
```
In case function 74 is active this should allow to patch ACF crtificate otherwise gives following insufficient privilege message
```
{
"error": {
{
"Message": "There are insufficient privileges for the account or credentials associated with the current session to perform the requested operation.",
"MessageId": …
```

Unauthorized ACF certificate upload (#243)

---

include/event_dbus_monitor.hpp
src/webserver_main.cpp

This commit fixes Event D-bus monitor CI failure
Fix CI failure 
../../../../../../../../../ibm-bmcweb/src/webserver_main.cpp: In function 'int run()':
| ../../../../../../../../../ibm-bmcweb/src/webserver_main.cpp:114:25: error: 'registerStateChangeSignal' is not a member of 'crow::dbus_monitor'
|   114 |     crow::dbus_monitor::registerStateChangeSignal();
|       |                         ^~~~~~~~~~~~~~~~~~~~~~~~~

Fix Event D-bus monitor CI failure

---

redfish-core/lib/chassis.hpp
redfish-core/lib/health.hpp

```
The health status of the current CPUs and powersupplies will not
rollup to chassis. This submission implements rollup of the health
status of CPUs and powersupplies to chassis.
Tested:
1. add the xyz.openbmc_project.Inventory.Item.Global interface to the
chassis.
I create a critical association of powersupply1 using the same method
as phosphor-logging[1].
[1] https://github.com/openbmc/phosphor-logging/blob/76198a2ea2e3deb14078e0d3dd3932b657ddd9b8/extensions/openpower-pels/service_indicators.cpp#L83
Then the chassis HealthRollup will become critical:
```
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Chassis/chassis
"Status": {
"HealthRollup": "Critical",
},
```
Signed-off-by: George Liu <liuxiwei@ieisystem.com>
Change-Id: …
```

1110: Implement HealthRollup in chassis schema

---

redfish-core/include/utils/pcie_util.hpp
redfish-core/lib/pcie.hpp

This commit makes redfish adapter objects unique, before this commit bmcweb shows redfish adapter objects with the same path even though all the dbus objects have unique paths
```
{"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/adapter1"},
{"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/adapter1"}
```
after this change bmcweb retrieve PCI device endpoint information and then, replace redfish PCI device as
"chassisN_io_moduleN_slotN_adapterN".
this change also affect below path because they also has slot and chassis value in their path.
"/xyz/openbmc_project/inventory/system/chassis/motherboard/pcieslot0/pcie_card0"
Tested result:
```
curl -k -H "X-Auth-Token: $token" -X GET  https://${bmc}/redfish/v1/Systems/system
{
...
...
...
...
{"@odata.id": …
```

1110: Make PCIe Adapters Unique Path  (#590)

---

redfish-core/lib/assembly.hpp
static/redfish/v1/JsonSchemas/OemAssembly/OemAssembly.json
static/redfish/v1/schema/OemAssembly_v1.xml

OemAssembly uses the inconsistent types between schema and the code. Schema uses like `Oem/Assembly/ReadyToRemove` [1], but the code is referencing it like `Oem/OpenBMC/ReadyToRemove` in Get/Patch [2].
```
tempyArray.at(assemblyIndex)["Oem"]["OpenBMC"]["@odata.type"] =
"#OemAssembly.v1_0_0.Assembly";
...
assemblyArray.at(assemblyIndex)["Oem"]["OpenBMC"]["ReadyToRemove"] = false;
...
if (!json_util::readJson(iter2->second, asyncResp->res, "OpenBMC", openbmc))
```
So, the schema will be changed to be consistent as `OpenBMC` like
```
`"#OemAssembly.v1_0_0.OpenBMC"
```
Tested:
- Validator passes
[1] https://github.com/ibm-openbmc/bmcweb/blob/44547a092b185ee76d6a6e3f5ab2a5814c3c8a47/static/redfish/v1/schema/OemAssembly_v1.xml#L32
[2] https://github.com/ibm-openbmc/bmcweb/blob/44547a092b185ee76d …

1060: Fix Inconsistent OemAssembly Schema type

---

redfish-core/include/schemas.hpp
redfish-core/lib/assembly.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemAssembly/OemAssembly.json
static/redfish/v1/schema/OemAssembly_v1.xml

This has 2 changes (which are needed together).
* Set Functional property after battery CM  (#558)
When bmcweb is told the RTC battery is replaced after a CM operation, set the Functional property on its assembly object path back to true before restarting the adcsensor daemon.
This does two things:
1) Causes the fault LED to turn off
2) Sets the Redfish representation back to healthy so the web UI doesn't
show it has unhealthy it after the CM operation.  Of course if
adcsensor detects an error again it would go back to unhealthy.
Since this is handling the fault LED, the previous code that explicitly turned off the fault LED group was removed.
* OEM Battery Concurrent Maintenance For Everest System (#549)
The current impementation of this feature supports the redfish OEM ReadyToRemove …

1110: OEM Battery Concurrent Maintenance (#549) (#558)

---

redfish-core/include/schemas.hpp
redfish-core/lib/fabric_adapters.hpp
redfish-core/lib/pcie_slots.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemFabricAdapter/OemFabricAdapter.json
static/redfish/v1/JsonSchemas/OemPCIeSlots/OemPCIeSlots.json
static/redfish/v1/schema/OemFabricAdapter_v1.xml

To support the correct location codes for spliiter I/O slots, new associations between FabricAdapter and its PCIeSlots are created by:
- https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/63812
- https://github.com/ibm-openbmc/pldm/pull/416
Using these associations, BMCWEB will show them via OEM properties as follows.
This also allowes multiple fabric adapters on a slot.
- Allow multiple fabric adapters on a PCIeSlots via `UpstreamFabricAdapters`
- FabricAdapter -> PCIeSlots
```
"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/chassis15361-logical_slot2-io_module2",
"Id": "chassis15361-logical_slot2-io_module2",
...
"Oem": {
"IBM": {
"@odata.type": "#OemFabricAdapter.v1_0_0.IBM"
"Slots": {
"@odata.id": …
```

1110: Implement FabricAdapter Oem Slots schema (#803)

---

redfish-core/lib/pcie_slots.hpp

The associated PCIeDevice is currently searched from PCIeSlot subtree with depth of 0, but PDLM expects it is under slots, particularly for multipath splitter.
PLDM models
- One physical slot (Slot with location code Cx)
- Two Logical slots  (Slots with location code Cx-R1/Cx-R2)
- One adapter under each of the logical slot
```
| |- /xyz/openbmc_project/inventory/system/chassis15873/motherboard3/slot1
|     | | |- /xyz/openbmc_project/inventory/system/chassis15873/motherboard3/slot1/logical_slot1
|     | | | `- /xyz/openbmc_project/inventory/system/chassis15873/motherboard3/slot1/logical_slot1/adapter1
|     | | `- /xyz/openbmc_project/inventory/system/chassis15873/motherboard3/slot1/logical_slot2
|     | |   `- /xyz/openbmc_project/inventory/system/chassis15873/motherboard3/slot1/logical_ …
```

1060: Find PCIeDevice with PCIeSlot with depth of 1

---

include/dbus_utility.hpp
redfish-core/lib/fabric_adapters.hpp

This commit implement changes to populate link to PCIeDevice schema in
case the given Fabric adapter also implements PCIeDevice interface.
Test:
Validator has been executed and no new error was found.
Sample Output:
curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Systems/system/FabricAdapters/pcie_card11                        
{
"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/pcie_card11",
"Id": "pcie_card11",
"Links": {
{
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/pcie_card11"
}
],
"PCIeDevices@odata.count": 1
},
…

Link Fabric adapter to PCIeDevice schema (#583)

---

redfish-core/lib/pcie_slots.hpp

This commit adds PCIeSlot to NVMe backplane assembly link. The link is listed in Oem property for each of the configured PCIe slots as Json output `AssociatedAssembly`.
This is for downstream only.
Issue: https://github.com/ibm-openbmc/dev/issues/3535
Testing:
- Validator PASSED
- List properties for all PCIe Slots
```
$ curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots
{
"Slots": [
{
"Lanes": 0,
"Links": {
"Oem": {
"IBM": {
"@odata.type": "#OemPCIeSlots.v1_0_0.PCIeLinks",
"AssociatedAssembly": {
"@odata.id": "/redfish/v1/Chassis/chassis/Assembly#/Assemblies/24"
}
}
},
},
},
...
}
$ curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis/Assembly#/Assemblies/24
{
...
{
"@odata.id": …
```

1110: bmcweb: Add PCIeSlot to Associated assembly link (#577)

---

http/http_request.hpp
http/routing.hpp

The `req` member data of the class `Request` is defined as a simple value.
```
struct Request
{
boost::beast::http::request<boost::beast::http::string_body> req;
...
}
```
This may exhibit a few issues.
- If it is moved to a lambda of user authentication async method call, the original `completeRequest()` may observe the invalid content of it [1]. This is causing a problem for audit recording.
```
crow::connections::systemBus->async_method_call(
[req{std::move(req)}, asyncResp, &rule, params](
```
- It may be copied (e.g. captured by value) and causing the excessive memory consumption [2], in case `req` is large like the case of code update.
```
getReqAsyncResp->res.setCompleteRequestHandler(std::bind_front(
afterIfMatchRequest, std::ref(app), asyncResp, req, ifMatch));
```
To address …

1060: Use shared_ptr for request body

---

meson.build
subprojects/boost.wrap

Upstream moves to boost-1.84.
This needs to be merged with https://github.ibm.com/openbmc/openbmc/pull/4517
---
This is the same version yocto uses.
Tested: Code compiles
Change-Id: I3bf7be18ecd0e5863ab8afd57748f918837ba5a3

1110: Update boost 1.83->1.84

---

meson.build
redfish-core/include/utils/dbus_utils.hpp
redfish-core/lib/account_service.hpp
redfish-core/lib/chassis.hpp
redfish-core/lib/ethernet.hpp
redfish-core/lib/sensors.hpp
redfish-core/lib/systems.hpp
redfish-core/src/utils/dbus_utils.cpp
test/redfish-core/include/utils/dbus_utils.cpp

There are currently 78 sdbusplus::asio::setProperty calls in redfish-core. 
This commit invents a setDbusProperty method in the redfish namespace that tries to handle all DBus errors in a consistent manner. 
Upstream commit: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/69477
Tested:
```
curl  -k --user "root:0penBmc" -H "Content-Type: application/json" -X PATCH -d '{"HostName":"openbmc@#"}' https://192.168.7.2/redfish/v1/Managers/bmc/EthernetInterfaces/eth0
```
Returns the appropriate error in the response
Base.1.16.0.PropertyValueIncorrect
Change-Id: If033a1112ba516792c9386c997d090c8f9094f3a

Pull Upstream commit: Create Redfish specific setProperty call

---

static/redfish/v1/JsonSchemas/OemPCIeSlots/OemPCIeSlots.json
static/redfish/v1/schema/OemPCIeSlots_v1.xml

This fixes the incorrect/missing Oem association.
Prior to this, "AssociatedAssembly" is missing.
```
curl -k -X GET  https://${bmc}:18080/redfish/v1/Chassis/chassis/PCIeSlots
"Slots": [
{
"Lanes": 0,
"Links": {
"Oem": {
"IBM": {
"AssociatedAssembly": [
{
"@odata.id": "/redfish/v1/Chassis/chassis/Assembly#/Assemblies/24"
}
]
}
},
{
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/motherboard_disk_backplane0_nvme0_dp0_drive0"
}
]
},
```

Fix Oem AssociatedAssembly Link (#603)

---

redfish-core/lib/log_services.hpp

Currently, resource dump redfish request takes parameters like: "Resource_<vspstring>_<password>". bmcweb will:
1. extracts the parameters with '_' as the separator
2. If there are 2 strings, it means resource dump create request is with just vsp string; if there are 3 strings, it means password is present
3. Makes a call to the backend dbus app with these extracted strings
There is no check currently to handle if more than 3 strings are present (which is an invalid usecase and error should be thrown)
Fixes: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=606451
Tested By:
* Created resource dump with "Resource_<str1>_<str2>_<str3>" and verified that error is sent back to the redfish client [1] POST …

Fix resource dump create with multiple params

---

.clang-tidy
http/app.hpp
http/http_client.hpp
http/logging.hpp
http/routing.hpp
http/verb.hpp
http/websocket.hpp
include/async_resolve.hpp
include/dbus_privileges.hpp
include/dbus_utility.hpp
include/google/google_service_root.hpp
include/multipart_parser.hpp
meson.build
meson_options.txt
redfish-core/include/utils/chassis_utils.hpp
redfish-core/include/utils/query_param.hpp
redfish-core/lib/account_service.hpp
redfish-core/lib/ethernet.hpp
redfish-core/lib/hypervisor_system.hpp
redfish-core/lib/log_services.hpp
redfish-core/lib/network_protocol.hpp
redfish-core/lib/pcie.hpp
redfish-core/lib/redfish_util.hpp
redfish-core/lib/sensors.hpp
redfish-core/lib/virtual_media.hpp
src/json_html_serializer.cpp

See this fail in CI
```
In file included from ../include/ibm/utils.hpp:3,
from ../include/ibm/locks.hpp:3,
from ../test/include/ibm/lock_test.cpp:1:
../http/logging.hpp: In instantiation of 'void BMCWEB_LOG_DEBUG(const crow::FormatString&, Args&& ...) [with Args = {int}]':
../include/ibm/locks.hpp:373:21:   required from here
../http/logging.hpp:236:38: error: cannot bind non-const lvalue reference of type 'int&' to an rvalue of type 'int'
236 |         format, std::make_format_args(std::forward<Args>(args)...));
|
```
Cherry-pick:
1) https://gerrit.openbmc.org/c/openbmc/bmcweb/+/69480
2) https://gerrit.openbmc.org/c/openbmc/bmcweb/+/70033 
3) https://gerrit.openbmc.org/c/openbmc/bmcweb/+/70575 
4) https://gerrit.openbmc.org/c/openbmc/bmcweb/+/70130 
5) …

Fix failing CI 

---

redfish-core/lib/account_service.hpp

* ReadOnly users should not have ssh
This changes the Redfish create new user API (POST /redfish/v1/AccountService/Accounts/) so only Administrator users will have the HostConsole AccountType value.  This is the same as the "ssh" phosphor privilege group.
Doing so prevents new ReadOnly users from using SSH port 2200.
Note that ReadOnly user created prior to this change will have the HostConsole AccountType privilege.  A BMC admin can PATCH a user's AccountTypes property to add or remove the Hostconsole value.
Tested: Yes

1110: ReadOnly users should not have ssh (#408) (#514)

---

redfish-core/lib/log_services.hpp

```
Currently, resource dump redfish request takes parameters like:
"Resource_<vspstring>_<password>". bmcweb will:
1. extracts the parameters with '_' as the separator
2. If there are 2 strings, it means resource dump create request is
with just vsp string; if there are 3 strings, it means password is
present
3. Makes a call to the backend dbus app with these extracted strings
There is no check currently to handle if more than 3 strings are present
(which is an invalid usecase and error should be thrown)
Tested By:
* Created resource dump with "Resource_<str1>_<str2>_<str3>" and
verified that error is sent back to the redfish client
[1] POST https://${bmc}/redfish/v1/Systems/system/LogServices/Dump/Actions/LogService.CollectDiagnosticData -d '{"DiagnosticDataType":"OEM", …
```

1110: Fix resource dump create with multiple params (#889)

---

redfish-core/include/registries/composition_message_registry.hpp
redfish-core/include/registries/environmental_message_registry.hpp
redfish-core/include/registries/ethernet_fabric_message_registry.hpp
redfish-core/include/registries/fabric_message_registry.hpp
redfish-core/include/registries/heartbeat_event_message_registry.hpp
redfish-core/include/registries/job_event_message_registry.hpp
redfish-core/include/registries/license_message_registry.hpp
redfish-core/include/registries/log_service_message_registry.hpp
redfish-core/include/registries/network_device_message_registry.hpp
redfish-core/include/registries/platform_message_registry.hpp
redfish-core/include/registries/power_message_registry.hpp
redfish-core/include/registries/sensor_event_message_registry.hpp
redfish-core/include/registries/storage_device_message_registry.hpp
redfish-core/include/registries/telemetry_message_registry.hpp
redfish-core/include/registries/update_message_registry.hpp
scripts/parse_registries.py

Upsteam: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/70746
We want this for the license service https://github.com/ibm-openbmc/bmcweb/pull/873
Before Redfish put all messages in Base, but as the Messages became more specific Redfish started creating new registries. Redfish might have went a little registry happy. HeartbeatEvent just has 1 message and all these new ones registries each just have a handful of messages.
Add the remaining 15 registries:
composition, environmental, ethernetfabric, fabric, heartbeat_event, job_event, license, logservice, networkdevice, platform, power, sensor_event, storage_device, telemetry, update.
Some of these are wanted for both current development and future development but it is hard to decide which ones so just added them all. power, fabric, …

Pull in all registries

---

redfish-core/lib/account_service.hpp
redfish-core/lib/service_root.hpp
static/redfish/v1/JsonSchemas/OemManagerAccount/OemManagerAccount.json
static/redfish/v1/JsonSchemas/OemServiceRoot/OemServiceRoot.json
static/redfish/v1/schema/OemManagerAccount_v1.xml
static/redfish/v1/schema/OemServiceRoot_v1.xml

1.  Add ACFWindowActive to /redfish/v1 (#331)(#525)
This adds the Oem.IBM.ACFWindowActive boolean property to the Redfish service root at URI /redfish/v1.
```
and simulating button press via
busctl set-property "com.ibm.PanelApp" "/com/ibm/panel_app" \
"com.ibm.panel" "ACFWindowActive" b true
```
2. New property to always AllowUnauthACFUpload (#466) (#678)
* New property to always AllowUnauthACFUpload
This adds a new BMC security setting as a Redfish OEM property:
URI /redfish/v1/AccountService/Accounts/service property
Oem.IBM.ACF.AllowUnauthACFUpload can be set by the admin.  When
true, any network agent is allowed to upload an ACF file to the BMC.
The default value is false.  This capability is included in the
existing URI /redfish/v1 property Oem.IBM.ACFWindowActive.  For
example, …

1110: Add ACFWindowActive and AllowUnauthACFUpload (#525)(#678)

---

redfish-core/include/redfish.hpp
redfish-core/lib/systems.hpp
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemComputerSystem/OemComputerSystem.json
static/redfish/v1/schema/OemComputerSystem_v1.xml

1. Add GET Panel EnabledFunctions (#771)
Add GET EnabledPanelFunctions in /redfish/v1/Systems/system.
An example output is:
```
curl -k -X GET https://${bmc}/redfish/v1/Systems/system
{
...
"Oem": {
"IBM": {
"EnabledPanelFunctions": [
21,
22,
65
],
```
2. Add Oem action to execute Panel function (#773)
Add an Oem Action to ExecutePanelFunction for Panel functions,
and the action will be enabled and executable under a specific
conditions (e.g. IBM i systems).
```
$ curl -k -X GET https://${bmc}/redfish/v1/Systems/system
{
...
"Actions": {
...
"Oem": {
"#OemComputerSystem.v1_0_0.ExecutePanelFunction": { …
```

1110: Add Get And Action of Panel Functions (#771)(#773)

---

redfish-core/lib/log_services.hpp

Currently, resource dump redfish request takes parameters like: "Resource_<vspstring>_<password>". bmcweb will:
1. extracts the parameters with '_' as the separator
2. If there are 2 strings, it means resource dump create request is with just vsp string; if there are 3 strings, it means password is present
3. Makes a call to the backend dbus app with these extracted strings
There is no check currently to handle if more than 3 strings are present (which is an invalid usecase and error should be thrown)
Tested By:
* Created resource dump with "Resource_<str1>_<str2>_<str3>" and verified that error is sent back to the redfish client [1] POST https://${bmc}/redfish/v1/Systems/system/LogServices/Dump/Actions/LogService.CollectDiagnosticData -d '{"DiagnosticDataType":"OEM", …

Fix resource dump create with multiple params (#889)

---

redfish-core/include/redfish.hpp
redfish-core/lib/account_service.hpp
redfish-core/lib/assembly.hpp
redfish-core/lib/service_root.hpp
redfish-core/lib/systems.hpp
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemComputerSystem/OemComputerSystem.json
static/redfish/v1/JsonSchemas/OemManagerAccount/OemManagerAccount.json
static/redfish/v1/JsonSchemas/OemServiceRoot/OemServiceRoot.json
static/redfish/v1/schema/OemComputerSystem_v1.xml
static/redfish/v1/schema/OemManagerAccount_v1.xml
static/redfish/v1/schema/OemServiceRoot_v1.xml

Redfish: Implements Redfish Assembly Health (#553)(#628)
Look for the OperationalStatus to set the Assembly Health. 
If the OperationalStatus is false, then set the Health to "Critical"
If the OperationalStatus is true, then the Health is "OK"
```
$curl -k -X GET https://${bmc}:18080/redfish/v1/Chassis/chassis/Assembly
{
{
...
{
"@odata.id": "/redfish/v1/Chassis/chassis/Assembly#/Assemblies/2",
"Status": {
}
},
{
"@odata.id": "/redfish/v1/Chassis/chassis/Assembly#/Assemblies/3",
"Status": {
"Health": "Critical",
}
},
...
}
```

1110: Redfish: Implements Redfish Assembly Health (#553)(#628)

---

redfish-core/include/redfish.hpp
redfish-core/include/registries/privilege_registry.hpp
redfish-core/lib/account_service.hpp
redfish-core/lib/service_root.hpp
redfish-core/lib/systems.hpp
scripts/parse_registries.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemComputerSystem/OemComputerSystem.json
static/redfish/v1/JsonSchemas/OemManagerAccount/OemManagerAccount.json
static/redfish/v1/JsonSchemas/OemServiceRoot/OemServiceRoot.json
static/redfish/v1/schema/OemComputerSystem_v1.xml
static/redfish/v1/schema/OemManagerAccount_v1.xml
static/redfish/v1/schema/OemServiceRoot_v1.xml

Upstream is https://gerrit.openbmc.org/c/openbmc/bmcweb/+/70854 
Change 1 line in scripts/parse_registries.py and rerun the script.
Long term OpenBMC/bmcweb need more direction here on the Privilege Registry, but for now continue with the current direction of using the Privilege Registry and taking it from the DMTF.
There is new entries in 1.4/1.5 that are needed for future development.
Tested: It builds.
Change-Id: I4337dc44e794c58f00f7307ea0508b84f14e8c8f

Update Privilege Registry from 1.3.0 to 1.5.0

---

Redfish.md
redfish-core/include/redfish.hpp
redfish-core/lib/account_service.hpp
redfish-core/lib/service_root.hpp
redfish-core/lib/systems.hpp
redfish-core/lib/thermal_metrics.hpp
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemComputerSystem/OemComputerSystem.json
static/redfish/v1/JsonSchemas/OemManagerAccount/OemManagerAccount.json
static/redfish/v1/JsonSchemas/OemServiceRoot/OemServiceRoot.json
static/redfish/v1/schema/OemComputerSystem_v1.xml
static/redfish/v1/schema/OemManagerAccount_v1.xml
static/redfish/v1/schema/OemServiceRoot_v1.xml

TemperatureReadingsCelsius is a child of ThermalSubsystem schema[1] and it represents the thermal metrics of a chassis.
This commit implements the property Temperature (Celsius) for all relevant sensors of this device, which should contain the temperature of this subsystem (in degrees Celsius).
[1] https://redfish.dmtf.org/schemas/v1/ThermalMetrics.v1_0_1.json
"""
* GetAssociatedSubTree
- associationPath: /xyz/openbmc_project/inventory/system/chassis/all_sensors
- subtree: /xyz/openbmc_project/sensors/temperature
- depth: 0
- interfaces: xyz.openbmc_project.Sensor.Value """
Test:
1. Validator passed.
2. doGet method: """
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Chassis/chassis/ThermalSubsystem/ThermalMetrics {
"@odata.id": …

Implement TemperatureReadingsCelsius for ThermalMetrics (#571)

---

http/http_connection.hpp
http/http_response.hpp
http/http_stream.hpp
http/routing.hpp
http/routing/ruleparametertraits.hpp
http/routing/streamrule.hpp
include/dump_offload.hpp
include/event_dbus_monitor.hpp
redfish-core/include/redfish.hpp

This commit
1.Enables dynamic response support
2.Defines new bmcweb rule to support dump streaming 3.Implemented routes for system dump offload
Tested By:
System dump offload

1110 GHE: Add Dump offload support using http dynamic response

---

redfish-core/lib/oem/ibm/usb_code_update.hpp

This appears what we had in 1020-1060.
Tested: Enable USB code update. Load on rainier with no backend. 200 rc for manager resource.

Leave off USB code update if no backend

---

redfish-core/lib/account_service.hpp

As we have done in the past, ignore the error and move on if we can't get non-critical property, in this case, the ACF date.
This was bad we were clearing the response, remove that but go a step further and not throw an internalError.
This helps with 598833. Now the GUI logs in with an expired certificate.
An alternative change was https://github.com/ibm-openbmc/phosphor-certificate-manager/commit/66cbd8d4faea7dee870182dc4a16bf05c6aaeecb but the verify in ibm-acf was also deleting the expire date (code in this area)
https://github.com/ibm-openbmc/ibm-acf/blob/028f49460c04d94c29b67735a63e6f859aab8fac/subprojects/ce-login/celogin/src/CeLoginV2.cpp#L196
I decided this change is much safer 1. I understand this code and 2) this isn't acf validation or anything like that.. 
Tested:
```
"Oem": { …
```

Ignore if no ACF date

---

redfish-core/lib/network_protocol.hpp

There's currently a problem with phosphor-timesyncd, where enabling NTP doesn't immediately reflect in the system status on return[1].  To say it another way, NTP is not enabled/disabled atomically, which leads to the following problem.
// Disable NTP
PATCH /redfish/v1/Managers/bmc/NetworkProtocol
{"NTP":{"ProtocolEnabled": false}}
// Set the time manually
PATCH /redfish/v1/Managers/bmc {"DateTime": "<timestring"}
Doing this in rapid succession leads to a 500 error, which is obviously a bug.  In the prior commit, this error was changed to a PropertyValueConflict error, which is still incorrect, but at least informative of what's going on.  REST APIs are intended to have CRUD compliance.  The response should not be returned until the value has been accepted, and not doing that can lead to …

Fix NTP set race condition

---

redfish-core/lib/account_service.hpp

Like we have done in the past, ignore the error and just move on if can't get non-critical property, in this case the acf date.
This was bad we were clearing the response, remove that but go a step further and not throw an internalError.
This helps with 598833. Now the GUI logs in with an expired certificate.
Tested:
"Oem": {
"IBM": {
"@odata.type": "#OemManagerAccount.v1_0_0.IBM",
"ACF": {
"@odata.type": "#OemManagerAccount.v1_0_0.ACF",
"ACFFile": "",
"ExpirationDate": "",
"WarningLongDatedExpiration": null
}
}
},

1030: Ignore if no ACF date

---

redfish-core/lib/network_protocol.hpp

Upstream : https://gerrit.openbmc.org/c/openbmc/bmcweb/+/71026
Fixes : https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=599229
This commit re-introduces changes proposed earlier to support NetworkSuppliedServers property in bmcweb.
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/52671
It helps to differentiate between the static and DHCP assigned NTP servers. Networkd and Dbus has added support for StaticNTPServers to save the static configuration.
Tested by:
1. PATCH /redfish/v1/Managers/bmc/NetworkProtocol -d '{"NTP":{"NTPServers": [<ip>]}}' Verify that this adds the NTPs server to the NetworkProtocol
2. Enable DHCP to fetch NTP servers list from the DHCP server. Verify that they are listed when GET on NetworkProtocol as below "NTP": …

NetworkProtocol: Support NetworkSuppliedServers

---

redfish-core/lib/account_service.hpp

Like we have done in the past, ignore the error and just move on if can't get non-critical property, in this case the acf date.
This was bad we were clearing the response, remove that but go a step further and not throw an internalError.
This helps with 598833. Now the GUI logs in with an expired certificate.
Tested:
"Oem": {
"IBM": {
"@odata.type": "#OemManagerAccount.v1_0_0.IBM",
"ACF": {
"@odata.type": "#OemManagerAccount.v1_0_0.ACF",
"ACFFile": "",
"ExpirationDate": "",
"WarningLongDatedExpiration": null
}
}
},

1110: Ignore if no ACF date

---

redfish-core/include/redfish.hpp
redfish-core/lib/systems.hpp
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemComputerSystem/OemComputerSystem.json
static/redfish/v1/schema/OemComputerSystem_v1.xml

1. Add GET Panel EnabledFunctions (#771)
Add GET EnabledPanelFunctions in /redfish/v1/Systems/system.
An example output is:
```
curl -k -X GET https://${bmc}/redfish/v1/Systems/system
{
...
"Oem": {
"IBM": {
"EnabledPanelFunctions": [
21,
22,
65
],
```
Tested:
- Check `EnabledPanelFunctions` in /redfish/v1/Systems/system output
- Redfish Validator passed
2. Add Oem action to execute Panel function (#773)
Add an Oem Action to ExecutePanelFunction for Panel functions, and the action will be enabled and executable under a specific conditions (e.g. IBM i systems).
``` …
```

Add GET and Action for Panel Functions (#771)(#773)

---

redfish-core/include/redfish.hpp
redfish-core/include/schemas.hpp
redfish-core/lib/log_services.hpp
scripts/update_schemas.py
static/redfish/v1/$metadata/index.xml
static/redfish/v1/JsonSchemas/OemLogEntry/OemLogEntry.json
static/redfish/v1/JsonSchemas/OemLogEntryAttachment/OemLogEntryAttachment.json
static/redfish/v1/schema/OemLogEntryAttachment_v1.xml
static/redfish/v1/schema/OemLogEntry_v1.xml

This PR pulls in the downstream commits for the LogService modifications IBM made for PELs.  This includes:
- Adding the CELog log service that only shows event logs if their 'Hidden' property is true.
- Putting SRC words into the EventId property
- Updating the Message property to use PEL fields
- Adding the ManagementSystemAck property that is used for tracking HMC Acks
- Adding the OemPelAttachment that returns the parsed PEL in JSON.
I cherry picked the 5 commits in, and fixed up merge conflicts where necessary.  The biggest change was around the request-routes for the LogEntry attachment since there was some refactoring upstream.  I don't think we use this anymore anyway since it just returns the base64 PEL data, but I tested it does work.
There are no current plans to upstream any …

Pull PEL related EventLog changes into 1110

---

redfish-core/include/schemas.hpp
redfish-core/lib/oem/ibm/pcie_topology_refresh.hpp
redfish-core/lib/systems.hpp
static/redfish/v1/JsonSchemas/OemComputerSystem/OemComputerSystem.json
static/redfish/v1/schema/OemComputerSystem_v1.xml

This implements PATCH of PCIeTopologyRefresh & SavePCIeTopologyInfo.
This pulls in the following 1030 PRs:
- https://github.com/ibm-openbmc/bmcweb/pull/377
- https://github.com/ibm-openbmc/bmcweb/pull/382
- https://github.com/ibm-openbmc/bmcweb/pull/404
- https://github.com/ibm-openbmc/bmcweb/pull/406
This commit also adds functionality, where bmcweb creates a watchdog (using timer) where timer waits for one second and then checks if PCIe Topology gets refreshed or not. If not, then wait for one more second and repeat this process eight times, and then the watchdog expires in between if it gets refreshed then unblock the request.
Tested:
PATCH:
```
curl -k -H "Content-Type: application/json" -X PATCH https://${bmc}:18080/redfish/v1/Systems/system/ -d …
```

1110: Refresh of PCIe Topology(#593)

---

redfish-core/lib/ethernet.hpp

This commit removes the VLAN related code from the bmcweb
Tested by:
1. Verified VLAN resource is not listed while GET on the eth interfaces

Remove VLAN support from Redfish interface (#511)

---

http/http_connection.hpp
include/dump_utils.hpp

Handle invalid dump attachment better as NotFound (#706)(#735)
An invalid `/redfish/v1/Managers/bmc/LogServices/Dump/Entries/INVALID/attachment` or `/redfish/v1/Systems/system/LogServices/Dump/Entries/INVALID/attachment` generates non-redfish style error messages.
```
% curl -k -X GET https://${bmc}:18080/redfish/v1/Managers/bmc/LogServices/Dump/Entries/INVALID/attachment
% echo $?
Output:
This <BMC> page can’t be found
No webpage was found for the web address:
`https://<BMC>:18080/redfish/v1/Managers/bmc/LogServices/Dump/Entries/INVALID/attachment`
HTTP ERROR 404
```
```
$https://${bmc}:18080/redfish/v1/Managers/bmc/LogServices/Dump/Entries/INVALID/attachment
<BMC> is currently unable to handle this request.
HTTP ERROR 503
```
The better output will be like
```
{
"error": { …
```

1110: Handle invalid dump attachment better as redfish NotFound (#706)(#735)

---

redfish-core/lib/bios.hpp

Current implementation displays internal error message when BIOS attribute value is not within the lower and upper bound values. Also, the same internal error message is displayed when the length of the String type value for the attribute to be updated is not within the specified limit.
This commit displays property value out of range error message for Integer type-based attributes in case of an error, and property value incorrect for String type-based attributes.
Testing:
```
$ curl -k -H "Content-Type: application/json" -X PATCH \
-d '{"Attributes":{"hb_mfg_flags_current": "000000000000000000000000000000000"}}' \
https://${bmc}/redfish/v1/Systems/system/Bios/Settings
{
"error": {
{
"Message": "The property …
```

1110: Use Bios dbus util and Add Bios ValueOutOfRange (#430)

---

meson.build
meson_options.txt
src/webserver_main.cpp

This is a PR of 1060 [c7592df96dbffe46702778375a0b67023c7ae428](https://github.com/ibm-openbmc/bmcweb/commit/c7592df96dbffe46702778375a0b67023c7ae428).
Create a Meson build option to enable and disable event subscription at /subscribe. 
By default, this is enabled.

1110: Create Event Subscription meson build option

---

redfish-core/lib/power.hpp
redfish-core/lib/redfish_util.hpp
redfish-core/lib/sensors.hpp

bmcweb failed Project Redfish-Service-Validator
removing Item.Boars from below file will fix error we seen in vaildator
- redfish-core/lib/power.hpp
- redfish-core/lib/redfish_util.hpp
- redfish-core/lib/sensors.hpp

1110: remove Item.Board from Power Redfish_util sensors (#491)

---

redfish-core/lib/systems.hpp

If Panel backend daemon is not running, redfish API may fail
```
Apr 25 20:57:35 p10bmc bmcweb[727]: [ERROR systems.hpp:2710] Get Enabled Panel Functions D-bus error: 113
Apr 25 20:57:35 p10bmc bmcweb[727]: [CRITICAL error_messages.cpp:286] Internal Error \
/usr/src/debug/bmcweb/1.0+git/redfish-core/lib/systems.hpp(2711:40) \
`redfish::getEnabledPanelFunctions(....)
Apr 25 20:57:35 p10bmc bmcweb[727]: [ERROR http_connection.hpp:514] 0x17bc500 Error while reading: stream truncated
```
Tested:
- Stop panel daemon
- redfsih GET passes
```
curl -k -X GET https://${bmc}:18080/redfish/v1/Systems/system
```

Bypass ACFWindow and PanelFunc without Backend

---

.secrets.baseline

This creates a baseline file (and initial responses to any potential secrets found).
After this file is merged, all CI jobs after will run the detect-secrets tool against incoming commits to verify no potential secrets are being shared. If one is found, CI will fail until the .secrets.baseline is updated for the new issue.
See the following for more info:
https://github.com/IBM/detect-secrets

1110:CI-only: create detect-secrets baseline file

---

redfish-core/lib/ethernet.hpp
redfish-core/lib/hypervisor_system.hpp

This commit adds support to update hypervisor ethernet interfaces routes to use hypervisor network manager dbus app.
Tested By:
[1] GET https://${bmc}/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth0 [2] PATCH -d '{"DHCPv6": {"OperatingMode":"Disabled"}}' https://${bmc}/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth0 [3] PATCH -d '{"StatelessAddressAutoConfig": {"IPv6AutoConfigEnabled":false}}' https://${bmc}/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth0 [4] PATCH -D patch.txt -d '{"IPv4StaticAddresses": [{"Address": "<>", "SubnetMask": "<>", "Gateway": "<>"}]}' https://${bmc}/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth0 [5] PATCH -D patch.txt -d '{"IPv6StaticAddresses": [{"Address": "", PrefixLength": <>}]}' …

Use hypervisor n/w manager for hypervisor routes

---

http/websocket.hpp
include/obmc_shell.hpp
meson.build
meson_options.txt
src/webserver_main.cpp

This commit includes a web-based shell, making it possible to access secure shell servers through standard web browsers using WebSocket.
Path of WebSocket:
wss://{hostname}/bmc-console
Implementation:
So when bmcweb WebSocket gets a request for a new connection, it
creates a child process of bmcweb using the forking bmcweb process
(which begins a new process operating in a pseudoterminal).
Then on that pseudoterminal call exec("/bin/sh") which replaces the
current process image with a "/bin/sh" process image.
bmcweb is communicating with that child process using
stream_descriptor, similar to read write from a file descriptor,
with asynchronous ability. So the shell can execute all commands
like ls, cd, etc.
WebSocket here only acts as a mediator between child process, which
acts as a …

1110: Add BMC_SHELL web-base_shell (#483)(#473)

---

redfish-core/lib/roles.hpp

1110 update:
This is a straight cherry-pick of https://github.com/ibm-openbmc/bmcweb/commit/ca474f12a1d268c92901fc5c351698769c40b4f4 
It applied cleanly. 
1050 original commit msg:
* Restrict the Operator role (#319)
This changes the Operator role to Restricted=true which means no users can have the Operator role.
Tested:
1. GET /redfish/v1/AccountService/Roles/Operator and ensure it has Restricted:true.
2. POST /redfish/v1/AccountService/Accounts/new with Role:Operator Ensure it failed with message Base.1.9.0.RestrictedRole. Posting a new Administrator user is successful.
3. PATCH /redfish/v1/AccountService/Accounts/ordinary with Role:Operator.  Ensure it failed.
Changing a user to the ReadOnly role is successful.
4. PATCH the OemIBMServiceAgent role as the LocalRole within the …

Restrict the Operator role (#319) (#526)

---

include/obmc_hypervisor.hpp
meson.build
meson_options.txt
src/webserver_main.cpp

This commit adds `wss://${window.location.host}/console1` WebSocket into bmcweb. it retrieves 'PHYP debug shell' info and displays WebSocket data into WebUI using SOL (Serial over LAN) console.
console1 reads data from UNIX domain socket '@obmc-console.hypervisor' and display it in WebUI.
Privilege is set to {"OemIBMPerformService"}.
Tested:
Used webUI to open Hypervisor console. Console window was displayed.
However, we are not getting the shell because the BMC goes to
Quiecsed state and the Host does not move to 'Running' state.
There is still some level of missing support on 1110-ghe, and this
needs testing once we have all the missing support is enabled.

Added Hypervisor Serial Socket (#488)

---

redfish-core/include/query.hpp
redfish-core/include/utils/query_param.hpp
redfish-core/lib/service_root.hpp
test/redfish-core/include/utils/query_param_test.cpp
test/redfish-core/lib/service_root_test.cpp

1) Limit Query Expand to 3 
2) Only allow expand on three parts of the tree:
/redfish/v1/Chassis
/redfish/v1/Systems/system
/redfish/v1/Cables
These URIs are where the GUI's sensor page and PCIe topology page uses expand

Check expand uris & limit to 3 

---

.secrets.baseline
redfish-core/lib/systems.hpp
static/redfish/v1/JsonSchemas/OemComputerSystem/OemComputerSystem.json
static/redfish/v1/schema/OemComputerSystem_v1.xml

Add Redfish ChapData Redfish OEM API for GET and PATCH of ChapName and ChapSecret.
Its dbus property is added via
- https://github.com/ibm-openbmc/phosphor-dbus-interfaces/pull/88
The related PLDM PRs are:
- https://github.com/ibm-openbmc/pldm/pull/464
- https://github.com/ibm-openbmc/pldm/pull/482
1.Validator passes
2. GET /redfish/v1/Systems/system
```
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Systems/system
{
...
"Oem": {
"IBM": {
"ChapData": {
"ChapName": "",
"ChapSecret": ""
},
...
}
```
3. PATCH ChapData
```
$ curl -k -H "X-Auth-Token: $token" -X PATCH \
-d '{ "Oem" : { "IBM" : { "ChapData": { "ChapName": "chap-name", "ChapSecret" : "chap-secret" }}}}' \ …
```

1110: Add Redfish ChapData Refish OEM API (#794)(#798)

---

Redfish.md
redfish-core/include/utils/fan_utils.hpp
redfish-core/lib/environment_metrics.hpp
redfish-core/lib/fan.hpp

This is a redo of https://github.com/ibm-openbmc/bmcweb/pull/837, but this keeps 1060's behavior (as PR 837 is not working).
1060: Redfish: Implement EnvironmentMetrics
- Add FanSpeedsPercent
Upstream Link: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57715
Changed-Id: I4cfc0aa28d68e7e0fa947251363deb6f06e36225
- Add PowerWatts
Upstream Link: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57717
Changed-Id: Ibe84a5e7fe0d2b232f925e457a094c021ca85d36
- Add PowerLimitWantts:
Upstream Link: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/47300
Changed-Id: Iacd244e537ccab6572a0a55b7f30871774e097ff
upstream: https://gerrit.openbmc.org/q/topic:%22redfish-EnvironmentMetrics%22

1110:  Add EnvironmentMetrics - PowerWatts and FanSpeedPercent

---

redfish-core/lib/pcie_slots.hpp

This commit fixes this STG Defect 478749. This commit adds location code for pcieSlots.
Tested:
-Ran Redfish service validator,
No new error and can see the Location code for pcieSlots
-Verified on Rainier100 system, Location code shows up for PCIedevices.
curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots {
"Slots": [
{
{
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/
motherboard_disk_backplane0_nvme2_dp0_drive2"
}
]
},
"Location": {
"ServiceLabel": "U78DA.ND0.       -P1-C2"
}
},
...
},
Change-Id: I2bef85d9dbd95d5f0b923f5453c8cc72381ce546

Bmcweb: Add PcieSlots Location Code(#650)

---

redfish-core/lib/processor.hpp

This is a rebase of a single commit from https://github.com/ibm-openbmc/bmcweb/pull/542:
https://github.com/ibm-openbmc/bmcweb/commit/a7a3704428676da0886f4b1bef30cbb78d8c41dd
Also changes `afterSetProcessorObject()` to call the new function `isProcObjectMatched()`. This is a rebase of the equivalent call made with https://github.com/ibm-openbmc/bmcweb/commit/4dbe5ec81f8e11ba5f5e8e942715d04842f40814
Cleanup changes were made to follow current upstream coding style.
redfish-core: Processor: Workaround to handle DCM
- The BMC inventory modeled processor object as "dcmN/cpuN" to support DCM (Dual-Chip Module) package (that contains two processors) based on system model.
- The Redfish does not support "Chip Module" (DCM or MCM (Multi-Chip Module)) but, due to inventory changes ("dcmN/cpuN") …

1110: redfish-core: Processor: Workaround to handle DCM

---

redfish-core/lib/pcie_slots.hpp

1110 update: 
Cherry-pick of 1b105f0357
Upstream is https://gerrit.openbmc.org/c/openbmc/bmcweb/+/62219 
1050 PR:
https://github.com/ibm-openbmc/bmcweb/pull/650 added PcieSlots Location Code but it throws an internal error when there is no location code interface. Location code isn't required and logical slots don't have a location code so just leave off location code if the interface isn't there. This is what we had for 1030.
Archana was seeing "Base.1.13.0.InternalError", at https://${bmc}/redfish/v1/Chassis/chassis15364/PCIeSlots
Tested: Loaded onto the system and didn't see the error anymore.

Don't internal error if no slot location code (#683)

---

include/sessions.hpp
redfish-core/lib/account_service.hpp

When a user's password is changed, existing Redfish sessions for that user, created with the old password, continue to work.
As per OWASP session management, "The session ID must be renewed or regenerated by the web application after any privilege level change within the associated user session... Common scenarios to consider include; password changes, permission changes, or switching from a regular user role to an administrator role within the web application." [1] https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html
This commit removes existing user sessions when the user's password is changed. This commit leaves the current session in place though a new removeSessionsByUsernameExceptSession().
This commit doesn't completely get us fully to what owasp says …

Remove sessions on user password update

---

.secrets.baseline
redfish-core/lib/log_services.hpp

requestRoutesDBusCELogEntryCollection() handling hits a core due to a missing nullptr of variable `hidden` in log_services.hpp.
This is introduced by a mistake during https://github.com/ibm-openbmc/bmcweb/commit/a325bc8c07cac21c02df624298b4f3b94864e42f
```
Core was generated by `/usr/bin/bmcweb'.
Program terminated with signal SIGSEGV, Segmentation fault.
...
std::shared_ptr<bmcweb::AsyncResp> const&, std::__cxx11::basic_string<char, std::char_traits<char>,
std::allocator<char> > const&)#1}::operator()(crow::Request const&, std::shared_ptr<bmcweb::AsyncResp> const&, std::__cxx11::basic_string<char,
...
std::shared_ptr<bmcweb::AsyncResp> const&, std::__cxx11::basic_string<char, std::char_traits<char>,
std::allocator<char> > const&)#1}::operator()(crow::Request const&, …
```

1110: Check nullptr before using var at log-services

---

redfish-core/lib/processor.hpp

PR https://github.com/ibm-openbmc/bmcweb/pull/918 introduced a problem with getting the PrettyName for Processors.
getPrettyName() expects only a single object in the MapperServiceMap. Processors have two: org.open_power.OCC.Control and xyz.openbmc_project.Inventory.Manager.
Without fix, pretty name is not used and an error is returned:
```
$ curl -k -H "X-Auth-Token: $token" https://${bmc}/redfish/v1/Systems/system/Processors/dcm0-cpu0
{
"@odata.id": "/redfish/v1/Systems/system/Processors/dcm0-cpu0",
"@odata.type": "#Processor.v1_18_0.Processor",
"Id": "dcm0-cpu0",
"Location": {
"ServiceLabel": "U78DA.ND0.WZS004A-P0-C15"
}
},
"MaxSpeedMHz": 0,
"Model": "5C67",
"Name": "Processor",
"PartNumber": "03JM290", …
```

1110: Fix get Processor data handling of PrettyName

---

redfish-core/lib/chassis.hpp

https://gerrit.openbmc.org/c/openbmc/bmcweb/+/60914 implements topology links for chassis using `getAssociationEndPoints()` for `containing/contained_by` associations.
However, the same associations can also be used for the other cases which may also be used for the other types.
For example, https://gerrit.openbmc.org/c/openbmc/openbmc/+/70372 adds the associations between chassis and the other resources.
In that case, Chassis Links gives the incorrect result including the non-chassis resources in `Contains` collection..
```
$ curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis
{
"@odata.id": "/redfish/v1/Chassis/chassis",
"@odata.type": "#Chassis.v1_22_0.Chassis",
"Links": {
"Contains": [
...
{
"@odata.id": "/redfish/v1/Chassis/connector4"
},
...
```
This causes Redfish Service …

1110: Revert "Add topology links for Chassis"

---

redfish-core/include/utils/hw_isolation.hpp
redfish-core/lib/memory.hpp
redfish-core/lib/processor.hpp

The following commits are cherry picked
[redfish-core: Core: Enabled the isolation (aka guard) feature](https://github.com/ibm-openbmc/bmcweb/pull/542/commits/1780452abef6b9e167ffac8c27d6cbdd0be7934f)
[redfish-core: Memory: Enabled the isolation (aka guard) feature](https://github.com/ibm-openbmc/bmcweb/pull/542/commits/70c213769052d24244ce58e9836f6f45cedf474c)

Core enabled hw iso onwards

---

include/dump_offload.hpp
include/dump_utils.hpp
redfish-core/lib/log_services.hpp

This PR refactors the host dumps code to consume the latest interfaces that are changed in PDC.
Tested:
GET, DELETE, Create and ClearLog actions on both System and BMC dumps
BMC Dump offload

Refactor Dump LogService as per latest dump-manager D-bus re-design

---

redfish-core/lib/processor.hpp
redfish-core/src/redfish.cpp

Rebase of two commits for SubProcessor for processor core. Includes changes to align with current upstream code style and some semantic changes.
(Note: https://github.com/ibm-openbmc/bmcweb/pull/986 pulled in this in-progress PR and merged first. So it added the new functions needed for SubProcessor support but not the routes.)
1) First commit (https://github.com/ibm-openbmc/bmcweb/commit/1afe3f87f66ecaa87f8f431d92869aac605f8866):
Implement SubProcessors for processor core
- Add the SubProcessors class to bmcweb to support processor cores.
- The SubProcessors collection is a collection under the processor schema. An association, <insert association name>, is used to link the core to the processor.
Tested: Validator passes
```
curl -k -H "X-Auth-Token: $token" …
```

1110: Implement SubProcessors for processor core

---

redfish-core/lib/processor.hpp

In the current state, the logic is bmcweb for displaying cores is: It checks the Present property on core dbus object to update the [Status][State] as Enabled/Absent.
In addition to Present property, we should also use the Available property , if the Available is false, then set the [Status][State] should be set as "UnavailableOffline".
Refer: ibm-openbmc/dev#3481

Consume availability interface for cores (#254)

---

redfish-core/include/utils/name_utils.hpp

The method getPrettyName() may be called more than one time.
This will generate journal logging messages for the required Service name
if there are unexpected service names.

Logging invalid service name for debug (#291) (#626)

---

redfish-core/lib/processor.hpp

Add missing path to SubProcessors from Processor
Fixes Defect 620172. Already fixed in 1110.
Since SubProcessors are supported there should be a link from the Processor to the Redfish URI for its SubProcessors. It is missing.
Without fix:
```
curl -k -H "X-Auth-Token: $token" https://${bmc}/redfish/v1/Systems/system/Processors/dcm0-cpu0
{
"@odata.id": "/redfish/v1/Systems/system/Processors/dcm0-cpu0",
"@odata.type": "#Processor.v1_18_0.Processor",
"Id": "dcm0-cpu0",
"Location": {
"ServiceLabel": "U78DA.ND0.1234567-P0-C15"
}
},
"MaxSpeedMHz": 0,
"Model": "AB42",
"Name": "System processor module 0",
"PartNumber": "2345678",
"ProcessorId": {
"Step": "0xFFFF"
},
"ProcessorType": "CPU",
"SerialNumber": "YLAB42010000", …
```

Add missing path to SubProcessors from Processor

---

redfish-core/lib/pcie.hpp

phophor-dbus-interfaces changes the default of lanesInUse to MAXINT by https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/53650
Thus bmcweb also changes the logic to hide the field if it is MAXINT.
Change-Id: Ib229112374eb5a65e0a8ac97669c09c498ac26c7
upstream: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/70008

1110: Fix handling of lanesInUse default value

---

redfish-core/lib/pcie.hpp

Not all PCIeSlots may have LinkStatus DBus properties. Currently it fails on PCIeDevice GET object like
```
curl -k -X GET https://${bmc}/redfish/v1/Systems/system/PCIeDevices/chassis_motherboard_pcieslot0_pcie_card0
{
...
"code": "Base.1.16.0.InternalError",
"message": "The request failed due to an internal service error.  The service is still operational."
}
```
Its journal record may be:
```
[ERROR dbus_utils.hpp:20] DBUS property error in property: LinkStatus, reason: 0
[CRITICAL error_messages.cpp:286] Internal Error /usr/src/debug/bmcweb/1.0+git/redfish-core/lib/pcie.hpp(259:32)
`void redfish::addPCIeSlotProperties(crow::Response&, const boost::system::error_code&, const dbus::utility::DBusPropertiesMap&)`:
```
This is to handle the case when the dbus field is not presented, like …

1110: Handle Missing PCIeSlot LinkStatus on PCIeDevice

---

redfish-core/lib/assembly.hpp

It currently produces Assembly output with the incorrect ReadyToRemove field where it should not be included.
```
curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis/Assembly
{
...
"Assemblies": [
{
"@odata.id": "/redfish/v1/Chassis/chassis/Assembly#/Assemblies/0",
...
"Name": "motherboard",
"Oem": {
"OpenBMC": {
"ReadyToRemove": false     <== This should not be included
}
},
...
},
```
This will also cause the Redfish Service Validator error because it does not contain the @odata.type.
Tested:
- Verify `curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis/Assembly`
- Redfish Service Validator passes
```
python3 RedfishServiceValidator.py --auth Session -i https://${bmc} -u $USER -p $PASS \
--payload Single …
```

1110: Fix Assembly ReadyToRemove GET

---

redfish-core/lib/fabric_adapters.hpp

Link from FabricAdapter to PCIeDevice is incorrectly set without using the buildUniquePath.
```
{
"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/motherboard-pcieslot11-pcie_card11",
"Id": "motherboard-pcieslot11-pcie_card11",
{
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/pcie_card11"
}
],
PCIeDevices@odata.count: 1
},
```
This also causes Redfish Service Validator failure.
This will be set like
```
"Links": {
{
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/chassis_motherboard-pcieslot11-pcie_card11"
}
```
Tested:
- Check the output of `/redfish/v1/Systems/system/FabricAdapters/motherboard-pcieslot11-pcie_card11`
- Redfish Service Validator passes

1110: Fix Link FabricAdapter to PCIeDevice

---

include/ssl_key_handler.hpp

This is downstream only commit to disable peer certificate verification in redfish events path.
Currently http_client code verifies ssl certificate provided by HMC during SSL handshake
certificate validation fails with unknown CA, since BMC can't trust HMC provided certificates
HMC-BMC certificate flows needs to be enabled to pass this certificate validations.
This commit disable peer certificate verification during redfish events ssl handshake
Tested by:
Verified redfish events on HMC

RedfishEvents: Disable peer certificate verification

---

redfish-core/include/utils/error_log_utils.hpp
redfish-core/include/utils/hw_isolation.hpp
redfish-core/lib/log_services.hpp
redfish-core/lib/processor.hpp

[HW-Isolation: Fix, Use GetAncestors to get the parents id (](https://github.com/ibm-openbmc/bmcweb/pull/542/commits/5307884fdf10eeef4336e7fe9159be6eeae5c0c6)
[HW-Isolation: Fix, Don't throw internal error if failed to get error …](https://github.com/ibm-openbmc/bmcweb/pull/542/commits/1b35f765516e01f8c5ad9038031caf6e4f6cc3e3)
[Core: Fix, Patch a core into the respective parent processor (](https://github.com/ibm-openbmc/bmcweb/pull/542/commits/24bba109f81d1ed31325219f1e780f9aa9e7991c)

Get ancestor

---

redfish-core/lib/systems.hpp

There are a few Redfish Service Validator errors like
```
python3 RedfishServiceValidator.py --auth Session -i https://${bmc} -u $USER -p $PASS \
--payload Single  /redfish/v1/Systems/system
...
1 failInvalidArray errors in /redfish/v1/Systems/system
1 fails errors in /redfish/v1/Systems/system
```
Its details are:
```
ERROR - Property EnabledPanelFunctions should not be a List
ERROR - This object's type EnabledPanelFunctions should be a Collection, but it's of type Resource.OemObject...
ERROR - EnabledPanelFunctions: Value of property is an array but is not a Collection
```
```
{
"Oem": {
"IBM": {
"@odata.type": "#OemComputerSystem.IBM", <---
"EnabledPanelFunctions": [],
"LampTest": false, …
```

1110: Fix Redfish Validator Errors on system

---

redfish-core/include/utils/hw_isolation.hpp
redfish-core/lib/log_services.hpp

Here is the list of the original commits that are cherry-picked
[HW-Isolation: Return ResourceCannotBeDeleted error](https://github.com/ibm-openbmc/bmcweb/pull/542/commits/6c60bc3f7e92c05c3f28052a6292892181904ae4)
[HW-Isolation: Fix, Don't handle the Unavailable D-Bus error](https://github.com/ibm-openbmc/bmcweb/pull/542/commits/3e3fdb5f8c0bc96d82a381bd91678c01e5e22747)
[LogService: HW-Isolation: Return an appropriate error](https://github.com/ibm-openbmc/bmcweb/pull/542/commits/a858ac1ecb46d94a4bbc66e14bbea24bdfc781d6)

Resource cannot be deleted others

---

redfish-core/lib/bios.hpp

This change updates the BaseBIOSTable in bios.hpp according to the modifications made in the schema upstream.
Fixes the defect https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=625977
schema : https://github.com/ibm-openbmc/phosphor-dbus-interfaces/blob/1110/yaml/xyz/openbmc_project/BIOSConfig/Manager.interface.yaml#L64
Upstream: NA, Downstream only code.
Tested by:
Redfish response before the fix:
get /redfish/v1/Systems/system/Bios
{
"@Redfish.Settings": {
"@odata.type": "#Settings.v1_3_0.Settings",
"SettingsObject": {
"@odata.id": "/redfish/v1/Systems/system/Bios/Settings"
}
},
"@odata.id": "/redfish/v1/Systems/system/Bios",
"@odata.type": "#Bios.v1_1_0.Bios",
"Actions": {
"#Bios.ResetBios": {
"target": …

Fix the BaseBIOSTable according to upstream schema

---

include/authentication.hpp

This reverts commit 093eebecf9c395aff3543b8252e2794e51530e59 to fix defect 629044.
Defect 629044 reported an endless redirect loop of `/?next=/`
This was found using git bisect. 
Tested: A 2nd test with and without this commit showed, the endless redirect without this commit but fixed by this commit.

Revert "Fix regression in metadata"

---

redfish-core/lib/bios.hpp
redfish-core/lib/message_registries.hpp
redfish-core/src/redfish.cpp

Redfish Service Validator is failing like this.
```
1 failGet errors in /redfish/v1/Registries/BiosAttributeRegistry/BiosAttributeRegistry
1 fails errors in /redfish/v1/Registries/BiosAttributeRegistry/BiosAttributeRegistry
ERROR - URI did not return resource /redfish/v1/Registries/BiosAttributeRegistry/BiosAttributeRegistry
```
It can also be verified by doing this.
```
curl -k -X GET https://${bmc}/redfish/v1/Registries/BiosAttributeRegistry/BiosAttributeRegistry
{
"error": {
"code": "Base.1.16.0.ResourceNotFound",
"message": "The requested resource of type MessageRegistryFile named 'BiosAttributeRegistry' was not found."
```
It is because bmcweb does not handle the overlapping routes with
- `/redfish/v1/Registries/<str>/<str>`
- …

1110: Fix Handling of BiosAttributeRegistry

---

redfish-core/lib/license_service.hpp
redfish-core/lib/log_services.hpp
redfish-core/schema/oem/openbmc/csdl/OemLogEntryAttachment_v1.xml
redfish-core/schema/oem/openbmc/json-schema/OemLogEntryAttachment.json

This fixes 2 warnings
1) Fix Incorrect URI id on LicenseService
Redfish Service validator shows an warning on LicenseService.
```
WARNING - /redfish/v1/LicenseService @odata.id: Expected @odata.id to match URI link /redfish/v1/LicenseService/
```
```
curl -k -X GET https://${bmc}/redfish/v1/LicenseService
{
"@odata.id": "/redfish/v1/LicenseService/",
}
```
2) Fix Redfish Validator Warnings on Oem LogServices
```
- On /redfish/v1/Systems/system/LogServices/EventLog/Entries
WARNING - Couldn't get schema for object (?), skipping OemObject OpenBMC : 'LogEntry'
- On /redfish/v1/Systems/system/LogServices/AuditLog/Entries
Couldn't get schema for object (?), skipping OemObject IBM : 'IBM'
WARNING - Couldn't get schema for object (?), skipping OemObject IBM : 'LogEntry'
```
``` …
```

1110: Fix Validator Warning on Oem Schemas

---

redfish-core/lib/bios.hpp

Currently patch operation on BIOS attributes fails, This PR fixes this defect  631792
Tested By:
Verified Patch operation on bios attributes

Fix BIOS attributes Patch operation

---

http/http_client.hpp

This PR pulls the following commits that fixes HMC no connection issue (which was already merged to 1060 branch but is missed to be pulled down to 1050):
No Connection: Fix for http client stale connection ([link](https://github.com/ibm-openbmc/bmcweb/commit/2523e033cc84c2a0d9405a64e682969a0e8a8664))
http_client: fix for broken connection ([link](https://github.com/ibm-openbmc/bmcweb/commit/6363ab5631e90f518be748adb1fa7d30e7325959))
Sync http client socket handling to upstream ([link](https://github.com/ibm-openbmc/bmcweb/commit/44547a092b185ee76d6a6e3f5ab2a5814c3c8a47))
These commits are for fixing the broken HTTP connection issue (Eg: Connection termination by server due to keep alive timeout).
So whenever there is a connection termination, and when client tries to send/receive data …

No connection issue fix

---

redfish-core/include/utils/sw_utils.hpp
redfish-core/lib/update_service.hpp

A Minimum Version interface was added.[1] This is the minimum software version that a component must have to operate. Like other interfaces it is optional. MinimumVersion maps to Redfish's LowestSupportedVersion.[2]
"LowestSupportedVersion": {
"description": "The lowest supported version of this software.",
"longDescription": "This property shall represent the lowest
supported version of this software.  This string is formatted using the same format used for the `Version` property.",
"readonly": true,
"type": [
"string",
"null"
],
"versionAdded": "v1_1_0"
phosphor-bmc-code-mgmt has support for minimum version.[3]
phosphor-bmc-code-mgmt logs a Software Incompatible[4] error if this minimum version is not met. Mapping this error to a Redfish error is not done here but could be added later. …

1110: Software: Add LowestSupportedVersion

---

redfish-core/include/utils/sw_utils.hpp
redfish-core/lib/update_service.hpp

A Minimum Version interface was added.[1] This is the minimum software version that a component must have to operate. Like other interfaces it is optional. MinimumVersion maps to Redfish's LowestSupportedVersion.[2]
"LowestSupportedVersion": {
"description": "The lowest supported version of this software.",
"longDescription": "This property shall represent the lowest
supported version of this software.  This string is formatted using the same format used for the `Version` property.",
"readonly": true,
"type": [
"string",
"null"
],
"versionAdded": "v1_1_0"
phosphor-bmc-code-mgmt has support for minimum version.[3]
phosphor-bmc-code-mgmt logs a Software Incompatible[4] error if this minimum version is not met. Mapping this error to a Redfish error is not done here but could be added later. …

1060: Software: Add LowestSupportedVersion

---

http/http_client.hpp
include/ssl_key_handler.hpp

This is downstream only patch to enable TLS1.2 support
Currently TLS1.3 is hardcoded in http client which restricts redfish events path to work with TLS1.3
and fails with TLS1.2
This commit enables TLS1.2 along with TLS1.3 in http_client and make sure redfish events work with HMC for both TLS1.2 and TLS1.3
Tested by:
Verified redfish events on HMC with TLS1.2 and TLS1.3

RedfishEvents GHE: Enable TLS1.2 in http client

---

redfish-core/include/utils/sw_utils.hpp
redfish-core/lib/update_service.hpp

```
A Minimum Version interface was added.[1] This is the minimum software
version that a component must have to operate. Like other interfaces it
is optional. MinimumVersion maps to Redfish's LowestSupportedVersion.[2]
"LowestSupportedVersion": {
"description": "The lowest supported version of this software.",
"longDescription": "This property shall represent the lowest
supported version of this software.  This string is formatted using the
same format used for the `Version` property.",
"readonly": true,
"type": [
"string",
"null"
],
"versionAdded": "v1_1_0"
phosphor-bmc-code-mgmt has support for minimum version.[3]
phosphor-bmc-code-mgmt logs a Software Incompatible[4] error if this
minimum version is not met. Mapping this error to a Redfish error is
not done here but could be added …
```

1050: Software: Add LowestSupportedVersion (#1012)

---

redfish-core/lib/cable.hpp

To make Redfish Cable and Port consistent, this is to limit Cable ports to find only Connector.Port interfaces for
- UpstreamPorts
- DownStreamPorts
For example,
```
curl -k -X GET https://service:0penBmc0@gfwa816.aus.stglabs.ibm.com:2443/redfish/v1/Cables/dp0_cable0
{
"Links": {
"UpstreamPorts": [
{
"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/motherboard-pcieslot10-pcie_card10/Ports/c10_connector0"
],
}
],
```
However,  if `c10_connector0` is not an interface of `Connector.Port`, this UpstreamPorts may potentially point to the non-existent ports.
Tested:
- GET cable and check Upstream/DownstreamPorts like `curl -k -X GET https://${bmc}/redfish/v1/Cables/dp0_cable0`
- Redfish Service Validator for Cables

1110: Use Connector.Port interface for Cable Ports

---

include/ibm/management_console_rest.hpp

This commit fixes VMI certificate exchange SignCSR request
This fixes D-bus match which waits for CSR object status set by pldm
Tested by:
Ran SignCSR rest commands, it works.

Fix VMI certificate exchange

---

redfish-core/lib/log_services.hpp
redfish-core/lib/task.hpp

This change is required for resource dump creation usecase where a task is started on dump creation request. The task starts with "Running" state and moves to "Completed/Cancelled". For resource dump creation, there is validation of input parameters and this has to be notified back to the user. So the tasks are created with "Starting" state and moved to "Running" only when the inputs are validated, else the state changes to "Cancelled/Completed". For all other dumps, the task state change will be like: "Starting" -> "Running" -> "Completed/Cancelled".
Tested By:
[1] POST https://${bmc}/redfish/v1/Systems/system/LogServices/Dump/Actions/LogService.CollectDiagnosticData -d '{"DiagnosticDataType":"OEM", "OEMDiagnosticDataType":"Resource_vsp_globalfr_0penBmc0"}'

Task: Initialise tasks with "Starting" State

---

redfish-core/lib/environment_metrics.hpp

Starting in 1050, we picked up this Sensor Optimization[1] that moved the sensors to sensortype_sensorname. E.g.
/redfish/v1/Chassis/my_chassis/Sensors/temperature_my_sensor. This was wrong in Environment Metrics so fix this. Found while looking at a different defect.
[1]: https://github.com/openbmc/bmcweb/commit/c1d019a6056a2a0ef50e577b3139ab5a8dc49355
Commented upstream at https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57717

1110: Fix total power pointer

---

redfish-core/lib/environment_metrics.hpp

Starting in 1050, we picked up this Sensor Optimization[1] that moved the sensors to sensortype_sensorname. E.g.
/redfish/v1/Chassis/my_chassis/Sensors/temperature_my_sensor. This was wrong in Environment Metrics so fix this. Found while looking at a different defect.
[1]: https://github.com/openbmc/bmcweb/commit/c1d019a6056a2a0ef50e577b3139ab5a8dc49355
Commented upstream at https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57717

1060: Fix total power pointer

---

redfish-core/lib/environment_metrics.hpp

```
Starting in 1050, we picked up this Sensor Optimization[1] that moved
the sensors to sensortype_sensorname. E.g.
/redfish/v1/Chassis/my_chassis/Sensors/temperature_my_sensor. This was
wrong in Environment Metrics so fix this. Found while looking at a
different defect.
[1]: https://github.com/openbmc/bmcweb/commit/c1d019a6056a2a0ef50e577b3139ab5a8dc49355
Signed-off-by: Gunnar Mills <gmills@us.ibm.com>```

1050: Fix total power pointer (#1032)

---

redfish-core/lib/hypervisor_system.hpp
redfish-core/lib/systems.hpp

/redfish/v1/Systems/hypervisor/Actions/ComputerSystem.Reset was returning a 404. On closer inspection, it was due to hitting the System .Reset Action and not making it to the Hypervisor specific action. [1].
Remove the Hypervisor specific action and call the method from the System .Reset Action. This is how we do the handleHypervisorSystemGet already. [2]
Fixes defects 637587 and 632508.
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/73203 is upstream 
[1]: https://github.com/ibm-openbmc/bmcweb/blob/1110/redfish-core/lib/systems.hpp#L3335
[2]: https://github.com/ibm-openbmc/bmcweb/blob/1110/redfish-core/lib/systems.hpp#L2906C9-L2906C34
Tested: Loaded this on a system and was able to "Continue to OS running".

Fix 404 on Hypervisor Reset

---

redfish-core/lib/pcie_slots.hpp

A previous commit[1] improperly removed "Id" from PCIeSlots.
Unfortunately, it causes Redfish Service Validator error.
```
1 err.Resource.Id errors in /redfish/v1/Chassis/chassis/PCIeSlots
1 failMandatoryExist errors in /redfish/v1/Chassis/chassis/PCIeSlots
2 fails errors in /redfish/v1/Chassis/chassis/PCIeSlots
ERROR - Id: Mandatory prop does not exist
```
It is suggested to add "Id" as "PCIeSlots" like
```
{
"@odata.type": "#PCIeSlots.v1_5_0.PCIeSlots",
"Name": "PCIe Slot Information",
"Id": "PCIeSlots",
...
}
```
Tested:
- GET PCIeSlots and check "Id" `curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots`
- Redfish Service Validator passes on PCIeSlots
[1] https://github.com/ibm-openbmc/bmcweb/commit/67ce7565ab8fe69219d …

Add Id back to PCIeSlots redfish json

---

redfish-core/lib/ethernet.hpp

Currently UseDomainName status is not updated properly as per corresponding UseDomainName D-bus value
This commit populates UseDomainName for DHCPv4 and DHCPv6 parameters as per D-bus values.
Tested by:
Enable/Disable DHCP UseDomainName and check values of UseDomainName
```
- curl -k -H "X-Auth-Token:${bmc_token}" -X PATCH -D patch.txt -d '{"DHCPv4": {"UseDomainName": false}}'  https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth0
-curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth0
```
Change-Id: I6440e9ee99cf48b140f6ef7df877768117b25175

Populate DHCP UseDomainName with right D-bus values

---

redfish-core/lib/ethernet.hpp

```
Currently UseDomainName status is not updated properly as per
corresponding UseDomainName D-bus value
This commit populates UseDomainName for DHCPv4 and DHCPv6 parameters as
per D-bus values.
Tested by:
Enable/Disable DHCP UseDomainName and check values of UseDomainName
Change-Id: I6440e9ee99cf48b140f6ef7df877768117b25175
Co-authored-by: Ravi Teja <raviteja28031990@gmail.com>```

1110: Populate DHCP UseDomainName with right D-bus values (#1036)

---

redfish-core/lib/hypervisor_system.hpp

Currently, Redfish validator fails for two things when doing a GET on hypervisor ethernet interfaces:
1. Empty mac address getting displayed, and
2. Empty Address origin
This commit ensures that the redfish validator passes by adding appropriate checks in the GET handler method.
Upsrteam: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/73196
Fixes: [
](https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=637212)
Tested By:
Validator Passed.

Hypervisor fix validator errors

---

redfish-core/lib/log_services.hpp

On every dump initiation, bmcweb creates a task with "Starting" state. bmcweb will listen to "DumpRequestStatus" property changed signal and move the task state to "Cancelled/Running" based on the validation of the user input for "resource dump" creation.
The following commit has changed a few enum values for "DumpRequestStatus" property:
[1] https://github.com/openbmc/phosphor-dbus-interfaces/commit/980fb7b56960951d8bfb471e9fe63b9d0bacf127
This PR contains changes made w.r.t the above dbus interfaces change to handle the new enum values.
Tested By:
* Created a resource dump and verified the task state move to "Running/Completed" based on the "DumpRequestStatus" property.

Resource dump create: Handle new errors

---

redfish-core/lib/pcie_slots.hpp

PCIeSlot UpstreamFabricAdapter link field shows URI incorrectly and it needs to be translated with `buildFabricUniquePath()`.
For example,
```
{
"Links": {
"Oem": {
"IBM": {
"UpstreamFabricAdapters": [
{
"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/io_module1"
}
],
"UpstreamFabricAdapters@odata.count": 1
}
},
```
This needs to be
```
"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/chassis15363-logical_slot1-io_module1"
```
Tested:
- GET PCIeSlots on MEX
- Redfish Validator on MEX chass

1110: Use UniquePath on PCIeSlot UpstreamFabricAdapter

---

redfish-core/lib/chassis.hpp

Add support for the Version property of Chassis resources.  That property was added in Chassis schema v1.21.0.
This makes use of the "xyz.openbmc_project.Inventory.Decorator.Revision" interface that is already defined by phosphor-dbus-interfaces.
Tested:
Validator passed and Version property was correctly populated.  No issues on other Chassis resources which do not have a Version property.
I added this to an entity-manager json config:
"xyz.openbmc_project.Inventory.Decorator.Revision": {
"Version": "$PRODUCT_VERSION"
}
The PRODUCT_VERSION field from a given FRU eeprom was picked up by FruDevice and it was exposed under the associated Chassis resource:
busctl get-property xyz.openbmc_project.FruDevice \ /xyz/openbmc_project/FruDevice/Test \
xyz.openbmc_project.FruDevice PRODUCT_VERSION
s …

1110: Chassis: Add support for Version property

---

redfish-core/include/utils/hw_isolation.hpp
redfish-core/lib/processor.hpp

- In an OpenPOWER based system, a user can isolate the Processor Core from the next boot of the system so add the support for same in this patch to do isolation through redfish interface.
- In Redfish, the "Enabled" property (which is added in Processor schema) to enable or disable the respective resource so using the same property for isolation feature.
- The "Enabled" property was added in Processor.v1_12_0 version so bumped the processor schema version in all places.
- The "Enabled" Redfish property is mapped with "xyz.openbmc_project.Object.Enable::Enabled" dbus property.
- In this patch, added the utility function for hardware isolation so any redfish resource can use that utility function if that redfish resource will support hardware isolation for the system.
Note: The hardware …

redfish-core: Core: Enabled the isolation (aka guard) feature

---

include/pam_authenticate.hpp

There is a regression issue found with this commit in password update https://gerrit.openbmc.org/c/openbmc/bmcweb/+/73605 This commit fixes PAM conversation for password update
Tested by:
PATCH https://${bmc}/redfish/v1/AccountService/Accounts/root -d '{"Password":"0penBmc1"}'
Change-Id: Ifcede67364c35ced899a3f726f67253cdb51002e

Fix password update

---

redfish-core/lib/systems.hpp

Have seen pldm send back errors in cases like it is powering off. Just ignore all ChapData errors. The HMC doesn't use ChapData. We will still return a 500 here in 1050/1060 but for 1110, let's just ignore all errors.
Fixes defect 642324

Ignore all ChapData errors

---

redfish-core/lib/redfish_v1.hpp

This will fix the 404 error from JsonSchema FileGet
```
% redfishtool raw GET  -r ${bmc}  -u root -p 0penBmc -S Always \ 
/redfish/v1/JsonSchemas/ComputerSystem/ComputerSystem.v1_22_2.json
redfishtool: Transport: Response Error: status_code: 404 -- Not Found
redfishtool: raw: Error getting response
```
Tested:
- Get `/redfish/v1/JsonSchemas/<schema>/<schema>` and use its
`Location/Uri` for the next redfishtool
- Verify redfishtool result like
```
redfishtool raw GET  -r ${bmc}  -u root -p 0penBmc -S Always /redfish/v1/JsonSchemas/<schema>/<schema>.<version>.json
```
- Redfish Service validator passes
Change-Id: I0ca443177537d0a73a31a7195deb3cfb028c49b5

1110: Fix 404 status from JsonSchemas FileGet

---

redfish-core/lib/ethernet.hpp

This commit updates IPv6 static default gateway implementation to use modified D-bus interfaces 
PrefixLength property removed from StaticGateway D-bus interface
https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/71271
Tested by:
-d '{"IPv6StaticDefaultGateways": [{"Address": "2006:905:15F:36:10:10:3:1"}]}'
-d '{"IPv6StaticDefaultGateways": [{},{"Address": "2007:905:18F:36:10:9:5:1"}]}'

Fix IPv6 static default gateway

---

http/http_response.hpp
include/openbmc_dbus_rest.hpp
include/webassets.hpp
redfish-core/lib/log_services.hpp
redfish-core/lib/redfish_v1.hpp

This will fix the incorrect status 500 to status 404 for the non-eixstent JsonSchema FileGet.
```
% redfishtool raw GET  -r ${bmc}  -u root -p 0penBmc -S Always /redfish/v1/JsonSchemas/ComputerSystem/ComputerSystem.v1_99_1.json
redfishtool: Transport: Response Error: status_code: 500 -- Internal Server Error
redfishtool: raw: Error getting response
```
This commit also refactor `Response::openFile()` to return `ec` so that the caller can check the reason of the failure.
Tested:
- Verify redfishtool result for the non-existent JsonSchema file like
```
% redfishtool raw GET  -r ${bmc}  -u root -p 0penBmc -S Always /redfish/v1/JsonSchemas/<schema>/<non-existent-schema>.json
redfishtool: Transport: Response Error: status_code: 404 -- Not Found
redfishtool: raw: Error getting response
```
- …

1110: Fix status for non-existent JsonSchema FileGet

---

redfish-core/include/registries/openbmc.json
redfish-core/include/registries/openbmc_message_registry.hpp

https://github.com/ibm-openbmc/bmcweb/commit/a09d6d12e1c499672c4feb314ecbd5bef3d06840 pushed several things to 0.6. but forgot a few. We will go with 0.6. for 1110.00, even if we add another message. We can control when we release so we don't need to bump for every message like upstream. Upstream is 0.5 so it makes sense we are 1 version above since we added a few messages.

Make everything 0.6. for the OpenBMC message registry

---

redfish-core/lib/account_service.hpp

The IBM patch to allow ACF uploads by unauthenticated users in some cases https://github.com/ibm-openbmc/bmcweb/commit/bf5f34f394e4119845e14e5a5fa403736ef3fd6a missed an if test, which allowed no such uploads.
Tested: scenarios with these results:
- upload ACF authorized with good ACF - SUCCESS
- upload ACF authorized with bad ACF (bad base64) - took internal error (same as before), should have better message
- upload ACF bad-auth - correctly indicated unauthorized
- upload ACF no auth (unauthorized) - correctly indicated unauthorized
- upload ACF no auth (unauthorized) when allowed by system setting - SUCCESS
Change-Id: I509af6a969fa503c2ce7db93ea3b0de8ab99c7de

Fixup unauthenticated ACF upload

---

Redfish.md
redfish-core/lib/account_service.hpp

This PR pulls the following upstream commits (currently under review) to support MFA on P11 systems
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/74667
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/74807
Tested By:
[1] GET https://${bmc}/redfish/v1/AccountService
This lists "MultiFactorAuth" property defined in
AccountService.v1_12_0 schema
```
"MultiFactorAuth": {
"GoogleAuthenticator": {
"Enabled": false
}
}
```
[2] GET [https://${bmc}/redfish/v1/AccountService/Accounts/<user_name>](https://${bmc}/redfish/v1/AccountService/Accounts/%3Cuser_name%3E);
This lists "MFABypass" property defined in ManagerAccount.v1_10_0
schema
```
"MFABypass": {
"BypassTypes": [
"GoogleAuthenticator"
]
}
```
[3] curl -k -H "X-Auth-Token: $bmc_token" -H "Content-Type: application/json" -X POST …

MFA Support

---

redfish-core/include/event_service_manager.hpp
redfish-core/include/snmp_trap_event_clients.hpp
redfish-core/include/utils/sw_utils.hpp
redfish-core/lib/cable.hpp
redfish-core/lib/chassis.hpp
redfish-core/lib/ethernet.hpp
redfish-core/lib/event_service.hpp
redfish-core/lib/fabric_adapters.hpp
redfish-core/lib/fan.hpp
redfish-core/lib/hypervisor_system.hpp
redfish-core/lib/led.hpp
redfish-core/lib/log_services.hpp
redfish-core/lib/managers.hpp
redfish-core/lib/memory.hpp
redfish-core/lib/metric_report_definition.hpp
redfish-core/lib/network_protocol.hpp
redfish-core/lib/pcie.hpp
redfish-core/lib/power.hpp
redfish-core/lib/power_subsystem.hpp
redfish-core/lib/power_supply.hpp
redfish-core/lib/processor.hpp
redfish-core/lib/sensors.hpp
redfish-core/lib/storage.hpp
redfish-core/lib/systems.hpp
redfish-core/lib/task.hpp
redfish-core/lib/telemetry_service.hpp
redfish-core/lib/thermal_subsystem.hpp
redfish-core/lib/trigger.hpp
redfish-core/lib/update_service.hpp
redfish-core/lib/virtual_media.hpp

Cherry-pick merged commits, resolved multiple merge conflicts:
1. https://gerrit.openbmc.org/c/openbmc/bmcweb/+/72225 - Consistently use generated enumerations
2. https://gerrit.openbmc.org/c/openbmc/bmcweb/+/73530 - fix power state regression
Tested:
- Redfish Service Validator - no new failures running on Rainier hardware

1110 use generated enums

---

Redfish.md
redfish-core/include/utils/sensor_utils.hpp

Cherry-pick upstream commit: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/73700
Changes here are to add support for Redfish for Thermal Equipment[1].
Add the SpeedRPM property for a Rotational fan sensor. This property is part of the Redfish Sensor schema since version 1_2_0.[2]
This change is so we will always have a property with the RPM. This allows a client (e.g. webui-vue) to always look for the SpeedRPM property.
Note: Redfish defines the Reading property for a fan to be a percentage value. Currently for this type of fan sensor the Reading value is being set to the RPM value. To preserve backwards compatibility the SpeedRPM property is added without altering the Reading value. However this may change in the future to match the expected Redfish implementation. Clients are advised to …

1110 Sensors: Add SpeedRPM property

---

redfish-core/lib/account_service.hpp

This commit adds the correct AccountService schema version (AccountService_v1_15_0.*) and fixes the redfish validator failure. It also fixes a bug where "MFABypass" user-level option was not displayed in the redfish response.
Upstream: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/74667
Tested By:
[1] GET https://${bmc}/redfish/v1/AccountService/Accounts/testmfaadminA
Redfish Validator passed.
Change-Id: I406e7113c3b6ceae9396bb5d9f0d9249299d6267

mfa: Add right AccountService schema version

---

redfish-core/include/error_messages.hpp
redfish-core/lib/redfish_sessions.hpp
redfish-core/src/error_messages.cpp

This commit adds the GenerateSecretKeyRequired to the bmcweb registry
which will indicate if the MFA is enabled and if the user has to
authenticate with TOTP configuring the secret key generated in a
device the user posses.
Tested by:
Enable MFA and try to create a session,
Response:
{
{
"Message": "The Time-based One-Time Password (TOTP) secret key
for this account must be generated before access is granted. Perform
the GenerateSecretKey action at URI
'/redfish/v1/AccountService/Accounts/service' and retain the secret
key from the response.",
"/redfish/v1/AccountService/Accounts/service"
],
"MessageId": "Base.1.19.0.GenerateSecretKeyRequired",
"MessageSeverity": "Critical",
"Resolution": "Generate …

Add "GenerateSecretKeyRequired" registry in bmcweb 

---

redfish-core/lib/event_service.hpp

SNMP out of range port doesn't works, it should throw HTTPS 400 error It went ahead and configures it, with default port which is not the correct behaviour.
Fixes: https://github.com/ibm-openbmc/dev/issues/3643
Tested: If the snmp port is out of range, a 400 error will be thrown.
```
p10$ curl --header "Content-Type: application/json" X POST -i -k -u service:0penBmc https://{bmc}/redfish/v1/EventService/Subscriptions --data-raw '{"Destination": "snmp://xx.xx.xx.76:65537","SubscriptionType": "SNMPTrap", "Protocol": "SNMPv2c"}' -vv
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:2443...
* Connected to 127.0.0.1 (127.0.0.1) port 2443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 …
```

Fix snmp port out of range

---

Redfish.md
redfish-core/include/utils/sensor_utils.hpp
redfish-core/lib/thermal_metrics.hpp
test/redfish-core/include/utils/sensor_utils_test.cpp

Cherry-picked upstream commit and resolved merge conflicts:
- https://gerrit.openbmc.org/c/openbmc/bmcweb/+/65286
Change-Id: I6e4ed1f281fd5371c978983b6cc5666badd3752c
Note: TemperatureReadingsCelsius for ThermalMetrics was already implemented downstream. This commit is a rebase that aligns the implementation with upstream. This does result in some semantic differences with the current downstream implementation:
1. @odata.id is no longer part of TemperatureReadingsCelsius array element per Redfish spec.
2. DataSourceUri is corrected to be existing Redfish Uri for associated sensor.
3. The sort of TemperatureReadingsCelsius  array elements now uses the human sort. This results in a consistent sort.
4. @odata.count added for TemperatureReadingsCelsius  array.
Tested:
- Redfish service …

1110: Implement TemperatureReadingsCelsius property for ThermalMetrics

---

redfish-core/lib/account_service.hpp

MFA-Bypass option is disabled for service user.
Service user will be always bypassed for MFA and the patch operation should be disabled from  altering it.

MFA-Bypass: Disable service user for MFA bypass

---

redfish-core/include/utils/fabric_util.hpp

Splitter added a segment to the D-Bus path.. 
Currently given redfish to dbus mapping below, both map to the same redfish object.
"/redfish/v1/Systems/system/FabricAdapters/board1-logical_slot1-io_module1" <->
/xyz/openbmc_project/inventory/system/chassis15873/board1/logical_slot1/io_module1
"/redfish/v1/Systems/system/FabricAdapters/board1-logical_slot1-io_module1" <->
/xyz/openbmc_project/inventory/system/chassis15874/board1/logical_slot1/io_module1
Adding another segment to the redfish fabric adapter id will allow the chassis id to be considered for splitter, for mex, it will add the system segment but this shouldn't cause problems, it is just an id. We should hash like we do software ids, so using more segments to make unique should also work.
We have all this code because our D-Bus …

Add another segment to fabric adapter id

---

Redfish.md
redfish-core/lib/service_root.hpp
redfish-core/schema/oem/ibm/csdl/IBMServiceRoot_v1.xml
redfish-core/schema/oem/ibm/json-schema/IBMServiceRoot.v1_0_0.json

This PR contains the changes to get the d-bus value of Multi factor enabled and populate it under service root in redfish response
Tested by:
GET https://${bmc}/redfish/v1
"Name": "Root Service",
"Oem": {
"IBM": {
"@odata.type": "#IBMServiceRoot.v1_0_0.IBM",
"ACFWindowActive": false,
"DateTime": "2024-11-08T09:00:58+00:00",
"DateTimeLocalOffset": "+00:00",
"Model": "9105-22A",
"MultiFactorAuthEnabled": true,
"SerialNumber": "139EF60"
}
},
Fixes : https://jsw.ibm.com/browse/PFEBMC-3585
Upstream : OEM property, downstream only.

Add service root OEM for MFA flag

---

redfish-core/lib/ethernet.hpp

```
Currently UseDomainName status is not updated properly as per
corresponding UseDomainName D-bus value
This commit populates UseDomainName for DHCPv4 and DHCPv6 parameters as
per D-bus values.
Tested by:
Enable/Disable DHCP UseDomainName and check values of UseDomainName
Change-Id: I6440e9ee99cf48b140f6ef7df877768117b25175
Co-authored-by: Ravi Teja <raviteja28031990@gmail.com>```

1050: Populate DHCP UseDomainName with right D-bus values (#1036)

---

redfish-core/include/utils/get_chassis_names.hpp
redfish-core/include/utils/telemetry_utils.hpp
redfish-core/lib/metric_definition.hpp
redfish-core/lib/telemetry_service.hpp
redfish-core/src/redfish.cpp

```
Added MetricDefinition node to Redfish code. Now user is able to list
all available metrics in OpenBMC that are supported by Telemetry
service. Metrics are grouped by reading type.
MetricDefinitions contains all physical sensors supported by redfish,
algorithm iterates through all chassis and collects results for each
node available in that chassis (Power, Thermal, Sensors).
When BMCWEB_NEW_POWERSUBSYSTEM_THERMALSUBSYSTEM will be enabled by
default (meson option redfish-new-powersubsystem-thermalsubsystem) it
will be possible to optimize this algorithm to only get sensors from
Sensors node. Currently Sensors node doesn't contain all available
sensors.
Removal of ResourceNotFound in sensors.hpp to fix MetricDefinition
Collection REST Get call.
Tested:
- MetricDefinitions response is …
```

1110: Add support for MetricDefinition scheme

---

Redfish.md
redfish-core/lib/account_service.hpp

Tested By:
Read-only user will be generate secret key and verify totp.
All users will be able to generate secret key and verify only for self. Admin has no control over other users.
Verified all MFA operations with both Adminstrator privilege user and operator-priv user
Login:
POST https://${bmc}/redfish/v1/SessionService/Sessions -d '{"UserName":"test_readonly2", "Password":"0penBmc0", "Token": "<>"}'
Generate Totp:
POST https://${bmc}/redfish/v1/AccountService/Accounts/test_readonly2/Actions/ManagerAccount.GenerateSecretKey
Verify Totp:
POST https://${bmc}/redfish/v1/AccountService/Accounts/test_readonly2/Actions/ManagerAccount.VerifyTimeBasedOneTimePassword -d '{"TimeBasedOneTimePassword":"<>"}'
Enable Google Auth:
PATCH '{"MultiFactorAuth":{"GoogleAuthenticator":{"Enabled":true}}}' …

Pull latest MFA upstream changes along with user privilege changes in route handler

---

redfish-core/include/utils/json_utils.hpp
test/redfish-core/include/utils/json_utils_test.cpp

Pulling in an upstream commit to fix a problem with objectKeyCmp() which causes bmcweb to core dump. Haven't seen this core dump downstream but thought it would be safer to pull in the fix since we are using this function:
- https://gerrit.openbmc.org/c/openbmc/bmcweb/+/75867
bmcweb replaces underscores with spaces in sensor names for better readability. The existing objectKeyCmp function did not handle this case, leading to core dumps in the sensor load path.
Error details are provided below.
```
bmcwebd[1368]: [DEBUG sensors.hpp:507] Added sensor P0_NS_VR_FAN_2
bmcwebd[1368]: terminate called after throwing an instance of
'boost::detail::with_throw_location<boost::system::system_error>'
bmcwebd[1368]:   what():  leftover [boost.url.grammar:4]
```
Implemented a new algorithm that …

1110: Rebase: json utility: fixed core dump during sensor load

---

include/dbus_privileges.hpp
include/sessions.hpp
redfish-core/lib/redfish_sessions.hpp

Return an error when the user try to get/patch without completing MFA setup when MFA is enabled.
Tested by:
Enable MFA in the system.
Verified generate secret key message is returned when creating a redfish session
Verified generate secret key message is returned if get/patch is executed.
Fixes : https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=652534
Upstream : https://gerrit.openbmc.org/c/openbmc/bmcweb/+/74938

Restrict the user till MFA setup is complete

---

redfish-core/lib/log_services.hpp
redfish-core/src/utils/dbus_utils.cpp

Three commits here to return a better error when resolve/delete error log is unavailable due to active gard record. This is part of the spare cores overwrite story. 
The 1st commit is  [Switch resolved to use SetProperty](https://github.com/ibm-openbmc/bmcweb/commit/ad5b2a67cd6032189c065e597ed044d7c8f66b87). This follows patterns elsewhere and is already done upstream at https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/log_services.hpp#L1806. There is a lot of downstream commits in this area so pulling upstream wasn't possible 
2nd commit is [Map Error.Unavailable to something better](https://github.com/ibm-openbmc/bmcweb/commit/1525466aaf0629f9f609c4105176b7aa0d4107cf). Upstream at https://gerrit.openbmc.org/c/openbmc/bmcweb/+/75570 
3rd commit is [Add specific error on …

Correct errors for spare core overwrite

---

redfish-core/lib/account_service.hpp

Upstream: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/76046
Tested By:
[1] POST https://${bmc}/redfish/v1/AccountService/Accounts/<username>/Actions/ManagerAccount.ClearSecretKey
Change-Id: If416c26f21f8c1fb1884b1d022619f0f065e8a5d

MFA: Add ClearSecretKey redfish action for user

---

redfish-core/lib/log_services.hpp

We removed internal interface in dump manager and we are currently using an external interface. So, changing it to support FaultData dump.
Before:
```
Dec 05 18:14:15 valid-hostname phosphor-dump-manager[521]: Initiating new BMC dump with type: user path:
Dec 05 18:14:41 valid-hostname pldmd[715]: Dumping the flight recorder into : /tmp/pldm_flight_recorder
Dec 05 18:14:53 valid-hostname phosphor-dump-manager[1658]: performing dump compression /tmp/BMCDUMP.139F230.00000002.20241205181415
Dec 05 18:14:56 valid-hostname phosphor-dump-manager[1658]: Adding Dump Header :/usr/share/dreport.d/include.d/gendumpheader
Dec 05 18:15:09 valid-hostname phosphor-dump-manager[1658]: Thu Dec  5 18:15:09 UTC 2024 Report is available in /var/lib/phosphor-debug-collector/dumps/2
Dec 05 18:15:09 …
```

Change FaultData dump type parameter as per dump manager

---

redfish-core/lib/memory.hpp

https://github.com/ibm-openbmc/bmcweb/pull/542 (1050/1060) https://github.com/ibm-openbmc/bmcweb/pull/918 (1110) added PrettyName for Processors, Assembly, Chassis, Storage but not Memory. I believe this was due to not needed it for Memory at the time. We want it now so the GUI can use on the inventory page.  (#973) pulled this in for 1060 but was missed for 1110. 
Fixes 667557
No upstream here, https://jsw.ibm.com/browse/PFEBMC-2871 tracks getting prettyname upstream 
Tested: 
```
curl -k https://$bmc/redfish/v1/Systems/system/Memory/dimm0
...
"Name": "Memory module 0",
```

Dimm: Look at Pretty Name 

---

redfish-core/include/task_messages.hpp

The previous commit 6152509d51a27d4ffaacbf45bcff124d1c3c6f6c [1] changes the format of MessageId format from 3-digit version to 2-digit version like
- `Base.1.19.0.ResourceNotFound` to `Base.1.19.ResourceNotFound`
However, there is one missing hard-coded Oem message `taskAborted()`, and this fixes it.
Tested:
- Run Code Update which may cause the abort situation
- Verify the Tasks like
```
curl -k -X GET https://${bmc}/redfish/v1/TaskService/Tasks/0
...
"MessageId": "TaskEvent.1.0.1.TaskAborted",
```
After fix, this will be changed like
```
"MessageId": "TaskEvent.1.0.TaskAborted",
```
[1] https://github.com/ibm-openbmc/bmcweb/commit/6152509d51a27d4ffaacbf45bcff124d1c3c6f6c

1110: Fix MessageId for Oem taskAbort Error

---

redfish-core/lib/ethernet.hpp

Whenever IPv6 SLAAC is enabled and DHCPv4 is enabled, the "DHCPEnabled" value in the backend will be "v4v6stateless". Currently in bmcweb, the check to translate this value to bool for ipv4 is not present and will return false. That means, "DHCPEnabled" is wrongly displayed 'false' while the correct value is 'true'.
Upstream: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/76560
Change-Id: I8713d73727c6a382f06b7bf0d598ab61a757e1e3

network: fix dhcp values in redfish response

---

meson.build
redfish-core/lib/ethernet.hpp
test/redfish-core/lib/ethernet_test.cpp

There's a number of conditions in setting gateways that don't work properly.  Specifically, one of the issues is setting a gateway on an address that already exists.  It returns a PropertyValueConflict error on Ipv4Addresses/1/Gateway with Ipv4Addresses/1/Gateway
Obviously an address can't conflict with itself, so this is wrong.
To address this, move the gateway setting and selection code into a routine outside of the main loop, after all the gateways are accounted for, and so we can treat them separately.
Tested;
PATCH to an existing ip address works, and no longer returns the error.
Fixes : https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=635827
Upstream : https://gerrit.openbmc.org/c/openbmc/bmcweb/+/75859
Change-Id: …

Fix setting gateways

---

redfish-core/lib/power_subsystem.hpp

The existing code had 2 async calls updating the "AllocatedWatts" parameter. There is no guarantee that the values would be updated in same order everytime.
This change will ensure the 2nd async call happens after the first and the correct value will be returned for AllocatedWatts.
Change-Id: I3cf10e6ecb2ab3719034521f1e9d05dbe1c72936

Fix race condition updating AllocatedWatts from CapLimits

---

redfish-core/lib/log_services.hpp

When the guard severity is OK, it could be associated with an informational PEL.  And the informational PELs are listed under /redfish/v1/Systems/system/LogServices/CELog/Entries/ and the other PELs are listed under
/redfish/v1/Systems/system/LogServices/EventLog/Entries/
So based on the guard type, assign the URI. Tested with guards that have severity as OK and the URI maps to CELog and for other guards, it maps to EventLog
Test Results:
```
curl -k -H "X-Auth-Token: $bmc_token" -XGET https://${BMC_IP}/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries
"@odata.id": "/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries",
"@odata.type": "#LogEntryCollection.LogEntryCollection",
"Description": "Collection of System Hardware Isolation Entries",
"Members": [
{ …
```

HW-Isolation: Fix info PEL AdditionalDataURI

---

redfish-core/lib/account_service.hpp

When a user generates secret key, currently there is a check to see if the global mfa is enabled. And only if it is enabled, secret key generation is allowed for the user.
This commit removes the check, and enables users to generate secret key even if the global mfa is disabled.
Upstream: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/74667
Tested By:
'''
POST https://${bmc}/redfish/v1/AccountService/Accounts/<>/Actions/ManagerAccount.GenerateSecretKey
'''

Generate secret key: Remove global mfa check

---

redfish-core/lib/pcie.hpp

I needed this to debug a problem. Might be useful in the future.
[ERROR pcie.hpp:381] PCIeDevice /xyz/openbmc_project/inventory/system/chassis15873/motherboard3/slot24/logical_slot2/adapter1 is associated with more than one PCIeSlot: 2
Upstream is merged at https://gerrit.openbmc.org/c/openbmc/bmcweb/+/77209

Add path of problem device to trace

---

redfish-core/lib/fan.hpp
redfish-core/lib/power_supply.hpp

Use getPrettyName like we do for Processors, Assembly, Chassis, Storage, Memory.
https://github.com/ibm-openbmc/bmcweb/pull/542 (1050/1060) https://github.com/ibm-openbmc/bmcweb/pull/918 (1110) added PrettyName for Processors, Assembly, Chassis, Storage but not PowerSupplies/Fan. I believe this was due to not needed at the time. https://github.com/ibm-openbmc/bmcweb/pull/1111 added PrettyName for Dimm. 
Fixes 668395
No upstream here, https://jsw.ibm.com/browse/PFEBMC-2871 tracks getting prettyname upstream
Tested: 
Before 
`"Name": "Power Supply",`
and 
`"Name": "Fan",`
After:
`"Name": "powersupply0",`
and 
`"Name": "fan1",`

Power Supply, Fan: Look at PrettyName

---

redfish-core/lib/update_service.hpp

Have seen a problem where BMC code update is timing out. This is temp code to get a dump. I set a TODO to remove this 4/1/25
We have this defect 661124, where we are seeing the code update timeout.
Have no idea what is slowing things down so this adds code to get a dump
after it times out.
Tested: Lowered this timeout to 2 seconds and see the dump generated.
```
busctl introspect xyz.openbmc_project.Dump.Manager  /xyz/openbmc_project/dump/bmc/entry/3 xyz.openbmc_project.Common.OriginatedBy 
NAME                                    TYPE      SIGNATURE RESULT/VALUE                             FLAGS
.OriginatorId                           property  s         "bmcweb-internal"                        emits-change writable
.OriginatorType                         property  s …
```

Add BMC Dump when code update timeout

---

redfish-core/lib/memory.hpp

This change should have been part of
```https://github.com/ibm-openbmc/bmcweb/pull/953/commits/7d6dd2c6b632d24752eba7870343ed9c790d638e```
Here is the original commit.
```https://github.com/ibm-openbmc/bmcweb/pull/171/files```
Due to this missing change, the deconfiguration type is not displayed in the GUI. After including this change, here is the redfish output.
```
curl -k -H "X-Auth-Token: $bmc_token" -XGET https://${BMC_IP}/redfish/v1/Systems/system/Memory/dimm1
{
"/Status/Conditions/0/Severity": "OK",
"@odata.id": "/redfish/v1/Systems/system/Memory/dimm1",
"@odata.type": "#Memory.v1_12_0.Memory",
"AllowedSpeedsMHz": [],
"BaseModuleType": "RDIMM",
"BusWidthBits": 0,
"CapacityMiB": 32768,
"DataWidthBits": 0,
"Enabled": false,
"ErrorCorrection": "NoECC",
"FirmwareRevision": "0",
"Id": …
```

Hw-Isolation: Deconfiguration type for DIMMs

---

redfish-core/lib/redfish_sessions.hpp

Changes to add the GenerateSecretKeyRequired incorrectly removed the audit logging for session creation. [1] Adding it back.
This fixes STG Defect 673437.
Tested:
Created session. Checked audit entry added using both ausearch and was returned as part of /redfish/v1/Systems/system/LogServices/AuditLog/Entries
```
/* Session shows up in ausearch results */
type=USYS_CONFIG msg=audit(01/22/25 23:09:09.379:25) : pid=1603 uid=root auid=unset ses=unset msg='op=POST:/redfish/v1/SessionService/Sessions acct=service exe=/tmp/bmcweb hostname=p10bmc addr=10.0.2.1 terminal=? res=success' 
/* Session shows up in response from request to retrieve audit entries */
$ curl -k -H "X-Auth-Token: $token"  https://${BMC_IP}/redfish/v1/Systems/system/LogServices/AuditLog/Entries?\$top=1
{
"@odata.id": …
```

Audit Log: Correct logging of sessions

---

redfish-core/lib/ethernet.hpp

Ethernet Port: Add LLDP port schema to interfaces
Link Layer Discovery Protocol is a Data Link Layer protocol used for
discovering devices on a local network. LLDP advertises information
about themselves to directly connected devices. This information
includes the device's identity, capabilities, and network management
information, which can be used for network monitoring, topology
discovery and network troubleshooting.
This commit will add Bmcweb changes required to enable/disable LLDP
property in ethernet interfaces.
Schema:
https://redfish.dmtf.org/schemas/v1/PortCollection.json
https://redfish.dmtf.org/schemas/v1/Port.v1_14_0.json
Tested by
Get/Patch on
curl https://xxx/redfish/v1/Managers/bmc/DedicatedNetworkPorts/eth1
{
"@odata.id": …

Ethernet Port: Add LLDP port schema to interfaces

---

redfish-core/lib/ethernet.hpp

When modifying a static default gateway, the existing entry is deleted, and a new D-Bus object is created with the updated gateway.
Currently, this operation fails with an Internal Server Error and causes a bmcweb crash because the gateway value is passed as a std::string_view. Debugging revealed that the data's lifetime ends before it is accessed.
This commit resolves the issue by replacing std::string_view with const std::string&.
Tested By:
Assuming there are currently three IPv6StaticDefaultGateways configured, the following command modifies the second entry:
'''
PATCH -D patch.txt -d '{"IPv6StaticDefaultGateways": [{},{"Address": "<new modified gateway>"},{}]}' https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth1 '''
Change-Id: I1bd18005fb71a1567b1844b04c4cc4cd322cdf6e

Fix crash when modifying static v6 default gateway

---

redfish-core/lib/assembly.hpp

MEX Assemebly gives incorrectly as same as CEC assemblies.
For example,
- CEC Assembly : https://rain118bmc.aus.stglabs.ibm.com/redfish/v1/Chassis/chassis/Assembly
- MEX Assembly : https://rain118bmc.aus.stglabs.ibm.com/redfish/v1/Chassis/chassis15363/Assembly
Tested:
- Check MEX assembly

1110: Fix Assembly for MEX

---

include/authentication.hpp
include/cookies.hpp

As PE00QD48 shows the HMC/TomCat cookie is interfering with the Cookie set by BMCWEB. Reading online shows a session cookie name of BMCWEB-SESSION is more inline so let's just rename our SESSION cookie to BMCWEB-SESSION.
Tested: Using the HMC proxy, this works 
Upstream: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/77539

Change Session Cookie name

---

redfish-core/include/utils/error_log_utils.hpp
redfish-core/include/utils/hw_isolation.hpp
redfish-core/lib/log_services.hpp

Resolve the issue where LogEntry and Severity key-value pairs are being treated as separate elements instead of being structured under the status/Conditions hierarchy.

Fix log entry

---

redfish-core/src/utils/dbus_utils.cpp
test/redfish-core/include/utils/dbus_utils.cpp

Taking latest upstream changes to fix multiple success message seen in response. Now the behaviour is similar to what upstream does, which mean there is no message in the response. The response is set with no_content flag.
Upstream change : https://github.com/openbmc/bmcweb/blob/master/redfish-core/src/utils/dbus_utils.cpp#L91

Fix 670598: dbus_util changes to fix response message

---

include/authentication.hpp
include/cookies.hpp

This reverts commit 05b61c64f39e58e36cebfca10d52dbb1f6791f64.
In DVT, we are hitting an error 
```
Keyword 'Upload Image To BMC' failed after retrying 1 time. The last error was: SSLError: HTTPSConnectionPool(host='xxxxxx', port=443): Max retries exceeded with url: /redfish/v1/UpdateService/update (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2427)')))
```
I can't explain it but reverting this commit appears to fix it

Revert "Change Session Cookie name (#1130)"

---

redfish-core/lib/account_service.hpp

Currently, a readonly user is able to bypass MFA for self, which allows the user to continue with the session unauthorized.
This commit disallows a readonly user to bypass MFA when global MFA is enabled. Only users with admin privilege will be able to bypass MFA for self and for other users.
Tested By:
'''
PATCH -D patch.txt -d '{"MFABypass":{"BypassTypes":["GoogleAuthenticator"]}}' https://${bmc}/redfish/v1/AccountService/Accounts/test_readonly -H "Content-Type: application/json"
This throws an "InsufficientPrivilege" error for readonly user. '''

MFA: Disallow bypass option to Readonly user

---

include/authentication.hpp

As PE00QD48 shows the HMC/TomCat cookie is interfering with the Cookie set by BMCWEB. This hack switches find to rfind so our cookie is found first.
This doesn't impact going to the GUI directly because we only have the one
SESSION cookie. Don't want to check both because this might allow
attackers to negate the anti brute force measures by testing multiple
passwords at once. [1]
Gets testing off the ground, doesn't break DVT, and 1 line change.
Upstream: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/77539
https://jsw.ibm.com/browse/PFEBMC-3844 tracks fixing this correctly.
Drive upstream but will try to make it happen for 1110.
[1]: https://github.com/openbmc/bmcweb/commit/9f217c26f58c0a99c18e7cac7b095dcf6068562d
Tested: GUI works directly and the proxy now works

 Make the proxy GUI work

---

redfish-core/lib/account_service.hpp

This commit includes the changes to remove other sessions of the same user on successful verification of TOTP only when MFA is enabled. 
Tested By:
1. Created multiple redfish sessions of the same user
2. Verified other sessions are cleared only when MFA is enabled.
3. Verified when MFA is disabled, other sessions of the same user is not cleared
Change-Id: I95dbecc107258836f3ec8f8f06b80cd6f91b6f79
Upstream : https://gerrit.openbmc.org/c/openbmc/bmcweb/+/74807

MFA: Remove the session only when MFA is enabled

---

redfish-core/lib/network_protocol.hpp

This changes support for URI /redfish/v1/Managers/bmc/NetworkProtocol property SSH.Enabled.  The implementation is currently hardcoded to support the "dropbear" SSH service.  This commit changes it to "sshd" which is the OpenSSH service.
This builds okay, but this function requires an accompanying change in the service config manager.
See https://github.com/ibm-openbmc/service-config-manager/pull/4
The community is exploring the right way to adapt to whichever SSH server is being used.
Tested:
Yes, together with the srvcfg-manager change.
```
curl -k -H "X-Auth-Token: $TOKEN" -H "Content-Type: application/json" \
-X PATCH https://${bmc}/redfish/v1/Managers/bmc/NetworkProtocol \
-d'{"SSH": {"ProtocolEnabled": true}}'
```
Change-Id: If680f62f9cdc88f83e9bb4ad995947be9ceba0b6

Move to OpenSSH

---

config/bmcweb.service.in

Rebase for 1120.
Currently our systemd service are automatically restarted on failure a
max of 3 times over 30 seconds. I.e. our current settings are:
StartLimitInterval=30
StartLimitBurst=2 (this PR increases this to 4) 
Certificate manager restarts bmcweb when a new certificate is uploaded,
we have seen this happen more than 3 times in a 30 second period.
Allow bmcweb to be restarted 5 times over a 30 second period before
stopping.
This is a short term fix, the long term fix is Certificate manager will
throttle how often it restarts bmcweb.

Increase bmcweb automatic restart (#356) (#810)

---

meson.options
redfish-core/include/privileges.hpp
redfish-core/lib/account_service.hpp
redfish-core/lib/roles.hpp
redfish-core/schema/oem/openbmc/csdl/OemManagerAccount_v1.xml
redfish-core/schema/oem/openbmc/json-schema/OemManagerAccount.v1_0_0.json
redfish-core/schema/oem/openbmc/meson.build

For the 1120 rebase, merge all ACF and Service user commits into one. This will ensure future cherry-picks of this downstream function are easier to bring in. Having it spread across multiple commits makes the process of bringing it back in during rebases unnecessarily complex.
The properties of the "service" user has been
extended to include ["Oem"]["IBM"]["ACF"]
The patch and get methods to the route
"/redfish/v1/AccountService/Accounts/service"
now return the ACF properties to the request.
These properties include:
ACFFile, ExpirationDate, ACFInstalled,
WarningLongDatedExpiration, BMCCurrentDate
These were added in support for acf upload functionality.
A summary of these properties are as follows:
ACFFile : contents of the ACF file uploaded
ExpirationDate : date of expiration for the …

Accounts/service ACF properties added

---

config/meson.build
http/app.hpp

1120: Cherry-pick of upstream commit: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/78337
With this commit I'm able to run 1120 built bmcweb on upstream flash image on simulator. Running bmcweb out of /tmp I'm able to connect through port 18080.
The commit [1] altered how sockets are created and inadvertently removed the default port 18080. We use this port extensively in development. The bmcweb documentation describes the port 18080 for this use. [2] Adding back the default port 18080.
The commit [1] added meson build options for adding additional ports. In attempting to enable port 18080 using that mechanism I ran into various build errors when additional-ports has a value. I've corrected the config/meson.build file to address those errors. These changes are not necessary to re-enable …

Enable port 18080

---

Redfish.md
redfish-core/lib/led.hpp
redfish-core/lib/power_supply.hpp

Cherry-pick of upstream commit https://gerrit.openbmc.org/c/openbmc/bmcweb/+/42221
Tested using upstream flash image on hardware simulator. Redfish validator was run. Lots of unrelated errors, but the checks for LocationIndicatorActive passed.
Implement LocationIndicatorActive for PowerSupplies schema to set/get the status of the location LED for each power supply.[1] When working with Redfish to get or set the "LocationIndicatorActive" property, the initial step involves locating the corresponding LED group through the "identifying" association.[2][3][4] Following this, we can proceed to either get or set the "Asserted" property.[5]
[1] https://redfish.dmtf.org/schemas/v1/PowerSupply.v1_5_0.json
[2] https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/yaml/xyz/openbmc_project/L …

Implement LocationIndicatorActive for PowerSupplies (#818)

---

Redfish.md
redfish-core/lib/chassis.hpp
redfish-core/lib/pcie_slots.hpp
redfish-core/schema/oem/ibm/csdl/IBMPCIeSlots_v1.xml
redfish-core/schema/oem/ibm/json-schema/IBMPCIeSlots.json
redfish-core/schema/oem/ibm/json-schema/IBMPCIeSlots.v1_0_0.json
redfish-core/schema/oem/ibm/meson.build
redfish-core/schema/oem/meson.build
redfish-core/src/redfish.cpp

This is to layout the initial rebase set for PCIeSlots and Oem IBMPCIeSlots 
- 67ce7565ab  Fix PCIeSlots when empty association (#1031)
- 9004f77d08  Add Id back to PCIeSlots redfish json (#1045)
- 6b23780745 Add Pcie slot to Pcie device link (ibm-openbmc#570) (#847)
- d012981d35  Add Get for PCIe properties LinkId (#578) (#843)
Tested:
- Perform the tests for each commit
- Redfish-Service-Validator passes

1120: Rebase pcieslot base set

---

Redfish.md

This commit will add redfish shema details on dedicated network port to
the redfish.md file
This was missed in below commit
https://github.com/ibm-openbmc/bmcweb/pull/1121
Upstream commit https://gerrit.openbmc.org/c/openbmc/bmcweb/+/76569

Redfish.md: Changes to redfish documentation

---

Redfish.md
redfish-core/lib/fan.hpp

Rebase of [PR 819](https://github.com/ibm-openbmc/bmcweb/pull/819). That PR had two commits. The "Enable Redfish New Powersubsystem Thermalsubsystem" commit has merged upstream and is already part of 1120. So this PR only includes the "Fan LocationIndicatorActive" commit.
Upstream commit: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/42210
Tested using upstream flash image on hardware simulator. Redfish validator was run. Lots of unrelated errors, but the checks for LocationIndicatorActive passed.
Implement LocationIndicatorActive for Fan schema to set/get the status of the location LED for each Fan. When working with Redfish to get or set the "Location Indicator Active" property, the initial step involves locating the corresponding LED group through the "identifying" association. …

Implement LocationIndicatorActive for Fan (#819)

---

Redfish.md
redfish-core/include/utils/sensor_utils.hpp
redfish-core/lib/environment_metrics.hpp

Rebase of [PR 956](https://github.com/ibm-openbmc/bmcweb/pull/956). Using cherry-pick of upstream commit https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57717 since it is close to merging upstream and uses new PDI interface.
Tested using upstream flash image on hardware simulator. Redfish validator was run. Lots of unrelated errors, but the checks for PowerWatts passed.
The EnvironmentMetrics schema[1] provides for efficient retrieval of environmental metrics by separating them from performance metrics. EnvironmentMetrics is a property of the Chassis schema since v1_15_0[2]. EnvironmentMetrics was added to Redfish release 2021.2 [3] to be used instead of the deprecated Power schema.[4]
This commit adds PowerWatts property of the EnvironmentMetrics schema. PowerWatts has been part of the …

Add PowerWatts for EnvironmentMetrics (#956)

---

redfish-core/lib/fabric_adapters.hpp
redfish-core/lib/pcie_slots.hpp
redfish-core/schema/oem/ibm/csdl/IBMFabricAdapter_v1.xml
redfish-core/schema/oem/ibm/json-schema/IBMFabricAdapter.json
redfish-core/schema/oem/ibm/json-schema/IBMFabricAdapter.v1_0_0.json
redfish-core/schema/oem/ibm/json-schema/IBMPCIeSlots.v1_0_0.json
redfish-core/schema/oem/ibm/meson.build

Implement & rebase FabricAdapter OemSlot schema (#866)
To support the correct location codes for spliiter I/O slots,
new associations between FabricAdapter and its PCIeSlots are
created by:
- https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/63812
- https://github.com/ibm-openbmc/pldm/pull/416
Using these associations, BMCWEB will show them via OEM properties
as follows.
This also allowes multiple fabric adapters on a slot.
- Allow multiple fabric adapters on a PCIeSlots via
`UpstreamFabricAdapters`
- FabricAdapter -> PCIeSlots
```
"@odata.id": "/redfish/v1/Systems/system/FabricAdapters/chassis15361-logical_slot2-io_module2",
"Id": "chassis15361-logical_slot2-io_module2",
...
"Oem": {
"IBM": {
"@odata.type": …
```

1120: Implement and Rebase FabricAdapter OemSlot schema (#866)

---

redfish-core/lib/network_protocol.hpp

```
This changes support for URI /redfish/v1/Managers/bmc/NetworkProtocol
property SSH.Enabled.  The implementation is currently hardcoded to
support the "dropbear" SSH service.  This commit changes it to "sshd"
which is the OpenSSH service.
This builds okay, but this function requires an accompanying change
in the service config manager.
The community is exploring the right way to adapt to whichever SSH
server is being used.
Tested:
Yes, together with the srvcfg-manager change.
curl -k -H "X-Auth-Token: $TOKEN" -H "Content-Type: application/json" \
-X PATCH https://${bmc}/redfish/v1/Managers/bmc/NetworkProtocol \
-d'{"SSH": {"ProtocolEnabled": true}}'
Change-Id: If680f62f9cdc88f83e9bb4ad995947be9ceba0b6
Signed-off-by: Joseph Reynolds <joseph.reynolds1@ibm.com>```

1120: Move to OpenSSH (#1136)

---

redfish-core/lib/assembly.hpp

Error occurred for panel and panel display under Concurrent Maintenance tab when user toggles the button.
This happened because Oem data is missed out in redfish query data for panel and panel display in case FRU is present.
Changes made to fix above issue, by always sending Oem data irrespective of FRU is present or not.

Fix defect: Enable panel toggling in CM tab

---

redfish-core/lib/update_service.hpp

As seen in DVT with defect 661124, have cases where this times out. This timer includes both the time to write the image to /tmp/images/ as well as the time for the code update app to untar the image and create a D-Bus object.
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/78644 is upstream

1120: Up the code update timeout to 50 secs

---

redfish-core/lib/update_service.hpp

Revert the pervious generate a dump during time out of code update 
https://github.com/ibm-openbmc/bmcweb/commit/9073415afd8d3a627e8b888465cef69dd8aea4ed
And bump the code update time to 50 seconds 
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/78644 is upstream

Change code update timeout

---

include/audit_events.hpp

Cherry-pick and rebase PR https://github.com/ibm-openbmc/bmcweb/pull/739
Tested:
- Verififed detail data for non-update actions properly logged.
- Verified data limit for update caught 
```
[WARNING audit_events.hpp:230] Audit buffer too small for data: bufLeft=215 detailLen=257
[DEBUG audit_events.hpp:268] auditEvent: bufLeft=201  opPathLen=41 detailLen=257 userLen=14
root@p10bmc:/tmp# ausearch -i | grep UpdateService
type=USYS_CONFIG msg=audit(01/22/25 22:17:21.909:34) : pid=1522 uid=root auid=unset ses=unset msg='op=POST:/redfish/v1/UpdateService/update acct=service exe=/tmp/bmcweb hostname=p10bmc addr=10.0.2.1 terminal=? res=success' 
```
bmcweb currently consumes the excessive memory during firmware update. It is due to the replications of the req.body (which is the full content of …

Reduce memory usage during Firmware update (#739)

---

redfish-core/lib/redfish_sessions.hpp

Upstream is merged at https://github.com/openbmc/bmcweb/commit/8812e8becaf44d810e68ed80692c2797b2f114ac
This fixes defect 674611 
When a web interface sends a DELETE request for a session other than it's using itself the reply shouldn't ask the web browser to delete the cookies and to clear the site data.
Tested: logging in to BMC, observing the session identifier returned by POST to Sessions, then opening another private window and logging in on the same BMC, getting another session ID. Then navigating to "Security and access -> Sessions" and pressing "Disconnect" button for the session opened in the first window just deletes the session normally and the web interface of the second private window that performed the operation continued to work. Pressing "Log out" deletes the current …

Do not remove wrong cookies on Session DELETE

---

redfish-core/lib/roles.hpp

* Restrict the Operator role (#319)
This changes the Operator role to Restricted=true which means no users can have the Operator role.
This is downstream only due to upstream having the operator role
Tested:
1. GET /redfish/v1/AccountService/Roles/Operator and ensure it has Restricted:true.
2. POST /redfish/v1/AccountService/Accounts/new with Role:Operator Ensure it failed with message Base.1.9.0.RestrictedRole. Posting a new Administrator user is successful.
3. PATCH /redfish/v1/AccountService/Accounts/ordinary with Role:Operator.  Ensure it failed.
Changing a user to the ReadOnly role is successful.
4. PATCH the OemIBMServiceAgent role as the LocalRole within the RemoteRoleMapping property && ensure it failed.
* Fixup clang boolean expression
---------

Restrict the Operator role (#319) (#526) (#954)

---

redfish-core/include/utils/query_param.hpp
redfish-core/lib/service_root.hpp
test/redfish-core/include/utils/query_param_test.cpp
test/redfish-core/lib/service_root_test.cpp

This was supposed to be done for 1050 but somehow was missed.
upstream this is https://gerrit.openbmc.org/c/openbmc/bmcweb/+/78192 
Tested: Any expand greater than 3 rejects.

Limit Query Expand to 3

---

Redfish.md
redfish-core/lib/processor.hpp

Rebase of 1110 commit 7c25f4b. Also made some restructuring changes to address common upstream review comments.
Tested on 1120 using hardware simulator. Redfish validator was run. Lots of unrelated errors, but the checks for LocationIndicatorActive passed.
- Add the getLocationIndicatorActive method and the setLocationIndicatorActive method to bmcweb to support the LocationIndicatorActive property for processor.
- A client would use the `LocationIndicatorActive` property to identify or locate the processor. This would be accomplished `LocationIndicatorActive` to true by the `doPatch` method. The LED group manager, defined by the `identify_led_group` association, should then turn on the LEDs associated with this processor. The LEDs should then be turned off when `LocationIndeicatorActive` …

Implement LocationIndicatorActive for CPU resource (#937)

---

redfish-core/lib/hypervisor_system.hpp

This PR has two commits to fix issues with hypervisor network configurations:
Remove explicit setting of enabled prop - This commit removes explicit setting of Enabled property of IP address object in the backend. This logic will be done by the backend.
Fix error while patching defaultGateway6 with null.
Fixes:
https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=685272
https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=685259

Hypervisor issues fix

---

include/authentication.hpp
include/cookies.hpp

1) revert the hack at https://github.com/ibm-openbmc/bmcweb/commit/b90a2c3beb6e93a007a8839608f948d9ba95a4d7 
It doesn't work for sarafi browser because for some reason that hmc cookie is coming in 2nd 
686862 
2) Change Session Cookie name
Upstream is https://gerrit.openbmc.org/c/openbmc/bmcweb/+/77539
This was added at https://github.com/ibm-openbmc/bmcweb/pull/1130 but
had to be reverted at https://github.com/ibm-openbmc/bmcweb/pull/1138
due to DVT failing.
We have a use case where the GUI sits behind a Apache Tomcat proxy[1].
In this environment the cookie looks like:
```
en-US,en;q=0.9cookie:
JSESSIONIDSSO=4E999D77EF4E01CB72DE63949D5FF830;
CCFWSESSION=48A66EB93C00AD4F6327FB3FC2A338FC; LOGIN_MODE=Dashboard;
XSRF-TOKEN=Ue1La3Ik48Bn5NosyLnJ; SESSION=pCAdqApWt4Kb4IUV9vh8dnt:
```
The …

Change cookie name

---

redfish-core/lib/update_service.hpp
redfish-core/schema/oem/ibm/csdl/OemUpdateService_v1.xml
redfish-core/schema/oem/ibm/json-schema/OemUpdateService.json
redfish-core/schema/oem/ibm/json-schema/OemUpdateService.v1_0_0.json
redfish-core/schema/oem/ibm/meson.build
redfish-core/src/redfish.cpp

This commit adds a new update command to be used by the management console to perform concurrent updates. It works like the current update command, but with added support for the OnReset apply time setting.
Tested:
-  Ensured that redfish command updates as usual, and updates still occured while the ApplyTime was in OnReset state.
```
$ curl -k -H "X-Auth-Token: $token" -H "Content-Type: application/octet-stream"  -X POST -T ${image} \
https://${bmc}/redfish/v1/UpdateService/Actions/Oem/OemUpdateService.ConcurrentUpdate
```
- Redfish Service Validator passes

1120: Redfish OEM Update Command for Concurrent Update (#812)

---

redfish-core/lib/update_service.hpp

Updates to resolve getting a response for wrong URI in Update
Service URI (/redfish/v1/UpdateService/FirmwareInventory/)
Tested with the correct URI and results are correct.
Tested with wrong URI and 404 is returned

Updates to resolve getting a response for wrong URI in Update

---

redfish-core/lib/account_service.hpp

Restrict the admin user's privileges to only self-configuration when the session state is in self-configure mode. Currently, the admin can modify other users' information even when the admin session is in isConfigureSelfOnly mode, which appears to be incorrect. Eg:
1) Expire the admin user password
2) Login bmc with admin credentials
3) Password change required error is generated for the user
Expected after step 3
Admin should not be able to change any user information belonging to other users until they have changed their own password.
Observed after step 3
Admin was able to change other user's information before changing own password
Tested By:
1) Expire the admin password using passwd --expire 2) Change user name of other user  as below
```
patch …
```

AccountService: Restrict self-configure privilege

---

redfish-core/lib/update_service.hpp

Resolve getting a response for wrong URI in Update Service URI (/redfish/v1/UpdateService/FirmwareInventory/)
- After the fix a wrong URI that partially matches the last characters in a valid URI now gets a 404 as shown in the example below :
$ curl -k -H "X-Auth-Token: $bmc_token" -X GET
https://$bmc/redfish/v1/UpdateService/FirmwareInventory/5e {
"error": {
{
"Message": "The resource at the URI '/redfish/v1/
UpdateService/FirmwareInventory/5e' was not found.",
"/redfish/v1/UpdateService/FirmwareInventory/5e"
],
"MessageId": "Base.1.19.ResourceMissingAtURI",
"MessageSeverity": "Critical",
"Resolution": "Place a valid resource at the URI or
correct the URI and resubmit the request."
}
],
"code": …

1120 Fix getting a response for wrong URI

---

redfish-core/lib/managers.hpp

The "Status" of the BMC has been historically fairly simple. If the BMC is at the point where it can respond to the Redfish call then it's "OK" and it's "On". Its "Status" could be derived based on the startup systemd target, multi-user.target, as either "Starting" or "Enabled".
However, with the introduction of new BMC states it is no longer this simple. The following design introduced a new "Quiesced" state for the BMC[1]
There has was also a new BMC state introduced, "UpdateInProgress", which indicates the BMC is in the middle of a firmware update.
These new BMC states require additional logic when responding to Redfish queries for the BMC "Status".
When a BMC is in a "Quiesced" state it is an indication that a critical BMC service has entered the failed state. It is important for BMC …

Populate BMC state based on state manager property (#520) (#870)

---

config/bmcweb.service.in

The design of bmcweb is to simply respond to callers with unavailable if a needed d-bus resource is not available. This caused a lot of defects and issues with our HMC team because their code is not built to handle that (BMC also had some bugs in the downstream code returning InternalErrors in some of these cases).
The simplest solution was to just put the specific dependencies into the downstream bmcweb service file. This commit combines all of those service dependencies into one commit for our P11 release.
Tested:
- Confirmed bmcweb started after required services

Add required service dependencies in downstream

---

include/cookies.hpp

Fixes 688940 
Upstream is merged at
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/68251
This was broke by a rebase with master at
[commit]: https://github.com/ibm-openbmc/bmcweb/commit/ab9a4801960fd34f53179036c86f6f3f8e1c21f6
It is already in 1120 at
https://github.com/ibm-openbmc/bmcweb/blob/1120/include/cookies.hpp#L29
d8139c68[1] added:
asyncResp->res.addHeader("Clear-Site-Data",
R"("cache","cookies","storage")");
This causes the browsers to clear the cache, cookie, and storage for that site. [2]
Don't see where OWASP recommends Clear-Site-Data response header. [3]
This seems reasonable but breaks our server manager (HMC) when using webui-vue from the HMC proxy. [4][5]
The HMC is also using the cookie and storage from the same URI. The proxy works by going to a URI and the HMC proxing …

1110: Remove cookie clear

---

config/meson.build
http/websocket.hpp
http/websocket_impl.hpp
include/obmc_shell.hpp
meson.options
src/webserver_run.cpp

This commit includes a web-based shell, making it possible to access secure shell servers through standard web browsers using WebSocket.
Path of WebSocket:
wss://{hostname}/bmc-console
Implementation:
So when bmcweb WebSocket gets a request for a new connection, it
creates a child process of bmcweb using the forking bmcweb process
(which begins a new process operating in a pseudoterminal).
Then on that pseudoterminal call exec("/bin/sh") which replaces the
current process image with a "/bin/sh" process image.
bmcweb is communicating with that child process using
stream_descriptor, similar to read write from a file descriptor,
with asynchronous ability. So the shell can execute all commands
like ls, cd, etc.
WebSocket here only acts as a mediator between child process, which
acts as a …

1120: Add BMC_SHELL web-base_shell (#483)(#473) (#936)

---

redfish-core/lib/ethernet.hpp

The error response is incorrect when a bad network id is used in /redfish/v1/Managers/bmc/DedicatedNetworkPorts/badid
After this patch the response will be resource not found for bad port id
Tested By:
curl --insecure -X GET -D headers.txt -H "X-Auth-Token: $bmc_token" https://${bmc_ip}/redfish/v1/Managers/bmc/DedicatedNetworkPorts/badid
Observed Result
404 Not Found

Fix 692953: Fix in error response path network port

---

include/ibm/locks.hpp
include/ibm/management_console_rest.hpp
test/include/ibm/configfile_test.cpp
test/include/ibm/lock_test.cpp

This commit adds all the usecases of /ibm/v1
1. ConfigFile multipart update
2. Lock management fixes
3. SignCSR feature for VMI interface
4. Broadcast message event

Rebase: 1120 Add ibm/v1 route features

---

http/http_request.hpp
redfish-core/include/query.hpp
redfish-core/lib/update_service.hpp

https://github.com/ibm-openbmc/bmcweb/pull/1248 is the 1120 
2 commits: 
1)  Pull in https://github.com/ibm-openbmc/bmcweb/pull/1176 
The commit https://github.com/ibm-openbmc/bmcweb/commit/102a4cdacb0a6d8c8c3c97e10bedbb66000ac5dc [1] changes Request as shared_ptr<Request>, but handleIfMatch() still does the full copy of Request with If-Match with non-empty ETag [2], whether ETag matches or not.
For example,
curl   -k -X GET https://${bmc}/redfish/v1/AccountService/Accounts/readonly -etag-save etag.out
ETAG=`cat etag.out`;  echo $ETAG
redfishtool.py raw -r ${bmc} -u ${user} -p ${pass} \
-S Always PATCH /redfish/v1/AccountService/Accounts/readonly \
--data='{"RoleId":"Administrator"}'
Or,
curl   -k -H "Content-Type: application/json" -H "If-Match:${ETAG}" \
-X PATCH …

Remove body after code update write

---

http/http_request.hpp
redfish-core/include/query.hpp
redfish-core/lib/update_service.hpp

https://github.com/ibm-openbmc/bmcweb/pull/1240 is 1110 
2 commits:
Pull in 
https://github.com/ibm-openbmc/bmcweb/pull/1176
The commit https://github.com/ibm-openbmc/bmcweb/commit/102a4cdacb0a6d8c8c3c97e10bedbb66000ac5dc [1] changes Request as shared_ptr, but handleIfMatch() still does the full copy of Request with If-Match with non-empty ETag [2], whether ETag matches or not.
For example,
curl -k -X GET https://${bmc}/redfish/v1/AccountService/Accounts/readonly -etag-save etag.out
ETAG=cat etag.out; echo $ETAG
redfishtool.py raw -r ${bmc} -u ${user} -p ${pass}
-S Always PATCH /redfish/v1/AccountService/Accounts/readonly
--data='{"RoleId":"Administrator"}'
Or,
curl -k -H "Content-Type: application/json" -H "If-Match:${ETAG}"
-X PATCH …

1120: remove body after code update write

---

redfish-core/lib/pcie.hpp

This commit publishes Name under PCIeDevice schema.
Test:
```
Redfish Validator was executed and no new error was found.
{
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/
chassis_motherboard_pcieslot12_pcie_card12",
"Id": "chassis_motherboard_pcieslot12_pcie_card12",
"Links": {
"Oem": {
"IBM": {
"@odata.type": "#IBMPCIeDevice.v1_0_0.PCIeLinks",
"PCIeSlot": {
"@odata.id": "/redfish/v1/Chassis/chassis/PCIeSlots"
}
}
}
},
"Name": "USB 3.0 port (front)",
"Oem": {
"IBM": {
"@odata.type": "#IBMPCIeDevice.v1_0_0.IBM",
"LinkReset": false
}
},
"PCIeFunctions": {
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/
chassis_motherboard_pcieslot12_pcie_card12/PCIeFunctions"
},
"PCIeInterface": {
"LanesInUse": null
},
"Slot": {
"Location": { …
```

Publish Name under PCIeDevice schema

---

Redfish.md
redfish-core/lib/environment_metrics.hpp

This is a cherry-pick of two commits:
- eb83b29 - Add PowerLimitWatts in EnvironmentMetrics
- a2f6f88 - Update to use power cap limits from CapLimits instead of Cap (https://github.com/ibm-openbmc/bmcweb/pull/1113). **Note**: For this commit only the part for the PowerLimitWatts was pulled in since the PowerSubsystem is not yet in 1120.
Additional changes made:
- Moved long lambda functions into named functions per current upstream coding requirements.
- Used Redfish generated enums.
Tested on hardware simulator after powering on. Redfish validator passes for PowerLimitWatts with no related warnings.
PowerLimitWatts is a new object in Redfish version 2021.2.
This property shall contain the power limit control for corresponding resource.
It contains …

Add PowerLimitWatts in EnvironmentMetrics

---

redfish-core/include/utils/sw_utils.hpp
redfish-core/lib/update_service.hpp

Upstream: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/72224
A Minimum Version interface was added.[1] This is the minimum software version that a component must have to operate. Like other interfaces it is optional. MinimumVersion maps to Redfish's LowestSupportedVersion.[2]
"LowestSupportedVersion": {
"description": "The lowest supported version of this software.",
"longDescription": "This property shall represent the lowest
supported version of this software.  This string is formatted using the same format used for the `Version` property.",
"readonly": true,
"type": [
"string",
"null"
],
"versionAdded": "v1_1_0"
phosphor-bmc-code-mgmt has support for minimum version.[3]
phosphor-bmc-code-mgmt logs a Software Incompatible[4] error if this minimum version is not met. Mapping this error …

Software: Add LowestSupportedVersion

---

redfish-core/lib/memory.hpp

Look for OperationalStatus for the memory Health.
When functional is false, health is critical.
When functional is true, health is ok.
Set the dimm0 OperationalStatus to false, and see the health:
```
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Systems/system/Memory/dimm0
{
"Status": {
"Health": "Critical",
}
}
```

1120: Redfish : Look for OperationalStatus for the memory Health

---

config/meson.build
meson.options
redfish-core/lib/log_services.hpp
redfish-core/lib/systems_logservices_hwisolation.hpp
redfish-core/src/redfish.cpp

- In an OpenPOWER based system, a user or an application (in the error path if the hardware is faulty) can isolate hardware and the respective isolated hardware part will be ignored to init during the next boot of the host.
- The isolated hardware details are stored in BMC and a user may need to get that information through an external interface.
- In this patch, added a new HardwareIsolation LogService to get or manage the isolated hardware.
- This HardwareIsolation feature can be enabled by using the "hw-isolation" compile-time feature flag. It is enabled by default.
Other Reference:
- Design document for hardware isolation (aka guard) https://github.com/openbmc/docs/blob/master/designs/guard-on-bmc.md
Tested:
- Checked whether the HardwareIsolation LogService is showing in …

hw-isolation rebase: Added HardwareIsolation service

---

redfish-core/lib/pcie.hpp

The commit publishes Location code  under PCIeDevice schema.
Validator was executed and no new error was found.
Test:
curl -k -H "X-Auth-Token: $bmc_token" -X GET "https://${BMC_IP}/redfish/v1/Systems/system/PCIeDevices/chassis_motherboard_pcieslot0_pcie_card0" {
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/chassis_motherboard_pcieslot0_pcie_card0",
"Id": "chassis_motherboard_pcieslot0_pcie_card0",
"Oem": {
"IBM": {
"@odata.type": "#IBMPCIeDevice.v1_0_0.IBM",
"LinkReset": false
}
},
"PCIeFunctions": {
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/chassis_motherboard_pcieslot0_pcie_card0/PCIeFunctions"
},
"PCIeInterface": {
"LanesInUse": null
},
"Slot": {
"Location": {
"ServiceLabel": "U78DA.ND0.WZS003T-P0-C0" …

Publish Location code under PCIeDevice schema (#1083)

---

meson.options
redfish-core/include/utils/dbus_event_log_entry.hpp
redfish-core/lib/log_services.hpp
redfish-core/lib/systems_logservices_celog.hpp
redfish-core/schema/oem/ibm/json-schema/IBMLogEntryAttachment.v1_0_0.json
redfish-core/schema/oem/openbmc/csdl/OpenBMCLogEntry_v1.xml
redfish-core/schema/oem/openbmc/json-schema/OpenBMCLogEntry.json
redfish-core/schema/oem/openbmc/json-schema/OpenBMCLogEntry.v1_0_0.json
redfish-core/schema/oem/openbmc/meson.build
redfish-core/src/redfish.cpp
test/redfish-core/include/dbus_log_watcher_test.cpp

Pull PEL related EventLog changes into 1110 (#905)
* bmcweb: Add support for CE Event Log
This commit allows users of any privilege to access Event Log entries
with 'Hidden' property set to false. The Log entries with 'Hidden'
property set to true are only accessed by users with admin role.
This commit is for downstream only
Testing:
Used P11 bring-up openbmc and upstream bmcweb. User Authentication was
disabled.
```
$ curl -k http://${bmc}/redfish/v1/Systems/system/LogServices
```
Note: Does not show URI to CELog due to an explicit check on whether
the requested operation is allowed with specified privileges. The
specified privilege 'ConfigureManager' is not allowed, and the entry
is not shown.
```
$ curl -k http://${bmc}/redfish/v1/Systems/system/LogServices/EventLog
{
...
"DateTime": …
```

1120: Pull PEL related EventLog changes (#905)

---

redfish-core/lib/log_services.hpp

This change ensures that resource dump creation requests are permitted to admin and service user — specifically, a user with the "priv-oemibmserviceagent" and "priv-admin" privilege.
Admin users must be allowed to issue resource dumps without any password string, and PHYP checks their authority based on the exact macro they invoked.
Requests from any other users will be denied with an "Insufficient Privilege" error response from bmcweb.
The rationale behind this restriction is that resource dumps are intended solely for debugging issues in resources of the host, which are to be collected exclusively by service user. As such, access is limited to service und admin sers and explicitly restricted for all others.
Tested By:
[1] POST https://${bmc}/redfish/v1/Systems/system/LogServices/Dump/Act …

Restrict Resource Dump Creation to service user

---

config/meson.build
meson.options
redfish-core/lib/chassis.hpp
redfish-core/lib/health.hpp

This reverts commit 7ac13cc939beaf9a2a7af870ba9b5650c98e409e.
This reverts the health.hpp commit and adds it to chassis (The only place use it)

1120: Add HealthRollup support for Chassis 
