ibm-openbmc/bmcweb

include/sessions.hpp
if the role is not found in the in memory user role map.
For the local users, the user role map is kept hot in memory
and further changes are tracked using dbus match object.
For the remote users, get the role from the user manager module,
which abstracts how the remote user details are stored and retrieved.
Tested:
-   Created a local user having admin privilege and verified that he is
able to restart the system
/redfish/v1/Systems/system/Actions/ComputerSystem.Reset
-d '{"ResetType": "GracefulRestart"}'
-   Created a local user having user privilege and verified that he is
unauthorized to restart the system
/redfish/v1/Systems/system/Actions/ComputerSystem.Reset
-d '{"ResetType": "GracefulRestart"}'
-   Created a remote user having admin privilege and verified that he is
able to restart …
=> Updated UserRoleMap::getUserRole() to call GetUserInfo()

crow/include/crow/http_connection.h, include/logging_middleware.hpp
Handled a few more review comments.
Still working on getting the routes to
define whether or not traffic on that route
should be logged.
Change-Id: Ia54e1964b8954b3a1941be0f9f6c1e301bec6694
=> Some updates to bmcweb logging

redfish-core/include/redfish.hpp, redfish-core/lib/chassis.hpp, redfish-core/lib/sensors.hpp
Redfish implementation of SensorCollection. This is a collection of all power and current sensors.
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/22496/
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/22496/
Testing:
Verified SensorCollection and Sensor output on a Witherspoon system.
Verified no errors from RedfishServiceValidator.
=> bmcweb: Implement SensorCollection

redfish-core/lib/chassis.hpp, redfish-core/lib/sensors.hpp
This addresses changes made in:
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/22496/
Revisions Included: 13 -> 16
Signed-off-by: Anthony Wilson <wilsonan@us.ibm.com>
=> bmcweb: SensorCollection code review update

redfish-core/lib/sensors.hpp
Added scaling for Threshold properties in SensorCollection
This addresses changes made in:
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/23699
Revisions Included: 15 -> 17
Signed-off-by: Anthony Wilson <wilsonan@us.ibm.com>
=> bmcweb: Add Threshold property scaling

redfish-core/lib/sensors.hpp
This address changes made in:
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/22496/
Revisions included: 17 -> 18
Signed-off-by: Anthony Wilson <wilsonan@us.ibm.com>
=> bmcweb: SensorCollection update

redfish-core/include/redfish.hpp, redfish-core/lib/certificate_service.hpp, redfish-core/lib/managers.hpp
Incorporate changes done in master related to GenerateCSR
Link to gerrit code changes
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/19421/56..66
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/21650/44
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/21654/44
=> Bmcweb changes for generating CSR from master

redfish-core/lib/systems.hpp
The IndicatorLED at /redfish/v1/Systems/system does not work and
has never worked.
The problem is it calls xyz.openbmc_project.LED.Controller.identify
which IBM does not use.
https://github.com/openbmc/bmcweb/blob/944ffaf9ccae2a084cd650370facfb3f76701186/redfish-core/lib/systems.hpp#L650
With OP940 closing in and this not being a needed Redfish Property,
remove for now.
https://github.com/ibm-openbmc/dev/issues/1202 tracks fixing
this. Will leave the defect open but defer out of OP940 if
this workaround is accepted.
Tested: Loaded bmcweb on a Witherspoon. System Resource looks
good as do others.
=> SW474357: Remove not working Server Identify LED

redfish-core/lib/ethernet.hpp, static/redfish/v1/schema/EthernetInterface_v1.xml
FallbackAddress property added in latest schema.
we need this latest schema to support link local fallback option
Signed-off-by: raviteja-b <raviteja28031990@gmail.com>
Change-Id: Ic4749f8701c60b52835f198dce629cf228e83846
=> Redfish: Update EthernetInfterface schema to EthernetInterface.v1_5_1

include/kvm_websocket.hpp
Currently, bmcweb allows just one KVM session. To make it support
multiple concurrent KVM sessions, this commit adds KVM session class
implementation. It limits the number of sessions to 4 to secure the
connection quality.
Tested: Up to 4 concurrent KVM sessions worked.
Change-Id: I37342ba2e30f840131d6287b4249a298aa17a1f1
Signed-off-by: Jae Hyun Yoo <jae.hyun.yoo@linux.intel.com>
Signed-off-by: LuluTHSu <Lulu_Su@wistron.com>
=> Add concurrent KVM sessions support

http/routing.hpp, redfish-core/lib/event_service.hpp, redfish-core/lib/hypervisor_system.hpp
=> fix CI issues in ibm forked bmcweb

redfish-core/lib/bios.hpp
Since the P10 system has BMC to manage the BIOS attributes,
and bmcweb does not know the attribute values of the BIOS,
it should allow the host to be able to set BIOS readOnly
attributes, while the redfish-doPATCH operation should not
be allowed.
With this change, when a redfish command to update a bios
attribute (which is read-only), is fired, bmcweb will send
the error back to the client.
Tested By:
Updation of read-only attr:
-X PATCH https://${bmc}/redfish/v1/Systems/system/Bios/Settings -d '{"Attributes":{"hb_debug_console":"Disabled"}}'
{
"hb_debug_console@Message.ExtendedInfo": [
{
"Message": "The property hb_debug_console is a read only property and cannot be assigned a value.",
"hb_debug_console"
],
"MessageId": …
=> Restrict patching of read-only bios attributes

include/ibm/management_console_rest.hpp
Since the REST API that maps directly to D-Bus API's is being
deprecated, This interface[1] should be under the /ibm/v1 namespace.
[1]: https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/yaml/org/open_power/OCC/PassThrough.interface.yaml
Tested:
1. enabled ibm-management-console
2. curl -k -H "X-Auth-Token: $token" -X POST
https://${bmc}/ibm/v1/OCC/Control/occ0/Actions/PassThrough.Send -d
'{"Send": [100,200]}'
=> ibm: Move OCC pass through REST api under /ibm/v1 namespace

redfish-core/include/utils/name_utils.hpp, redfish-core/lib/chassis.hpp, redfish-core/lib/processor.hpp, redfish-core/lib/storage.hpp, redfish-core/lib/update_service.hpp
Created this PR to pull upstream patch (https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/43967/18) to address the below comments.
- https://github.com/ibm-openbmc/bmcweb/pull/76/commits/e24e24bb4345617c907e4942428cd175e7e89a07#r705862703
- https://github.com/ibm-openbmc/bmcweb/pull/77#issuecomment-918159390
=> util: Add pretty name for resources

redfish-core/lib/update_service.hpp
There are apparently places where we make complete copies of the request
structure, including the body data within it.  Recently,
59b98b2222fddbea3d6f678d9e94006521f0c381 came along and made the size of
the Request structure include the body payload.  This is good for object
ownership, but bad for code that wants to make a copy.
This commit tries to do something less insane, and construct the Payload
object (which only really includes the http headers, uri and method)
before jumping into callback hell, thus meaning that the Payload object
is copied 4 times instead of the Request object.
Tested:
Code compiles.  Deleted the boost::beast::http::message copy
constructor, and observed that new code now compiles without needing a
copy.
Signed-off-by: Ed Tanous <edtanous@google.com>
Change-Id: …
=> Make fewer copies

meson.build, meson_options.txt, redfish-core/include/redfish.hpp, redfish-core/lib/log_services.hpp
Created this PR to fix a bunch of conflicts which are got after rebased the upstream bmcweb into ibm-openbmc/bmcweb/1020
**Note:** In this PR, addressed all the comments (few are clarification) which are posted in https://github.com/ibm-openbmc/bmcweb/pull/76 - Please refer [here](https://github.com/ibm-openbmc/bmcweb/pull/76) to get to know the comments history.
=> Added new LogServices for Hardware Isolation (aka Guard) feature

redfish-core/lib/fan.hpp, redfish-core/lib/pcie_slots.hpp, redfish-core/lib/power_supply.hpp
This PR adds location code information for PcieSlots, Fans and PowerSupplies. Upstream commits are here:
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/46591 for PcieSlots
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/41086 for Fans
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/40326 for PowerSupplies
=> Location Code For PCIeSlots, Fans and Power Supplies

redfish-core/lib/log_services.hpp, scripts/update_schemas.py, static/redfish/v1/$metadata/index.xml, static/redfish/v1/JsonSchemas/OemLogEntry/index.json, static/redfish/v1/schema/OemLogEntry_v1.xml
A new property is added to support hmc ack
=> HMC ack support added for LogEntry

redfish-core/include/registries/openbmc_message_registry.hpp, redfish-core/lib/bios.hpp
This fixes issues we are seeing after the -31 rebase 
=> Fix compilation issues after -31 rebase

redfish-core/lib/hypervisor_system.hpp
This PR has the fix for the following defects:
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW538538 (FW1020 Rainier: Redfish Validator error for hypervisor ethernet interfaces)
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW538507 (FW1020 Rainier VMI:Changing mode to dhcp is not enabling dhcp as true)
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW515335 (SW515335 : eBMC: Witherspoon- Tacoma - VMI does not erase dynamic IP when we switch to static mode)
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW522283 (SW522283 : eBMC: Witherspoon Tacoma -vmi IPv4Addresses read only property gets deleted with 202 status code,although throws message id PropertyNotWritable)
gerrit: 
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/45063/
Redfish Validator …
=> Resolve error in setting DHCP to true & fix validator failures

include/ibm/management_console_rest.hpp
Locks are cleaned up when there is a graceful logout /
session expiration due to timeout. But there are possibilities
of leaving stale lock entries in the BMC, if the session is
abruptly terminated.
This commit is to check for the existence of the session
whenever there is a lock conflict. If the session is not active,
remove the lock record considering that as a stale record and
return no error. If the session is active, return the lock
conflict to the client.
It fixes the following defect:
https://w3.rchland.ibm.com/projects/bestquest/?verb=view&id=SW538023&table=defect
Change-Id: I1b97895cbdc4e602e00313bfd3b59e3b3445bd59
=> Remove stale lock table entries of invalid sessionid

include/event_dbus_monitor.hpp, redfish-core/include/privileges.hpp, redfish-core/lib/chassis.hpp, redfish-core/lib/sensors.hpp
One commit in this PR is upstream at https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/48795/
The other two commits are for code that we only have in downstream.
=> 1020 reduce error traces in bmcweb

redfish-core/lib/FabricAdapters.hpp
The commit updates Fabric adapter schema to populate inventory
properties like Model, SparePartNumber, LocationCode,
PartNumber for the given adapter.
It also updates the schema to make use of prettyName to
populate name field.
=> Fabric Adapter schema update

include/event_dbus_monitor.hpp
Event log entries are split into EventLog and CELog entries
depending on Hidden property value. The event log entry paths
are different for EventLog and CELog. Current implementation
emits events with EventLog path irrespective of Hidden property
value. This commit provides log entry paths correctly for both
EventLog and CELog depending on the Hidden property value.
Testing:
- Injected INFO and ERROR events using busctl command, and verified
the paths in journal log.
Example:
bmcweb[3689]:(2021-11-30 16:41:59)[DEBUG "event_dbus_monitor.hpp":369]
EventLog path:
/redfish/v1/Systems/system/LogServices/EventLog/Entries/659
bmcweb[3689]:(2021-11-30 16:42:25)[DEBUG "event_dbus_monitor.hpp":362]
CELog path: /redfish/v1/Systems/system/LogServices/CELog/Entries/660
- HMC team verified that CELog …
=> bmcweb: CElog entry not received by HMC

redfish-core/lib/license_service.hpp
This fixes redfish license service validator errors
Tested By:
GET  
Ran redfish service validator
=> Modify LicenseService as per DMTF released schemas

redfish-core/lib/pcie.hpp, redfish-core/lib/pcie_slots.hpp
This PR implement changes to populate PCIeDevice schema with desired properties and populate link between PCIeSlot and PCIeDevice schema.
=> PCIeDevice Schema and PCIeSlot to PCIeDevice link

include/ibm/management_console_rest.hpp
This commit handles the file upload status and does the dir size
calculation for each file upload in the multipart request
Tested by:
1. Tested file upload where the middle file is of 0KB size to verify
that file and the next file upload fails with right error message
2. Tested file upload in sinlge command where total dir size can exceed
10MB. Verified that it fails with right error message
Change-Id: I43e458a30d3f97fbf181f3ea47a18fff24fbd79a
=> Multipart form data upload fixes

redfish-core/lib/environment_metrics.hpp
Environmental Metrics has an internal error.
resolved by: https://github.com/ibm-openbmc/dev/issues/3401
upstream: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/43170
Signed-off-by: Albert Zhang <zhanghaodi@inspur.com>
Change-Id: I6a75dfbc94f39d90a1368770076b874608394691
=> Fix Environmental Metrics internal Error

redfish-core/lib/pcie_slots.hpp
The commit implement channges to populate link(s) to
processor associated witha given PCIeSlot.
The association is established by fetching mapper endpoints
"upstream_processor" w.r.t given PCIeSlot.
Validator is executed and no new error has been found.
Sample Output:
{
"Lanes": 0,
"Links": {
"Processors": [
{
"@odata.id": "/redfish/v1/Systems/system/Processors/dcm0-cpu0"
}
],
"Processors@odata.count": 1
},
"Location": {
"ServiceLabel": "U78DA.ND0.WZS0042-P0-C0"
}
},
"SlotType": "FullLength"
}
}
=> Link PCIeSlots to Processor schema

redfish-core/lib/environment_metrics.hpp
=> EnvironmentMetrics: Fix Redfish Validator Error

include/event_dbus_monitor.hpp
When the system IPLs, numbers of boot progress indicators
are generated, and each code generates an event. HMC consumes
this event and displays the boot progress at HMC GUI
While sending the events, bmcweb does a costly dbus call to get
the current postcode - "GetPostCodesWithTimeStamp"
This commit removes this dbus call. This changed logic to
calculate the current postcode url while sending the event
improves the IPL time and reduces the dbus overhead
Tested by:
1. Manual IPL tests
2. IPL automation
3. GET on the postcode urls for sanity check
4. Verified that HMC displays the progress codes correctly
during each test
Change-Id: I21e26889bf32545d43394c6011bf561324927460
=> PostCode event performance improvement

include/dump_offload.hpp
Currently we store dump offload unix socket files at /var/lib.
There is no need to persist these file and persistency causing 
issues in few cases, throwing socket already in use errors after reset.
so create socket file at /tmp/DumpOffloadSockets
increase socket connect timeout and retry as well
Tested By:
BMC dump offload
System dump offload
=> Move socket files to /tmp directory

redfish-core/lib/processor.hpp
In the current state, the logic is bmcweb for displaying cores is:
It checks the Present property on core dbus object to update
the [Status][State] as Enabled/Absent.
In addition to Present property, we should also use the Available
property , if the Available is false, then set the [Status][State]
should be set as "UnavailableOffline".
Refer: https://github.com/ibm-openbmc/dev/issues/3481
=> Consume availability interface for cores

meson.build, meson_options.txt, redfish-core/lib/oem/ibm/system_attention_indicator.hpp, redfish-core/lib/systems.hpp, static/redfish/v1/JsonSchemas/OemComputerSystem/index.json, static/redfish/v1/schema/OemComputerSystem_v1.xml
Added OEM commands for platform and partition to set/get SAI
refer: https://github.com/ibm-openbmc/dev/issues/2120
=> Add set/getSystemAttentionIndicator

redfish-core/lib/power_supply.hpp
Add Firmware Version to Power Supplies schema
https://redfish.dmtf.org/schemas/v1/PowerSupply.v1_3_0.json
Tested : Validator passes.
curl -k -H "X-Auth-Token: $token" -XGET
https://${bmc}/redfish/v1/Chassis/chassis/PowerSubsystem/PowerSupplies/powersupply0
{
"@odata.id": "/redfish/v1/Chassis/chassis/PowerSubsystem/PowerSupplies/powersupply0",
"@odata.type": "#PowerSupply.v1_0_0.PowerSupply",
"EfficiencyRatings": [
{
"EfficiencyPercent": 90
}
],
"FirmwareVersion": "test-powersupplyversion-123",
"Id": "powersupply0",
"Model": "",
"Name": "powersupply0",
"PartNumber": "",
"SerialNumber": "",
"SparePartNumber": "",
"Status": {
}
}
=> Redfish : Add Firmware Version to Power Supplies

http/http_client.hpp
When the event send fails at any stage, the http client
retries to send the event again and increments the retryCount.
This is not reset to zero after the next successful send-recv
This commit resets the counter to zero and adds more error
debug traces
Tested by:
1. Successful event send usecases
2. Retry scenarios
Change-Id: Ie0b045536362908cd6bd012cd86fd1d6a975a714
=> Redfish event: Reset retryCount after successful send-recv

include/ibm/management_console_rest.hpp
This commits add CRITICAL traces for debugging VMI certificate exchange issues
=> VMI Cert:Add CRITICAL traces for debug

redfish-core/include/error_messages.hpp, redfish-core/include/utils/hw_isolation.hpp, redfish-core/src/error_messages.cpp
It fixes [SW546086](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW546086)
Gerrit patch for the first commit: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/52159
=> HW-Isolation: Return an appropriate error if the request is failed.

redfish-core/lib/log_services.hpp
On Create dump request, if the user gives invalid inputs
like invalid password/resource selector, the backend was
not returning proper dbus errors earlier.
Now with the new changes in the backend, there are proper
errors returned on create dump dbus call. This PR contains
changes that catches these errors and translates it to
proper redfish error response which will be added to the
message part of the task that is started at the time of receiving
the redfish request. The task will be cancelled with the
appropriate error.
This fixes: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW521505
Tested By:
POST https://${bmc}/redfish/v1/Systems/system/LogServices/Dump/Actions/LogService.CollectDiagnosticData -d '{"DiagnosticDataType":"OEM", "OEMDiagnosticDataType":"Resource_meminfo -pmm …
=> Add proper redfish error response for resource dumps

redfish-core/lib/fan.hpp
Modify ThermalSubsystem fan objects from sensors-based to
fan inventory FRU.
Signed-off-by: Albert Zhang <zhanghaodi@inspur.com>
=> Modify fan related bugs

include/ibm/management_console_rest.hpp
There is possibility that bmcweb may miss status property change signal
which pldmd sets.
This commit reads object status before timing out so that even though
bmcweb misses D-bus signal, still bmcweb returns certificate to client.
This commit fixes defect
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW547418
Tested by:
Verified signCSR request when host powered off
Verified signCSR request  when host is running
=> VMI Cert: Read object status before timeout request

http/http_server.hpp, include/persistent_data.hpp
Currently bmcweb_persistent_data.json file collected as part of BMC
dump, but this file does not contain all existing redfish sessions data.
This commit is to collect all sessions into bmcweb_current_session_persistent_data.json
during bmc dump creation, on receiving SIGUSR1 from dump manager.
Dump manager sends SIGUSR to bmcweb while creating bmc dump,
bmcweb catches this signal and dumps sessions data into a file.
This sessions data will be useful for debugging redfish session related issues.
Added event config and event subscriptions data along with session data
Tested by:
Kill  -10 bmcweb-pid
Check content of bmcweb_current_session_persistent_data.json
=> FFDC: Collect current in-memory sessions for BMC dump

include/event_dbus_monitor.hpp
This change sends an event to the client when
there is a method change on the vmi interface from
static to DHCP and vice versa.
This is needed because, say, when the client changes method
from static to dhcp and if the dhcp is not connected, the
client wont receive any event from bmcweb, thus the cient thinks
that the method is static on that interface.
Fixes: https://w3.rchland.ibm.com/projects/bestquest/?verb=view&id=SW548700&table=defect
Tested By:
Connected HMC and verified whether the events are
being sent.
=> Send event for VMI method change on ethernet intf

http/obmc_shell.hpp
This commit creates a terminal that allows users to log in to the
system using their session name (username), where a password is not
required. because we are passing '-f', which Does not perform
authentication; the user is pre-authenticated
This commit removes the setting user ID (Setuid), allowing users to
access the terminal.
Tested: 
tested using obmc_shell (bmcweb) and web-UI on the Rainer system. 
- Currently, any user who has access to the system can access
WebSocket.
Ex: service user can access as service (root user because it gets
converted into root user)user, Admin user can access as an admin
user, etc.
In the future, we will add prvilege check for WebSockets
=> shell support via pty to bmcweb

redfish-core/lib/fan.hpp
At present,there is no verification of chassisID in the
...redfish/v1/Chassis/chassis/ThermalSubsystem/Fans directory.
In order to display this function correctly for multiple chassis,
add the verification of chassisID.
Signed-off-by: Albert Zhang <zhanghaodi@inspur.com>
=> Add the verification of chassisID

http/app.hpp, http/obmc_shell.hpp, http/routing.hpp, include/dbus_monitor.hpp, include/kvm_websocket.hpp, include/obmc_console.hpp, include/obmc_hypervisor.hpp, include/vm_websocket.hpp
Revert due to https://w3.rchland.ibm.com/projects/bestquest/?defect=SW550265
Reopened https://w3.rchland.ibm.com/projects/bestquest/?defect=SW549923
Reverts ibm-openbmc/bmcweb#329
=> Revert "SW549923: Add Support for WebSocket privilege check"

http/app.hpp, http/http_connection.hpp, http/http_response.hpp, http/routing.hpp, http/websocket.hpp
Revert due to https://w3.rchland.ibm.com/projects/bestquest/?defect=SW550265
Reopened https://w3.rchland.ibm.com/projects/bestquest/?defect=SW549923
Reverts ibm-openbmc/bmcweb#322
=> Revert "SW549923: Add asyncResp support during handleUpgrade"

redfish-core/lib/pcie_slots.hpp
SW543568: When we have more than one chassis in the system, the code
would wrongly compare the total number of slots across all the chassis
to the number of slots in the PATCH request's payload (which is for a
specific chassis). This would cause the PATCH to fail without any
error.
This commit fixes the count check by properly counting the slots that
don't belong in the chassis of interest.
Tested:
Tested this on a system with Mex chassis and a CEC chassis.
Verified that the PATCH on LocationIndicatorActive now works fine
even when we have two chassis trees on D-Bus.
=> Fix PCIe Slot Count Check

redfish-core/lib/license_service.hpp
Currently pldmd listens for LicenseString property change signal
and forwards license string to phyp.
This commit resets LicenseString and LicenseActivationStatus after request completed.
so that for further requests licenseString property change signal generated.
Increased  timeout to 20 sec to wait for response from pldmd
There are cases where phyp response arrives between 10-20 secs
This PR Fixes https://w3.rchland.ibm.com/projects/bestquest/?defect=SW544557
MUST FIX approved
Tested:
1. Upload new license key and check if its installed.
2. Upload same license key again and check if user got success
instead of error
=> Reset LicenseString and Status property after request completed

redfish-core/lib/pcie.hpp
This commit allows us to retrieve the PCIeSlot path from the PCIeDevice.
The old code was trying to retrieve the PCIe device name from the dbus path.
That functionality gets disabled because one of the patches updates the PCIe Device naming mechanism.
Tested:
```
curl -k -H 'X-Auth-Token: $bmc_token' -X GET https://${BMC_IP}/redfish/v1/Systems/system/PCIeDevices/motherboard_disk_backplane0_nvme2_dp0_drive2
{
"@odata.id": ["/redfish/v1/Systems/system/PCIeDevices/motherboard_disk_backplane0_nvme2_dp0_drive2"](https://rain118bmc.aus.stglabs.ibm.com:18080/redfish/v1/Systems/system/PCIeDevices/motherboard_disk_backplane0_nvme2_dp0_drive2),
"Id": "motherboard_disk_backplane0_nvme2_dp0_drive2",
"Name": "NVMe Drive",
"Oem": { …
```
=> Map PCIeSlot path with PCIeDevice

redfish-core/lib/FabricAdapters.hpp
Partially fix SW551681. This adds additional, pretty standard Redfish properties:
...
"Status": {
}
These properties were already out on D-Bus some of the time. (@manojkiraneda could explain why we didn't have Status all the time.)
Did not do a default Status Health/State.
FabricAdapters isn't upstream today but we should get it in upstream and
this could follow.
Still need to figure out how to do LocationIndicatorActive (not in https://redfish.dmtf.org/schemas/FabricAdapter.v1_3_0.json so would have to be OEM)
Tested: Saw these properties and ran the validator.
=> FabricAdapters: Add Status State and Health

redfish-core/lib/hypervisor_system.hpp
This commit adds "StatelessAddressAutoConfig" support. This option,
when enabled from Redfish, will enable ipv6 stateless auto
configuration on that interface.
Tested by:
GET
PATCH -d '{"StatelessAddressAutoConfig": { "IPv6AutoConfigEnabled": true}}'
PATCH -d '{"StatelessAddressAutoConfig": { "IPv6AutoConfigEnabled": false}}'
Change-Id: If4332a70d56cc14b482ed17ce649ddd04388779c
=> ADD hypervisor IPv6 SLAAC support

include/ibm/management_console_rest.hpp, include/login_routes.hpp, include/multipart_parser.hpp, include/ut/multipart_test.cpp
This fixes [SW557058]
Tested by:
1. Upload multiple config files 
2. Upload single config file
=> Multipart parser fix

meson.build, meson_options.txt, src/webserver_main.cpp
Create a Meson build option to enable and disable event subscription at /subscribe. By default, this is enabled
=> 1040: Create Event Subscription meson build option

redfish-core/lib/FabricAdapters.hpp
Defect sw551681: add missing LocationIndicatorActive for MEX CMC and fanout modules. Added GET and PATCH for LocationIndicatorActive. The GUI will add support for this on the inventory page. This was added to Fabric adapters in 1_4_0.
Tested: Redfish Validator didn't introduce any new errors. Used curl to test PATCH setting LocationIndicatorActive property.
This should go into 1030 as well.
Signed-off-by: Frank Nichols <nichols3.fn@gmail.com>
=> Fabric adapter: Add LocationIndicatorActive

redfish-core/lib/assembly.hpp
When bmcweb is told the RTC battery is replaced after a CM operation, set the Functional property on its assembly object path back to true before restarting the adcsensor daemon.
This does two things:
1) Causes the fault LED to turn off
2) Sets the Redfish representation back to healthy so the web UI doesn't
show it has unhealthy it after the CM operation.  Of course if
adcsensor detects an error again it would go back to unhealthy.
Since this is handling the fault LED, the previous code that explicitly turned off the fault LED group was removed.
Defect PE00DX9W.  For 1030.10
Signed-off-by: Matt Spinler <spinler@us.ibm.com>
=> Set Functional property after battery CM

http/obmc_shell.hpp
This commit provides BMC console with root shell instead of
regular user shell. It also sets the privilege to oemIBMPerformService.
=> Retrieve Xterminal using username

static/redfish/v1/schema/OemSession_v1.xml
This commit replaces Oem Session schema properties to ComplexType
Co-authored-by: Abhishek Patel <Abhishek.Patel@ibm.com>
=> bmcweb: replace EntityType to ComplexType

redfish-core/lib/hypervisor_system.hpp, redfish-core/lib/systems.hpp
This commit enables hypervisor network configuration support that allows user to create, delete and patch hypervisor network config propertiesvia redfish
=> Add hypervisor n/w config support

redfish-core/lib/log_services.hpp
This is a cherry-pick of
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/46886 with heavy modification for downstream. The heavy modification was needed because we have this separate CElog and we already had this bool ServiceProviderNotify support.
This is needed because we picked up 3c7b858a in a recent rebase. https://github.com/ibm-openbmc/phosphor-dbus-interfaces/commit/3c7b858a13aa5fde934d6d789c9a6027490f78dc
And the phosphor-logging change as well.
https://github.ibm.com/openbmc/openbmc/commit/9540c8a68ef3e177cb3cf3d87304e9a7c96178b1#diff-2f4a5d3a11e1bd59bb17797d11c691e415dd4dfd4279facd279d840b6617d2ca
Routes like /redfish/v1/Systems/system/LogServices/CELog were getting an internalError.
The journal:
```
eb 01 17:38:16 xxx bmcweb[1808]: (2023-02-01 17:38:16) [CRITICAL …
```
=> Move to ServiceProviderNotify enum

meson.build, meson_options.txt, redfish-core/include/error_messages.hpp, redfish-core/include/license_messages.hpp, redfish-core/include/redfish.hpp, redfish-core/include/registries/license_message_registry.hpp, redfish-core/lib/license_service.hpp, redfish-core/lib/message_registries.hpp, redfish-core/lib/service_root.hpp, redfish-core/src/error_messages.cpp, scripts/parse_registries.py, static/redfish/v1/odata/index.json, test/redfish-core/lib/service_root_test.cpp
This commit implements LicenseService support and LicenseRegistry support
This is IBM only Downstream implementation 
Tested By: 
POST https://{bmc}/redfish/v1/LicenseService/Licenses -d '{"LicenseString": "CA1F000000412C200000gyLzCwvb3rRUTg"}'
 { 
"error": { "@Message.ExtendedInfo": [ { "@odata.type": "#Message.v1_0_0.Message", "Message": "Indicates that the license is not applicable to the target.", "MessageArgs": null, "MessageId": "License.1.0.0.notApplicableToTarget", "Resolution": "None.", "Severity": "Critical" } ], "code": "License.1.0.0.notApplicableToTarget", "message": "Indicates that the license is not applicable to the     target." }
 }  
POST https://{bmc}/redfish/v1/LicenseService/License -d '{"LicenseString": "CA1F000000412C200000gyLzCwvb3rRUT1"}' 
{ 
"error": …
=> Add LicenseService support

redfish-core/lib/systems.hpp
This commit is added get and set for StopBootOnFault Policy. The StopBootOnFault is defined in ComputerSystem(boot). It contains two values "Never" and "AnyFault".
ref:https://redfish.dmtf.org/schemas/v1/ComputerSystem.v1_15_0.json
Tested:
1.Validator passes
2.doGet method to get StopBootOnFault.
https://${bmc}/redfish/v1/Systems/system
{
"Boot": {
...
"RemainingAutomaticRetryAttempts": 3,
"StopBootOnFault": "Never",
"TrustedModuleRequiredToBoot": "Disabled"
}
...
}
3. doPatch method set the "StopBootOnFault" property to AnyFault or Never and report error when set to other values
'{ "Boot" …
=> 1050 Add support for redfish StopBootOnFault

include/ibm/management_console_rest.hpp
Since the REST API that maps directly to D-Bus API's is being deprecated, This interface[1] should be under the /ibm/v1 namespace.
[1]: https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/yaml/org/open_power/OCC/PassThrough.interface.yaml
Tested:
1. enabled ibm-management-console
2. curl -k -H "X-Auth-Token: $token" -X POST https://${bmc}/ibm/v1/OCC/Control/occ0/Actions/PassThrough.Send -d '{"Send": [0,0,1,32]}'
ai 784 67 0 0 3 11 195 0 3 0 3 0 0 0 0 0 0 0 0 0 0 0 111 112 95 57 52 48 95 50 48 49 48 50 48 97 0 0 83 69 78 83 79 82 5 1 84 69 77 80 0 2 6 27 0 0 0 17 0 30 0 0 0 20 0 30 0 0 0 23 0 30 0 0 0 26 0 29 0 0 0 29 0 29 0 0 0 32 0 29 0 0 0 35 0 29 0 0 0 38 0 30 0 0 0 41 0 30 0 0 0 44 0 30 0 0 0 47 0 30 0 0 0 50 0 30 0 0 0 53 0 30 0 0 0 56 0 30 0 0 0 71 0 29 0 0 0 74 0 30 0 0 …
=> 1050: Move OCC pass through REST api under /ibm/v1 namespace

redfish-core/lib/assembly.hpp
Status::State reflects the presence status of FRU being populated in the schema.
"Enabled" state that FRU is present.
"Absent" implies that device is not present.
Validator was executed and no new error was found.
=> Update Assembly Schema To Populate Status::State

redfish-core/lib/assembly.hpp
Redfish : Implement LocationIndicatorActive for Assembly
1030: https://github.com/ibm-openbmc/bmcweb/commit/4adb3a8ecfaabb636e3ecf5942907a196642c740
Upstream :  https://gerrit.openbmc.org/c/openbmc/bmcweb/+/42441
Implement LocationIndicatorActive for Assembly schema, We can use locationindicatoractive to set or get the status of the location led of each Assembly.
1、Get LocationIndicatorActive
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Chassis/chassis/Assembly
{
"Assemblies": [
{
"@odata.id": "/redfish/v1/Chassis/chassis/Assembly#/Assemblies/0",
"MemberId": "0", …
=> Implement LocationIndicatorActive for Assembly

redfish-core/lib/assembly.hpp
Look for the OperationalStatus to set the Assembly Health. 
If the OperationalStatus is false, then set the Health to "Critical" 
If the OperationalStatus is true, then the Health is "OK"
upstream:
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/50317
=> Redfish: Implements Redfish Assembly Health

redfish-core/lib/systems.hpp, static/redfish/v1/JsonSchemas/OemComputerSystem/index.json, static/redfish/v1/schema/OemComputerSystem_v1.xml
Add indicator when OCCs are in safe mode.
Tested: occ reset to safe mode, curl cmd or GUI see flag
Change-Id: Iee4493da81c0d40ec3a902e54f2f9bc086f82902
=> Add safe mode to user interface

redfish-core/lib/memory.hpp
Look for OperationalStatus for the memory Health.
When functional is false, health is critical.
When functional is true, health is ok.
No upstream commit. 1020 PR: https://github.com/ibm-openbmc/bmcweb/pull/152
Set the dimm0 OperationalStatus to false, and see the health: curl -k -H "X-Auth-Token: $token" -X GET
https://${bmc}/redfish/v1/Systems/system/Memory/dimm0 {
"Status": {
"Health": "Critical",
}
}
=> 1050: Redfish : Look for OperationalStatus for the memory Health

redfish-core/lib/oem/ibm/lamp_test.hpp
This commit pulls the following commits into 1050
a1b2b76 Trigger panel lamp test
893571c SW541807:Changing error to debug trace for lamp test
Tested and code works as expected.
=> 1050:Pull lamptest related commits to 1050

redfish-core/lib/cable.hpp
This commit adds a downstream/upstream port, downstream/upstream resource, and downstream/upstream chassis link into the cable JSON response, which represents an association between resources associated via cables for williwakas and cable cards.
Upstream: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/61122
(More discussion is in https://github.com/ibm-openbmc/dev/issues/3533)
Tested using a rainier system and run Redfish-Service-Validator/ both pass
```
$ curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Cables/dp0_cable0
{
"@odata.id": "/redfish/v1/Cables/dp0_cable0",
"CableType": "",
"Id": "dp0_cable0",
"Links": {
"DownstreamPorts": [
{
"@odata.id": …
```
=> 1050: PCIe Topology Cable Links (#338)

redfish-core/lib/pcie_slots.hpp
This commit adds PCIeSlot to NVMe backplane assembly link. The link is listed in Oem property for each of the configured PCIe slots.
This is downstream only.
Issue: https://github.com/ibm-openbmc/dev/issues/3535
Testing:
- Validator PASSED
- List properties for all PCIe Slots
```
$ curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots
{
"Slots": [
{
"Lanes": 0,
"Links": {
"Oem": [
{
"@odata.id":
"/redfish/v1/Chassis/chassis/Assembly#/Assemblies/24"
}
],
{
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/drive0"
}
]
},
},
...
}
$ curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis/Assembly#/Assemblies/24
{
...
{
"@odata.id": …
```
=> 1050: bmcweb: Add PCIeSlot to Associated assembly link (#343)

redfish-core/lib/memory.hpp
- Add the getLocationIndicatorActive method and the setLocationIndicatorActive method to bmcweb to support the LocationIndicatorActive property for memory.
Tested: Validator passes
https://${bmc}/redfish/v1/Systems/system/Memory/dimm0 {
"@odata.id": "/redfish/v1/Systems/system/Memory/dimm0",
"@odata.type": "#Memory.v1_11_0.Memory",
"Id": "dimm0",
...
}
'{"LocationIndicatorActive":true}'
https://${bmc}/redfish/v1/Systems/system/Memory/dimm0
https://${bmc}/redfish/v1/Systems/system/Memory/dimm0 {
"@odata.id": "/redfish/v1/Systems/system/Memory/dimm0",
"@odata.type": "#Memory.v1_11_0.Memory",
"Id": "dimm0", …
=> 1050: Implement LocationIndicatorActive for Memory resource

redfish-core/lib/processor.hpp
Implement SubProcessors for processor core
Implement LocationIndicatorActive for CPU resource
Consume availability interface for cores
=> 1050 Add SubProcessors and CpuCore

redfish-core/lib/systems.hpp, static/redfish/v1/schema/OemComputerSystem_v1.xml
Code passes validator
Change-Id: I0ad58da48a2866724d98fddf0255f53154cd3003
=> Fix path for OEM property SafeMode

redfish-core/lib/log_services.hpp
This fixes MalformedJSON errors when trying to patch the Resolved or ManagementSystemAck properties in an EventLog or CELog.
The first 8 bytes of the request JSON data in the Request structure was corrupt if it was read after an async D-Bus method call.  Testing showed that up until the method call was made, it was fine.
This commit changes the code to access that patch data earlier, before any D-Bus calls are made.  This makes it similar to how it was done for the Resolved property in the upstream code.
The code had been refactored when the CELog entries were added downstream to give more commonality, and that is where the change had been made to read the patch JSON data after reading the Hidden property on D-Bus.  It did work fine then though, and it also even worked when the commits …
=> Read patch data earlier during an event log patch

redfish-core/lib/account_service.hpp
This commit enhances the redfish API to set and unset userGroups information for each user account.
UserGroups retrieve data are "redfish", "ssh", "web", and "ipmi", where redfish DMTF Schema has predefined enum type as described below.
```
"AccountTypes": {
"enum":["Redfish", "SNMP", "OEM", "HostConsole", "ManagerConsole",
"IPMI", "KVMIP", "VirtualMedia", "WebUI"]
}
```
Users with ConfigureUsers level privilege can patch (Set and Unset) AccountTypes of each user role. In addition, a user with "ConfigureSelf" level privilege can only set or Update their password.
"Redfish" is always enabled in each user role. However, "ConfigureUsers" can disable other user redfish services. But if "ConfigureUsers" try to disable its redfish service, that generates an error.
"ssh" userGroup has to be …
=> 1050: GET PATCH userGroups Information ("AccountTypes") (#270)(#284)

redfish-core/lib/ethernet.hpp
This commit has following changes
1.Adds "StatelessAddressAutoConfig"
support as per latest EthernetInterface.v1_8_0 schema. 2.Update schema version to EthernetInterface.v1_8_0 3.Remove support for deprecated Stateful and Stateless enums of DHCPv6 "OperatingMode"
Tested by:
GET PATCH -d '{"StatelessAddressAutoConfig": {"IPv6AutoConfigEnabled": true}}' PATCH -d '{"StatelessAddressAutoConfig": { "IPv6AutoConfigEnabled": false}}' PATCH -d '{"DHCPv6" : {"OperatingMode":"Enabled"}}' PATCH -d '{"DHCPv6" : {"OperatingMode":"Disabled"}}'
Redfish Validator passed
Change-Id: I29d471750ef513074bc5e49c31a16fa15d3d760c
=> Add IPv6 StatelessAddressAutoConfiguration

redfish-core/lib/environment_metrics.hpp
This adds the chassis association to the environment metric fans to ensure the fans belong to that chassis. E.g. CEC fans don't show up for i/o expansion drawer chassis 
Defect: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=457136
Port to 1020, 1040
The 1050 will be separate
Upstream is https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57715
resolved: https://github.com/ibm-openbmc/dev/issues/3619
=> 1030: Fix environment metrics should chassis association

redfish-core/lib/pcie.hpp
There are a few issues in the current 1050 pcie.hpp.
First, it uses a global variable to keep all PCIeDevices, and it is constructed and populated only once.
Any consecutive PCIeDevice interactions will use it. As the result, if a new device is added/discovered later, it will not be found via bmcweb.
Even after the fix of this gobal variable,
the code invokes the unnecessary and excessive calls of GetSubTree.
For example,
```
void getPCIeDevices()
{
GetSubTree(pcieInterace)
...
getAllDProperties()
addLinkStatusToPcieDevice()
{ This again go thru GetSubTree() to find pcieSlot <==
findPcieSlotServiceMap() to get pcieSlot info }
}
```
This can be optimized as
```
void getPCIeDevices()
{
GetSubTreePaths() to find a device & pcieSlot name
GetObject => serviceName
GetAllObject for its …
```
=> 1050: Fix and Refactor PCIeDevice handling

redfish-core/lib/ethernet.hpp
Currently there is no support to setting up the Static Default IPv6 gateway via redfish.
This commit adds IPv6StaticDefaultGateways parameter to the ethernet interface, on which user can send PATCH request and setup the Static IPv6 gateway for the interface.
Backend does not support the DefaultGateway6 as array. So this commit ignores the PrefixLength and just sets the Address on to the dbus property and corresponding network file.
Tested by:
PATCH https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/<id>
-d '{"IPv6StaticDefaultGateways": [{"Address": "2002:903:15F:325:9:3:29:1",
"PrefixLength": 24}]}'
PATCH https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/<id>
-d '{"IPv6StaticDefaultGateways": [{"Address": "2002:903:15F:325:9:3:29:1"}]}'
PATCH …
=> Support IPv6StaticDefaultGateways

redfish-core/lib/fan.hpp
The ThermalSubsystem info not be based on the tach sensors but rather the FRUs.
Resloved: https://github.com/ibm-openbmc/dev/issues/3621
=> 1050: Fix fan resources in the ThermalSubsystem info

include/event_dbus_monitor.hpp
=> 1030: test bmcweb PR 685

redfish-core/lib/ethernet.hpp
Currently there is no support to setting up the Static Default IPv6 gateway via redfish.
This commit adds IPv6StaticDefaultGateways parameter to the ethernet interface, on which user can send PATCH request and setup the Static IPv6 gateway for the interface.
Backend does not support the DefaultGateway6 as array. So this commit ignores the PrefixLength and just sets the Address on to the dbus property and corresponding network file.
Tested by:
PATCH https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/<id>
-d '{"IPv6StaticDefaultGateways": [{"Address": "2002:903:15F:325:9:3:29:1",
"PrefixLength": 24}]}'
PATCH https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/<id>
-d '{"IPv6StaticDefaultGateways": [{"Address": "2002:903:15F:325:9:3:29:1"}]}'
PATCH …
=> Support PATCH on IPv6StaticDefaultGateways

redfish-core/lib/hypervisor_system.hpp
This commit adds redfish support for patching
"IPv6DefaultGateway" property for each ethernet interfaces for a static configuration. In case of dynamic configuration, patching of this property will not be permitted in the backend networkd app and an error response will be sent back to the client.
Address the following defect:
https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=543926
The phosphor networkd changes are here:
https://github.com/ibm-openbmc/phosphor-networkd/pull/88
Tested By:
[1] PATCH -d '{"IPv6DefaultGateway":"<ipv6Gateway>"}' https://${bmc}/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth<0/1>
Change-Id: Iaa48431147ba510eac6be9eec2f330303d588005
=> Hypervisor: Add support for default IPv6 gateway

redfish-core/lib/environment_metrics.hpp
Fixes https://github.com/ibm-openbmc/dev/issues/3620
=> 1050: Add Redfish total_power object

redfish-core/lib/pcie_slots.hpp
PCIe Slot LocationIndicatorActive PATCH is not working correctly all the time.
https://github.com/ibm-openbmc/dev/issues/3631
Below is an Everest PATCH of all LEDs to true.
- You will notice not all go true.
- This has also been reported on Rainier.
- This has also been reported when moving the LocationIndicatorActive to false.
- This has been reported on the GUI.
```
Set all slots to be true.
$ curl -k  -X PATCH https://$bmc/redfish/v1/Chassis/chassis/PCIeSlots \
-d '{"Slots":[{"LocationIndicatorActive":true},{"LocationIndicatorActive":true},  \
... \
{"LocationIndicatorActive":true},{"LocationIndicatorActive":true}]}'
$ curl -s -k https://$bmc/redfish/v1/Chassis/chassis/PCIeSlots | grep LocationIndicatorActive
"LocationIndicatorActive": true,
"LocationIndicatorActive": true,
... …
```
=> 1050: Fix PCIeSlot LocationIndicatorActive Patch Handling

redfish-core/lib/pcie.hpp
In PATCH logic, readJson() is incorrectly used and it causes the error
```
curl -k -X PATCH https://$bmc/redfish/v1/Systems/system/PCIeDevices/chassis_motherboard_pcieslot8_pcie_card8 \
-d '{"Oem": {"IBM": {"LinkReset": true}}}'
{
"Oem@Message.ExtendedInfo": [
{
"Message": "The value 'null' for the property Oem is of a different type than the property can accept.",
"null",
"Oem"
],
"MessageId": "Base.1.13.0.PropertyValueTypeError",
"MessageSeverity": "Warning",
"Resolution": "Correct the value for the property in the request body and resubmit the request if the operation failed."
}
]
}
```
It is used to use the proper json data type
```
std::optional<std::vector<nlohmann::json>> slotsData;
-->
std::optional<nlohmann::json> …
```
=> 1050: Fix PCIeTopology ResetLink PATCH Handling

http/http_client.hpp
This commit sets the retry policy to retry forever. Connection state is set to idle when all retries gets exhaused. Request queue is cleared when the queue gets full.
Tested by:
Good HMC subscriber gets all events
BMC keeps sending events in retry loop for a bad subscriber
Change-Id: I23b2e6a1888f80ef0ff7e279bdcbda77899d6354
=> Events: Add RetryForever support

include/login_routes.hpp, include/security_headers.hpp, include/sessions.hpp, include/user_monitor.hpp, src/webserver_main.cpp
PR Includes below fixes:
1. Security: Deleted users can continue to use their Redfish session: 
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/55050
2. PenTesting:Security- found couple of low severity missing header vulnerabilities on BMC
-  https://gerrit.openbmc.org/c/openbmc/bmcweb/+/63455
-  https://gerrit.openbmc.org/c/openbmc/bmcweb/+/64205
=> 1050: Security fixes.

include/dump_utils.hpp
Dump offloadss other than BMC or System-types are not handled correctly by the previous commit 6d88023f2db24204a5a10bc83673d63615f6e984.
Those examles may include 'sbe', 'hostboot', etc which have the entry IDs like
/redfish/v1/Systems/system/LogServices/Dump/Entries/System_XXX/ as system dumpType /redfish/v1/Systems/system/LogServices/Dump/Entries/Hostboot_XXX/ as hostboot dumpType etc
Tested:
- Run redfish validator passes
- Run valid & invalid attachment queries like
```
% curl -k -X GET https://${bmc}:18080/redfish/v1/Managers/bmc/LogServices/Dump/Entries/1/attachment
% curl -k -X GET https://${bmc}:18080/redfish/v1/Managers/bmc/LogServices/Dump/Entries/INVALID/attachment
% curl -k -X GET https://${bmc}:18080/redfish/v1/Systems/system/LogServices/Dump/Entries/System_1/attachment
% …
```
=> 1050: Fix dump-offload handling of Invalid dump attachments (#706)

redfish-core/include/snmp_trap_event_clients.hpp
This commit handles invalid SNMP destination error
Tested by:
Configure SNMP with invalid destination IP address '{"Destination": "snmp://10.6.6.256:162",
"SubscriptionType": "SNMPTrap", "Protocol": "SNMPv2c"}'
=> Fix SNMP invalid Destination error

http/http_connection.hpp
```
Have seen with defects 581366 and 580644 hitting the max connection
limit after multiple HMCs added, etc.
Signed-off-by: Gunnar Mills <gmills@us.ibm.com>```
=> 1020: Up the max requests in flight to 200 (#778)

redfish-core/lib/event_service.hpp
1. Allow empty port, eg: "snmp://9.41.166.76:".
2. Invalid ports and out of range ports are not allowed, eg: "snmp://9.41.166.76:ab" "snmp://9.41.166.76:-40" "snmp://9.41.166.76:65536".
Tested:
1. Empty port:
```
curl -k -H "X-Auth-Token: $bmc_token" -X POST -D headers.txt https://${bmc}/redfish/v1/EventService/Subscriptions -d '{"Destination":"snmp://9.41.166.76:", "SubscriptionType":"SNMPTrap", "Protocol":"SNMPv2c"}'
{
{
"Message": "The resource has been created successfully.",
"MessageId": "Base.1.13.0.Created",
"Resolution": "None."
}
]
}
```
2. Invalid port:
```
curl -k -H "X-Auth-Token: $bmc_token" -X POST -D headers.txt …
```
=> Check snmpTrap port

redfish-core/lib/managers.hpp
Upstream: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/50494 We can use the following command to set LocationIndicatorActive to true or false:
'{"LocationIndicatorActive":false}'
https://${bmc}/redfish/v1/Managers/bmc
=> Implement LocationIndicatorActive property for Manager

redfish-core/lib/pcie.hpp
This commit adds Status and Health elements to the json object of PCIe Device when requested to get the device properties. These two elements are derived from LinkStatus of the PCIe Slot.
This commit is downstream only.
Testing:
- Validator test PASSED for PCIe Device related GET APIs
https://service:passwd@rain118bmc:18080/redfish/v1/Systems/system/PCIeDevices/pcie_card0 {
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/pcie_card0",
...
"Status": {
"Health": "Warning",
}
}
https://service:passwd@rain118bmc:18080/redfish/v1/Systems/system/PCIeDevices/pcie_card0 {
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/pcie_card0",
... …
=> 1110: bmcweb: Add link Status and Health to PCIe device (#570)

http/http_client.hpp
The commit 2523e03[1] changes `conn` of http_client as a pointer and This makes the discrepancy from the upstream and causes the issue.
```
- boost::asio::ip::tcp::socket conn;
+ std::unique_ptr<boost::asio::ip::tcp::socket> conn;
```
This commit is to sync up with upstream in handling http client.
[1] https://github.com/ibm-openbmc/bmcweb/commit/2523e033cc84c2a0d9405a64e682969a0e8a8664
=> 1060: Sync http client socket handling to upstream

redfish-core/lib/managers.hpp
The "Status" of the BMC has been historically fairly simple. If the BMC is at the point where it can respond to the Redfish call then it's "OK" and it's "On". Its "Status" could be derived based on the startup systemd target, multi-user.target, as either "Starting" or "Enabled".
However, with the introduction of new BMC states it is no longer this simple. The following design introduced a new "Quiesced" state for the BMC[1]
There has was also a new BMC state introduced, "UpdateInProgress", which indicates the BMC is in the middle of a firmware update.
These new BMC states require additional logic when responding to Redfish queries for the BMC "Status".
When a BMC is in a "Quiesced" state it is an indication that a critical BMC service has entered the failed state. It is important for BMC …
=> Populate BMC state based on state manager property (#520)

redfish-core/lib/cable.hpp
This commit adds a downstream/upstream port, downstream/upstream resource, and downstream/upstream chassis link into the cable JSON response, which represents an association between resources associated via cables for williwakas and cable cards.
Upstream: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/61122
(More discussion is in https://github.com/ibm-openbmc/dev/issues/3533)
Tested using a rainier system and run Redfish-Service-Validator/ both pass
```
$ curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Cables/dp0_cable0
{
"@odata.id": "/redfish/v1/Cables/dp0_cable0",
"CableType": "",
"Id": "dp0_cable0",
"Links": {
"DownstreamPorts": [
{
"@odata.id": …
```
=> 1110: Add PCIe Topology Cable Links (#576)

redfish-core/lib/log_services.hpp
This commit adds support for various dumps such as Resource, Hostboot, SBE, Hardware.
Tested By:
* Create:
1. BMC dumps: [1] POST https://${bmc}/redfish/v1/Managers/bmc/LogServices/Dump/Actions/LogService.CollectDiagnosticData -d '{"DiagnosticDataType":"Manager"}'
2. System dumps: [1] POST https://${bmc}/redfish/v1/Systems/system/LogServices/Dump/Actions/LogService.CollectDiagnosticData -d '{"DiagnosticDataType":"OEM", "OEMDiagnosticDataType":"System"}'
3. Resource dumps: [1] POST https://${bmc}/redfish/v1/Systems/system/LogServices/Dump/Actions/LogService.CollectDiagnosticData -d '{"DiagnosticDataType":"OEM", "OEMDiagnosticDataType":"Resource_<resource>_<pwd>"}'
* Get:
1. BMC dumps: [1] GET https://${bmc}/redfish/v1/Managers/bmc/LogServices/Dump/Entries [2] GET …
=> Add support for multiple dump types

redfish-core/lib/pcie_slots.hpp
This commit implements to detect and populate link btween PCIe slot and PCIe device attached to that slot.
Sample output for one slot:
{
"Lanes": 0,
"Links": {
{
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/pcie_card8"
}
]
},
"Location": {
"ServiceLabel": "U78DA.ND0.WZS004K-P0-C8"
}
},
"LocationIndicatorActive": false
}
}
It is rebasing 1060 commit - https://github.com/ibm-openbmc/bmcweb/commit/cc625a7e94736ad5af3750fc21a7c75a91c3ea2d. (which is a part of https://github.com/ibm-openbmc/bmcweb/pull/570)
=> 1110: Add Pcie slot to Pcie device link (#570)

redfish-core/lib/assembly.hpp
Update Assembly Schema To Populate Status::State
Status::State reflects the presence status of FRU being
populated in the schema.
"Enabled" state implies that the FRU is present.
"Absent" implies that the FRU is not present.
Validation:
Validator was executed and no new error was found w.r.t
Assembly State change.
Test:
curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Chassis/chassis/Assembly#/Assemblies/6
{
"Assemblies": [
{
"@odata.id": "/redfish/v1/Chassis/chassis/Assembly#/Assemblies/0",
"Location": {
"ServiceLabel": "U78DA.ND0.WZS004A-D0"
}
},
"MemberId": "0",
"Model": …
=> 1110: Update Assembly Schema To Populate Status::State

meson.build, meson_options.txt, redfish-core/include/redfish.hpp, redfish-core/lib/license_service.hpp, redfish-core/lib/message_registries.hpp, redfish-core/lib/service_root.hpp, static/redfish/v1/odata/index.json
Tested: Tested by executing following curl requests 
1) /redfish/v1/Registries/License(Get)
2) /redfish/v1/Registries/License/License
3) /redfish/v1/LicenseService(Get)
4) /redfish/v1/LicenseService/Licenses
Change-Id: Ieeeb1ceb0ad40c5cba2de0d7a1d4583b74abd5f8
=> License manager changes to enable license feature

redfish-core/lib/network_protocol.hpp
There's currently a problem with phosphor-timesyncd, where enabling NTP doesn't immediately reflect in the system status on return[1].  To say it another way, NTP is not enabled/disabled atomically, which leads to the following problem.
// Disable NTP
PATCH /redfish/v1/Managers/bmc/NetworkProtocol
{"NTP":{"ProtocolEnabled": false}}
// Set the time manually
PATCH /redfish/v1/Managers/bmc {"DateTime": "<timestring"}
Doing this in rapid succession leads to a 500 error, which is obviously a bug.  In the prior commit, this error was changed to a PropertyValueConflict error, which is still incorrect, but at least informative of what's going on.  REST APIs are intended to have CRUD compliance.  The response should not be returned until the value has been accepted, and not doing that can lead to …
=> Fix NTP set race condition

redfish-core/lib/cable.hpp
1. Add CableStatus - State, Health, and PartNumber (#357) Add CableStatus, Status.State, Status.Health to cables collection
Testing
1) curl testing:
```
curl -k -H "X-Auth-Token: $t" https://${bmc}/redfish/v1/Cables/dp0_cable1
{
"@odata.id": "/redfish/v1/Cables/dp0_cable1",
"Id": "dp0_cable1",
...
"Name": "Cable",
"Status": {
"State": "StandbyOffline"
}
}
```
2.  Add PartNumber to Cables (#394)
Add PartNumber property to cables.
Also fix code so CableType and LengthMeters properties display correctly.
Testing:
1) Redfish validator passed
2) curl testing:
```
$ curl -k -H "X-Auth-Token: $token" -X GET \
https://${bmc}/redfish/v1/Cables/external_cable_0
{
"@odata.id": "/redfish/v1/Cables/external_cable_0", …
```
=> 1110: Add Cable State, Health, and PartNumber (#357)(#394)

redfish-core/lib/network_protocol.hpp
This commit re-introduces changes proposed earlier to support NetworkSuppliedServers property in bmcweb.
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/52671
It helps to differentiate between the static and DHCP assigned NTP servers. Networkd and Dbus has added support for StaticNTPServers to save the static configuration.
Tested by:
1. PATCH /redfish/v1/Managers/bmc/NetworkProtocol -d '{"NTP":{"NTPServers": [<ip>]}}' Verify that this adds the NTPs server to the NetworkProtocol
2. Enable DHCP to fetch NTP servers list from the DHCP server. Verify that they are listed when GET on NetworkProtocol as below "NTP": { "NTPServers": [ <static ntp server ip> ], "NetworkSuppliedServers": [ <dynamic ntp server ip> ], "ProtocolEnabled": true },
3. Redfish validator run
Change-Id: …
=> NetworkProtocol: Support NetworkSuppliedServers (#934)

redfish-core/lib/ethernet.hpp
This commit pull upstream commits to support 
1. Support PATCH on IPv6StaticDefaultGateways
2. DHCP4 and DHCP6 parameters independently
3. Fix UseDomainName configuration
=> Network  DHCP settings & IPv6StaticDefaultGateways

meson_options.txt
=> Enable audit by default

redfish-core/lib/processor.hpp
This is 1110 rebase of single commit from [PR 542](https://github.com/ibm-openbmc/bmcweb/pull/542):
https://github.com/ibm-openbmc/bmcweb/commit/335f1ee09120bc255e43e5b737170f84c6ed7899
Cleanup changes were made to follow current upstream coding style.
Note: setProcessorObject() was changed to always pass the locationIndicatorActive value. The called functions were adjusted accordingly.
Upstream commit (abandoned due to inactivity): https://gerrit.openbmc.org/c/openbmc/bmcweb/+/37045
Implement LocationIndicatorActive for CPU resource
- Add the getLocationIndicatorActive method and the setLocationIndicatorActive method to bmcweb to support the LocationIndicatorActive property for processor.
- A client would use the `LocationIndicatorActive` property to identify or locate the processor. …
=> 1110: Implement LocationIndicatorActive for CPU resource

redfish-core/lib/memory.hpp
This is 1110 rebase of single commit from https://github.com/ibm-openbmc/bmcweb/pull/542:
[10c9933](https://github.com/ibm-openbmc/bmcweb/commit/10c9933e8a4b65da2000170c49374a3385a580c8)
Cleanup changes were made to follow current upstream coding style.
Note: setDimmObject() was changed to always pass the locationIndicatorActive value. The called functions were adjusted accordingly.
Upstream commit (abandoned due to inactivity): https://gerrit.openbmc.org/c/openbmc/bmcweb/+/37310
- Add the getLocationIndicatorActive method and the setLocationIndicatorActive method to bmcweb to support the LocationIndicatorActive property for memory.
Tested: Validator passes
```
https://${bmc}/redfish/v1/Systems/system/Memory/dimm0 {
"@odata.id": …
```
=> 1110: Implement LocationIndicatorActive for Memory resource

redfish-core/lib/assembly.hpp
The commit makes required change to enable base and LCD panel CM on Everest systems.
To achieve that whenever the FRU is set for removal,CCIN property needs to be cleared as some sensors are dependent of panel presence and listening for CCIN property of the FRU.
Also post the FRU is replaced, vpd-manager is trigerred to collect VPD of the FRU and restore its CCIN value and present property.
Test:
Ran validator, no new error
Redfish run result-
{
"@odata.id": "/redfish/v1/Chassis/chassis/Assembly#/Assemblies/2",
"Location": {
"ServiceLabel": "UABCC.ND0.0000111-D0"
}
},
"MemberId": "2",
"Model": "51F4",
"Name": "panel0",
"Oem": {
"OpenBMC": {
"@odata.type": "#OemAssembly.v1_0_0.Assembly", …
=> Update schema to enable panel CM (#575)

redfish-core/lib/fabric_adapters.hpp
This update adds the GET and PATCH support for LocationIndicatorActive to fabric adapters. Only some fabric adapters support this option.
I manually tested this using the following commands:
```
curl -k -H "X-Auth-Token: $token" -X  GET \
https://${bmc}/redfish/v1/Systems/system/FabricAdapters/chassis-motherboard-disk_backplane0
```
and
```
curl -k -H "Content-Type: application/json" -X  PATCH -d '{"LocationIndicatorActive":true}' \
https://${bmc}/redfish/v1/Systems/system/FabricAdapters/chassis-motherboard-disk_backplane0
```
I first ran the above GET command, which showed that LocationIndicatorActive was false. I then ran the above PATCH command, which also succeeded. Finally I ran the GET command which succeeded and now showed that LocationIndicatorActive was true.
Change-Id: …
=> 1110: Add LocationIndicatorActive for fabric adapters (#630)

redfish-core/lib/memory.hpp
This is a rebase of https://github.com/ibm-openbmc/bmcweb/pull/571. This commit restructures the original functions for this option.
Note: The Memory "Enabled" option has not yet been rebased to 1110. This commit does not include the changes from the 1060 commit related to that option. When the commit [redfish-core: Memory: Enabled the isolation (aka guard) feature](https://github.com/ibm-openbmc/bmcweb/commit/70c213769052d24244ce58e9836f6f45cedf474c) is rebased the calls to its functions will need to be added to the new locations.
Implement LocationIndicatorActive for Memory resource (#571)
- Add the getLocationIndicatorActive method and the setLocationIndicatorActive method to bmcweb to support the LocationIndicatorActive property for memory.
Tested: Validator passes
```
curl -k -H …
```
=> 1110: Implement LocationIndicatorActive for Memory resource (#571)

redfish-core/include/utils/name_utils.hpp, redfish-core/lib/chassis.hpp, redfish-core/lib/processor.hpp, redfish-core/lib/storage.hpp
Cherry picked and resolved conflicts for the following commit.
[util: Add pretty name for resources](https://github.com/ibm-openbmc/bmcweb/pull/542/commits/39d15319d1ec2a4fa835c32b5e919c826c6b7913)
=> Rebase Pretty-name

redfish-core/lib/systems.hpp, static/redfish/v1/JsonSchemas/OemComputerSystem/OemComputerSystem.json, static/redfish/v1/schema/OemComputerSystem_v1.xml
Tested: Forced safe mode and verified dbus was updated
Change-Id: Ia2e23154454025ca7a8107e54f2de3883363490a
=> Systems: Add OEM safe mode to user interface

redfish-core/include/utils/hw_isolation.hpp, redfish-core/lib/assembly.hpp, redfish-core/lib/log_services.hpp
List of original commits that are cherry-picked
[HW-Isolation: Fix, Update State if the Core and DIMM are recovered](https://github.com/ibm-openbmc/bmcweb/pull/542/commits/5f34f2c02f1e8d0b959031ce02b76ee42c0c63df)
[registry: Add PropertyValueResourceConflict registry](https://github.com/ibm-openbmc/bmcweb/pull/542/commits/a1c5c574609721b646b5c13814fd99b405e132c9)
[HW-Isolation: Return an appropriate error if the request is failed.](https://github.com/ibm-openbmc/bmcweb/pull/542/commits/c728c4070eacaa0b1fdec1dd4b9d6af3a9612e56)
[HW-Isolation: Fill OriginOfCondition for the TPM and Motherboard](https://github.com/ibm-openbmc/bmcweb/pull/542/commits/1079d5d205981a18fdfa0ceed6fc70cc3a0f6705)
=> Update state and others

redfish-core/lib/account_service.hpp
Allow PATCHing the ManagerAccount AccountTypes property.
Tested: compiles
Change-Id: I4539d8d7127c8143e205b484ba9cfbbec9e1615d
=> Allow patching AccountTypes

redfish-core/include/utils/error_log_utils.hpp, redfish-core/include/utils/hw_isolation.hpp, redfish-core/include/utils/name_utils.hpp, redfish-core/lib/log_services.hpp, redfish-core/lib/memory.hpp
List of commits cherry picked
https://github.com/ibm-openbmc/bmcweb/commit/31c5c4a8b066cac72273eda97ac2dc9575d51cbb - LogEntry: HW-Isolation: Removed the Resolved property (#341)
https://github.com/ibm-openbmc/bmcweb/commit/fd0d6dcddcbafb28451ff4cfd981ca760d8b4165 - HW-Isolation: Map Manual error message to OK in entry message (#405) (#637)
https://github.com/ibm-openbmc/bmcweb/commit/24e176a9cb3a1b4b86c1f7eb02e2b334628b96d4 - Using sdbusplus::asio::getProperty
https://github.com/ibm-openbmc/bmcweb/commit/bac61b0752e2a5e70f2668667fdd3f22b4dd1c14 - Using sdbusplus::asio::getAllProperties
=> LogEntry: HW-Isolation: Removed the Resolved property (#341)

redfish-core/lib/log_services.hpp
The JSON file created by phosphor-auditlog now uses named fields for the expected message parameters. It also no longer knows about the message registry message. Adjust bmcweb to build the message from the expected JSON fields.
Addresses [comment from review](https://github.com/ibm-openbmc/phosphor-logging/pull/41#discussion_r1442173025) of original implementation.
Must be merged with dependent change: https://github.com/ibm-openbmc/phosphor-logging/pull/64
Tested:
- Verified Redfish response same after change.
- Redfish Validator passed.
=> Audit Log: Use named fields for log entries

redfish-core/lib/pcie_slots.hpp
PCIeSlots schema is being deprecated and not maintained in upstream, and causes WebUI to show the empty PCIeSlots page.
This fix uses the `containing/contained_by` associations to find PCIeSlots for the given chassis.
Tested:
- GET PCIeSlots
```
curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots
```
- Redfish Service Validator passes on PCIeSlots
=> 1110: Fix PCIeSlots schema via containing association

redfish-core/lib/pcie_slots.hpp
In case when there is no association between chassis and pcieslots, `getAssociatedSubTreePaths()` may give the empty Paths rather than the error return.
This is to skip the non-associated pcieslots rather than generating an internal error.
This happens when PLDM discovers the additional slots which may not be associated with the other inventory chassis.
```
curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis
...
> debug code:
pcieSlotPath=/xyz/openbmc_project/inventory/system/chassis15363/logical_slot1, chassisID=chassis
```
Tested:
- curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis
=> 1110: Fix PCIeSlots when empty association

redfish-core/lib/hypervisor_system.hpp
Currently VMI IPv6StaticAddresses patch operation fails due to a missing 1110 rebase commit.
These changes were missed as part of 1110 rebase PR  https://github.com/ibm-openbmc/bmcweb/pull/938
This commit fixes VMI IPv6StaticAddresses patch operation.
This commit requires the address and gateway. IPv4 network setting needs these values together to setup the IP. This is not a redfish need - but a networkd need. 
The basic VMI IP configuration is upstream, VMI is a IBM specific term so the more complex stuff is not upstream. https://github.com/ibm-openbmc/bmcweb/pull/938 would have to go upstream first. 
Tested by:
PATCH -d '{"IPv6StaticAddresses": [{"Address": "2002:903:15f:290:9:3:109:39","PrefixLength": 120}]}'
=> Hypervisor: Fix IPv6StaticAddresses Patch operation

.secrets.baseline, include/authentication.hpp, include/login_routes.hpp, include/pam_authenticate.hpp, redfish-core/lib/redfish_sessions.hpp
This PR pulls upstream commits to support multi factor authentication with MFA token property 
Upstream commits (merged)
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/73605
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/69470
=> Redfish Session: Implement MFA "Token" property

http/http_server.hpp, include/dump_offload.hpp, include/event_dbus_monitor.hpp, include/ibm/management_console_rest.hpp, redfish-core/lib/hypervisor_system.hpp, redfish-core/lib/log_services.hpp
BMCWEB_LOG_INFO vs BMCWEB_LOG_CRITICAL.
PE wants this backported to 1060.
Fixes 613773
=> 1060: Downgrade INFO logs to just that

http/http_server.hpp, include/dump_offload.hpp, include/event_dbus_monitor.hpp, include/ibm/management_console_rest.hpp, redfish-core/lib/hypervisor_system.hpp
BMCWEB_LOG_INFO vs BMCWEB_LOG_CRITICAL.
Fixes 613773
=> Downgrade INFO logs to just that

redfish-core/lib/log_services.hpp
HttpBody has added support to use unix_fd to read the data to be downloaded. Update the handling of FullAudit attachment download to use this approach.
```
curl -k -H "X-Auth-Token: ${token}" -X GET https://${bmc}/redfish/v1/Systems/system/LogServices/AuditLog/Entries/FullAudit/attachment
```
Upstream commit which added the unix_fd support and modified the BMC dump to use it: [67667](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/67667)
Tested:
- Used version of phosphor-auditlog to always return the same full audit log file, size 10MB. Ran curl command to download the file in a loop 500 times on hardware and confirmed downloaded file matched expected data on all iterations.
=> Audit Log: Use HttpBody to download FullAudit attachment

redfish-core/lib/ethernet.hpp
The Redfish schema for creating static IPv4 addresses requires the IP address, the netmask, and a gateway IP address. There's an issue inherent with this method. A network interface is only permitted a single IPv4 default gateway. If more than one IPv4 static address is assigned to the NIC each entry is processed, and potentially conflicting default gateways may be assigned. The last entry processed assigns the IPv4 default gateway. This behavior will cause unexpected results. It is necessary to prevent assigning mismatched default gateway values.
The IPv4 address removal process requires additional work also. The default gateway value is left in place even after the final static IPv4 address is removed. It is necessary to perform an additional action to clear the gateway address. Without …
=> Delete IPv4 default gateway when deleting an IPv4 static address

redfish-core/lib/pcie.hpp
The commit publishes Location code and Name under PCIeDevice schema.
Validator was executed and no new error was found.
Test:
curl -k -H "X-Auth-Token: $bmc_token" -X GET "https://${BMC_IP}/redfish/v1/Systems/system/PCIeDevices/chassis_motherboard_pcieslot0_pcie_card0"
{
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/chassis_motherboard_pcieslot0_pcie_card0",
"Id": "chassis_motherboard_pcieslot0_pcie_card0",
"Name": "PCIe4 x16 or PCIe5 x8 adapter",
"Oem": {
"IBM": {
"@odata.type": "#IBMPCIeDevice.v1_0_0.IBM",
"LinkReset": false
}
},
"PCIeFunctions": {
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/chassis_motherboard_pcieslot0_pcie_card0/PCIeFunctions"
},
"PCIeInterface": {
"LanesInUse": null
},
"Slot": {
"Location": { …
=> Publish Location & Name under PCIeDevice schema

redfish-core/include/utils/json_utils.hpp, redfish-core/lib/sensors.hpp, test/redfish-core/include/utils/json_utils_test.cpp
Cherry-picked merged commit:
- https://gerrit.openbmc.org/c/openbmc/bmcweb/+/74926
Modified sort utility to be able to sort on a specified key. New utility function sortJsonArrayByKey() added.
Note:
- Function odataObjectCmp() renamed to objectKeyCmp()
- New function odataObjectCmp() created which calls objectKeyCmp() with @odata.id key specified.
- Comments for odataObjectCmp() didn't match behavior for object without key. These objects are sorted as less than objects with the key.
- sortJSONResponse() modified to use the new sortJsonArrayByKey().
Tested:
- Added new unit tests. These tests are in addition to the existing tests. So they focus on testing comparing by different keys. The existing tests already cover the different permutations of the basic comparisons.
- Redfish Service …
=> 1110 json utility: Update sort algorithms

redfish-core/lib/pcie.hpp
It adds the missing links from PCIeDevice to PCIeSlot. This will make this release to be compatible with the previous releases.
For example, "Links|Oem|IBM|PCIeSlot" property will be added like
```
curl -k -X GET https://${bmc}/redfish/v1/Systems/system/PCIeDevices/chassis_motherboard_pcieslot11_pcie_card11
{
"Links": {
"Oem": {
"IBM": {
"@odata.type": "#IBMPCIeDevice.v1_0_0.PCIeLinks",
"PCIeSlot": {
"@odata.id": "/redfish/v1/Chassis/chassis/PCIeSlots"
}
}
}
},
```
Tested:
- GET PCIeDevice and check whether it has a link to PCIeSlot
- Redfish Service Validator passes
=> 1110: Add Oem Link PCIeSlot from PCIeDevices

redfish-core/lib/account_service.hpp
This commit introduces changes to remove all sessions except the current one upon top verification
Tested By:
Created multiple sessions
Verified other sessions are terminated except the current one post totp validation.
Upstream : https://gerrit.openbmc.org/c/openbmc/bmcweb/+/74807
Fixes : https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=661824
Change-Id: I95dbecc107258836f3ec8f8f06b80cd6f91b6f79
=> MFA: Delete session except current after totp verification

redfish-core/lib/redfish_sessions.hpp
This PR is need to check if MFA is enabled for the user and if enabled a secret key generation is required for the user before giving him full access for redfish. https://gerrit.openbmc.org/c/openbmc/bmcweb/+/74938 is corresponding upstream commit
=> Mfa check before session creation

redfish-core/lib/environment_metrics.hpp, redfish-core/lib/power_subsystem.hpp
The power cap limits were previously hosted by Settings, but those are system settings and the limits are not really settings (users can not adjust these).
A new dbus interface will host these power cap limits:
xyz.openbmc_project.Control.Power.CapLimits
Tested on Rainier:
'''
=> GET /redfish/v1/Chassis/chassis/EnvironmentMetrics ...
"PowerLimitWatts": {
"AllowableMax": 2777,
"AllowableMin": 1286,
"ControlMode": "Disabled",
"SetPoint": 2500
},
==> GET /redfish/v1/Chassis/chassis/PowerSubsystem (no powercap enabled) ...
"Allocation": {
"AllocatedWatts": 2777,
"RequestedWatts": 2777
},
== Enable 2121W power cap ==
=> GET /redfish/v1/Chassis/chassis/EnvironmentMetrics ...
"PowerLimitWatts": {
"AllowableMax": 2777,
"AllowableMin": 1279,
"ControlMode": "Automatic",
"SetPoint": 2121
},
==> GET …
=> Update to use power cap limits from CapLimits instead of Cap

redfish-core/include/event_service_manager.hpp, redfish-core/include/utils/json_utils.hpp
Updates to fix build issue with debug enabled option --buildtype=debug.
Tested --buildtype=debug and build works
=> Fix debug enabled build issue.

include/persistent_data.hpp
This commit fixes the file path of session data collection which was added as part of PR https://github.com/ibm-openbmc/bmcweb/pull/909
=> FFDC: Fix session data collection file path

redfish-core/lib/roles.hpp
This is required for the new "Restricted" property.
Seeing Validator errors because of this.
This restricted role is downstream
=> redfish: bump Role to v1_3_0 (#831)

redfish-core/lib/processor.hpp
Rebase of 1110 commit https://github.com/ibm-openbmc/bmcweb/commit/54ee816fd163f327e823381c57ccb4a259dc75e4
Story for upstream support: [PFEBMC-2356](https://jsw.ibm.com/browse/PFEBMC-2356)
Tested on 1120 hardware simulator. Redfish validator didn't report error with this path.
- The BMC inventory modeled processor object as "dcmN/cpuN" to support DCM (Dual-Chip Module) package (that contains two processors) based on system model.
- Redfish does not support "Chip Module" (DCM or MCM (Multi-Chip Module)) but, due to inventory changes ("dcmN/cpuN") the existing Processor schema support won't work i.e we will see it as like below so we cannot locate the correct cpu object into inventory when want to pull its details or its subunits details.
```
-> "@odata.id": …
```
=> redfish-core: Processor: Workaround to handle DCM (#959)

redfish-core/lib/log_services.hpp
This change ensures that resource dump creation requests are permitted only when initiated by a service user — specifically, a user with the "priv-oemibmserviceagent" privilege.
Requests from any other users will be denied with an "Insufficient Privilege" error response from bmcweb.
The rationale behind this restriction is that resource dumps are intended solely for debugging issues in resources of the host, which are to be collected exclusively by service user. As such, access is limited to service users and explicitly restricted for all others.
Fixes: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=681755
Tested By:
[1] POST https://${bmc}/redfish/v1/Systems/system/LogServices/Dump/Actions/LogService.CollectDiagnosticData -d …
=> Restrict Resource Dump Creation to service user

redfish-core/lib/systems.hpp
* Systems: Add OEM safe mode to user interface
Tested: Forced safe mode and verified dbus was updated
Change-Id: Ia2e23154454025ca7a8107e54f2de3883363490a
=> Systems: Add OEM safe mode to user interface (#976)

redfish-core/lib/hypervisor_system.hpp
404 error on hypervisor redfish endpoint was not handled properly due to which redfish validator failed. This commit fixes it.
Tested By:
Redfish Validator Passed.
=> hypervisor: Fix validator failure
